### ISSUE TITLE
Flutter Location Plugin : for offline use 

### ISSUE THREAD

**Issue by GauravPatni** [Lyokone/flutterlocation#100]
Please let us know whether we can use this **Flutter Location Plugin for offline apps** ?

e.g. App having BLE communication with some system ( IOT sensor ) to provide GPS coordinates via mobile app . No internet connection available .

Thanks,
Gauarv

**Comment by GauravPatni** [comment]
Please reply !!

**Comment by Lyokone** [comment]
Hey ! It's not a feature that I'm currently looking into. If you have some example of code in iOS / Android it might be added in the future.

**Comment by GauravPatni** [comment]
I dont have sample code for getting GPS coordination without having internet connection .
But on app store / google play store there are few apps which gives GPS coordinate offline .

Is it means that , for now , offline GPS coordinate feature is not available with 'Flutter Location' plugin ?

**Comment by ride4sun** [comment]
> Is it means that, for now, offline GPS coordinate feature is not available with 'Flutter Location' plugin ?

I would be interested in that answer also. Why would that plugin not work offline? Or in other words. What does the GPS todo with internet connection?

**Comment by Lyokone** [comment]
Hey ! I haven't got time to check this, but it's definitely weird for me too.
As long as you are not in AirPlane mode, I cannot see why the plugin wouldn't work. I'll test that myself.

**Comment by aitorres** [comment]
Hello! @Lyokone 
I just tested this out. I opened an app I am using this plugin in, on an Android device without internet connection (no Wifi nor mobile data). It successfully found my current location. So I'd say it is working offline.

**Comment by Lyokone** [comment]
Hey ! 
Thanks for the notice, this is the results I get. I was waiting to get an actual iOS device but it seems to be the same thing 😉 I'll close this.
