### ISSUE TITLE
Package is not production ready for Android

### ISSUE THREAD

**Issue by mulderpf** [Lyokone/flutterlocation#102]
I used this library in a production version of my app and approximately 25% of all my Android users suffered with an issue where:

```
try {
  currentLocation = await location.getLocation;
} on PlatformException {
  currentLocation = null;
}
```
would immediately throw a PlatformException and keep doing so for about 40-60 seconds until it seems like the GPS has warmed up.  Unfortunately due to having to rush in a patch to figure out what was going on, I only captured e.code which was always "ERROR".  I didn't pick this up in testing until my users reported the issue - the easiest way to recreate it is to turn off location services, attempt to get location, turn it back on and then this horrible mess starts.

I would not expect this plugin to work this way on Android and at least make an attempt at getting location rather than just throwing an error.  On Android native I had a timeout of 20 seconds which has been sufficient for hundreds of thousands of devices since 2013.

I've replaced this with the geolocator package (https://pub.dartlang.org/packages/geolocator) using the "best" location accuracy and I haven't seen this issue re-occur.  Similarly, in my attempt to recreate the issue where location would resume after about 40-60 seconds, the other plugin does it in about 15 seconds.

**Comment by thomas01155** [comment]
I think is related to: https://github.com/Lyokone/flutterlocation/issues/82

I'm waiting out till location is supported officially. All the plugins I've tried have one issue or another.

**Comment by mulderpf** [comment]
Since switching to geolocator, I've not seen further production issues (app is used by around 2700 people per day with the vast majority of them choosing to use location services).

The issue report is possibly the same, but in my testing, the device recovered after about 40-60 seconds.

**Comment by thomas01155** [comment]
I found geolocator quite slow compared to this one (when this one works), maybe I had the accuracy higher on geolocator?  Is your app published to Apple App store or only the Play Store? I also got some weird email from Apple after using geolocator about various "Missing Purpose String in Info.plist File".

**Comment by mulderpf** [comment]
My app is published to both.  All my purpose strings are completed in the Info.plist file for the permissions I require in the app.  That needs to be setup if you use location services regardless of which plugin you use to obtain it.

The only time geolocator is slow, is when the phone is trying to obtain a GPS fix.  But that's normal and if I am using an "await" statement, I expect the app to at least try and get the fix, rather than return a PlatformException.  Being really fast in returning a PlatformException isn't useful to me.

**Comment by fvisticot** [comment]
Any update of this issue. I have the same issue the plugin is workin on some Android devices and is failing on other one (Samsung A5 is not working)

**Comment by davi19** [comment]
Same here, in Moto E4  don`t work and in Samsung J4 work perfectly.  In IOS work perfectly too. The exception in my case of Moto E4 is:

`E/flutter (20115): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/text.dart': Failed assertion: line 237 pos 15: 'data != null': is not true.
E/flutter (20115): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter (20115): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter (20115): #2      new Text (package:flutter/src/widgets/text.dart:237:15)
E/flutter (20115): #3      DadosPrincipal.minhaAgencia (package:divicred_digital/ui/principal.dart:694:29)
E/flutter (20115): #4      DadosPrincipal.build.<anonymous closure>.<anonymous closure> (package:divicred_digital/ui/principal.dart:381:31)
E/flutter (20115): #5      State.setState (package:flutter/src/widgets/framework.dart:1122:30)
E/flutter (20115): #6      DadosPrincipal.build.<anonymous closure> (package:divicred_digital/ui/principal.dart:379:19)
E/flutter (20115): <asynchronous suspension>
E/flutter (20115): #7      _BottomNavigationBarState._createTiles.<anonymous closure> (package:flutter/src/material/bottom_navigation_bar.dart:568:26)
E/flutter (20115): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (20115): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (20115): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (20115): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (20115): #12     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (20115): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
E/flutter (20115): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (20115): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (20115): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter (20115): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (20115): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (20115): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (20115): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (20115): #21     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (20115): #22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (20115): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (20115): #24     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (20115): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter (20115): `

**Comment by Lyokone** [comment]
Hey ! The plugin should be more reliable with the latest 2.1 version. Please check it out :)
