### ISSUE TITLE
 Location package Not working on First Time App Install

### ISSUE THREAD

**Issue by Hina-Hussain** [Lyokone/flutterlocation#103]
The only problem I am facing is that whenever there is a fresh install of a new apk of the app, the app does not find the location after location permission has been granted.
After location has been granted I have set up a print statement to print out the user's location but for some reason it is not printing anything the first time only. After I restart the app then it prints out the location just fine.

**Comment by Lyokone** [comment]
Hey ! First time authorisation should be handle more reliable in version 2.1, pls check it out :)
