### ISSUE TITLE
AndroidX Support 

### ISSUE THREAD

**Issue by ebastuart** [Lyokone/flutterlocation#107]
## AndroidX Support

Google has updates all their flutter dependencies, what causes to migrate to AndroidX libs.
Unfortunately this plugin crashes after migration. 

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

UPDATE:
just wanted to add the error message from console:

```
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:10: error: package android.support.annotation does not exist
import android.support.annotation.MainThread;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:11: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:12: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:289: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {
                                   ^
  symbol: class NonNull
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by CodeNextGen** [comment]
Open the **android folder of Flutter project in Android Studio** (It is highlighted for a reason , read it carefully) and it will show you location just as in image below 
```
import androidx.annotation.MainThread;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import [androidx.core.app.ActivityCompat;
import androidx.legacy.app.*;
```
<img width="1417" alt="screenshot 2019-01-31 at 9 15 23 am" src="https://user-images.githubusercontent.com/34705304/52029426-2247b880-2539-11e9-9145-546a5ab278e1.png">


blue highlighted part is the replaced part which was giving here , now annotation and AppCompact comes from androidx.
It worked like a charm

**Comment by ebastuart** [comment]
True story, seems to work. **Thanks a lot.** (It is highlighted for a reason as well ;) )
I have to mention two things:
1.) it took a while til I got shown the plugins folders.  I had waited for two minutes in my Android Studio and than it appears. (I guess it depends from the system speed)
2.) a square bracket is misplaced
`import [androidx.core.app.ActivityCompat; ` => `import androidx.core.app.ActivityCompat;`

**Comment by CodeNextGen** [comment]
> True story, seems to work. **Thanks a lot.** (It is highlighted for a reason as well ;) )
> I have to mention two things:
> 1.) it took a while til I got shown the plugins folders. I had waited for two minutes in my Android Studio and than it appears. (I guess it depends from the system speed)
> 2.) a square bracket is misplaced
> `import [androidx.core.app.ActivityCompat; ` => `import androidx.core.app.ActivityCompat;`

Thanks I have updated, it was just placed when I dropped screenshot at wrong place , yes when you open it in Android studio it takes time and time will vary and it depends upon number of third party plugins you are using so gradle will download all dependencies(  it may take one hour many time , suppose you are using a library which is based upon Android SDK version 24 and build tool version 24 or something i, it is of nearly one GB size,it will depend upon your internet speed and system speed both. so best practice is to use updated plugin , if plugin is old then download on local and update settings to new and in pubsec.yaml , call the plugin from local path).
