### ISSUE TITLE
On android it is giving me 9 errors

### ISSUE THREAD

**Issue by CodeNextGen** [Lyokone/flutterlocation#109]
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:14: error: package android.support.annotation does not exist
import android.support.annotation.MainThread;
                                 ^
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:15: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:16: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:17: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:18: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:192: error: cannot find symbol
        int permissionState = ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION);
                              ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:197: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
        ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:202: error: cannot find symbol
        return ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.ACCESS_FINE_LOCATION);
               ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
/Users/sanjeevmoga/.pub-cache/git/flutterlocation-f263ee980693d73fa8d996628568729ac300390c/android/src/main/java/com/lyokone/location/LocationPlugin.java:295: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {
                                   ^
  symbol: class NonNull
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by CodeNextGen** [comment]
Solved I was using androidx and there is guide to migrate https://developer.android.com/jetpack/androidx/migrate

**Comment by bulgariamitko** [comment]
i am getting the same error and when i go to Refactor > Migrate to AndroidX i am getting `No Usages Found In This Project` and i am still getting the error, what should i do?

flutter doctor is returning this 
`/home/dimitar/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, v1.1.8, on Linux, locale bg_BG.UTF-8)
    • Flutter version 1.1.8 at /home/dimitar/flutter
    • Framework revision 985ccb6d14 (преди 4 седмици), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/dimitar/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
Process finished with exit code 0`
