### ISSUE TITLE
[Question] Run the plugin in the background mode

### ISSUE THREAD

**Issue by angel1st** [Lyokone/flutterlocation#110]
I wonder if this plugin returns location if the app is in the background mode? If not, can you add this feature?

**Comment by vincekruger** [comment]
Is there an eta on this feature?

**Comment by fre391** [comment]
Yes, I agree. I stumble about the same issue. It would be great, if your plugin supports to run in background. I would appreciate to help figuring out and do testing...Do you have already any ideas?

**Comment by vincekruger** [comment]
Here is a great article that I found: https://medium.com/curbside/requesting-location-permissions-in-ios-9e5a3b814a8b.

I forked this repo and made the ios modifications myself for now.

**Comment by Lyokone** [comment]
Hey ! I've started the implementation in Android. But I think we're not talking about the same background : I mean a truly background task that would wake the application even if it has been closed by the user and that would give location several times each hour depending on system limitations. If you have an iOS implementation feel free to do a PR to help the community 😉

**Comment by fre391** [comment]
wow, what a great support... Thank you so much... Nice to hear, that you have plans for a real background task, which is even better... Im looking forward, to test it out in Android. Good luck!

**Comment by vincekruger** [comment]
While I was running my fingers crazy on the internet to find out more about this "always" background mode, I never saw anything relating to waking the app at least I think this is not possible with the iOS - I stand to be corrected ;)

I will push a PR later today with the two extra functions mentioned in [#146](https://github.com/Lyokone/flutterlocation/issues/146)

**Comment by Lyokone** [comment]
To my understanding, this article describe what i mean for iOS, I might be wrong tho, didn't started implementation for iOS : https://developer.apple.com/documentation/corelocation/getting_the_user_s_location/handling_location_events_in_the_background?language=objc.

**Comment by vincekruger** [comment]
I thought Apple would have blocked this feature, but they don't which is great.  A combination of both would be amazing.  I will push my PR which will address requesting the two types of location permissions the evening. :)

**Comment by Lyokone** [comment]
Hey, just to let you know that work related with background location will be pushed to [this branch](https://github.com/Lyokone/flutterlocation/tree/background_location)

**Comment by angel1st** [comment]
Thanks for the update, @Lyokone!. Quick Q - when the readme for this new branch will be updated to reflect the newly added background support?

**Comment by Lyokone** [comment]
Hey, no ETA yet, I'm not sure when I will be able to work on the iOS side of the functionnality. Probably during the week tho.

**Comment by angel1st** [comment]
Thanks, @Lyokone, excellent work so far. I believe there are plenty of people out there look forward to seeing the release!

**Comment by Lyokone** [comment]
Thanks @angel1st  :) 

I've finished the iOS part of the plugin which is pushed on [this branch](https://github.com/Lyokone/flutterlocation/tree/background_location). I'll write the documentation to setup the background location system probably tomorrow. 
I will probably keep this version of the plugin on a separate branch for a little while, I had to switch to the master branch of Flutter to get all the feature needed to implement it and the background part still need some testing ;)
In the meanwhile, once the documentation is ready, you will be able to use it with:
```
dependencies:
  location:
    git:
      url: git://github.com/Lyokone/flutterlocation.git
      ref: background_location
```

**Comment by angel1st** [comment]
Thanks for the update @Lyokone, I am on another project ATM, however, I believe I can give a try on bg feature in a week or two.
Looking forward to seeing the feature merged to the master branch! Excellent work!
