### ISSUE TITLE
error on compile

### ISSUE THREAD

**Issue by dikshaonline** [Lyokone/flutterlocation#112]
flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:17: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;

**Comment by aboda1986** [comment]
this package is not compatible with AndroidX

**Comment by dikshaonline** [comment]
> this package is not compatible with AndroidX

which package is compatible with AndroidX for geolocation

**Comment by aboda1986** [comment]
@dikshaonline until now no location package compatible with androidX, for temp solution roll back to previous version of your packages before migrate to androidX

**Comment by fritz-playmaker** [comment]
Upgrade to `version ^2.0.0`

**Comment by Lyokone** [comment]
Thank you for your help :)
