### ISSUE TITLE
Get heading/direction

### ISSUE THREAD

**Issue by LinusU** [Lyokone/flutterlocation#114]
Would it be possible to add a `"heading"`, or `"direction"`, key to the supplied location object, that tells the direction that the device is currently rotated in. This is very useful when building an app that shows a compass to navigate the user to a specific place.

This value can be read on iOS using the `trueHeading` (or, failing that, the `magneticHeading`) from the  `CLHeading` object.

On Android this can be read using the `SensorManager.getOrientation` function.

Look at this project for some actual code: https://github.com/hemanthrajv/flutter_compass

Cheers 🍻

**Comment by Lyokone** [comment]
Hey ! I will probably have a look into it over the weekend :)

**Comment by Lyokone** [comment]
Has been added in version 2.1 :)

**Comment by LinusU** [comment]
Awesome, thanks!
