### ISSUE TITLE
onLocationChanged not found

### ISSUE THREAD

**Issue by agreensh** [Lyokone/flutterlocation#116]
Trying to subscribe to the onLocationChanged stream
location version 1.4.1
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D42, locale en-GB)
   • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

```
    _locationSubscription = _location.onLocationChanged.listen((Map<String, double> locationData) {
      _newLocation = {
        "latitude": locationData["latitude"],
        "longitude": locationData['longitude'],
      };
    });  
```

Get this error.
`lib/pages/location_page.dart:66:39: Error: The getter 'onLocationChanged' isn't defined for the class 'dart.core::Map<dart.core::String, dart.core::double>'.`

**Comment by MungaraJay** [comment]
Just use **onLocationChanged()** instead of onLocationChanged.

It will fix your issue.
