### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by xspid3r** [Lyokone/flutterlocation#121]
Got this error while trying to run the app

    Launching lib/main.dart on SM J415F in debug mode...
    Initializing gradle...                                       1,1s
    Resolving dependencies...                                    7,8s
    Gradle task 'assembleDebug'...
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:processDebugResources'.
    > Android resource linking failed
      Output:  C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:197: error: resource android:attr/fontVariationSettings not found.
      C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:198: error: resource android:attr/ttcIndex not found.
      error: failed linking references.
    
      Command: C:\Users\MYPC\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\65a53401679d9d285dcf9a42cdf7413f\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
              D:\APPS\Programmes\Android\Sdk\platforms\android-27\android.jar\
              --manifest\
              C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
              -o\
              C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
              -R\
              @C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
              --auto-add-overlay\
              --java\
              C:\Users\MYPC\Desktop\gpsloc\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
              --custom-package\
              com.example.gpsloc\
              -0\
              apk\
              --output-text-symbols\
              C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\symbols\debug\R.txt\
              --no-version-vectors
      Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
      Output:  C:\Users\MYPC\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\5df4e1bfcb59c950c366db4ab0fc0e10\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.
    
      C:\Users\MYPC\.gradle\caches\transforms-1\files-1.1\core-1.0.0-rc01.aar\5df4e1bfcb59c950c366db4ab0fc0e10\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.
    
      error: failed linking references.
      Command: C:\Users\MYPC\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\65a53401679d9d285dcf9a42cdf7413f\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
              D:\APPS\Programmes\Android\Sdk\platforms\android-27\android.jar\
              --manifest\
              C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
              -o\
              C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
              -R\
              @C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
              --auto-add-overlay\
              --java\
              C:\Users\MYPC\Desktop\gpsloc\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
              --custom-package\
              com.example.gpsloc\
              -0\
              apk\
              --output-text-symbols\
              C:\Users\MYPC\Desktop\gpsloc\build\app\intermediates\symbols\debug\R.txt\
              --no-version-vectors
      Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 18s
    
    Gradle task 'assembleDebug'... Done                         18,8s
    Gradle task assembleDebug failed with exit code 1

> Flutter doctor

    Doctor summary (to see all details, run flutter doctor -v):
    [√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [version 10.0.17763.316], locale fr-FR)
    [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [√] Android Studio (version 3.2)
    [√] IntelliJ IDEA Community Edition (version 2018.3)
    [√] Connected device (2 available)

    • No issues found!

**Comment by dumpcoder** [comment]
I'm getting the exact same error. Don't know what to do.

**Comment by Kiani012** [comment]
I am also getting the same error :/

**Comment by xspid3r** [comment]
@dumpcoder @Kiani012 I fixed it by changing **compileSdkVersion** and **targetSdkVersion** to 28

**Comment by Kiani012** [comment]
Where can I change this compile and Target sdk version?

**Comment by dumpcoder** [comment]
@xspid3r It work! @Kiani012 Go to the 'andriod/app/build.gradle' to change.
