### ISSUE TITLE
 location.onLocationChanged().listen((Map<String, double> currentLocation) throwing error

### ISSUE THREAD

**Issue by fritz-playmaker** [Lyokone/flutterlocation#124]
Changed the version from `1.4.1` to `2.0.0` and the code which used to work is now throwing an error

var location = new Location();

location.onLocationChanged().listen((Map<String,double> currentLocation) {
  print(currentLocation["latitude"]);
  print(currentLocation["longitude"]);
  print(currentLocation["accuracy"]);
  print(currentLocation["altitude"]);
  print(currentLocation["speed"]);
  print(currentLocation["speed_accuracy"]); // Will always be 0 on iOS
});

**Comment by fritz-playmaker** [comment]
I have seen the changes in the docs. I'll advise that you put a vivid example in the READ.ME

Changes
Before (version1.4.1)  ===> Current (version 2.0.0)

Map<String, double> _startLocation; ===>  LocationData _startLocation;
Map<String, double> _currentLocation;  ===> LocationData _currentLocation;

_currentLocation["latitude"] ==>_currentLocation.latitude
_currentLocation["longitude"] ==>_currentLocation.longitude
_currentLocation["accuracy"] ==>_currentLocation.accuracy
_currentLocation["altitude"] ==>_currentLocation.altitude
_currentLocation["speed"] ==>_currentLocation.speed
_currentLocation["speed_accuracy"] ==>_currentLocation.speed_accuracy
_currentLocation["heading"] ==>_currentLocation.heading


###Old onLocationChanged CallBack
```
location.onLocationChanged().listen((Map<String,double> currentLocation) {
print(currentLocation["latitude"]);
print(currentLocation["longitude"]);
print(currentLocation["accuracy"]);
print(currentLocation["altitude"]);
print(currentLocation["speed"]);
print(currentLocation["speed_accuracy"]); // Will always be 0 on iOS
});

```

###Current onLocationChanged CallBack
```
location.onLocationChanged().listen((LocationData currentLocation) {
  print(currentLocation.latitude);
  print(currentLocation.longitude);
  print(currentLocation.accuracy);
  print(currentLocation.altitude);
  print(currentLocation.speed);
  print(currentLocation.speed_accuracy); // Will always be 0 on iOS
  print(currentLocation.heading);
});
```

**Comment by Nik4u22** [comment]
I was also facing the same issue as location.onLocationChanged() is not defined or invocked.

Request to make following changes will be helpful to run code successfully
<img width="526" alt="11" src="https://user-images.githubusercontent.com/64134540/85647333-dc563c00-b6bb-11ea-9626-421510b692f9.png">
<img width="572" alt="12" src="https://user-images.githubusercontent.com/64134540/85647338-e2e4b380-b6bb-11ea-8fa9-1d8f6b9e8170.png">


for more details request to visit 

https://pub.dev/packages/location

This will help to solve the issue
