### ISSUE TITLE
inconsistent behaviour (iOS vs. Android) when asking if permission is granted

### ISSUE THREAD

**Issue by PerrchicK** [Lyokone/flutterlocation#127]
Hi, I'm using this plugin for a while and it works great!
Let's improve it even more!

Description:
- in iOS, when using the `hasPermission` method the plugin immediately asks for permissions.
- some apps wouldn't like to immediately asks for permissions, but wait for user action instead.

Solved in PR: https://github.com/Lyokone/flutterlocation/pull/126

Thanks a lot!
Perry

**Comment by Lyokone** [comment]
Thanks again a lot for your PR ! :)
