### ISSUE TITLE
[iOS] location.hasPermision() returns true on the first time

### ISSUE THREAD

**Issue by PerrchicK** [Lyokone/flutterlocation#128]
### Description
in iOS, When calling `location.hasPermission()` for the first time the plugin returns `true` although it's not. The issue occurs because of this condition check: https://github.com/Lyokone/flutterlocation/blob/eb2fad8c064dbe52b0f7e357f3b9ec8a773bc314/ios/Classes/LocationPlugin.m#L83

The status is not `kCLAuthorizationStatusDenied` on the first time, it is actually `kCLAuthorizationStatusNotDetermined `.

### Fix
Fixed in this PR: https://github.com/Lyokone/flutterlocation/pull/126

The correct determination can be found here:
https://github.com/Lyokone/flutterlocation/pull/126/commits/866bd9426b95cf4a869c64b1b896e8846e918c4a#diff-a955000e105e0fd852921707f7924fccR103

**Comment by Lyokone** [comment]
Hey ! Thank you for all your contributions, I'll look into those during the weekend :D

**Comment by PerrchicK** [comment]
With pleasure.
Sounds great :)
