### ISSUE TITLE
[Android]  Error when app building on android.

### ISSUE THREAD

**Issue by md67167** [Lyokone/flutterlocation#130]
Finished with error: ProcessException: Process "E:\flutterWorkSpace\location\flutterlocation-master\example\android\gradlew.bat" exited abnormally:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
  Command: E:\flutterWorkSpace\location\flutterlocation-master\example\android\gradlew.bat -v

**Comment by Lyokone** [comment]
Hey ! Have you updated your app to AndroidX ?

**Comment by figengungor** [comment]
This issue occurs because the example project is missing the gradle-wrapper.jar. It is ignored by .gitignore.

**Comment by Lyokone** [comment]
Thanks for catching that, I've update the .gitignore
