### ISSUE TITLE
How to invoke LocationSettingsRequest.Builder() ?

### ISSUE THREAD

**Issue by tolotrasamuel** [Lyokone/flutterlocation#134]
I could not find on your api documentation how to enable the gps without navigating to settings althrough I found that your java code includes: LocationSettingsRequest.Builder()

**Comment by Lyokone** [comment]
Hey ! There is currently no way to enable the GPS exposed in Flutter. I'm pretty sure that exposing it for iOS would cause the app to be rejected by Apple Guidelines so there is no plan to have it directly in the plugin.

**Comment by tolotrasamuel** [comment]
Hey! I meant : enabling the GPS without redirecting the user to the setting screen as mentioned here on Flutter:  https://stackoverflow.com/questions/29744257/android-can-i-enable-the-gps-without-redirecting-the-user-to-the-settings-scree


In your LocationPlugin.java , you have the same lines here: 
```
try {
                            // Show the dialog by calling startResolutionForResult(), and check the
                            // result in onActivityResult().
                            ResolvableApiException rae = (ResolvableApiException) e;
                            rae.startResolutionForResult(activity, REQUEST_CHECK_SETTINGS);
                        } catch (IntentSender.SendIntentException sie) {
                            Log.i(METHOD_CHANNEL_NAME, "PendingIntent unable to execute request.");
                        }
```

But instead of opening the dialog, it just fails

**Comment by Lyokone** [comment]
Well this part of the code is only code a way of mitigating no Location Services for Android, It's only called for the listener. I'll call this bit of code for the one shot Location data too, but keep in mind that you should check the location service status before requesting location and gracefully handle no location services.
