### ISSUE TITLE
GPS not enabling

### ISSUE THREAD

**Issue by tolotrasamuel** [Lyokone/flutterlocation#136]
I used the version 2.1
When the GPS is turned off I get:
```
I/flutter ( 2767): Permission: true
I/flutter ( 2767): PlatformException(ERROR, Failed to get location., null)
``` 

I would expect a dialog to enable location service instead. What am I doing wrong ?

**Comment by Lyokone** [comment]
Hey, I'm developing a method to know whether or not the location service is enable, but I would suggest that you catch the exception and prompt the user to active the Service Location manually in the mean time. 
Tracking this in #92

**Comment by tolotrasamuel** [comment]
Thanks I see your update on 2.2
