### ISSUE TITLE
Update rate is 20 seconds

### ISSUE THREAD

**Issue by ride4sun** [Lyokone/flutterlocation#139]
I see an update rate around 20 seconds. Can I change that closer to once every second?
20 seconds is not useable for my use-case.

**Comment by Lyokone** [comment]
Hey ! I've planned to add options for accuracy and refresh rate for next version so it should come soon ;)

**Comment by Lyokone** [comment]
Hey ! f7f847d91baa10f9c4967bc003f06351e0db2586 added the possibility to set the precision and the refresh interval of Location Requests. I'll push it to 2.3 with a couple of other changes but if you want the update faster feel free to clone this ;)

**Comment by ride4sun** [comment]
Thanks - that helps a lot. What is the ETA for 2.3 ?

**Comment by Lyokone** [comment]
Hey, I just want to add distance filter for update first so 2.3 should be up before the end of the weekend 😉

**Comment by Lyokone** [comment]
I've just published it :)

**Comment by ride4sun** [comment]
Tanks for ur work. I will try it today.

**Comment by ride4sun** [comment]
I just tried it and the update rate is speeding up from 10 seconds to 1 Second as set in the settings. I guess that comes from finding the satellites after startup - right?
The units of the settings should be documented as ms - correct?


Thanks for your great work.
