### ISSUE TITLE
Error and Confusing doc

### ISSUE THREAD

**Issue by kingsleykbc** [Lyokone/flutterlocation#141]
Hi. your documentation is quite unclear, and there are a few errors i keep getting. 
1. The specific  build.gradle file we are supposed to modify isn't stated.
2. The on `PlatformException ` keyword says `PlatformException isn't a type and can't be used in an on-catch`
3. I'm getting a `A value of type 'LocationData' can't be assigned to a variable of type 'Type'` error.
It would be nice if you made your documentation more clear, as well as provide a full working example. Thank you

**Comment by Lyokone** [comment]
Hi,
1. I'm from an Android Background so it may be obvious for me but not for everyone, I'll update this.
2. The PlatformException is something generic, have your imported the necessary Flutter components as shown in the example ?
3. The example is what I always test my code against, if you clone the whole repository you should get a running example.
