### ISSUE TITLE
Error on iOS with "requestPermission"

### ISSUE THREAD

**Issue by darrencole** [Lyokone/flutterlocation#144]
Hi, thanks for the updates. They were exactly what I needed. One problem though. On iOS, `requestPermission()` seems to return `false` before the user can select deny or allow. Please correct this.

**Comment by Lyokone** [comment]
Hey ! Thanks for the notice, I'll look into that quickly !

**Comment by Lyokone** [comment]
2.3.1 fixes that and has been published.
