### ISSUE TITLE
Error Building building app in debug and release

### ISSUE THREAD

**Issue by abumoallim** [Lyokone/flutterlocation#145]
Suddenly my app is showing this error :

FAILURE: Build failed with an exception.

    What went wrong:
    Could not determine the dependencies of task ':app:preDebugBuild'.

    Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
    Could not resolve com.google.android.gms:play-services-location:15.+.
    Required by:
    project :app > project :location
    > Failed to list versions for com.google.android.gms:play-services-location.
    > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml.
    > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml'.
    > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by rchabot32** [comment]
same thing for me.

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
         project :app > com.google.android.gms:play-services-places-placereport:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       9.0s
Gradle task assembleRelease failed with exit code 1

**Comment by rchabot32** [comment]
it seems to be corrected

**Comment by abumoallim** [comment]
But caused that issue need to to be known. What if it repeats again when you are going to release an app ?

**Comment by abumoallim** [comment]
@rchabot32 I am still receiving the same thing.

**Comment by Lyokone** [comment]
Hey ! Do you have the right repository linked in your build.gradle ? https://stackoverflow.com/questions/46467561/difference-between-google-and-maven-url-https-maven-google-com

**Comment by abumoallim** [comment]
Yes , This is my Gradel file : `buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

Also what I think is when I try to debug the application this issue comes in the android studio. I think so.

**Comment by Lyokone** [comment]
Hum that's strange, what is the result of your Flutter Doctor ?

**Comment by abumoallim** [comment]
Result : 
```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_IN)
    • Flutter version 1.2.1 at /home/abubakker/flutterProjects/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/abubakker/Android/android-sdk-linux/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/abubakker/Android/android-sdk-linux
    • Java binary at: /home/abubakker/android-studio-3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at /home/abubakker/android-studio-3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code (version 1.32.3)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM J730GM • 520075d4e817740d • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.
```

**Comment by Lyokone** [comment]
If you have properly set `compileSdkVersion 28` in app/build.gradle, I would suggest to run `flutter clean` then retry to build. If it is still not working, you can maybe check if another plugin you are using is using another version of `com.google.android.gms`. FlutterLocation is using `com.google.android.gms:play-services-location:15.+`.

**Comment by abumoallim** [comment]
But it suddenly came. I didn't add any package for 2 days. and Everything was running fine.

**Comment by Lyokone** [comment]
Maybe one of your package updated its dependencies ?

**Comment by abumoallim** [comment]
But I think it points to this package : `project :app > project :location`

**Comment by abumoallim** [comment]
My Package List : 
```
cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.0
  http: ^0.12.0+1
  google_maps_flutter: ^0.4.0
  flutter_google_places: ^0.2.1
  geolocator: '^3.0.1'
  location : ^2.3.0
  shared_preferences : ^0.5.0+1
```

**Comment by Lyokone** [comment]
Well if the error is still only from the 502 code in your first message: https://status.bintray.com/.
It seems that the server got an error this morning. Should be resolved now.
(https://stackoverflow.com/questions/49510176/android-studio-gradle-sync-failed-could-not-head-received-status-code-5)

**Comment by abumoallim** [comment]
Again the Error Started. This is some new serious issue. I am working in android since long but never came up with this issue.

**Comment by Lyokone** [comment]
I can successfully build in debug and release, so it might be an issue with your internet connexion on your end ?

**Comment by abumoallim** [comment]
Are you using android studio ? Can you see if you can keep breakpoints ?

**Comment by Lyokone** [comment]
I'm not, I'm using Visual Studio Code, I can try tonight tho.

**Comment by abumoallim** [comment]
Ok

**Comment by night-wielder** [comment]
I am still having this problem.
It appears links like `https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-location/maven-metadata.xml` and other things are unaccessible.
