### ISSUE TITLE
WhenInUse & Always Permission

### ISSUE THREAD

**Issue by vincekruger** [Lyokone/flutterlocation#146]
Would it be possible to add two morer functions for ios?
- requestInUsePermission
- requrstAlwaysPermission

According to apples guidelines when you an app requests always access to the location, both NSLocationWhenInUseUsageDescription and NSLocationAlwaysAndWhenInUseUsageDescription are required.
NSLocationAlwaysUsageDescription is for iOS 10 and earlier.

**Comment by Lyokone** [comment]
Hey, background location is tracked in #110. It's the next feature I want to implement.
