### ISSUE TITLE
android build issue

### ISSUE THREAD

**Issue by comeonbuddy** [Lyokone/flutterlocation#147]
i am having an android build issue below, any idea whats happening?

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:15.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Could not list versions using M2 pattern 'https://raw.github.com/g123k/ShortcutBadger/master/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
            > Could not get resource 'https://raw.github.com/g123k/ShortcutBadger/master/com/google/android/gms/play-services-location/'.
               > Could not GET 'https://raw.github.com/g123k/ShortcutBadger/master/com/google/android/gms/play-services-location/'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Lyokone** [comment]
Hey ! 
It seems that you're trying to get the version from @g123k, I'm not sure how you installed the plugin ?

**Comment by franci22** [comment]
Hey everyone,
I think this issue ( and #145 ) is caused by the old version of play-services-location that is in conflict with other plugins:
https://github.com/Lyokone/flutterlocation/blob/ea5817b93e99f56173b9de9407c9c3c0106ae167/android/build.gradle#L42
I had the same problem and I tried to change it locally to 16.+ and it worked!

**Comment by Lyokone** [comment]
Hey ! Thanks for the info, Ill update it :)
