### ISSUE TITLE
Remove hardware requirement of GPS

### ISSUE THREAD

**Issue by philipgiuliani** [Lyokone/flutterlocation#148]
Because of a recent change, apps that use this library cannot be installed on devices without GPS (for example Chromebooks).

https://github.com/Lyokone/flutterlocation/blob/master/android/src/main/AndroidManifest.xml#L7

![Bildschirmfoto 2019-03-27 um 09 33 59](https://user-images.githubusercontent.com/5446019/55061271-97d09080-5073-11e9-9b2b-4e880c2e3462.png)

In red you can see the numbers of the devices which are not supported anymore.

**Comment by Lyokone** [comment]
Hey, I'll verify if `serviceEnabled()` is still working without this and remove it if so :)

**Comment by Lyokone** [comment]
It has been fixed and pushed with 2.3.2
