### ISSUE TITLE
location.altitude WGS 84 on Android and sea level on iOS

### ISSUE THREAD

**Issue by BirdyF** [Lyokone/flutterlocation#149]
Hi Lyokone,

Thanks for your work!  The package is working well for me.
But I noticed that the altitude given is different on Android and iOS.
Correct me if I am wrong but I think that altitude is on Android is WGS 84 (mentioned in your comment) but iOS is sea level.
Is there a way get sea altitude on Android too?

**Comment by Lyokone** [comment]
Hey ! Thanks I'm happy to know it helps people 😁
And thanks for noticing this, I'll correct it tommorow to align Android on sea level !

**Comment by Lyokone** [comment]
Hey, was harder than what I believe, but if you have enough satellite you will get the MSL altitude after a couple of seconds. Android and iOS altitude should be more consistent.

**Comment by BirdyF** [comment]
Thanks, that was quick!
I have tested 2.3.3 and with accuracy of 3m after 30 seconds I still found 30m difference between iOS and Android.
But I am not at my place for the moment so can not compare precisely because I dont know what is the right altitude.
I will try with more devices this week-end at a known altitude and will let you know.

**Comment by Lyokone** [comment]
Hey !
It relies heavily on the GPS precision and quality so it may be off a lot. During my testing I was within 10 meters of my actual elevation if I believe Google Maps.
The next step to get the most precise elevation would be to use Google's Elevation API ;)

**Comment by BirdyF** [comment]
Merci Guillaume.
In fact to check I can use IGN maps. For instance I know my home's altitude is very to close to 300m.
I can also go to a "point de nivellement" to get exact altitude 
[https://www.geoportail.gouv.fr/donnees/reseau-de-nivellementhttps://www.geoportail.gouv.fr/donnees/reseau-de-nivellement](url)
Sometimes it is good to be French!

I want to use off line (no Google API) because I am developing a small app for riders.
Next step after that for me is to use barometer in devices (starting from iPhone 6s and now a lot of Android phones) to get a precise total ascent (what the cyclist has climbed). But barometer are good to give  relative ascent. Using GPS altitude is good to know the absolute altitude.

**Comment by BirdyF** [comment]
Hi Guillaume,
After additional tests I think that there is still a problem to get sea level altitude on Android.

In front of my home I get:
- On iOS using flutter location between 300-310m (which is close to what IGN map shows).
- On Android using flutter location, around 350m with 3m accuracy
- With the altimer app on Android,  305-310m with 5m accuracy (elipsoid is at 367m)

I compared on the same device with this app 
[https://play.google.com/store/apps/details?id=com.arlabsmobile.altimeterfree&hl=fr](url)
The value given by your package is closer than elipsoid than sea level.

Let me know if you need more tests.

**Comment by Wackymax** [comment]
Hi,

Android now returns both WGS 84 and then later on MSL. This makes it difficult to correct the altitude based on location. Would it be possible to include a property to say what type of altitude is returned?
