### ISSUE TITLE
Error in getLocation()

### ISSUE THREAD

**Issue by HassanMeer** [Lyokone/flutterlocation#150]
`currentLocation = await location.getLocation();` not Working Shows redline.
and
```
location.onLocationChanged().listen((LocationData currentLocation) {
  print(currentLocation.latitude);
  print(currentLocation.longitude);
});
``` 
also not working properly after installation in virtual device first time its only allow the permission and don't get the value  longitutde and latitude etc , but after restart the application it will get latitude  values etc.

**Comment by Lyokone** [comment]
Hey, what do you mean by "show redline" ?
On which virtual device are you testing ? iOS simulator is having trouble putting realtime location.

**Comment by Lyokone** [comment]
Closed
