### ISSUE TITLE
Type error with getLocation();

### ISSUE THREAD

**Issue by MatyasK** [Lyokone/flutterlocation#152]
I'm trying to get user current location, but it doesn't work, I got this error: 
error: A value of type 'LocationData' can't be assigned to a variable of type 'Type'.
I have the latest version.

**Comment by Lyokone** [comment]
Hey ! Do you have any sample of code to show me what you're doing ? You have a working sample app to help you start.

**Comment by MatyasK** [comment]
sure here is the method: `void refresh() async {
    

    var currentLocation = LocationData;

    var location = new Location();

// Platform messages may fail, so we use a try/catch PlatformException.
    try {
      currentLocation = await location.getLocation();
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
        error = 'Permission denied';
      }
      currentLocation = null;
    }

    final GoogleMapController controller = await _controller.future;

//    controller.animateCamera(CameraUpdate.newCameraPosition(CameraPosition(target: LatLng(currentLocation["latitude"], currentLocation["longitude"]),zoom: 14)));
  }`

**Comment by Lyokone** [comment]
Well this is exactly what the error says: you are attributing to currentLocation the Type LocationData.
If you want to declare a variable this is the correct syntax in Dart:
`LocationData currentLocation`. 
Please check the sample app for more explanation.

**Comment by MatyasK** [comment]
well, that's totally my bad, thanks for the help!
