### ISSUE TITLE
What is the format of the timestamp

### ISSUE THREAD

**Issue by ride4sun** [Lyokone/flutterlocation#153]
not sure how to decode the double time stamp in the Location Data.
Would a String type not be more appropriate?

Can this be converted with?

> ${DateTime.fromMillisecondsSinceEpoch(int.parse(stream.data.dateTime))}')

If yes - could you add that to the documentation?

The opposite function would be :  DateTime.now().toUtc().millisecondsSinceEpoch.toString(),

**Comment by Lyokone** [comment]
Hey ! 
Yes it's exactly how you can convert it :)
``` dart
DateTime.fromMillisecondsSinceEpoch(result.time.toInt())
```
I'll add that to documentation since it can be useful for others.

**Comment by ride4sun** [comment]
Cool thanks
