### ISSUE TITLE
Error: null on first load though in Future await

### ISSUE THREAD

**Issue by carter3rix** [Lyokone/flutterlocation#155]
Added the location package recently and did all the required build.gradle setting.
`location: ^2.3.3`
But i noticed that data (LocationData) on first load print Error: null. I didn't noticed though i could see the error on the debugger until i build a new app using the default provided in the example which gave the same error.... also issue of 
`Future<Map<String, double>>someFunction()` of the LocationData or getLocation.
I hope i have a help out thank you...

**Comment by Lyokone** [comment]
Hey, I'm not sure if you are talking about the sample app, but its normal that the location is null for a little bit of time since they are defined before the location call.

**Comment by carter3rix** [comment]
> Hey, I'm not sure if you are talking about the sample app, but its normal that the location is null for a little bit of time since they are defined before the location call.

Alright  Understood..... Was not sure why it sets the Error Label if its a normal behaviour. Thank you. What of mapping the LocationData  Map<String, double> ?

**Comment by Lyokone** [comment]
Yeah i should probably say something like waiting, but the location could be null after the fix which could be an error.
