### ISSUE TITLE
Target of URI doesn't exist: 'package:location/location.dart'

### ISSUE THREAD

**Issue by MunasirPv** [Lyokone/flutterlocation#157]
When I am trying to import 'package:location/location.dart' After adding the dependency location: ^2.3.3. Showing the error "Target of URI doesn't exist: 'package:location/location.dart'".

**Comment by Lyokone** [comment]
Hey, have you try to run `flutter packages get` and to restart your IDE ?

**Comment by MunasirPv** [comment]
> Hey, have you try to run `flutter packages get` and to restart your IDE ?

Thank you, it is working fine.
