### ISSUE TITLE
Example code crashes on start

### ISSUE THREAD

**Issue by joshuamataaraya** [Lyokone/flutterlocation#158]
It shows the following error when I try to run the example code on a mac with an android emulator.:

I/Process (11873): Sending signal. PID: 11873 SIG: 9
Lost connection to device.

**Comment by Lyokone** [comment]
Hey, do you have any other errors to give ?
Can you have some logcat to provide ?

**Comment by joshuamataaraya** [comment]
It works now, I had to update the play services to be com.google.android.gms:play-services-base:16.0.1

**Comment by Lyokone** [comment]
Great, I've updated to 16+ for the next version of the plugin :)
