### ISSUE TITLE
Android dependency 'androidx.print:print:1.0.0-rc01' is set to compileOnly/provided which is not supported

### ISSUE THREAD

**Issue by h4m3d66** [Lyokone/flutterlocation#159]
Hi,
I got this error when I want to run the app after installing flutterlocation:
`Android dependency 'androidx.documentfile:documentfile:1.0.0-rc01' is set to compileOnly/provided which is not supported`

**Comment by Lyokone** [comment]
Hey, what other plugins do you have in your project ? :)

**Comment by h4m3d66** [comment]
this is my dependencies:

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences: ^0.5.1+2
  google_maps_flutter: ^0.5.3
  location: ^2.0.0
  cupertino_icons: ^0.1.2

**Comment by Lyokone** [comment]
Thanks, do you have perform the migration to AndroidX ?

**Comment by h4m3d66** [comment]
I'm very sorry, You are right, I did not performed the migration to AndroidX...

**Comment by Lyokone** [comment]
No problem ;)
