### ISSUE TITLE
AndroidX compatibility 

### ISSUE THREAD

**Issue by PDesire** [Lyokone/flutterlocation#161]
Gradle does not build the app, seems to be an AndroidX issue

Tested on:
 - Android, API Level 28 simulator

Logs:
`/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:14: error: package android.support.annotation does not exist
import android.support.annotation.MainThread;                           
                                 ^                                      
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:15: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;                              
                                 ^                                      
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:16: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;                             
                                 ^                                      
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:17: error: cannot find symbol
import android.support.v4.app.ActivityCompat;                           
                             ^                                          
  symbol:   class ActivityCompat                                        
  location: package android.support.v4.app                              
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:18: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;                        
                                 ^                                      
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:193: error: cannot find symbol
        int permissionState = ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION);
                              ^                                         
  symbol:   variable ActivityCompat                                     
  location: class LocationPlugin                                        
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:198: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
        ^                                                               
  symbol:   variable ActivityCompat                                     
  location: class LocationPlugin                                        
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:203: error: cannot find symbol
        return ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.ACCESS_FINE_LOCATION);
               ^                                                        
  symbol:   variable ActivityCompat                                     
  location: class LocationPlugin                                        
/home/android/Flutter/.pub-cache/hosted/pub.dartlang.org/location-1.4.1/android/src/main/java/com/lyokone/location/LocationPlugin.java:296: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {               
                                   ^                                    
  symbol: class NonNull                                                 
9 errors                                                                
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':location:compileDebugJavaWithJavac'.        
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         2,3s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
`

**Comment by PDesire** [comment]
Nevermind, my flutter failed upgrading

**Comment by Shtibel** [comment]
I have the same problem
How did you fix this ?

**Comment by PDesire** [comment]
@Shtibel remove package.lock and add the latest version to pubspec.yaml. Then try to get the packages again

**Comment by Shtibel** [comment]
@PDesire do you mean remove the pubspec.lock ?
