### ISSUE TITLE
Add Last know location feature

### ISSUE THREAD

**Issue by KlausJokinen** [Lyokone/flutterlocation#165]
https://developer.android.com/training/location/retrieve-current

That would speed up the one time location check.

**Comment by Lyokone** [comment]
Hey, I believe that if you request the location with the LocationAccuracy.POWERSAVE settings you will get the same kind of result, that means a not very accurate location.
Let me know if it suit you're usage or I'll check to add this in next version.

**Comment by aitorres** [comment]
Hello! I just came here with this request in mind hahaha
@Lyokone one question regarding your previous answer.

If I previously asked for a (most accurate) location, and then request the location again but with LocationAccuracy.POWERSAVE, will I get the previous result I already found?

I will try and test it, but I'm asking nonetheless. Thanks!

**Comment by sirkalmi** [comment]
This would be an essential service, I really miss it too, please do it!
