### ISSUE TITLE
Add function to open app settings

### ISSUE THREAD

**Issue by crisp00** [Lyokone/flutterlocation#166]
**Is your feature request related to a problem? Please describe.**
At the moment the library has some permission handling capabilities, but these are not complete without a function to open the Platform App Settings application to enable location or give permission once it has been erroneously denied.

**Describe the solution you'd like**
A function that when called will open the appropriate settings application depending on which platform it is running on. something like openAppSettings()

**Describe workarounds you've considered**
So far I've been using another library to do the permission handling, but that is really not necessary if I'm only using the location permission, I'd much rather have it all in the location library.
The problem with permission libraries is that they force you to declare permissions you are never planning to use when publishing on the App Store.

I feel like this library's permission handling capabilities would be complete with the addition of this function, eliminating the need for a second library.

**Comment by Lyokone** [comment]
Hey, I haven't considered the use case in which the user permanently disabled the location permission. I don't know if its considered as "Good Practice" to ask the user to go in Settings to change it again.
I'll check some things around this subject and update this thread.

**Comment by keane032** [comment]
i have the same problem
