### ISSUE TITLE
Add option to make library AppLifecycle aware

### ISSUE THREAD

**Issue by RyanRamchandar** [Lyokone/flutterlocation#167]
**Is your feature request related to a problem? Please describe.**
It would be nice if Location updates were lifecycle aware. Currently, we have to manage the `Location().onLocationChanged().listen()` stream ourself and manage when to pause, resume or cancel it.

**Describe the solution you'd like**
It would be nice to pause the location change stream when the App Lifecycle enters `AppLifecycleState.paused`, and resume the stream when the App Lifecycle enters `AppLifecycleState.resumed`.

Flutter provides multiple ways of handing AppLifecycle changes. Some of those ways are described here: https://stackoverflow.com/questions/49869873/flutter-update-widgets-on-resume.

It could be implemented with a fluent API call like:
```
Location().observeAppLifecycle(true)
```

**Describe workarounds you've considered**
Currently we have to manage the stream of location changes manually.

**Comment by Lyokone** [comment]
Hey ! Thanks for the nice description of the feature ;)
I'll be looking into adding this feature once the background location feature will be done :)

**Comment by RyanRamchandar** [comment]
Hey @Lyokone this one is waiting on your response. Should it be stale closed?
