### ISSUE TITLE
getLocation() hangs forever on Android

### ISSUE THREAD

**Issue by apgapg** [Lyokone/flutterlocation#169]
**Describe the bug**
If the location is off on android, then upon calling getLocation(), a dialog pops up "For a better experience, turn on device location....". If one clicks NO, THANKS, the getLocation() isnt returning any error etc. The code hangs on that getLocation() code.

**Expected behavior**
Exception to be thrown that location is off

**Tested on:**
 - Android, API Level [e.g. 27] real device (LINEAGE OS)

**Additional logs**
No Logs

**The dialog**
![Screenshot_20190418-150322_Google_Play_services](https://user-images.githubusercontent.com/13887407/56351763-759dde80-61eb-11e9-9c17-6993fa1fbe47.png)

**Comment by Lyokone** [comment]
Hey ! Thanks for the report, I'll check this out as soon as possible ;)

**Comment by apgapg** [comment]
I guess you can provide a certain duration timer for fetching location. This will throw exception after the timer completes if location isnt available

**Comment by RyanRamchandar** [comment]
@apgapg is your device using Google Play Services or an alternative like MicroG?
I've seen issues related to that framework and Android location in general.

**Comment by apgapg** [comment]
Yes My device use Google play services. This isnt my device specific issue. All of the devices that i came across have this issue. 
I tried to use timer in flutter for the workaround. But thats makes code complicated

**Comment by apgapg** [comment]
Any progress on this issue?

**Comment by ratinggorilla** [comment]
Yes this issue persists... Please reopen. Its stuck on `await location.getLocation()`

**Comment by cassioseffrin** [comment]
Any update on this? It's the same for me using real devices. It's happening when GPS is disabled for any apps and the permission for use GPS on the flutter app is enabled.

**Comment by cassioseffrin** [comment]
While this issue haven't fixed yet I have made a workaround setting a timeout. It's not so complicated.

The workaround:
```
        try {
          pos = await getLocation().timeout(Duration(seconds: 4));
        } on TimeoutException catch (_) {
          print('A timeout occured when getting location');
        }
```
