### ISSUE TITLE
Widget Enlightenment

### ISSUE THREAD

**Issue by ljfreelancer88** [Lyokone/flutterlocation#17]
Hi, newbie here using flutter. I just want some enlightenment on this widget/module. Because I'm planning to create a map where i call "loop all lat & lng from Firebase" w/ marker, and when i click one of those marker, a modal will pop-up and show the Name of that person.

**Here are the things that i want to know.**
(1) Is this something like Geolocation Watch? 
(2) How to add marker if possible.
(3) Any documentation how to loop json fetch from Firebase or to make it short, a manual on how to use it.

Thank You.

**Comment by avioli** [comment]
It is similar to the browser's [`navigator.geolocation.watchPosition`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition) and [`navigator.geolocation.getCurrentPosition`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition).

As `navigator.geolocation` doesn't do markers - this doesn't either.

Sorry, but probably no-one here will help you with how to work with Firebase, nor how to decode and parse your JSON. For these - read the documentation on both Firebase's website and re JSON - on Flutter/Dart. They are very good and elaborate. The Firebase package for Flutter has a good example how to decode your JSON.
