### ISSUE TITLE
Get current Location Service Mode

### ISSUE THREAD

**Issue by venkata-ramana** [Lyokone/flutterlocation#171]
**Is your feature request related to a problem? Please describe.**
Location Service is turned on, but location accuracy is changed to device only mode. By this method 
```
var locationMode = getCurrentLocationMode();
```
will return the current mode, thus allowing the developer to ask  the user to change the accuracy or trigger from app by using the existing method, 
```
changeSettings({LocationAccuracy accuracy: LocationAccuracy.HIGH, int interval: 1000, double distanceFilter: 0})
```

**Describe the solution you'd like**
```
var locationMode = getCurrentLocationMode();
```
Where locationMode will a enum.

**Comment by Lyokone** [comment]
Hello, this feature makes perfect sense, I'll probably add it before Background Location,
thanks !
