### ISSUE TITLE
Background location tracking

### ISSUE THREAD

**Issue by MichalMisiaszek** [Lyokone/flutterlocation#180]
**Is your feature request related to a problem? Please describe.**
I am using your plugin in app which tracks user location on request, using Bluetooth GPS trackers for better accuracy. If app goes to background the Flutter thread gets suspended so no location updates are generated. This requires implementation of Isolate and some callback mechanism to update app when woken up. 

**Describe the solution you'd like**
Collect location updates in background and push them to app when back in foreground.

**Describe workarounds you've considered**
Pay $300 for commercial plugin doing just that.

**Additional context**

**Comment by Lyokone** [comment]
Hey, have you seen this page of the wiki ? https://github.com/Lyokone/flutterlocation/wiki/Background-Location-Updates
Please let me know it this don't resolve your problem.

**Comment by MichalMisiaszek** [comment]
Thanks I have not seen it yet, I will check it out. My use case it to keep collecting location updates from an app which goes to background, it is not shutdown (which is probably the same on iOS).

**Comment by sjmcdowall** [comment]
@Lyokone -- Ok I need this as well, and I will give it a try tomorrow -- however, one question that I don't see .. how does one set how OFTEN one wants to get an update?  To save battery life I only need an update in the background every 5 minutes or so .. but in the foreground I have a timer to get it every 1 minute.. (I just poll every 1 minute currently) ... 

In any event -- I would like to set the background "timer" to send it every "so" often ...

Also I am on iOS -- don't we need to set any of the UIBackGroundModes?  Else I read that iOS will stop the app after 10 minutes? 

```
	<key>UIBackgroundModes</key>
	<array>
		<string>voip</string>
		<string>location</string>
	</array>
```

??

Cheers!

**Comment by erikmejias** [comment]
> @Lyokone -- Ok I need this as well, and I will give it a try tomorrow -- however, one question that I don't see .. how does one set how OFTEN one wants to get an update? To save battery life I only need an update in the background every 5 minutes or so .. but in the foreground I have a timer to get it every 1 minute.. (I just poll every 1 minute currently) ...
> 
> In any event -- I would like to set the background "timer" to send it every "so" often ...
> 
> Also I am on iOS -- don't we need to set any of the UIBackGroundModes? Else I read that iOS will stop the app after 10 minutes?
> 
> ```
> 	<key>UIBackgroundModes</key>
> 	<array>
> 		<string>voip</string>
> 		<string>location</string>
> 	</array>
> ```
> 
> ??
> 
> Cheers!

Did you find a way to do it? I was digging into the java source files with no results so far.

**Comment by Lyokone** [comment]
> @Lyokone -- Ok I need this as well, and I will give it a try tomorrow -- however, one question that I don't see .. how does one set how OFTEN one wants to get an update? To save battery life I only need an update in the background every 5 minutes or so .. but in the foreground I have a timer to get it every 1 minute.. (I just poll every 1 minute currently) ...
> 
> In any event -- I would like to set the background "timer" to send it every "so" often ...
> 

Hey, for now, i'm relying on Android and iOS "timer" to get update as often as possible. Those things, specially on Android harder and harder to set in newer version of the OS, so relying on OS choosing callback time is the way to go imo.

> Also I am on iOS -- don't we need to set any of the UIBackGroundModes? Else I read that iOS will stop the app after 10 minutes?
> 
> ```
> 	<key>UIBackgroundModes</key>
> 	<array>
> 		<string>voip</string>
> 		<string>location</string>
> 	</array>
> ```
> 
> ??
> 
> Cheers!

I'll look into this, I actually don't have any iOS real device to test my plugin so I'm heavily relying on iOS simulator.

**Comment by Lyokone** [comment]
To clarify things, and be sure we are talking about the same thing, the background plugin is for background wake up of the application when it has been closed.

**Comment by sjmcdowall** [comment]
@Lyokone -- Ok .. that is good to know.  How would I also get location updates when the App is not closed? I.e. it's running -- well -- "in the background" .. :)

**Comment by MichalMisiaszek** [comment]
So I believe there are two scenarios

1. App goes into background, no active thread and location not pulled.
2. App is closed (deliberately or accidentally). 

I am looking for solution to 1. I want location updated every 5 seconds in fact.

**Comment by sjmcdowall** [comment]
@MichalMisiaszek -- Pretty much the scenario I am hoping to solve as well .. but #2 is pretty cool but not as interesting .. (to me).

**Comment by MichalMisiaszek** [comment]
Yes, and I think this implementation do not provide it, does it ? Honestly I did not get to try it yet.

**Comment by fre391** [comment]
> Hey, have you seen this page of the wiki ? https://github.com/Lyokone/flutterlocation/wiki/Background-Location-Updates
> Please let me know it this don't resolve your problem.

Hey, I followed your instructions from the wiki carefully and tested the background functionality on Android 9 (Pixel 3a). I was able to get location update constantly, but whenever I  a) switch to another app in the background or b) when I shut off the display, the sample app seems to freeze. No location updates per notification delivered. When I switch the app to the foreground again it continues delivering location updates... I dont get an error message. 

Would be happy to get your feedback on this...Would be also happy to help in debugging (on Android). Thx for your work on this!

**Comment by sjmcdowall** [comment]
@Lyokone  -- I am trying this on iOS (finally) and I don't understand how this is supposed to work (and it's not) .. 

I also do not understand this rather obscure instruction in the Wiki 

_Please note that you need to have the location permission checked in order to receive background location._

What does that mean!?? What exactly needs to be done?  

This is on iOS -- and I am not seeing the registered plugin (exactly the same as the sample code) being called .. 

Also -- is the background callback only called when in the background?  (I know this sounds obvious but who knows) .. :) 

So in my logs I get:

```
flutter: FINE: 2019-06-19 19:49:05.561515: home - [_registerListener] - statusBackgroundLocation: true
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
...
<go into background>
r: FINER: 2019-06-19 19:54:04.645475: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:04.656702: home - Got location data of Lat<37.33340488> - Long<-122.02360226>
flutter: Received in Flutter, trying to dispatch
flutter: FINER: 2019-06-19 19:54:04.656995: carbyne_aml - [sendLoationUpstream] - Push AML Service invoked
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: FINER: 2019-06-19 19:54:04.657210: carbyne_aml - Service End point is: https://aml-service-dev.carbyneapi-dev.com/AMLService/ELS
flutter: FINE: 2019-06-19 19:54:05.163555: carbyne_aml - POST response is - status: <200 and <{"status":true}>
flutter: FINE: 2019-06-19 19:54:05.324226: home - Application eneterd state <AppLifecycleState.paused>
flutter: FINER: 2019-06-19 19:54:05.324555: home - Setting update refresh to 5 seconds
flutter: FINER: 2019-06-19 19:54:10.327690: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:10.332914: home - Got location data of Lat<37.33340488> - Long<-122.02360226>
flutter: FINER: 2019-06-19 19:54:10.333151: carbyne_aml - [sendLoationUpstream] - Push AML Service invoked
flutter: Received in Flutter, trying to dispatch
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: FINER: 2019-06-19 19:54:10.333343: carbyne_aml - Service End point is: https://aml-service-dev.carbyneapi-dev.com/AMLService/ELS
flutter: FINE: 2019-06-19 19:54:10.835232: carbyne_aml - POST response is - status: <200 and <{"status":true}>
flutter: FINER: 2019-06-19 19:54:15.328117: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:15.337940: home - Got location data of Lat<37.33340488> - Long<-122.02360226>
flutter: FINER: 2019-06-19 19:54:15.338185: carbyne_aml - [sendLoationUpstream] - Push AML Service invoked
flutter: Received in Flutter, trying to dispatch
flutter: FINER: 2019-06-19 19:54:15.338396: carbyne_aml - Service End point is: https://aml-service-dev.carbyneapi-dev.com/AMLService/ELS
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: FINE: 2019-06-19 19:54:15.824806: carbyne_aml - POST response is - status: <200 and <{"status":true}>
flutter: FINER: 2019-06-19 19:54:20.327573: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:25.329439: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:30.326699: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:35.330469: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:40.330819: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:45.326085: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:50.329620: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:54:55.328498: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:55:00.326414: home - [_setLocationData()]
flutter: FINER: 2019-06-19 19:55:05.329645: home - [_setLocationData()]


  static void backgroundCallback(List<LocationData> locations) {
    logger.finer(
        '[backgroundCallback] - BACKGROUND!! - Location data received from background: $locations');
  }

But I am not seeing my logger.finer() and after the first call .. it doesn't (as far as I can see) get called again? 

This is on an iOS simulator .. if that makes a difference? 

I am really not sure how this is supposed to work -- but I am willing to help debug if that helps ..
