### ISSUE TITLE
Permission being set is "wrong" one -- 

### ISSUE THREAD

**Issue by sjmcdowall** [Lyokone/flutterlocation#182]
**Describe the bug**
I need to do location detection in the background, etc. So I need the "Always" permission to be set -- yet when it asks it's setting the "While Using the App" permission.  I have the following in my Plist.info :
```
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>This app needs access to location when open and in the background.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to location when running in the foreground.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This app needs access to location when in the background.</string>
```

**Expected behavior**
I would hope the most permissive of the options (in iOS) would be set if needed? 

**Tested on:**
 - iOS, Version 12.2 [e.g. 10], simulator iPhone Xr

**Other plugins:**

I don't think any would interfere since none ask for any permissions .. but here is the list

 ```
  device_info: ^0.4.0+1
  dynamic_theme: ^1.0.1
  fluro: ^1.4.0
  flutter_secure_storage: ^3.1.1
  location: ^2.3.5
  logging: ^0.11.3+2
  native_widgets: ^1.0.0
  package_info: ^0.4.0
```

**Additional logs**

Nothing to see since it's all magic in the background ..

**Comment by sjmcdowall** [comment]
Looking at the code and the docs -- I don't think you are doing the logic right to request permission.. 

Here are the doc's
Overview

- To configure always authorization for location services, follow these steps (Listing 1 demonstrates steps 3-5):

- Add the NSLocationWhenInUseUsageDescription key and the NSLocationAlwaysAndWhenInUseUsageDescription key to your Information Property List file. (Xcode displays these keys as "Privacy - Location When In Use Usage Description" and "Privacy - Location Always and When In Use Usage Description" in the property list editor.)

- If your app supports iOS 10 and earlier, add the NSLocationAlwaysUsageDescription key to your Information Property List file. (Xcode displays this key as "Privacy - Location Always Usage Description" in the Info.plist editor.)

- Create and configure your CLLocationManager object.

- Call the requestWhenInUseAuthorization() initially to enable your app's basic location support.

- Call the requestAlwaysAuthorization() method only when the user enables a feature of your app that requires that level of authorization.


The code though looks like:

```
-(void) requestPermission {
    if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationWhenInUseUsageDescription"] != nil) {
        [self.clLocationManager requestWhenInUseAuthorization];
    }
    else if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"] != nil) {
        [self.clLocationManager requestAlwaysAuthorization];
    }
    else {
        [NSException raise:NSInternalInconsistencyException format:@"To use location in iOS8 and above you need to define either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in the app bundle's Info.plist file"];
    }
}
```

From what I can see there are 2 issues:

1. Code isn't checking for the "newer" (> iOS 10?) key ** NSLocationAlwaysAndWhenInUseUsageDescription**
2. The code should check the more permission option FIRST (one of the 2 always) and set the ALWAYS if that is set .. instead of checking the least permissive if both are set?

**Comment by sjmcdowall** [comment]
I am actually wondering if the code needs to FIRST call when USAGE .. and then call ALWAYS if set .. I removed the NSLocationWhenInUseUsageDescription -- and I no longer see the pop up authorization message .. at all!  Just hangs!

**Comment by Lyokone** [comment]
Hey,

Sorry for the delay in the response. Are you using the correct version of the location plugin ?
```
dependencies:
  location:
    git:
      url: git://github.com/Lyokone/flutterlocation.git
      ref: background_location
```

Have you looked at the sample project permissions?
```
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>I need it in background</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Because</string>
```

**Comment by sjmcdowall** [comment]
I am currently still using the "normal" version -- haven't tried the background version yet since I am concentrating on current location when in foreground -- but will try.

However, again -- it is only asking me to Permit When In Use -- and doesn't ever ask for ALWAYS -- and yes I have those strings set in Info.Plist .. Take a look at the code snippet and you can see why it wouldn't ask for ALWAYS .. (at least in the master branch)

**Comment by ozzy91** [comment]
This issue still exists and the background_location branch is far behind master.
