### ISSUE TITLE
[Question] How can i import plugin background in ios swift

### ISSUE THREAD

**Issue by duongtruong12** [Lyokone/flutterlocation#186]
i got a class ios build in swift code like this:

import UIKit
import Flutter
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("***************************************************")
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

i want to import locationPluginBackground like this in android     LocationPlugin.setPluginRegistrant(this)

but i dont know how can anyone show me pls thank you

**Comment by lyseiha** [comment]
why not answer?
