### ISSUE TITLE
iOS does not build

### ISSUE THREAD

**Issue by Salvatore-Giordano** [Lyokone/flutterlocation#19]
This is the error it gives: 

`GeneratedPluginRegistrant.m:6:9: fatal error: 'location/LocationPlugin.h' file not found
    #import <location/LocationPlugin.h>`

**Comment by jalakoo** [comment]
I'm encountering the same issue. Is it because the pod file needs to be completed?

**Comment by MizukiSonoko** [comment]
I'm encountering this too.
and I solved it (still I think dirty solution....) 

### Step 1)
`mkdir ios/Pods/Headers/location/`
### Step 2)
`cp  ~/.pub-cache/hosted/pub.dartlang.org/location-1.1.7/ios/Classes/   ios/Pods/Headers/location/`
### Step 3)
- Open Xcode
- Build settings -> Search Paths -> Header Search Paths
Add `"${PODS_ROOT}/Headers"` to Header Search Paths
### Step 4)
Run

In my opinion, This solution is not correct, so Could you tell me correct it 🙇

**Comment by JoeCherry** [comment]
If you created your flutter project with the iOS flag, follow the instructions here https://github.com/flutter/flutter/issues/15099
