### ISSUE TITLE
Issue with AndroidX

### ISSUE THREAD

**Issue by RubenPividori** [Lyokone/flutterlocation#190]
I've a failure building the app, seems to be an AndroidX compatibility issue.
I need to use the 1.4.1 version to avoid AndroidX, but something goes wrong...

This is the report:
Launching lib\main.dart on SM J530F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
D8: Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\53.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\58.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\59.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\62.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\63.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\65.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\66.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\68.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\69.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\70.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\73.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\76.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\78.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

My android\build.gradle is

buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

What can I do? Thanks in advance

**Comment by pratik037** [comment]
> I've a failure building the app, seems to be an AndroidX compatibility issue.
> I need to use the 1.4.1 version to avoid AndroidX, but something goes wrong...
> 
> This is the report:
> Launching lib\main.dart on SM J530F in debug mode...
> Initializing gradle...
> Resolving dependencies...
> Running Gradle task 'assembleDebug'...
> D8: Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> 
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\53.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\58.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\59.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\62.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\63.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\65.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\66.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\68.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\69.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\70.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\73.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\76.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\r.pividori\AndroidStudioProjects\sirp2\build\app\intermediates\transforms\dexBuilder\debug\78.jar
> > Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
> > Program type already present: android.support.v4.media.MediaBrowserCompat$ConnectionCallback$ConnectionCallbackInternal
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 11s
> 
> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> 
> Finished with error: Gradle task assembleDebug failed with exit code 1
> 
> My android\build.gradle is
> 
> buildscript {
> ext.kotlin_version = '1.2.71'
> repositories {
> google()
> jcenter()
> }
> 
> ```
> dependencies {
>     classpath 'com.android.tools.build:gradle:3.2.1'
>     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> }
> ```
> 
> }
> 
> allprojects {
> repositories {
> google()
> jcenter()
> }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
> project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
> project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
> delete rootProject.buildDir
> }
> 
> What can I do? Thanks in advance

Trying enabling multidex option maybe in android gradle file
