### ISSUE TITLE
background location update parameters

### ISSUE THREAD

**Issue by AF340** [Lyokone/flutterlocation#191]
Hi, Is there a way to set the time period of background location updates?
3/4 times per hour is too low to detect when enterring an area as example.
Thx

**Comment by sjmcdowall** [comment]
@AF340  - Did you get background location stuff working at all??  What platform?

**Comment by AF340** [comment]
Yes, I use it on android 9 and works fine, but with background, i"d like to increase the frequency.

**Comment by AF340** [comment]
UP

**Comment by 2277Dhruv** [comment]
Anyone getting this error when trying the background?

The method 'registerBackgroundLocation' isn't defined for the class 'Location'.
Try correcting the name to the name of an existing method, or defining a method named 'registerBackgroundLocation'.

**Comment by adim86** [comment]
```
await _locationService.changeSettings(
        accuracy: LocationAccuracy.HIGH, interval: 1000);
```

This calls the update every 1 second

**Comment by AF340** [comment]
> @AF340
> 
> ```
> await _locationService.changeSettings(
>         accuracy: LocationAccuracy.HIGH, interval: 1000);
> ```
> 
> This calls the update every 1 second

I tried this, but it only works when the app is in foreground for me, it works for u in bg? thanks

**Comment by angel1st** [comment]
@AF340 - when the app is in the background, so called fetch-event can occur once per every 15 minutes. This is the fastest frequency and this is limited by OS.
