### ISSUE TITLE
run in background after reboot

### ISSUE THREAD

**Issue by jack-adam** [Lyokone/flutterlocation#193]
hi thank you for the awesome plugin. my problem is i dont know if its possible to run the plugin automatically in the background after the phone is restarted. i am able to run the location in the background no problem, even after app is closed and that is indeed great, but after boot i cant get it to activate. i use background_fetch to trigger the requestPermission method and catcherror tells me "I/flutter ( 1953): error MissingPluginException(No implementation found for method requestPermission on channel lyokone/location)".. the plugin is not missing and as i mentioned everything works in background with app closed. only after reboot is it a problem. of course if i reopen the app after boot  and close the app its working nicely in background, but doing all of that is overkill. need plugin to work soon as phone boots. thank you!

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device

dependencies:
  location:
    git:
      url: git://github.com/Lyokone/flutterlocation.git
      ref: background_location  
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.16
  #location: ^2.3.5
  geoflutterfire: ^2.0.3+4
  cloud_firestore: ^0.11.0+2
  firebase_core: ^0.4.0+1
  rxdart: ^0.22.0
  connectivity: 0.4.3+1
  firebase_auth: ^0.11.1+5
  google_sign_in: ^4.0.2
  bloc_pattern: ^2.1.9+3
  background_fetch: '^0.2.0'

**Comment by lyseiha** [comment]
+1
