### ISSUE TITLE
Background location keeps firing even after I call removeBackgroundLocation()

### ISSUE THREAD

**Issue by sjmcdowall** [Lyokone/flutterlocation#196]
**Describe the bug**
I am using the beta Background location.  Once I register it fires the callback as expected. However, it CONTINUES to fire the callback even after I call removeBackgroundLocation().

**Expected behavior**
The callback shouldn't fire after calling removeBackgroundLocation()

**Tested on:**
 - iOS, Version iPhone Xr and X V12.2, Xr Sim -- X Real

**Other plugins:**
None

**Additional logs**

``` shell
**flutter: FINER: 2019-06-21 14:55:53.207118: home - [_removeListener] Unregistering background location getter**
flutter: FINER: 2019-06-21 14:55:53.207492: home - Setting update refresh to 5 seconds
flutter: FINER: 2019-06-21 14:55:53.207884: home - [build()]
flutter: FINER: 2019-06-21 14:55:53.208109: home - [_mainBody()]
flutter: FINER: 2019-06-21 14:55:58.211137: home - [_setLocationData()]
flutter: FINER: 2019-06-21 14:55:58.216371: home - Got location data of Lat<37.4950032> - Long<-122.30641809>
**flutter: Received in Flutter, trying to dispatch**
flutter: FINER: 2019-06-21 14:55:58.216688: carbyne_aml - [sendLoationUpstream] - Push AML Service invoked
**flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.**
flutter: FINER: 2019-06-21 14:55:58.216850: carbyne_aml - Service End point is: https://aml-service-dev.carbyneapi-dev.com/AMLService/ELS
flutter: Location data received from background: [Instance of 'LocationData']
flutter: Received in Flutter, trying to dispatch
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: Location data received from background: [Instance of 'LocationData']
flutter: FINE: 2019-06-21 14:55:58.997310: carbyne_aml - POST response is - status: <200 and <{status: true}>
flutter: FINER: 2019-06-21 14:55:58.998027: home - [build()]
flutter: FINER: 2019-06-21 14:55:58.998189: home - [_mainBody()]
flutter: FINER: 2019-06-21 14:56:03.210669: home - [_setLocationData()]
flutter: FINER: 2019-06-21 14:56:03.215898: home - Got location data of Lat<37.4950032> - Long<-122.30641809>
flutter: Received in Flutter, trying to dispatch
flutter: FINER: 2019-06-21 14:56:03.216132: carbyne_aml - [sendLoationUpstream] - Push AML Service invoked
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: FINER: 2019-06-21 14:56:03.216942: carbyne_aml - Service End point is: https://aml-service-dev.carbyneapi-dev.com/AMLService/ELS
flutter: Location data received from background: [Instance of 'LocationData']
flutter: Received in Flutter, trying to dispatch
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: Location data received from background: [Instance of 'LocationData']
flutter: FINE: 2019-06-21 14:56:04.020493: carbyne_aml - POST response is - status: <200 and <{status: true}>
flutter: FINER: 2019-06-21 14:56:04.021226: home - [build()]
flutter: FINER: 2019-06-21 14:56:04.021440: home - [_mainBody()]
flutter: FINER: 2019-06-21 14:56:08.211829: home - [_setLocationData()]
flutter: FINER: 2019-06-21 14:56:08.217211: home - Got location data of Lat<37.4950032> - Long<-122.30641809>
flutter: Received in Flutter, trying to dispatch
flutter: FINER: 2019-06-21 14:56:08.217758: carbyne_aml - [sendLoationUpstream] - Push AML Service invoked
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: FINER: 2019-06-21 14:56:08.218081: carbyne_aml - Service End point is: https://aml-service-dev.carbyneapi-dev.com/AMLService/ELS
flutter: Location data received from background: [Instance of 'LocationData']
flutter: Received in Flutter, trying to dispatch
flutter: handlerRawr Closure: (List<LocationData>) => void from Function 'backgroundCallback': static.
flutter: Location data received from background: [Instance of 'LocationData']
flutter: FINE: 2019-06-21 14:56:08.978231: carbyne_aml - POST response is - status: <200 and <{status: true}>
flutter: FINER: 2019-06-21 14:56:08.978907: home - [build()]
flutter: FINER: 2019-06-21 14:56:08.979050: home - [_mainBody()]
flutter: FINER: 2019-06-21 14:56:13.213476: home - [_setLocationData()]
flutter: FINER: 2019-06-21 14:56:13.218838: home - Got location data of Lat<37.4950032> - Long<-122.30641809>
flutter: FINER: 2019-06-21 14:56:13.219107: carbyne_aml - [sendLoationUpstream] - Push AML Service invoked
```

**Comment by sjmcdowall** [comment]
Perhaps this is a hint on how to properly turn these off on iOS? 

https://developer.apple.com/documentation/corelocation/cllocationmanager/1620568-allowsbackgroundlocationupdates

Perhaps toggling this based on registering a callback and deregistering one?

**Comment by sjmcdowall** [comment]
Also -- even with backgroundRegistry turned on -- after 10 minutes the app is "killed" and no more updates are being sent (that I can tell) ... how is this supposed to work exactly?

**Comment by sjmcdowall** [comment]
Well -- ok -- I built a production build and uploaded to Testflight -- and the app does NOT update at all in the background .. in "inactive" mode (i.e. slight swipe up) it does update .. but when put into "paused" (i.e. fully in the background) there are no updates occurring that I can see.  

Debug mode seems to run a lot differently than in a production build mode.. <shrug>

**Comment by billy124** [comment]
Hi @sjmcdowall,

I am having issues with trying to stop the background location from firing, can you please tell me if you managed to fix this, and how you actually closed the location subscription?


// start the connection subscription
    _connectivitySubscription =
        _connectivity.onConnectivityChanged.listen(_connectionStatusCallback);


I have tried the below in dispose
_locationSubscription.cancel();


however no joy.

**Comment by sjmcdowall** [comment]
Yeah -- I have been looking at this code -- and to be honest I don't think this approach is on the right track.  Instead I am looking at (kicking the tires) using the flutter plugin [Background location](https://github.com/flutter/plugins/tree/master/packages/location_background).

That is iOS only though .. which is fine for me as it turns out .. the example works perfect.  :) 

Maybe this would work though? 

https://pub.dev/packages/flutter_background_geolocation

Good luck!

**Comment by billy124** [comment]
Hey @sjmcdowall,

Thank you for our reply, I have had a look at this https://pub.dev/packages/flutter_background_geolocation already, unfortunately, it's a paid-for plugin.


I believe the issue is related to dispose() not running, on the initial page, ass you go forward down the tree, however as I am running the subscription on the landing page, there is no way to go back from this page.

**Comment by sjmcdowall** [comment]
How about the other free package?  The flutter plugin one?  

https://github.com/flutter/plugins/tree/master/packages/location_background

 And yeah, dispose() shouldn't be called (too often) .. why not do the .cancel() based of a page transition / route transition or something other than dispose()?  However, again, when I tried it (from a transition going from background to foreground) it never worked anyway..
