### ISSUE TITLE
No exception thrown when user denied.

### ISSUE THREAD

**Issue by lasseschmitt** [Lyokone/flutterlocation#20]
Hey, 

when the user does not accept the location permission (iOS) then there is no way to figure this out. I would accept that

```
var currentLocation = <String, double>{};

var location = new Location();

// Platform messages may fail, so we use a try/catch PlatformException.
try {
  currentLocation = await location.getLocation;
} on PlatformException {
  currentLocation = null;
}
``` 

throws an exception

**Comment by Lyokone** [comment]
Hey ! Sorry for the late response, you should be able to manage this with `requestPermission` and `hasPermission`. Moreover, on getLocation, the plugin will try to request permission for you.
Good day !
