### ISSUE TITLE
Background location service is not working.

### ISSUE THREAD

**Issue by shah-xad** [Lyokone/flutterlocation#200]
**Describe the bug**
I am just running your example [sample_background_updates](https://github.com/Lyokone/flutterlocation/tree/background_location/example/sample_background_updates) its working when app is in foreground, but if application is minimized or switch to another application, even when screen is turned off, It stops the call back..

**Expected behavior**
It should work in background as mentioned..

**Tested on:**
For now I just want it for android and test it at android API level 26 ,27 and 28.

**Comment by HardikkMadaan** [comment]
Any success ? I am also trying the same but no luck

**Comment by shahxadakram** [comment]
No success, But I found that service is always running in background, If I open any other location based application , It again starts sending  notifications.... But don't know how to sustain it without having any app(location based) in foreground.

**Comment by shahxadakram** [comment]
I have developed a working plugin for android which is working fine [background_location_service](https://github.com/shahxadakram/background_location_service) , Its only for android as I don't have a mac for iOS development..

**Comment by Zaxist** [comment]
I am also seeing this with the sample app. It keeps sending location updates for a few seconds after I go out of the app, but then stops until you go back to it.

**Comment by RomanJos** [comment]
The stale bot is so annoying, this issue need more attention. I'm also looking for a plugin similar to background_locator without its bug and limitations.

**Comment by shah-xad** [comment]
> The stale bot is so annoying, this issue need more attention. I'm also looking for a plugin similar to background_locator without its bug and limitations.

This issue has been resolved. Try the latest version.

**Comment by RomanJos** [comment]
Thank you for your reply ! I tried to implement it in my app but I need to have the location proces as a service unfortunately, I'm storing the positions in a file even if the app close so I'm stuck with background_locator 😓
