### ISSUE TITLE
Cant stop onLocationChanged Stream.

### ISSUE THREAD

**Issue by Iampopal** [Lyokone/flutterlocation#205]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe workarounds you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: do you know any Android of iOS sample code that could be used to develop this feature ?

**Comment by AngeeelD** [comment]
Did you tried to call **.cancel()** function on **StreamSubcription** object?

```dart
// listener initialization
StreamSubscription<LocationData> locationSubscription = 
    location.onLocationChanged().listen((LocationData newCurrentLocation){
        // newLocationData handling
});

// listener cancelation
locationSubscription.cancel();
```

**Comment by mikeyyg96** [comment]
@AngeeelD Thanks for this. This was causing my app to have a weird behavior; Everytime I would transition to another app, anytime my location changed, it would transition back to my app from the app I was on.

**Comment by adim86** [comment]
I am having this same issue, even when I call .cancel() in the dispose() function it still continues when I Pop the screen. The dispose function is also getting called (I verified this) but cancel does not stop the location stream

**Comment by ovaldi** [comment]
Same issue
