### ISSUE TITLE
Location always shows 37.(something) and -122.(something)

### ISSUE THREAD

**Issue by Arunva28** [Lyokone/flutterlocation#21]
Hi,

I used your library and am able to see only the location that you have shown in the readme file. Can you please help me with this?

**Comment by streetturtle** [comment]
Same for me, always getting 37,4219983 -122.084 and accuracy 23.429.

**Comment by streetturtle** [comment]
After I installed app on my phone location works as expected. So it seems that emulator is setting this location by default.

**Comment by Arunva28** [comment]
Perfect. @streetturtle , thank you. Works fine when i install the app on phone.
