### ISSUE TITLE
requestService then requestPermission shows no Pop-Up on iOS

### ISSUE THREAD

**Issue by emmett-deen** [Lyokone/flutterlocation#217]
**Describe the bug**
When my user starts our app I first check for the location service and if it is off I call requestService() after they return to the app and acknowledge they have turned it on I check for location permission and if we do not have it I call requestPermission() and the popup does not show. The user is forced to fully close the app and restart the app. It then skips the requestService() call and requestPermission() acts as expected.

**Expected behavior**
For the requestPermission() popup to show even if requestService() has been previously called.

**Tested on:**
 - iOS, Version 12.4, simulator

**Comment by dereklakin** [comment]
I follow a similar, but slightly different flow and get the same result. I request permission first, then if granted I try to get the location. However, if the user initially declines permission, then all subsequent calls to `requestPermission` just hang with no response.

**Comment by KingWu** [comment]
fix the same issue
