### ISSUE TITLE
onLocationChange() never called in IOS

### ISSUE THREAD

**Issue by Saeedtrs** [Lyokone/flutterlocation#222]
**Describe the bug**
onLocationChange() works correctly in android but in the IOS Devices Location is never updated.

**Tested on:**
 - Android, API Level 28 real device //Works
 - iOS, Version 12.4 real device //Not Works

**Comment by David-GIC** [comment]
I meet this issue too, on android onLocationChanged() work but not work on IOS.

**Comment by AresVampire** [comment]
I have this issue too.
