### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method changeSettings on channel lyokone/location)

### ISSUE THREAD

**Issue by Mohammadhamza43** [Lyokone/flutterlocation#223]
**Describe the bug**
The bug occurs when i combined this while calling api using longitude and latitude

**Expected behavior**
it  should return user latitude and longitude then geocoder library return the user address based on latitude and longitude and address will be sent to http request.

**Tested on:**
 - Android, API Level 22, real device

**Other plugins:**
 - geocoder (for address line)
 - http (for api calling)

**Additional logs**
hodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 2575): <asynchronous suspension>
E/flutter ( 2575): #1      Location.changeSettings (package:location/location.dart:51:16)
E/flutter ( 2575): #2      PageOneState.initPlatformState (package:compasss/Pages/pageone.dart:488:29)
E/flutter ( 2575): <asynchronous suspension>
E/flutter ( 2575): #3      PageOneState.datw (package:compasss/Pages/pageone.dart:58:11)
E/flutter ( 2575): <asynchronous suspension>
E/flutter ( 2575): #4      PageOneState.initState (package:compasss/Pages/pageone.dart:482:10)
E/flutter ( 2575): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
E/flutter ( 2575): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2575): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2575): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #31     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
E/flutter ( 2575): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
E/flutter ( 2575): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
E/flutter ( 2575): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #45     Compon
E/flutter ( 2575): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method changeSettings on channel lyokone/location)
E/flutter ( 2575): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 2575): <asynchronous suspension>
E/flutter ( 2575): #1      Location.changeSettings (package:location/location.dart:51:16)
E/flutter ( 2575): #2      PageOneState.initPlatformState (package:compasss/Pages/pageone.dart:488:29)
E/flutter ( 2575): <asynchronous suspension>
E/flutter ( 2575): #3      PageOneState.initState (package:compasss/Pages/pageone.dart:484:5)
E/flutter ( 2575): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
E/flutter ( 2575): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2575): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
E/flutter ( 2575): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #30     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
E/flutter ( 2575): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
E/flutter ( 2575): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
E/flutter ( 2575): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
E/flutter ( 2575): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
E/flutter ( 2575): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
E/flutter ( 2575): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
E/flutter ( 2575): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
E/flutter ( 2575): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
E/flutter ( 2575): #45     ComponentEleme

**Comment by MrJai** [comment]
I am facing this issue. Is there any workaround to this?

But I am facing this issue when running the app in the test environment. It works fine while running the app normally.

```
MissingPluginException(No implementation found for method changeSettings on channel lyokone/location)
  package:flutter/src/services/platform_channel.dart 157:7  MethodChannel._invokeMethod
```
