### ISSUE TITLE
Review iOS permissions documentation

### ISSUE THREAD

**Issue by awhitford** [Lyokone/flutterlocation#232]
Documentation says to specify these two things for iOS:
 * NSLocationWhenInUseUsageDescription
 * NSLocationAlwaysUsageDescription

However, [NSLocationAlwaysUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysusagedescription) has been _deprecated_.

It appears that this should be revised to specify [NSLocationAlwaysAndWhenInUseUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysandwheninuseusagedescription).

**Comment by awhitford** [comment]
Is this project still being maintained?

**Comment by deandreamatias-worldline** [comment]
Please, reopen this. Still necessary
