### ISSUE TITLE
AndroidManifest.xml clarification

### ISSUE THREAD

**Issue by awhitford** [Lyokone/flutterlocation#238]
I understand that we need to modify `AndroidManifest.xml` to add:
```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
However, a Flutter application has 3:
 1. ./android/app/src/profile/AndroidManifest.xml
 2. ./android/app/src/main/AndroidManifest.xml
 3. ./android/app/src/debug/AndroidManifest.xml

_Which file needs to be modified?  Or do all of them need to be modified?_

**Comment by srsandy** [comment]
here `./android/app/src/main/AndroidManifest.xml`

**Comment by MDSADABWASIM** [comment]
@awhitford  if the issue is solved, please close it.
