### ISSUE TITLE
Only works with High Accuracy Location Mode on Android

### ISSUE THREAD

**Issue by awhitford** [Lyokone/flutterlocation#239]
With Android, there are the following **Location Modes**:
 1. High accuracy - Use GPS, Wi-Fi, Bluetooth, or mobile networks to determine location
 2. Battery saving - Use Wi-Fi, Bluetooth, or mobile networks to determine location
 3. Device only - Use GPS and device sensors to determine location

I discovered that `getLocation()` does not return unless _High accuracy_ mode is enabled.  The annoying thing is that _Battery saving_ mode seems to be the out of the box default.

The user gets an alert saying:
> For a better experience, turn on device location, which uses Google's location service.
>
> No thanks | OK

Clicking OK does not change the mode -- it just dismisses the dialog, the same as _No Thanks._

I would expect `getLocation()` to work with any mode -- as long as Location services are enabled.

I am using Flutter 1.9.1+hotfix.6, Dart 2.5.0, and testing on Android API 27 and later (Android Go 8.1 and 10.)

**Comment by sm9i** [comment]
I didn't return anything, I didn't report an error
