### ISSUE TITLE
Is it Working when app killed/terminated?

### ISSUE THREAD

**Issue by lyseiha** [Lyokone/flutterlocation#242]
Need Help

**Comment by MDSADABWASIM** [comment]
Yes it is working in my case, tested in android.

**Comment by daniyalahmedkhan** [comment]
Location callback not working when app is terminated/killed. Working in foreground and background (app in recent). 
I've done the below.

```
location!.enableBackgroundMode(enable: true);

  location!.onLocationChanged.listen((LocationData currentLocation) {
           
    });
```

**Comment by Saikiran24** [comment]
yes, same here as well ,please fix this issue

**Comment by daniyalahmedkhan** [comment]
> yes, same here as well ,please fix this issue

Try backgroun_locator plugin, it will work properly
