### ISSUE TITLE
serviceEnabled() always gives "TRUE" results

### ISSUE THREAD

**Issue by mustofin** [Lyokone/flutterlocation#245]
**Describe the bug**
When I call serviceEnable() function, I always get TRUE results event if the Location Setting  is Off. But when I call getLocation() function, I get the Location Setting value with the correct value.

**Expected behavior**
I get the right value of the Location Setting by call serviceEnable() function.

**Tested on:**
 - Android, API Level 27 (Oreo 8.1.0), real device: Redmi Note 5

**Comment by srburton** [comment]
Open the same problem, I saw that many people have this problem of returning true ....
