### ISSUE TITLE
How to stop listening for location

### ISSUE THREAD

**Issue by Brabalawuka** [Lyokone/flutterlocation#247]
I have created aninstance to listen for location, right now hwo to stop listening？

**Comment by Hell4Ge** [comment]
I tried to use `listen(null)` but this do not work

**Comment by Hell4Ge** [comment]
Solved that by using StreamSubscription

`
StreamSubscription subscription;

...
subscription = location.onLocationChanged().listen(...);
...
subscription.cancel();
`
