### ISSUE TITLE
Stuck at await _locationService.getLocation(); When GPS is off

### ISSUE THREAD

**Issue by indrsidhu** [Lyokone/flutterlocation#249]
**Describe the bug**
I simplified code with this example
When GPS is off by default, await location.getLocation() stuck it never return 
any next print statement never execute.
But When I enable GPS by default and launch application then it works 
```
try{
      currentLocation = await location.getLocation();
      print("*******WORKING******");
 } on PlatformException catch (e) {
      print("*******PLATFORM EXCEPTION RETURNED******");
    }
```

**Expected behavior**
It should not be stuck under await, either it should throw an exception which I already handling

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device
 - Android, Emulator

**Other plugins:**
 - List of others Flutter plugins that could interfere
  http: ^0.12.0+2
  location: ^2.3.5
  google_maps_flutter: ^0.4.0

**Comment by nicowernli** [comment]
Same is happening to me when I don't allow to share the location

**Comment by IkhwanSI13** [comment]
I got the same problem.

For now, I use this solution, maybe it's not the best way but it works.

![Screen Shot 2019-11-26 at 14 18 15](https://user-images.githubusercontent.com/10230992/69607318-9e2a6880-1057-11ea-9c28-93fb71c6423f.png)

**Comment by kapilvallamkonda** [comment]
It is happening to me only on Android even if GPS is on and location is shared.

**Comment by Saleh-C** [comment]
It's 2024 and I am also experiencing the same issue when granting one time permissions to the location on any Android Emulator really. Of course I've checked if the service is set to enabled beforehand. The getLocation() call gets stuck without throwing any exception and the code after the call won't be executed.
