### ISSUE TITLE
Could not resolve com.google.android.gms:strict-version-matcher-plugin:1.1.0.

### ISSUE THREAD

**Issue by SnehKumarBhansali** [Lyokone/flutterlocation#252]
I have mentioned location package in pubspec.yaml file. Flutter pub get is executed successfully, but while executing the flutter run, it is giving below error: 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.google.android.gms:strict-version-matcher-plugin:1.1.0.
     Required by:
         project : > com.google.gms:google-services:4.2.0
      > Could not resolve com.google.android.gms:strict-version-matcher-plugin:1.1.0.
         > Could not get resource
         'https://dl.google.com/dl/android/maven2/com/google/android/gms/strict-version-matcher-plugin/1.1.0/strict-version-matcher-plugin
         -1.1.0.pom'.
            > Could not GET
            'https://dl.google.com/dl/android/maven2/com/google/android/gms/strict-version-matcher-plugin/1.1.0/strict-version-matcher-plu
            gin-1.1.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed:
               sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

In build.gradle file, I have changed the dependencies

buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

In gradle.properties, code is like this:
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536M

Can anyone faced the same issue? How did you resolve this.

**Comment by rodrigopfelix** [comment]
Hi. Try to change the kotlin_version to '1.3.0' or higher
