### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by luccascorrea** [Lyokone/flutterlocation#257]
PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference, null)

This bug happens when checking whether the location service is enabled but an exception happens during that check.

This crash has been happening for me for a couple of months now. I see that the problem starts with line 397 in the file [android/src/main/java/com/lyokone/location/LocationPlugin.java](https://github.com/Lyokone/flutterlocation/blob/master/android/src/main/java/com/lyokone/location/LocationPlugin.java#L397). More specifically, this call:
    
    if (this.checkServiceEnabled(null)) {

Inside the `checkServiceEnabled` method, [at line 379](https://github.com/Lyokone/flutterlocation/blob/master/android/src/main/java/com/lyokone/location/LocationPlugin.java#L379), there is no check to make sure the result parameter is not null before calling result.error()

I'd submit a pull request but I am not sure how to do it, sorry.

PS: thanks for the library!

**Comment by Sradom** [comment]
I was facing the same problem. The following piece of code fixed it for me. It was suggested by another user on a previous open issue
```bool hasPermission = await location.hasPermission() && await location.serviceEnabled();
if (Platform.isAndroid) {
    if (!hasPermission) {
        hasPermission = await location.requestPermission() && await location.requestService();
    }
}

**Comment by luccascorrea** [comment]
Just bumping this.
