### ISSUE TITLE
Not able to access changesetting function

### ISSUE THREAD

**Issue by AtmanBhatt** [Lyokone/flutterlocation#266]
I am using a location(1.4.0) library to show the current location in my flutter application. I have set up all the necessary things which are needed to use the library but I am not able to access changesetting function. 

Below is the code through which I am trying to access the function.
await location.changeSettings(accuracy: LocationAccuracy.HIGH, interval: 1000);

I have also checked inside the library and found that this function is not available inside the library. 

Kindly help me what to do, as I need to complete my application using this location library.

**Comment by nixuiui** [comment]
await location.changeSettings(accuracy: LocationAccuracy.LOW);
