### ISSUE TITLE
Background location Updates

### ISSUE THREAD

**Issue by Chaithanya26** [Lyokone/flutterlocation#272]
Unable to get  **registerBackgroundLocation** (_locationService.registerBackgroundLocation(backgroundCallback)) method to implement background locations.

**Comment by Lyokone** [comment]
The background experimentation implementation needs to heavily change since Flutter is now using the new Android V2 Embedding. 
I cannot find any example on how to implement the ServiceAware, so i'll wait a bit before retrying this :)
