### ISSUE TITLE
Does not seem to support flutter web

### ISSUE THREAD

**Issue by TimoKettunen** [Lyokone/flutterlocation#279]
**Describe the bug**
The package description advertises that the package supports, android, ios and **web**.
It does not seem to work in flutter web application.

**Expected behavior**
I wrote a flutter web application that uses this package.
I copied the initializing code from your example.
I expected that the methods 
```
    await _locationService.changeSettings(accuracy: LocationAccuracy.HIGH, interval: 1000);
...
    bool serviceStatus = await _locationService.serviceEnabled();

```
etc. would return but they never did  

**Tested on:**
 - Flutter web locally
 - Web app hosted on firebase, client run on desktop and mobile.

**Other plugins:**

**Additional logs**

**Comment by Lyokone** [comment]
Hey, this package does not support the web, but seems to be tagged as such on pub.dev, I'll check if it's something I can deactivate.

**Comment by Lyokone** [comment]
I added the list of supported platforms in the pubspec.yaml : https://github.com/Lyokone/flutterlocation/commit/cce38256daf05cf2a7ecb30a7f20ef304c815583
