### ISSUE TITLE
Type 'Future<dynamic>' is not a subtype of type 'Future<Map<String, double>>'

### ISSUE THREAD

**Issue by foolzoom** [Lyokone/flutterlocation#28]
Hi! I have the kind of error, when I try to get location:

`type 'Future<dynamic>' is not a subtype of type 'Future<Map<String, double>>' where
  Future is from dart:async
  Future is from dart:async
  Map is from dart:core
  String is from dart:core
  double is from dart:core`

The first string of the stack trace:
`#0      Location.getLocation (package:location/location.dart:12:16)`

**Comment by efortuna** [comment]
I made a fix for this issue, and submitted a PR, but in the meanwhile, you can just point to my fork: https://github.com/efortuna/flutterlocation

**Comment by GoHash-Include** [comment]
I updated flutter to the latest version, after update am getting too many bugs like above, now how can I fix this issues.
![screen shot 2018-04-04 at 11 09 00 pm](https://user-images.githubusercontent.com/31134868/38324211-3b8227dc-385d-11e8-9a33-1a902f104fdd.png)

**Comment by efortuna** [comment]
Did you see my link?  Put this in your pubspec.yaml:

    location:
        git: git://github.com/efortuna/flutterlocation.git

**Comment by GoHash-Include** [comment]
do you want remove this flutter package location: "^1.1.7" and put your code or keep both ?

**Comment by efortuna** [comment]
Until my PR is accepted: https://github.com/Lyokone/flutterlocation/pull/27... linking to my code is a stopgap to make your code work. You don't need the '^1.1.7' -- just the two lines I listed above.

**Comment by carter3rix** [comment]
> I made a fix for this issue, and submitted a PR, but in the meanwhile, you can just point to my fork: https://github.com/efortuna/flutterlocation

Hi @efortuna please how do i point to your fork to use in my project... Hope you can give me a guide. 
Thank you

**Comment by efortuna** [comment]
https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by carter3rix** [comment]
> https://www.dartlang.org/tools/pub/dependencies#git-packages

Thanks...
