### ISSUE TITLE
Problem in getting Location for Flutter Web

### ISSUE THREAD

**Issue by saadjavaidalvi** [Lyokone/flutterlocation#280]
**Describe the bug**
The programs stuck at the exact line where the location command is executed and does run returns anything in flutter web.

**Expected behavior**
The program should return some pop up for permission or directly current location on flutter Web

**Tested on:**
- Chrome web

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**
Here is the code that I am trying to run:
try {
      locationcords = await _location.getLocation();
    } catch (e) {
      locationcords = null;
    }

    if (locationcords != null) {
      locationisenabled = true;
      LOCATION = locationcords;
      _namelocation();
    } else
      setState(() {
        loading = false;
        locationisenabled = false;
      });

``` shell
some logs
```

**Comment by Lyokone** [comment]
Hey, sorry web isn't supported yet. I've fixed this in this commit : https://github.com/Lyokone/flutterlocation/commit/cce38256daf05cf2a7ecb30a7f20ef304c815583
