### ISSUE TITLE
getLocation() never completes while another getLocation() call is pending

### ISSUE THREAD

**Issue by gillesroux** [Lyokone/flutterlocation#281]
The getLocation() API does not support concurrent invocations and results in a future that never completes. It's preferable to avoid concurrent invocation but different parts of the app may be using the location plugin making it hard to avoid.

Here is a code sample demonstrating the issue. 'done' is never printed.
  print('start');
  final location1 = location.getLocation();
  final location2 = location.getLocation();
  await location1;
  await location2;
  print('done');

This behavior seems to be due to the fact that the plugin overwrites the method call result:
https://github.com/Lyokone/flutterlocation/blob/master/android/src/main/java/com/lyokone/location/LocationPlugin.java#L152

One workaround is to introduce a wrapper that serializes getLocation calls:
  final lock = Lock();
  Future<LocationData> getLocation() async =>
      lock.synchronized(() async => location.getLocation());

Tested on Android 10 on a Pixel 3.

**Comment by Lyokone** [comment]
Hey ! The getLocation is in fact not supporting concurrent calls. 
I'll evaluate if a lock, or an Array of getLocationResults is better for solving this :)

**Comment by halldorlogi** [comment]
Any news on this?

**Comment by Lyokone** [comment]
Hey ! I did not had time to tackle this yet. Sorry for the delay :/

**Comment by Kristijan505** [comment]
Hi,

we had the exact same issue while trying to get users location multiple times.

Our solution was to make a variable named lastLocation, where we would write users location every time that getLocation() has succeeded and set a timeout on getter with:

`LocationData lastLocation;` - as a global variable

`Location().getLocation().timeout(Duration(seconds: 1), onTimeout: () => lastLocation);`

I hope it helps.

**Comment by Dorbmon** [comment]
> Hi,
> 
> we had the exact same issue while trying to get users location multiple times.
> 
> Our solution was to make a variable named lastLocation, where we would write users location every time that getLocation() has succeeded and set a timeout on getter with:
> 
> `LocationData lastLocation;` - as a global variable
> 
> `Location().getLocation().timeout(Duration(seconds: 1), onTimeout: () => lastLocation);`
> 
> I hope it helps.

Thanks for your help.You saved the day haha
