### ISSUE TITLE
Attempt to invoke interface method 'void d.a.b.a.o$d.a(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by GiacomoK** [Lyokone/flutterlocation#282]
Sometimes sentry gets this error:

> PlatformException(error, Attempt to invoke interface method 'void d.a.b.a.o$d.a(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference, null)

The line of the error seems to be this:

    _location.onLocationChanged().listen((LocationData result) { // <--- this line
        widget.store.dispatch(new ActionGeoLocationChanged(result.latitude, result.longitude));
    });

The _location variable is defined by:

    var _location = new Location();

**Tested on:**
 - Android, real device

**Comment by Lyokone** [comment]
Hey ! Thanks for the report. I'll check this, but seems hard to reproduce with this small amount of code.

**Comment by Lyokone** [comment]
Hey, please check version 2.5.0, and reopen if this still occurs :)
