### ISSUE TITLE
GetLocation() method returns lat:0.0 lng:0.0

### ISSUE THREAD

**Issue by madaomaraly2010** [Lyokone/flutterlocation#288]
i implemented this code :
 `LocationData currentLocation;
    var location = new Location();

// Platform messages may fail, so we use a try/catch PlatformException.

    currentLocation = await location.getLocation();`
if i console location.latitude & location.longitude it return 0.0,0.0 Why???

**Comment by Lyokone** [comment]
Have you tried launching the example app ?
