### ISSUE TITLE
Ios request location permission issue

### ISSUE THREAD

**Issue by rohnsht** [Lyokone/flutterlocation#293]
**Describe the bug**
The plugin throws an exception when user has changed the location access to "Never" in settings and next time location.requestPermission() is called.

This is the exception thrown by the plugin:
`Unhandled Exception: PlatformException(PERMISSION_DENIED, User previously reject permissions, null)`

**Expected behavior**
Instead of throwing the exception the plugin should display the location permission dialog.

**Tested on:**
 - iOS, 12.4.5, iphone 6

**Additional logs**
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(PERMISSION_DENIED, User previously reject permissions, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      Location.requestPermission (package:location/location.dart:120:22)
```

**Comment by Lyokone** [comment]
Hey, thanks for the report, I'll change that to align with Android and return a PermissionStatus object

**Comment by Lyokone** [comment]
I've pushed to master a fix to align iOS handling of PermissionStatus, but be sure to understand, that once a user has denied your app a permission, iOS will not display any more popup.
