### ISSUE TITLE
speed and altitude is null 

### ISSUE THREAD

**Issue by bawantha** [Lyokone/flutterlocation#299]
**Describe the bug**
Speed ( `speed` ) Altitude (`altitude`)  is always is `null` , where from `LocationData` class

**Expected behavior**
speed of device and altitude of device should show from those values

**Tested on:**
 - Android, API Level  28 , simulator 
- Android, API Level  28 , real device
 

**Other plugins:**
 - google_maps_flutter: ^0.5.24+1

**Comment by Lyokone** [comment]
Seems to be working fine on my end, do you have the same error in the example app ?
