### ISSUE TITLE
Package doesn't exist (the pubspec for location 2.3.5 from git has version 2.5.3).

### ISSUE THREAD

**Issue by AlexHooper** [Lyokone/flutterlocation#306]
Attempting to use the `  location:
    git:
      url: git://github.com/Lyokone/flutterlocation.git
      ref: background_location` 
flutter package, I get the following error when attempting to run flutter packages get:
`Package doesn't exist (the pubspec for location 2.3.5 from git has version 2.5.3).`

**Comment by Lyokone** [comment]
Hey, not sure what this error is about, maybe you should try to specify the version from the pubspec.yaml of the background location branch 🤔?

**Comment by AlexHooper** [comment]
version: 1.0.0+1

**Comment by Lyokone** [comment]
Hey ! I'll close this, the background_location branch isn't really supported anymore. I'll try to use ServiceAware to upgrade it as soon as an official sample is published !
