### ISSUE TITLE
Doesn't work with Firebase plugins because they use com.google.android.gms:play-services-location:15.+

### ISSUE THREAD

**Issue by vagrantrobbie** [Lyokone/flutterlocation#31]
Is there a better way to set the gms version? Many of the Google plugins now use com.google.android.gms:play-services-location:15.+ which causes the app to crash when working with this plugin.

I have had to hard code the build.gradle implementation version for now to use the same as Firebase etc , eg

Was
```
dependencies {
    implementation 'com.google.android.gms:play-services-location:11.+'
}
```

Now
```
dependencies {
    implementation 'com.google.android.gms:play-services-location:15.+'
}
```

**Comment by natewilson** [comment]
Any reason flutterlocation shouldn't also be updated to 15.+?

**Comment by natewilson** [comment]
Is there any reason updating flutterlocation to depend on gms:15.+ would be problematic?
