### ISSUE TITLE
distanceBetween calculation?

### ISSUE THREAD

**Issue by pahoel** [Lyokone/flutterlocation#312]
I use a Timer to fetch the current position (location.getLocation()) at regular intervals. I need a method to compere the current value with the last one - to see if how far the user has been moving during the interval.
Something like the [geolacator](https://pub.dev/packages/geolocator) distanceBetween method.

LocationData currentLocation  <-> Loc ationData lastKnownLocation

Is this functionality on the roadmap, or do I have to dig up my own solution (suggestion welcomed :-) )

**Comment by Lyokone** [comment]
Hey, I feel like it's not the scope of this plugin. Feels like a simple helper method can do this if you store each LocationData. 
Please note that you can listen to event with an interval set in changeSettings, that may be better for battery consumption.

**Comment by pahoel** [comment]
Thanks for your fast reply :-)
I'm aware of the Location.changeSettings(), but I'm unsure how it works: If **interval** = 60000, will the  gps be activated only every 6 minutes, or will it only fire an event every 6 minutes? Do you think that it will be more energy efficient than a getLocation() call every 6 minutes?

There is a small problem with a helper function based on the values stored in the two LocationData variables: The values from getLocation() will never/very seldom be **exactly** like when called from the same position. So how do I detect  a movement of, let's say 1 m, from the inaccuracy of the gps reading?
