### ISSUE TITLE
requestService does not return any value on plugin version 2.5.3

### ISSUE THREAD

**Issue by sudip92** [Lyokone/flutterlocation#313]
**Describe the bug**
In plugin version 2.5.3 Location().requestService() does not return anything while we press 'OK' or 'No Thanks' in location request Dialog Android

**Expected behavior**
var result = await location.requestService();
it should return true false but it does not return any thing .

**Tested on:**
 - Android, API Level 29, simulator and real device

**Comment by Lyokone** [comment]
Hey, thanks for the report, I'll look into it.
Have you looked at the implementation in the demo app ?

**Comment by sudip92** [comment]
Yes i have checked your implementation.

**Comment by idrats** [comment]
I have faced with the same problem on Android.
`await location.requestService()` - never completes with any value, so the application can infinitely be awaiting the execution.
BTW v2.3.5 worked like a charm.

**Comment by EdwinBustamante** [comment]
I have the same problem.
bool flagPermission = await _locationService.requestService();

does not return the value of the dialog

**Comment by dasmobile** [comment]
Same issue here.

**Comment by kennethj** [comment]
This might be related
#318

**Comment by DevarshRanpara** [comment]
Facing the same issue in `2.5.3` and in `2.5.4` also,
Temporarily switched to `2.5.2`.

**Comment by YogeshLegendkiller** [comment]
this bug still persists ? am not getting any return value from requestPermission method

**Comment by Lyokone** [comment]
Hey ! Should be finally fixed with 3.0.3 :) Feel free to open another issue if it's not the case

**Comment by litzbalane2017** [comment]
> Hey ! Should be finally fixed with 3.0.3 :) Feel free to open another issue if it's not the case

There is no 3.0.3 at the moment. Will temporarily use 2.5.2.

**Comment by HerrNiklasRaab** [comment]
@Lyokone When will 3.0.3 be published?

**Comment by Lyokone** [comment]
Sorry ! I meant 3.0.2, that should already be released 😅

**Comment by RicardoRB** [comment]
@Lyokone it still doesn't work in 3.0.2
