### ISSUE TITLE
How to set the interval in changeSettings() function.

### ISSUE THREAD

**Issue by thanooshan** [Lyokone/flutterlocation#317]
Hi, First of all thanks for making our life easier. I've a problem. I want to delay the location data which receive from `onLocationChange()` function.

I found a method in the documentation. But couldn't able to configured properly.  This is how I implemented. 

**location.changeSettings(interval: 3000, distanceFilter: 10.0);**

But there is no difference in the speed. The data receives continuously. Because of that the map is crashing. 

I posted a [question](https://stackoverflow.com/questions/60628321/how-to-delay-the-flutter-location-data-receiver) in stackoverflow regarding this, but didn't receive any answers.

Any help would be much appreciated.
     
      Location location = new Location();
      StreamSubscription _locationSubscription;

      void initState() { 
        super.initState();
        _animateToUser();
      }

      @override
      void dispose() { 
        if (_locationSubscription != null) {
          _locationSubscription.cancel();
        }    
        super.dispose();
      }

      Widget build(BuildContext context) {
        return Stack(
          children: <Widget>[
            GoogleMap(
              initialCameraPosition: CameraPosition(
                target: LatLng(6.854399, 79.865463),
                zoom: 14.44,
              ),
              myLocationEnabled: true,
              onMapCreated: _onMapCreated,
            ),        
          ],
        );
      }
    
      _onMapCreated(GoogleMapController controller) {
        setState(() {
          mapController = controller;
        });
      }

      _animateToUser() async {
    
        location.changeSettings(interval: 3000, distanceFilter: 10.0); // <-- settings
        _locationSubscription = location.onLocationChanged().listen((newData) {
    
          print(newData.latitude);
    
          mapController.animateCamera(
            CameraUpdate.newCameraPosition(
              CameraPosition(
                target: LatLng(newData.latitude, newData.longitude), 
                zoom: 17.0
              )
            )
          );
    
        });
        
      }

**Comment by Lyokone** [comment]
Hey, not sure why itis not slowing down, It supposed to be working as intentend if you print it without the map, is it still crashing ?

**Comment by thanooshan** [comment]
Yes, it is. And I tested this IOS simulator only. Is that a problem?

**Comment by Lyokone** [comment]
Hey ! It might be problem for the simulator, not sure how they handle continuous location ?

**Comment by jeanbatm** [comment]
Hello, I experienced the same issue on android simulator. Even is latitude and longitude are static, accuracy is changing constantly.

**Comment by imasif** [comment]
Even in 2024 this issue hasn't been fixed! on IOS interval not working!
