### ISSUE TITLE
Cant tell if permission has not yet been set.

### ISSUE THREAD

**Issue by mindfullsilence** [Lyokone/flutterlocation#319]
**Is your feature request related to a problem? Please describe.**
Right now, there's no way for me to tell if a user has not already been asked because the hasPermission is always set to DENIED (default), DENIED_FOREVER, or GRANTED, but in this case, you would need an INDETERMINATE to know if permission needs to be requested. 

**Describe the solution you'd like**
Once my users have signed into the app, I need to know if I should show a welcome screen describing why I want to use their location and show the permission dialog after they click a button. If I was already given permission from the user, or was denied permission by the user, I dont want to nag them with this screen. The best way to do this is to know if the permission has never been requested - something like the following:

```
PermissionStatus hasPermission = await _location.hasPermission();
if(hasPermission == PermissionStatus.INDETERMINATE) {
  // something to this effect
  Navigator.push(RequestLocationPermissionPage());
}
```

**Describe workarounds you've considered**
Only workaround I can think of is to save the granted or denied status to something like shared prefs, then check for existence of the shared pref on app startup, but this requires more technical debt and could break if permission was changed from outside the app. 

**Additional context**
We have the ability to add this in iOS near these lines of code:

perhaps returning NULL here?
https://github.com/Lyokone/flutterlocation/blob/master/ios/Classes/LocationPlugin.m#L179

return `result(@3)` here if hasPermission val is null?
https://github.com/Lyokone/flutterlocation/blob/master/ios/Classes/LocationPlugin.m#L108

then add `case 3` here that returns PermissionStatus.INDETERMINATE
https://github.com/Lyokone/flutterlocation/blob/master/lib/location.dart#L156

I don't really know a whole lot about android - and am actually very new even to flutter so this is the best I could glean from the code. The real solution is probably quite different but wanted to give a good college try at suggestions.

**Comment by Lyokone** [comment]
Hey ! Thanks for this detailed issue, really appreciate it :) 
When you call _location.hasPermission(), if you get `denied` you can assume that your user is yet to have it denied it forever. 
I had considered adding a `indeterminate` state, maybe it's time reconsider it.
