### ISSUE TITLE
Crashing ios application when requests background location listener for second time

### ISSUE THREAD

**Issue by vaimikpatel2908** [Lyokone/flutterlocation#320]
**Describe the bug**
When first time requests for listener it goes fine and returns background location but it is not frequent so can't be used for tracking and application is crashing when try to request listener again after/before removing listener.

**Expected behavior**
It should not crash even the listener is registered and requesting for listener and expecting the frequent locations in background. 

**Tested on:**
 - iOS, Version 13.3, simulator and iPhone6s(don't remember the version)

**Comment by boran-northeastern** [comment]
same issue on iPhone 11 Pro Max (13.4)

**Comment by boranyldrm** [comment]
same issue on iPhone 11 Pro Max (13.4), simulator.

**Comment by vaimikpatel2908** [comment]
I am not sure about it but try to test it on real device. It might work. Because When I was writing native code, I had issues while accessing the heading it was crashing even though frequent locations generated. So my suggestion is to just give it a try on real device and test it.
