### ISSUE TITLE
Background location tracking, when app closed

### ISSUE THREAD

**Issue by zs-dima** [Lyokone/flutterlocation#322]
Thanks for the awesome library

Please, add background location tracking
So app closed but location tracking continue

This approach do not really works:
https://github.com/Lyokone/flutterlocation/wiki/Background-Location-Updates
more over it require static handler function that is not practical

**Comment by Lyokone** [comment]
Hey ! I'm waiting for an official plugin to demonstrate how to properly use Service Aware which is the official implementation for Android plugin ... Might experiment a bit there if nothing is published. It is planned tho :)

**Comment by julien-h** [comment]
Hello @Lyokone, 
Thanks for the plugin, it's super useful.

I need to create a gps-based app, much like a navigation system (think Google Maps / Waze / iOS Maps). Would the approach in https://github.com/Lyokone/flutterlocation/wiki/Background-Location-Updates be suitable for this? 

@z-dmitri says "it doesn't really work", what are the drawbacks ?

Or what could be an alternative using flutter? I'm new to smartphone dev and I find it pretty hard to find good resources on this topic.

**Comment by julien-h** [comment]
On [this page](https://developer.apple.com/documentation/corelocation/choosing_the_location_services_authorization_to_request) they say that iOS apps are considered in use when running in the background with the background location usage indicator enabled.

And a comment on [this SO](https://stackoverflow.com/questions/61127245/flutter-how-to-display-a-banner-when-my-app-is-not-in-foreground-as-maps-goo/61133145#61133145) question says: if your app has "when in use location permission", and you set background updates on your location manager and call startUpdatingLocation the blue indication is shown.

Any idea how I can do this using flutter? **This feels like a feature that could be added to this plugin.**

**Comment by komape** [comment]
Any updates on this issue?

**Comment by julien-h** [comment]
Best alternative I found so far is the following:

- on iOS, use `background_locator` plugin
- on Android use `foreground_service` together with `geolocator` plugin

Could not get `flutterlocation` to work with `foreground_service` but `geolocator` does a fine job.

You can just stream data from the `background_locator` isolate to your app or from the `foreground_service` to your app and it'll stay alive.

**Comment by mohamnag** [comment]
I don't know if you have seen this but both the article and code of this one looks interesting:

https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

https://github.com/bkonyi/FlutterGeofencing

might be someone familiar with both iOS and Android can perfection this and add it to this plugin.

**Comment by n0tc0ding** [comment]
push

**Comment by zaidrix** [comment]
up

**Comment by catirito** [comment]
Im looking forward to this! thx

**Comment by ovaldi** [comment]
> Im looking forward to this! thx

+1

**Comment by vicenterusso** [comment]
> Best alternative I found so far is the following:
> 
> * on iOS, use `background_locator` plugin
> * on Android use `foreground_service` together with `geolocator` plugin
> 
> Could not get `flutterlocation` to work with `foreground_service` but `geolocator` does a fine job.
> 
> You can just stream data from the `background_locator` isolate to your app or from the `foreground_service` to your app and it'll stay alive.

do you mind to upload a sample of this approach on github?

**Comment by smolugu** [comment]
> Best alternative I found so far is the following:
> 
> * on iOS, use `background_locator` plugin
> * on Android use `foreground_service` together with `geolocator` plugin
> 
> Could not get `flutterlocation` to work with `foreground_service` but `geolocator` does a fine job.
> 
> You can just stream data from the `background_locator` isolate to your app or from the `foreground_service` to your app and it'll stay alive.

Hi @julien-h , Can you please share a sample code?

Regards,
Shyam

**Comment by shantaly** [comment]
any updates on this feature? Would be sick to be able to get location updates in the background!

**Comment by TehRaab** [comment]
+1 also in need to be able to track gps location on both Android and iOS whilst the app is suspended in the background and/or the device screen is off/locked.

**Comment by julien-h** [comment]
You can check how I implemented the background collection in this app: https://github.com/julien-h/tmd-data-collection-app/tree/master/smartphone-app/lib

It worked fine 3 months ago. No longer working on it now so not answering questions.

**Comment by zachisit** [comment]
@julien-h We are seeing success with just using the `background_locator` in both iOS and Android devices and emulators to track geolocation in foreground and background usage of the app. Curious if you still require using numerous separate packages for the two devices?

**Comment by TehRaab** [comment]
> @julien-h We are seeing success with just using the `background_locator` in both iOS and Android devices and emulators to track geolocation in foreground and background usage of the app. Curious if you still require using numerous separate packages for the two devices?

Thanks - I need to test background_locator on a few different devices, but initial tests are working.  Out of interest, do you happen to know of a reliable package for converting long/lat into poly-lines to draw a path thats been provided?

**Comment by Lyokone** [comment]
Hi, sorry for not responding for a long time. 
`3.2.1` has some support for background location. It can be improved but it's a start :)

**Comment by AbhayJadoun** [comment]
any of the solution is working or not for location service when app on ios device in background or closed??
