### ISSUE TITLE
Location still enabled even after canceling stream

### ISSUE THREAD

**Issue by julien-h** [Lyokone/flutterlocation#323]
**Describe the bug**

On my android samsung galaxy s7 device, I can see an icon in android's top bar indicating whether the location service is being used or not.

If in my flutter widget I call : 
```
locationStream = locationService.onLocationChanged().listen(onNewLocation);
```
without manually requesting authorization and enabling the location service, then even when I cancel the stream (`locationStream.cancel`) and close my widget (`dispose()`), I can see in the top bar that the location icon remains until I manually kill the whole application. Problem: I suspect this drains the battery.

however, if I manually enabled the location service and requested authorization as shown in the readme before calling `onLocationChanged().listen`, then as soon as the widget is closed (`dispose()`), the icon disappears.

**Expected behavior**
As soon as the `onLocationChanged().listen` stream is cancelled, the icon disappears from the top bar.

**Tested on:**
 - Android, API Level 29,  real device

**Other plugins:**
 - none

**Additional logs**

``` shell
none
```

**Comment by Lyokone** [comment]
Hey ! Thanks for the report, I'll be looking into this, it is supposed to stop requesting location indeed :/

**Comment by Lyokone** [comment]
I do not have this bug on the example app on Android 29.
Would you have a minimal reproducible example ?

**Comment by julien-h** [comment]
Hmm can't reproduce either, that's weird caused I did check multiple times.

Sorry about that
