### ISSUE TITLE
Location for web

### ISSUE THREAD

**Issue by lehno** [Lyokone/flutterlocation#324]
Any plans to integrate it with flutter web. it would be great to have it working on the browser as well

**Comment by Lyokone** [comment]
Hey ! I've begin to work on this, but no ETA as of now, I don't have a lot of time on the project right now

**Comment by long1eu** [comment]
@Lyokone did you started on this? I want to do it.

**Comment by Lyokone** [comment]
Hey ! I've not started to do it, just studied how the officials plugins have done it ;)

**Comment by lehno** [comment]
I see this is in master, perfect, waiting for the release

**Comment by Lyokone** [comment]
It is released now :D Huge thanks to @long1eu for all the help :D
