### ISSUE TITLE
Build failed on iOS using 3.0.0 version

### ISSUE THREAD

**Issue by arthurpiccoli** [Lyokone/flutterlocation#328]
Xcode build is failing using package latest version.

Build log:
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_LocationPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Lyokone** [comment]
Hey ! Sorry about that, just published 3.0.1 that should resolve this. Don't forget to run a flutter clean before just to be sure :)

**Comment by granmoe** [comment]
Had this issue and 3.0.1 fixed it 👍

**Comment by Lyokone** [comment]
Great to here that :D
