### ISSUE TITLE
get issues when testing the exemple

### ISSUE THREAD

**Issue by walide67** [Lyokone/flutterlocation#329]
i test the exemple provided in the documentation and i get the following error :

> Exception has occurred.NoSuchMethodError (NoSuchMethodError: The method 'toRawHandle' was called on null.Receiver: nullTried calling: toRawHandle()) location package

android sdk 28

**Comment by Lyokone** [comment]
Hey,  everything is working on my end. Are you able to run other Flutter app correctly ?
