### ISSUE TITLE
build faild after adding Application.java

### ISSUE THREAD

**Issue by walide67** [Lyokone/flutterlocation#330]
when i add Application.java and change the xml file like descriptde in wiki i get this error :

> /home/walid/Desktop/covid19/covid19/android/app/src/main/kotlin/com/example/covid19/Application.java:17: error: incompatible types: PluginRegistry cannot be converted to FlutterEngine
        GeneratedPluginRegistrant.registerWith(registry);
                                               ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4m 52s

android sdk 28
Flutter 1.12.13+hotfix.8

**Comment by Lyokone** [comment]
Hey, this is not a problem with the plugin, please post on the Flutter repo if you think there is a problem with the Android Implementation v2 :)
