### ISSUE TITLE
PUB.DEV LINK Error

### ISSUE THREAD

**Issue by blondie63** [Lyokone/flutterlocation#334]
Hi, on page https://pub.dev/packages/location#-example-tab- the link under example/lib/main.dart is wrong..

ps. Can you help me to convert my code based on location: ^2.5.3 to 3.0.1 ? :)
this is my code:

`import 'dart:async';

import 'package:location/location.dart';
import '../models/user_location.dart';

class LocationService {
  // Keep track of current Location
  UserLocation _currentLocation;
  Location location = Location();
  // Continuously emit location updates
  StreamController<UserLocation> _locationController =
      StreamController<UserLocation>.broadcast();

  LocationService() {
    location.requestPermission().then((granted) {
      if (granted != null) {
        location.onLocationChanged().listen((locationData) {
          if (locationData != null) {
            _locationController.add(UserLocation(
              latitude: locationData.latitude,
              longitude: locationData.longitude,
            ));
          }
        });
      }
    });
  }

  Stream<UserLocation> get locationStream => _locationController.stream;

  Future<UserLocation> getLocation() async {
    try {
      var userLocation = await location.getLocation();
      _currentLocation = UserLocation(
        latitude: userLocation.latitude,
        longitude: userLocation.longitude,
      );
    } catch (e) {
      print('Could not get the location: $e');
    }

    return _currentLocation;
  }
}`

Error is in line "location.onLocationChanged().listen((locationData) {"

Thanks

**Comment by Lyokone** [comment]
Hey `onLocationChanged` is now a getter so you just need to remove the ()

**Comment by blondie63** [comment]
Thanks
