### ISSUE TITLE
How to 'Disable android permission' (Location, Camera, Storage etc…) programmatically in flutter

### ISSUE THREAD

**Issue by ManishAndroidIos** [Lyokone/flutterlocation#335]
I have n toggle button in which i am asking for the android manifest permission like Location, Camera, Storage, SMS etc.

But now when toggle button off i want to disable the permission may be all at a time or one by one, is that possible in flutter, if yes please guide me how can i achieve this.

Thanks in advance.

**Comment by AbanoubNassem** [comment]
did you figure it out?
