### ISSUE TITLE
[iOS] location.getLocation never returns

### ISSUE THREAD

**Issue by yokoboko** [Lyokone/flutterlocation#337]
**Describe the bug**
Future location.getLocation() never returns

**Expected behavior**
return result(any result)

**Tested on:**
 - iOS, Version 13.3.1, iPhone 6s

**Other plugins:**
 - No other pugins

**Steps to reproduce:**
1. Turn off location services.
2. Open the app
3. Try to get location
4. Go to settings and enable location services
5. Back to app and try to get location. getLocation never returns!

**Example code:**
Create new flutter project and add location to pub spec. Then use this code in main.dart

```
import 'package:flutter/material.dart';
import 'package:location/location.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Location location = Location();
  bool _serviceEnabled;
  PermissionStatus _permissionGranted;
  LocationData _locationData;

  void _getLocation() async {
    print('Check if service is enabled');
    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        return;
      }
    }

    print('Has permissions');
    _permissionGranted = await location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {
        return;
      }
    }

    print('Try to get location');
    _locationData = await location.getLocation();
    print(_locationData);
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Location:',
            ),
            Text(
              _locationData != null
                  ? '${_locationData.toString()}'
                  : 'no location',
              style: Theme.of(context).textTheme.headline6,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _getLocation,
        child: Icon(Icons.location_on),
      ),
    );
  }
}
```

**Comment by narek11** [comment]
for iPhone device worked as expected but not the simulator

**Comment by yokoboko** [comment]
We tested on two devices in the office, iPhone 6s and iPhone X and it had same issue. Found a workaround for now - using location_permissions plugin and once the user gives access, we use flutter location plugin to get location.

**Comment by binod-techindustan** [comment]
Same not working on Simulator even after permission is enabled.

**Comment by theolof** [comment]
> We tested on two devices in the office, iPhone 6s and iPhone X and it had same issue. Found a workaround for now - using location_permissions plugin and once the user gives access, we use flutter location plugin to get location.

@yokoboko I tried your solution - first `location_permissions` to get access, and then `location` to get the location. Still no luck. It never returns at
`locationData = await _location.getLocation();`
Can you share any working code?

**Comment by yokoboko** [comment]
@theolof Don't instantiate _location before you get access from location_permission plugin.

**Comment by theolof** [comment]
Thanks, but still no luck, at least not with the simulator.
I even copied all your code and tried it. It still hangs on
`        final currentLocation = await _location.getLocation();
`

Is it working for you in the simulator as well as on real devices?

**Comment by yokoboko** [comment]
@theolof Never tried it on a simulator. I always test on real device.

**Comment by philipgiuliani** [comment]
We have the exact same problem here. It does not work on my Simulator (Version 11.4.1), but it works on my friend's Simulator (Version 13.3). Maybe that is the problem.

**Comment by theolof** [comment]
It works for me on my real device.
I didn't have to use the workaround, it worked anyway.

**Comment by MichaelM97** [comment]
Hi all, I believe that your Simulators aren't working as expected due to there being no location set for it to use. I've opened #358 which adds steps on how to do this to the `README` :)

**Comment by rasmusir** [comment]
You are a savior @MichaelM97 ! This solved my problem! I could not wrap my head around why it worked on my real device but not the simulator, especially when it had been working earlier.

**Comment by kleyos** [comment]
I use real iPhone 6S and getLocation never returns location.

**Comment by ZantsuRocks** [comment]
I don't get why this was closed.
The issue ocur in real hardware too.
(iOS 13)
Steps to reproduce:

1. Disable Location Services
2. Open the App and instantiate Location()
3. Check permissions or try to check if service is enabled.
4. Enable the service.
5. Go back to App
(Don't matter if the app has permission or you are giving permissions now)
6. Try to get location
7. The method NEVER returns.

**Comment by DustinJSilk** [comment]
If anyone else ever finds this - my location was broken due to using a few different GPS spoofing apps.. I followed FakeGPSs owners guide to reseting it here: https://www.reddit.com/r/pokemongo/comments/4snzz1/fake_gps_creator_here_i_want_to_help_you_guys/

**Comment by ch-muhammad-adil** [comment]
I have faced same issue after upgrading to `flutter 2.2.1` and in latest version `location: 4.2.1`

Downgraded it back to  `location: 4.0.0` and it has started working for me.
