### ISSUE TITLE
PermissionStatus bug while using with permission_handler

### ISSUE THREAD

**Issue by rajeshjeshar** [Lyokone/flutterlocation#338]
using location: ^3.0.1 with permission_handler: ^5.0.0+hotfix.3 in a project porduces bug with PermiisonStatus enum

**Expected behavior**
location plugin uses location_platform_interface-1.0.0 plugin,there the Enum type PermissionStatus is named exactly like in permission_handler plugin,so rename the enum to LocationPermissionStatus or LocationStatus.

**Tested on:**
 - Android, API Level 28,Real device
 
**Other plugins:**
 permission_handler: ^5.0.0+hotfix.3
```
enum LocationStatus {
  granted, denied, deniedForever
}
```

**Comment by IkhwanSI13** [comment]
Just import using an alias.

```
import 'package:location/location.dart';
import 'package:permission_handler/permission_handler.dart' as ph;

var valueFromLocation = PermissionStatus.granted;
var valueFromPermissionHandler = ph.PermissionStatus.granted;
```
