### ISSUE TITLE
Request permission doesn't return PermissionStatus in android.

### ISSUE THREAD

**Issue by binod-techindustan** [Lyokone/flutterlocation#339]
After updating the flutter SDK to 1.12.13+hotfix.8 the `await location.requestPermission();` doesn't return any result. This issue occurs in Android only.

**Expected behavior**
It should return `PermissionStatus`.

**Tested on:**
 - Android, API Level 29, simulator

**Comment by binod-techindustan** [comment]
Git the status after migrating the `FlutterActiivity` to new `io.flutter.embedding.android.FlutterActivity`

**Comment by sajidbarcha** [comment]
I am having same problem. What do you mean migrating FlutterActivity? Did you change underlying android files? Are you using Flutter on top of a native project (which would make sense)
