### ISSUE TITLE
Location Permission Deny Forever

### ISSUE THREAD

**Issue by chauhanumesh** [Lyokone/flutterlocation#341]
When permission is denied forever 
then location.hasPermission() return PermissionStatus.denied instead of PermissionStatus.deniedForever
Unhandled Exception: PlatformException(PERMISSION_DENIED_NEVER_ASK, Location permission denied forever - please open app settings, null)

**Comment by Julien-Deudon** [comment]
Any informations about this issue please ?

**Comment by jotsinghdhillon** [comment]
location.requestPermission().then((val) async {
   print(val.toString());
   if(val == PermissionStatus.deniedForever){
     await location.requestPermission();
     initPlatformState();
   }
 });


This is not able to restore the permissions
