### ISSUE TITLE
requestService() gets stuck and doesnot return anything

### ISSUE THREAD

**Issue by saadjavaidalvi** [Lyokone/flutterlocation#342]
**Describe the bug**
The requestService() function does not returns anything when used when the location is enabled.
It pops up the dialog with the option to enable the location or cancel and it doesn't matter what option you choose, the code below that does compile after that
Here is what i am trying to perform:

if (await _location.serviceEnabled()) 
{
      _getlocation();
}
else
{
        var getloc = await _location.requestService();

        if(getloc)
        _getlocation();
        else
        {
          Fluttertoast.showToast(
          msg: 'Enable Location Service'
        );
}

**Expected behavior**
It should return with a true or false, depending on the selection I choose from the pop up location enable alert

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device
 - iOS, Version XX [e.g. 10], simulator or real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by hash13** [comment]
iam currenty have the same issue and see no helpful log output

**Comment by bojanivanovski** [comment]
I have the same issue, whenever I call requestService(), the dialog is shown, and if I click OK it doesn't return a value, but rather the dialog is shown again, and when I click OK again, nothing happens, no value is return and my app is blocked

**Comment by vuleanh** [comment]
Do we have any update on this issue? Thanks alot

**Comment by ShmuelPick** [comment]
Does someone find a solution for this, or alternative?

**Comment by NarHakobyan** [comment]
this issue still action on IOS
