### ISSUE TITLE
[web] hasPermission() throws an exception with Safari both Mac and iOS

### ISSUE THREAD

**Issue by ayushin** [Lyokone/flutterlocation#345]
Will post more details tomorrow, but hasPermission() throws an exception with Safari both Mac and iOS while requestPermission() returns PermissionStatus.granted without any prompt to the user.

Subsequent getLocation() does prompt for permission.

All methods work as expected in Chrome.

Will post more details tomorrow just thought this might have been a known issue?

**Comment by nmacherey** [comment]
Same here not working on Safari both iOS and Macbook Pro

**Comment by ayushin** [comment]
My workaround for now:
`_permissionGranted = kIsWeb ? null : await _location.hasPermission();`

**Comment by Lyokone** [comment]
Hey ! Thanks for the report, not sure if Flutter Web is fully supported on other browsers ?

**Comment by enrimon15** [comment]
I have the same problem. On my mac it works well with chrome but the web app crashes in location.hasPermission() with safari and also with chrome/safari on iphone. It doesn't return any value and it doesn't even ask me if I want to allow geolocation

**Comment by rchabot32** [comment]
My work around, first call getLocation.  if I get a location, I assume permission is granted.
This works on Flutter Web Safari Browser IOS 13.5
