### ISSUE TITLE
It doesn't work on web

### ISSUE THREAD

**Issue by Dorbmon** [Lyokone/flutterlocation#346]
```
Location location = new Location();
bool _serviceEnabled;
PermissionStatus _permissionGranted;
LocationData _locationData;
_serviceEnabled =
  await location.serviceEnabled();
if (!_serviceEnabled) {
  _serviceEnabled =
  await location.requestService();
  if (!_serviceEnabled) {
    return;
  }
}
_permissionGranted =
  await location.hasPermission();
if (_permissionGranted == PermissionStatus.denied) {
  _permissionGranted = await location
    .requestPermission();
  if (_permissionGranted !=
    PermissionStatus.granted) {
  return;
  }
}
_locationData = await location.getLocation();
```
This is an example same as what you gave me in readme.
But When I run it on web in debug mode,it throw a error:
![image](https://user-images.githubusercontent.com/17807931/79229464-a31c7700-7e95-11ea-906c-b2a555f0da75.png)
And after that,when I call it again,it will never return.

**Comment by nmacherey** [comment]
Same error here kind of blocking... Any workaround ?

Working in chrome but not in Safari

**Comment by Dorbmon** [comment]
> Same error here kind of blocking... Any workaround ?
> 
> Working in chrome but not in Safari

Haha,mine doesn't work in chrome and edge.

**Comment by Lyokone** [comment]
Are you able to launch the example app ? The implementation was tested with it :)

**Comment by Dorbmon** [comment]
> Are you able to launch the example app ? The implementation was tested with it :)

Let me have a try haha.

**Comment by Dorbmon** [comment]
> Are you able to launch the example app ? The implementation was tested with it :)

I had a try.
![image](https://user-images.githubusercontent.com/17807931/79749730-49f38e00-8342-11ea-81da-5fca7c8e2bda.png)
I think it still doesn't work in the example.

**Comment by Dorbmon** [comment]
Anything new?

**Comment by Dorbmon** [comment]
Anything new?
