### ISSUE TITLE
requestPermission returns deniedForever on web after pressing "allow"

### ISSUE THREAD

**Issue by Pikaju** [Lyokone/flutterlocation#348]
**Describe the bug**
I called `await location.requestPermission()` in a webapp. Chrome gave me the popup you would expect, asking me to give permission. I clicked allow. The call to `requestPermission` finishes with `PermissionStatus.deniedForever`. Subsequent calls to `hasPermission` finish with `PermissionStatus.granted`.

**Tested on:**
 - Chrome

**Comment by giorgio79** [comment]
I am just facing this bug now as well.

**Comment by pikaju** [comment]
Unfortunately not, no, sorry, although I haven't tried much since opening this issue.
