### ISSUE TITLE
No such module 'location' when building on macos

### ISSUE THREAD

**Issue by Gintasz** [Lyokone/flutterlocation#350]
`gintas-mac:mapphotos gintas$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.18.0-6.0.pre.106, on Mac OS X 10.15.4 19E287, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.43.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (3 available)

! Doctor found issues in 1 category.`

Trying to build on macos with `location: 3.0.2` but I get this error:

`
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                              8.1s
Building macOS application...
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/gintas/Documents/AppProjects/mapphotos/macos/Runner/MainFlutterWindow.swift
	CompileSwift normal x86_64 /Users/gintas/Documents/AppProjects/mapphotos/macos/Runner/AppDelegate.swift
	CompileSwift normal x86_64 /Users/gintas/Documents/AppProjects/mapphotos/macos/Flutter/GeneratedPluginRegistrant.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
Exception: Build process failed
`

![image](https://user-images.githubusercontent.com/6189625/79875705-add58f80-83f2-11ea-8bc8-fc94dfd4f46a.png)

full pubspec.yaml here: https://pastebin.com/RhCtc0LV

**Comment by DavBfr** [comment]
The symlink trick is not working, you have to copy the .m file from ios to macos.
Try:
```shell
cp ~/.pub-cache/hosted/pub.dartlang.org/location-3.0.2/ios/Classes/*.m ~/.pub-cache/hosted/pub.dartlang.org/location-3.0.2/macos/Classes/
```

**Comment by beagle-barks** [comment]
This works for me, thanks!

**Comment by Gintasz** [comment]
Works for me too. Could this be integrated into the pub?

**Comment by PieterAelse** [comment]
@Lyokone I also face this issue. Could it be fixed? Is it as easy as copying the .m file to `macos` folder indeed?

**Comment by DavBfr** [comment]
@Lyokone Is this repo still maintained?

**Comment by PieterAelse** [comment]
@DavBfr Good question... I'm only getting `stale` updates on issues...

**Comment by radvansky-tomas** [comment]
Still nothing ?
