### ISSUE TITLE
 MissingPluginException(No implementation found for method listen on channel lyokone/locationstream)

### ISSUE THREAD

**Issue by JustinWeru12** [Lyokone/flutterlocation#353]
location.dart failing with the following missing method errors.
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method hasPermission on channel lyokone/location`
` Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)`
`Unhandled Exception: MissingPluginException(No implementation found for method requestPermission on channel lyokone/location`

**Expected behavior**
request permission and if granted return the current location 

**Tested on:**
 - Android, API Level 28, real device

Flutter Doctor
`$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.xx], locale xx)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.44.2)
[√] Connected device (1 available)

• No issues found!`

**Comment by joshuakoh1** [comment]
How did you solve this?

**Comment by JustinWeru12** [comment]
The issue was with the package versions. older versions implemented different methods and functions so ensure you are either in the most recent version or the version you are using matches the methods. i would advice the prior over the latter.

**Comment by joshuakoh1** [comment]
Hello, thanks for replying!
I am using the latest package. It broke after I switched my MainApplication.kt to auto registration. I switched mine to this according to the flutter guide. Do you mind sharing yours?
```
 import android.view.WindowManager.LayoutParams
 import io.flutter.embedding.android.FlutterActivity
 
 class MainActivity: FlutterActivity() {
 }
```

**Comment by JustinWeru12** [comment]
`import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}`
