### ISSUE TITLE
location.requestService(); this function not return any value

### ISSUE THREAD

**Issue by vitulgoyani** [Lyokone/flutterlocation#357]
```
final bool serviceRequestedResult = await location.requestService();
    if (serviceRequestedResult) {
     Print("this section not called");
      return;
    } else {
      return;
    }
```

**Comment by FredG13** [comment]
Good morning,

I have the same problem.
Thank you in advance.

Yours sincerely,

Fred

**Comment by ravitejaavv** [comment]
I am also facing same problem. Do we have any temporary solution for this?

**Comment by sharmashashi** [comment]
Having same issue. requestService() never returned anything.

**Comment by mrangelba** [comment]
Hello,

Plugin is already using flutter embedding v2, so we have to update our Android project,  https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects or recreate the project using `flutter create .`

**Comment by LucasSolares** [comment]
Same issue

**Comment by sotisoti** [comment]
> Hello,
> 
> Plugin is already using flutter embedding v2, so we have to update our Android project, https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects or recreate the project using `flutter create .`
Did it work for you?

**Comment by dokinkon** [comment]
Same issue

**Comment by GadepalliAditya1998** [comment]
You have to update your project to Android v2 embedding, 

paste this code in mainActivity.java

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}

This code you can get it from new project also just do flutter create project_name and take this file.

You even need to copy paste the android v2 embedding meta tag from manifest:

  <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
paste this tags inside application tag and outside activity tag. and run the application and everything works.

**Comment by NarHakobyan** [comment]
It's not working on IOS
