### ISSUE TITLE
iOS different behaviour then Android

### ISSUE THREAD

**Issue by kelostrada** [Lyokone/flutterlocation#36]
Hey, thanks for a great plugin!

I used Location only with callback like this:
`_location.onLocationChanged.listen(_handleLocationChanged);`

This solution works on android (calls system requirements for permissions to Location services), but doesn't work on iOS (doesn't pop the dialog with requirements for permissions).

I needed to add line: `_location.getLocation;` to trigger the logic which calls system dialogs for permissions in iOS. I think this is inconsistent behaviour and should be corrected, but apart from that great work!

Regards

**Comment by Lyokone** [comment]
Hey, 

Should be corrected on 1.3.3, iOS behaviour should match Android behaviour :)
Feel free to post another issue if it's not corrected properly 👍
