### ISSUE TITLE
Platform Exception on MacOS

### ISSUE THREAD

**Issue by JayPerfetto** [Lyokone/flutterlocation#360]
**Describe the bug**
Platform exception on mac OS -> 

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method serviceEnabled on channel lyokone/location)
#0      MethodChannel._invoke

**Expected behavior**
After enabling all of the sandbox settings, I should see the same behavior I see on iOS and android. Currently the project does not build for macos with the location plugin added

**Tested on:**
 - Android, real device
 - iOS, real device
- Mac OS Desktop, real device

**Additional logs**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.34, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.0)
[✓] VS Code (version 1.24.1)
[✓] Connected device (3 available)

**Comment by PieterAelse** [comment]
@Lyokone please re-open this ticket, this is still an issue right?
