### ISSUE TITLE
Distance between two coordinates in meters

### ISSUE THREAD

**Issue by manishvill** [Lyokone/flutterlocation#365]
**Describe the solution you'd like**
I need the distance between two coordinates your plugin works awesome but for only one thing i need to install completely different plugin geolocator

**Comment by xmashallax** [comment]
Just implement this formula to calculate the distance => [https://en.wikipedia.org/wiki/Haversine_formula](https://en.wikipedia.org/wiki/Haversine_formula)

**Comment by manishvill** [comment]
Awesome..
I was thinking about same in mid night....

Thank you
