### ISSUE TITLE
[documentation] Units of "interval" and "distanceFilter" missing

### ISSUE THREAD

**Issue by PieterAelse** [Lyokone/flutterlocation#368]
**Describe the bug**
For the method `changeSettings` the units are missing for the parameters `interval` and `distanceFilter`. They're not mentioned in code or in the doc: https://pub.dev/documentation/location/latest/location/Location/changeSettings.html 

**Expected behavior**
Package with a score of 100 would have awesome documentation.

**Actual behavior**
Time lost searching for the units/meaning of the parameters. In the end found them described in the readme file.
But please add them to the docs too!  😄

**Comment by Malik056** [comment]
I am trying to find the units as well, Can you provide the link to readme file? or can write down the units, it will save me some time 👍

**Comment by Malik056** [comment]
Found them, had to read the almost everything on the readme file, thanks for the tip.

The units are milliseconds and meters.

**Comment by PieterAelse** [comment]
Haha I did not expect this issue would be the place were people would look for them/find them, but for as long as it helps;

For `changeSettings(LocationAccuracy accuracy = LocationAccuracy.HIGH, int interval = 1000, double distanceFilter = 0)` applies:
- The `interval` will set the desired interval for active location updates, in **milliseconds** (only affects Android).
- `distanceFilter` set the minimum displacement between location updates in **meters**.

[(source: Readme file)]( https://github.com/Lyokone/flutterlocation#public-methods-summary)

**Comment by PieterAelse** [comment]
@Lyokone Please re-open this issue and make sure it doesn't get closed because of "stale" until it's fixed.
