### ISSUE TITLE
2 calls to enable GPS and get a location

### ISSUE THREAD

**Issue by firelight22** [Lyokone/flutterlocation#37]
Hi,

I think the API is stuck on the `await _location.onLocationChanged.firstWhere((d) => d != null);` when the location is not enabled beforehand. The app still asks to enable the location but after enabling it, it's stuck.

If I want a location, I have to call my method again

```dart
Future _showMeAndCenter()async {
  // Platform messages may fail, so we use a try/catch PlatformException.
  try {
    //_currentLocation = await _location.getLocation;
    _location = new Location();
    _currentLocation = await _location.onLocationChanged.firstWhere((d) => d != null);
  } on Exception {
    _currentLocation = null;
  }
}
```

**Comment by Lyokone** [comment]
Hey,

Should be corrected on 1.3.3.
Feel free to post another issue if it's not corrected properly 👍
Thank you for your feedback !
