### ISSUE TITLE
‌Build Failed

### ISSUE THREAD

**Issue by saeedhpro** [Lyokone/flutterlocation#376]
I used location plugin in my project. but build has failed!

Building plugin location...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   16.1s
✓ Built build/app/outputs/repo.
Building plugin location_web...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    2.9s
> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :checkReleaseManifest UP-TO-DATE
> Task :generateReleaseBuildConfig UP-TO-DATE
> Task :generateReleaseResValues UP-TO-DATE
> Task :generateReleaseResources UP-TO-DATE
> Task :packageReleaseResources UP-TO-DATE
> Task :parseReleaseLibraryResources UP-TO-DATE
> Task :processReleaseManifest UP-TO-DATE
> Task :generateReleaseRFile UP-TO-DATE
> Task :javaPreCompileRelease UP-TO-DATE

> Task :compileReleaseJavaWithJavac FAILED

> Task :mergeReleaseShaders UP-TO-DATE
> Task :compileReleaseShaders UP-TO-DATE
> Task :generateReleaseAssets UP-TO-DATE
> Task :packageReleaseAssets UP-TO-DATE
> Task :packageReleaseRenderscript NO-SOURCE
> Task :prepareLintJarForPublish UP-TO-DATE
> Task :processReleaseJavaRes NO-SOURCE
> Task :mergeReleaseJniLibFolders UP-TO-DATE
> Task :mergeReleaseNativeLibs UP-TO-DATE
> Task :stripReleaseDebugSymbols UP-TO-DATE
> Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
17 actionable tasks: 1 executed, 16 up-to-date

/home/saeedhpro/.pub-cache/hosted/pub.dartlang.org/location_web-1.0.0/android/src/main/java/com/lyokone/location_web/LocationWebPlugin.java:3: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/home/saeedhpro/.pub-cache/hosted/pub.dartlang.org/location_web-1.0.0/android/src/main/java/com/lyokone/location_web/LocationWebPlugin.java:15: error: cannot find symbol
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) { }
                                  ^
  symbol:   class NonNull
  location: class LocationWebPlugin
/home/saeedhpro/.pub-cache/hosted/pub.dartlang.org/location_web-1.0.0/android/src/main/java/com/lyokone/location_web/LocationWebPlugin.java:20: error: cannot find symbol
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) { }
                                    ^
  symbol:   class NonNull
  location: class LocationWebPlugin
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin location_web could not be built due to the issue above.

* flutter doctor -v:

[✓] Flutter (Channel stable, v1.17.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.2 at /home/saeedhpro/other/softwares/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/saeedhpro/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/saeedhpro/Android/Sdk
    • Java binary at: /softwares/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /softwares/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is .github.com,.getcomposer.org,.laravel.com,.packagist.org,.npmjs.org,localhost,127.0.0.1,.yarnpkg.com,https://production.cloudflare.docker.com
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • SM J701F • 5200acc94e1cb43d • android-arm • Android 9 (API 28)

• No issues found!

**Comment by jeybs** [comment]
still no solutions for this?
