### ISSUE TITLE
GPS is not turned off after getLocation()

### ISSUE THREAD

**Issue by strigePC** [Lyokone/flutterlocation#378]
**Describe the bug**
After I check all permissions and whether the service is enabled or not, I call `Location().getLocation()`. It returns the LocationData object as usual. However, the icon in the toolbar that indicates if the GPS service is being used does not disappear.
Also, I am not sure, but it seems that it drains battery a bit faster (but I haven't tested it yet, so it might not affect battery at all).

**Expected behavior**
The icon on the toolbar should disappear right after the location had been fetched.

**Tested on:**
 - Android, API Level 28, OnePlus 7T

**Version**
- `flutter: 1.17.0`
- `location: 3.0.2`

**Screenshot**
![Screenshot_20200610-191631](https://user-images.githubusercontent.com/24938673/84272299-0bfb3500-ab4f-11ea-818f-c00fc93bf084.jpg)

**Comment by binhithaui** [comment]
Same error!

**Comment by strigePC** [comment]
still not solved, ehh...

**Comment by xni06** [comment]
> still not solved, ehh...

Are you still using `flutter: 1.17.0` and `location: 3.0.2` ?
