### ISSUE TITLE
`onLocationChanged` keeps firing location events after `cancel()` has been called

### ISSUE THREAD

**Issue by komape** [Lyokone/flutterlocation#379]
**Describe the bug**
After calling `cancel()` the `StreamSubscription` keeps firing location events. On a simulated device with API level 29 it does **not** happen.

```dart
StreamSubscription<LocationData> _locationStream;

_locationStream =
        location.onLocationChanged.listen((LocationData locationData) {
   print(locationData);
});

_locationStream.cancel(); // after this call I still receive prints of locationData
```

**Expected behavior**
The 'StreamSubscription` should stop receiving any location events.

**Tested on:**
 - Android, API Level 22, real device: Nexus 4

**Other plugins:**
 - flutter_map 0.9.0

**Comment by komape** [comment]
activity

**Comment by ovaldi** [comment]
Same issue, could you have a look? @Lyokone

**Comment by dasmobile** [comment]
Same here.  Any updates?

**Comment by HugoHeneault** [comment]
Same here. Did anyone find a solution?
Thanks.
