### ISSUE TITLE
Namespacing - clash with geolocator plugin

### ISSUE THREAD

**Issue by giorgio79** [Lyokone/flutterlocation#381]
Having both geolocator and location plugin gives this error

https://pub.dev/packages/location
https://pub.dev/packages/geolocator

```
Compiler message:
lib/screens/1_GetLocation.dart:17:46: Error: 'LocationAccuracy' is imported from both 'package:geolocator/geolocator.dart' and 'package:location_platform_interface/location_platform_interface.dart'.
        .getCurrentPosition(desiredAccuracy: LocationAccuracy.high)

```

**Describe the bug**

**Expected behavior**

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device
 - iOS, Version XX [e.g. 10], simulator or real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by JayakumarB** [comment]
Hi @giorgio79 ,

Use the alias option like below,

`import 'package:geolocator/geolocator.dart';
import 'package:location/location.dart' as locService;

locService.Location location = new locService.Location();`

Thanks,
JayakumarB
