### ISSUE TITLE
Location not working in web browser(Chrome, Safari ) on IOS device such as Iphone, Ipad

### ISSUE THREAD

**Issue by joumduk** [Lyokone/flutterlocation#387]
This plugin is not working in web browser(Chrome, Safari ) on IOS device such as Iphone, Ipad

In my case, 
The website is needed location for searching nearby places 
So, this page work with location plugin
But the page is stoped during to load the page on IOS device web browser
However, this page is showed on android device

**Comment by silau2005** [comment]
The implementation is iOS is a bit stricter on the following js function
`navigator.geolocation.getCurrentPosition(success[, error[, [options]])`

thr error part is required for iOS, this package's implementation did't touch the error handling, so it doesn't work on iOS device. 


[https://github.com/Lyokone/flutterlocation/search?q=getCurrentPosition&unscoped_q=getCurrentPosition](url)
[https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition](url)

**Comment by Faisalkc4u** [comment]
facing the same issue
Initially it's requesting for the permission.
Once "allowed" response

**Comment by xpat** [comment]
I was able to modify a tutorial for a weather app using just the Lyokone/Flutterlocation package.  Did you try it without Mozilla's Geolocation (and without Baseflow's Geolocator package)?  @silau2005

**Comment by mma180s** [comment]
I was able to get it working. Please have a look at the solution here: https://github.com/Lyokone/flutterlocation/issues/423#issue-705066149. Basically, check if platform is web and if it is on web, ignore the code blocks where service enabled and permission granted checks are being done. They do not work in iOS Safari. Directly calling the "await location.getLocation()" will give intended behavior but only lat & long will be available as browser API also only returns those 2 values.

**Comment by vadrian89** [comment]
> I was able to get it working. Please have a look at the solution here: [#423 (comment)](https://github.com/Lyokone/flutterlocation/issues/423#issue-705066149). Basically, check if platform is web and if it is on web, ignore the code blocks where service enabled and permission granted checks are being done. They do not work in iOS Safari. Directly calling the "await location.getLocation()" will give intended behavior but only lat & long will be available as browser API also only returns those 2 values.

I can confirm this worked for me aswell. Thank you!
