### ISSUE TITLE
Easily support the Location provider of Huawei Mobile Services

### ISSUE THREAD

**Issue by abusuioc** [Lyokone/flutterlocation#388]
Hello! First of all, thx for the great work on this library which simplifies considerably cross-platform location usage.

On the Android side of things, because there is a new player in town when it comes to mobile services (Huawei) it would be great if  Huawei Mobile Services fused location provider would be supported by your plugin as well.

There is a quick way to accomplish this - the integration effort would not go beyond 15 minutes of your time.

On native apps, developers are already using my wrapper library: [https://github.com/abusuioc/hms-gms-wrapper-location](https://github.com/abusuioc/hms-gms-wrapper-location)
The library allows you to immediately have location services available on HMS devices if you already own a Google Play Services (GMS) location implementation, as you do. The main advantage is that you can leave the code structure unchanged because the wrapper API follows the GMS API 1:1 and what it does under the hood is simply to route the calls depending on availability:  the default preference is still GMS.

Let's discuss more if you have further questions.
I hope this helps you and it will help other users of your library.

**Comment by junaidlodhi22** [comment]
We definitely need this merged.

**Comment by TheOneWithTheBraid** [comment]
I would like to extend the issue: What about libre software?

For stores such as F-Droid, inclusion of the Google Service Framework (or even a reference to their classes) is strictly prohibited. Is there any way to create a build which is not at all referencing Google's libraries?
