### ISSUE TITLE
changeSetting API should use the dart Duration Type not an int

### ISSUE THREAD

**Issue by ride4sun** [Lyokone/flutterlocation#392]
In order to have a self-describing robust API, the lib should use dart type Duration and not int
for the interval. Also, there is no description of what the int unit actually is. I guess `ms`
The duration can easily be converted back into int as needed for the call into the next layer.
```
  Future<bool> changeSettings({
    LocationAccuracy accuracy = LocationAccuracy.high,
    int interval = 1000,
    double distanceFilter = 0,
  }) {
```

**Comment by ride4sun** [comment]
Is this lib maintained?

**Comment by ride4sun** [comment]
This is really unprofessional closing defect because the maintainer is not reacting. I would advise people to use another lib. My 2 cents

**Comment by ride4sun** [comment]
I think not this issue is stale. The library is stale. My 2 Cents. No
support here

**Comment by ride4sun** [comment]
Is there anybody maintaining this?

**Comment by Lyokone** [comment]
Hi, sorry for not responding for this long.
I'll check when I'll have time, If you feel like submitting a PR, It will be very much appreciated :)

**Comment by ride4sun** [comment]
Maybe you should switch the robot off and avoid that issues will be cleared out automatically without any responses.I look into sending a PR but I need your time to approve it

**Comment by ride4sun** [comment]
any takers

**Comment by ride4sun** [comment]
Again just bad practice just closing issues. That does not make it look
better. So unprofessional.
