### ISSUE TITLE
await location.getLocation() Sometime taking too much time to response

### ISSUE THREAD

**Issue by Virakyuth-PK** [Lyokone/flutterlocation#393]

**Comment by lukaskurz** [comment]
I too am experiencing this issue. Code to reproduce is not much, basically create a location instance and call `getLocation`. Using the logs to measure, it often takes up to 4 seconds to request the location. Is this normal behaviour

```dart
Location location = Location();
dev.log("start");
final currentLocation = await location.getLocation();
dev.log("end");
```

### Versions
```
flutter --version
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (3 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```
```
location: ^3.0.2
```

**Comment by kumbhdesign** [comment]
@lukaskurz  Did you found the solution to reduce this time?

**Comment by lukaskurz** [comment]
Haven't touched that part of my codebase (or the project itself) for a long time, but I don't think I did. I just rewrote the logic to continually request locations in the background, so that one is immediately available when I need it.
