### ISSUE TITLE
location.getLocation does not work anymore

### ISSUE THREAD

**Issue by robertocoral** [Lyokone/flutterlocation#396]
**Describe the bug**
location.getLocation does not return anything (infinite or really long wait)

**Tested on:**
 - iOS, Version 12, simulator (iPhone 11 Pro Max and iPhone 8 Plus) and real device (iPhone 6S)

**Comment by skionthursday** [comment]
I am finding a similar behavior when -- getting a silent fail/exit from:
_locationData = await location.getLocation(); 

Digging deeper, I get same kind of no error trapped, silent fail/exit from :
try {
    _serviceEnabled = await location.serviceEnabled();
     }
     catch (e) {
      print('Error caught: $e');
    }

Interesting to note in that when running the code on the iOS simulator all works well, no problems, but when plugging in an actual iPad Air, the problem occurs.  

======
Flutter 1.17.5
VS Code 1.47.3 (June 2020)
Location 3.0.2
iPad Air model 1474 / MD785LL/B -- running iOS 12.4.8
iOS Simulator iPad Air (3 gen)

Running Flutter, VS Code, etc. on MacBook running MacOS Catalina 10.15.6

**Comment by dqr79** [comment]
same here - actually, _locationData = await location.getLocation(); works the very first time; but if I call it once more it waits infinitely without an error..

**Comment by DennisKragekjaer** [comment]
Same here

**Comment by Nico04** [comment]
Any news on this ?

**Comment by tanbtv-2058** [comment]
same here 
Flutter 1.14.6
Android API 23

**Comment by Flucadetena** [comment]
Same Here, it worked perfectly before, and now it doesn't:

Flutter 1.22.2
IOS: 14.0
