### ISSUE TITLE
checking for location services always returns true !

### ISSUE THREAD

**Issue by anirudhsharma392** [Lyokone/flutterlocation#406]
**Describe the bug**
serviceEnabled() function always return true even i switch off the GPS.

**Expected behavior**
It must return false if GPS is not activated.

**Tested on:**
 - Android, API Level 28, C103_C103_Coolpad

**Comment by anirudhsharma392** [comment]
Then how to make sure that GPS is not in power saving mode and we can get location.

**Comment by akashnigam010** [comment]
I am having same issue.
`await location.serviceEnabled();` always returns true for some devices.

**Comment by arunvast** [comment]
did any one found any solution on this? i'm facing same issue. thanks

**Comment by Brinfotech1407** [comment]
Still i am facing the same issue does anyone have working solution on how to check GPS is on or not ?
