### ISSUE TITLE
changeSettings - Accuracy doesnt seem to update

### ISSUE THREAD

**Issue by Josh-Mus** [Lyokone/flutterlocation#413]
**Describe the bug**
  ```
Location location = new Location();

    bool _serviceEnabled;
    PermissionStatus _permissionGranted;
    LocationData _locationData;

    await location.changeSettings(accuracy: LocationAccuracy.low);
```
It seems that the accuracy is staying on high. Ive followed the documentation but it seems to be out of date. Perhaps this is a caching issue, or i'm missing a step?

**Tested on:**
 - iOS, Version 12.3.1 real device (iPhone 6)

**Comment by attilavago** [comment]
I'm seeing the exact same issue. The example in the docs is very limited too, unfortunately. 😞

**Comment by haraldkofler** [comment]
I can confirm the same behavior on android.

**Comment by attilavago** [comment]
@mehmetf is this project still active, or has it been abandoned? I don't think auto-closing issues is the right way to go about things...

**Comment by mehmetf** [comment]
@Lyokone can comment on that. I don't have permissions to add or remove bots.

**Comment by parmarravi** [comment]
have any one cracked the answer?
