### ISSUE TITLE
The debug version of the code runs, while the release version throws an exception

### ISSUE THREAD

**Issue by kust-wulin** [Lyokone/flutterlocation#414]
In my code, I have a line of code:
LocationData position = await _location.getLocation();
In debug version of the code, this call return position.
However, in release version of the code, this call immediately throws an exception.
PlatformException(UNEXPECTED_ERROR, -5:Core error, null)
My cellphone is a Huawei's phone.

I have checked the source code of location and changed the error message to find which line throws this exception.  The line throws this exception is:
FlutterLocation.java:417
sendError("UNEXPECTED_ERROR", e.getMessage(), null);

Since the debug version of the code works, I expect the release version will return the location instead of throwing an exception.
In simulator, the code runs without error.  My location version is 3.0.2

I have tested on:
 - Android 9, API Level 28, real device

Because Huawei's phone cannot access gms service in china.  I used hms-gms-wrapper-location library at https://github.com/abusuioc/hms-gms-wrapper-location
this library allows me to use hms service instead.   The version of hms-gms-wrapper-location I use is 1.0-beta-1

**Comment by kust-wulin** [comment]
I found the solution.  Please refer to https://github.com/abusuioc/hms-gms-wrapper-location/issues/2

**Comment by abusuioc** [comment]
@kust-wulin I made a proposal to the developer to support the location wrapper, but unfortunately it was ignored: #388

**Comment by kust-wulin** [comment]
It is this proposal that we found your library.
I believe if more and more people use your library, the position team will support the wrapper.


Thanks a lot.&nbsp; Have a nice day.


Lin


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lyokone/flutterlocation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上7:56
收件人:&nbsp;"Lyokone/flutterlocation"<flutterlocation@noreply.github.com&gt;;
抄送:&nbsp;"吴霖"<52038994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Lyokone/flutterlocation] The debug version of the code runs, while the release version throws an exception (#414)





 
@kust-wulin I made a proposal to the developer to support the location wrapper, but unfortunately it was ignored: #388
