### ISSUE TITLE
Plugin project :location_web not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by Junaidhassan99** [Lyokone/flutterlocation#415]
I am getting this error while using the location package.

**Comment by xpat** [comment]
Are you using a recent version of Flutter?  I just used the Location/LocationData in a Flutter web project (instead of Baseflow's Geolocator).  

From the docs:

> location_web
> The web implementation of location.
> 
> Usage
> Import the package
> This package is the endorsed implementation of location for the web platform since version 3.0.0, so it gets automatically added to your dependencies by depending on location: ^3.0.0.
> 
> No modifications to your pubspec.yaml should be required in a recent enough version of Flutter (>=1.12.13+hotfix.4):
> 
> ...
> dependencies:
>   ...
>   location: ^3.0.0
>   ...
> Once you have location in pubspec.yaml you should be able to use package:location as normal.

**Comment by Junaidhassan99** [comment]
@xpat The error was resolved by using flutter clean. Thanks!.

**Comment by funder7** [comment]
`flutter clean` didn't work for me
