### ISSUE TITLE
Time out getting location

### ISSUE THREAD

**Issue by 2math** [Lyokone/flutterlocation#419]
**Is your feature request related to a problem? Please describe.**
The problem comes when the user is on a place where the GPS signal is crappy, then getting location may hang forever. 

**Describe the solution you'd like**
Will be nice to set a timeout timer, like 15 sec and if we don't get location till then to cancel the request.
Will be nice to have an option to cancel the request manually, this way the dev can implement the timer it self or canceling the request when the user goes to another screen.

**Describe workarounds you've considered**
Currently I use Bloc pattern and that way I'm protected of updating the screen for detached screens, but still there is a memory 
leak (I think ) in the bloc it self, since is waiting for a location that never comes.

**Comment by sm2017** [comment]
@Lyokone Is there any timeout option?

**Comment by satyajit-ink** [comment]
> @Lyokone Is there any timeout option?

ya bro just do .timeout
