### ISSUE TITLE
Build Failed for release android

### ISSUE THREAD

**Issue by jeybs** [Lyokone/flutterlocation#420]
I used location plugin in my project. but build has failed when im trying to create and release apk using this command
"flutter build apk --split-per-abi"

it gives me this error

> C:\Users\josep\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\location_web-1.0.0\android\src\main\java\com\lyokone\location_web\LocationWebPlugin.java:3: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\Users\josep\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\location_web-1.0.0\android\src\main\java\com\lyokone\location_web\LocationWebPlugin.java:15: error: cannot find symbol
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) { }
                                  ^
  symbol:   class NonNull
  location: class LocationWebPlugin
C:\Users\josep\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\location_web-1.0.0\android\src\main\java\com\lyokone\location_web\LocationWebPlugin.java:20: error: cannot find symbol
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) { }
                                    ^
  symbol:   class NonNull
  location: class LocationWebPlugin
3 errors

>FAILURE: Build failed with an exception.

>* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

>* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Here my flutter doctor result**

> [√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1082], locale en-PH)
    • Flutter version 1.20.3 at E:\flutter\fluttersdk
    • Framework revision 216dee60c0 (10 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\Android\sdk
    • Java binary at: E:\Android\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

>[√] Android Studio (version 3.6)
    • Android Studio at E:\Android\studio
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

>[√] Connected device (1 available)
    • Mi 9T Pro (mobile) • b4f7dc4d • android-arm64 • Android 10 (API 29)

>• No issues found!

any solutions for this build error?

**Comment by Luby1917** [comment]
I ran into this issue, the fix for was to edit the `<flutter_root>/.pub-cache/hosted/pub.dartlang.org/location_web-1.0.0/android/build.gradle` and add these lines: 
```
dependencies {
    implementation "androidx.annotation:annotation:1.1.0"
}
```
I don't know if there is a better workaround, but this solved the problem for me.

**Comment by azizkazdal** [comment]
I have the same issue. Have you got any solution  ?
