### ISSUE TITLE
getLocation() not responding in ios.

### ISSUE THREAD

**Issue by a7mdragab** [Lyokone/flutterlocation#422]
I am using this package in android.
When I moved to IOS, the function getLocation() is not responding.

**Comment by ahmedsalamay** [comment]
Same here too

**Comment by dan1229** [comment]
Same here as well - just switched to this package and it was working at first but now seems to hang on "getLocation()" even if the permission is granted.

**Comment by RajithShetty619** [comment]
same issue happening here did you guys found a fix??

**Comment by mikhaelr** [comment]
Same issue for me :/

**Comment by uday1st** [comment]
Facing the same issue!

**Comment by jeremiahlukus** [comment]
Same issue as well

**Comment by a7mdragab** [comment]
Any updates?

**Comment by jeremiahlukus** [comment]
My issue was due to the emulator. I needed to go to debug -> location -> Apple (or whatever you wanted).

**Comment by abdalmonem** [comment]
same here

**Comment by Flucadetena** [comment]
For anyones with the same issue in Emulator. The solution is as @jeremiahlukus stated, but to expand:

The emulator doesn't provide a location, so you need to configure one predefined or a custom one for the emulator. You can do this, by going into `Features > Location > ...` and choose either `Apple`, which will set the location in the Cupertino oficies  or any other option, in the menu of the emulator program, at the top of the screen. Not on the settings of the devices.

This will make it work. ;)

**Comment by aamirki** [comment]
I can't get `getLocation()` to work on the iOS simulator even after setting a custom location

**Comment by aamirki** [comment]
Has anyone found a solution to this? I am explicitly setting a location in the iOS Simulator via `Features > Location > Custom Location` and everytime I call `getLocation()` it will silently fail without an error.

**Comment by afifahsalimi** [comment]
> Has anyone found a solution to this? I am explicitly setting a location in the iOS Simulator via `Features > Location > Custom Location` and everytime I call `getLocation()` it will silently fail without an error.

I encountered same issue. In pubspec.yaml I used ^3.0.0 before, after I updated ^3.1.0, the problem is gone.

**Comment by mladenbrankovic** [comment]
I'm having the same issue. `getLocation()` works on Android, but not iOS. There doesn't seem to be any error thrown either, the Future just never finishes. Updating from 3.0.0 to 3.1.0 didn't help either.

**Comment by aamirki** [comment]
Can confirm this is still an issue even after updating to 3.1.0 @afifahsalimi

**Comment by giorgio79** [comment]
Same for 
`      _permissionGranted = await location.requestPermission();
`
Works like magic on Android

**Comment by giorgio79** [comment]
I got it to work.

Checked location permission, and it was set to "Never". Set it to Ask next time.

**Comment by aamirki** [comment]
A potential solution I found was removing this from `Info.plist`:
```
<key>EnableBackgroundLocationUpdates</key> <true/>
```

**Comment by Batres35** [comment]
> A potential solution I found was removing this from `Info.plist`:
> 
> ```
> <key>EnableBackgroundLocationUpdates</key> <true/>
> ```

That doesn't work for me, i still with this issue on version 3.1.0 with a physical ios device.

**Comment by Batres35** [comment]
I solve the issue, in my case i was calling the function getLocation() so many times at the same, causing a weird situation that doesn't allow to get a new location.

**Comment by Batres35** [comment]
In my case, the problem was the onLocationChanged stream, when i have an active stream of onLocationChanged, i can't use the function getLocation() because it don't respond.
If i don't activate the getLocation() stream, the function getLocation() works perfectly, this on a physical iPhone with plugin version ^3.1.0.
