### ISSUE TITLE
Solution for Flutter Web on iOS Safari/Chrome or iOS PWA

### ISSUE THREAD

**Issue by mma180s** [Lyokone/flutterlocation#423]
**Description**
Default example snippet from pub.dev when used for Flutter Web on iOS Browsers (iOS Safari/Chrome/PWA) won't work due to additional permission & service-enabled checks. The solution is to simply ignore permission & service checks and directly call "await location.getLocation();" if platform is web. Reason is clear if one looks at location_web implementation here: https://github.com/Lyokone/flutterlocation/blob/master/location_web/lib/location_web.dart. Also, on web platform, only latitude & longitude will be available while most of the rest of attributes will be 0 as browser API would only return lat & long.

**Tested on:**
 - iOS, Version 14.0, real device (Not as an iOS app, but as web app running on iOS 14 Safari or as PWA from Add To Home Screen command)
- Google Chrome desktop on Windows 10

**Solution**

    import "package:flutter/foundation.dart" show kIsWeb;

    Location location = new Location();
    LocationData _locationData;

    if (!kIsWeb) {
        bool _serviceEnabled;
        PermissionStatus _permissionGranted;
    
        _serviceEnabled = await location.serviceEnabled();
        if (!_serviceEnabled) {
          _serviceEnabled = await location.requestService();
          if (!_serviceEnabled) {
            return;
          }
        }
    
        _permissionGranted = await location.hasPermission();
        if (_permissionGranted == PermissionStatus.denied) {
          _permissionGranted = await location.requestPermission();
          if (_permissionGranted != PermissionStatus.granted) {
            return;
          }
        }
    }

    _locationData = await location.getLocation();

That's it.

**Comment by vadrian89** [comment]
Lovely, will give it a try as soon as I am able. Thank you very much.

**Comment by andaryjo** [comment]
As its works on web on all other platforms, there should be a better way than simply not performing `requestPermission()` and `hasPermission()` on web.

Is there any way to determine whether the app runs on a browser on iOS? Maybe by parsing the User-Agent?

**Comment by andaryjo** [comment]
I was able to use the `dart:html` library to access the User-Agent of the browser and retrieve the `platform` attribute, which contains the host OS of the browser the application is executed in.

Keep in mind that dart:html can only be imported in Flutter Web and you will need to implement a conditional import if you're targeting other platforms too.

**Comment by Limvunhoy** [comment]
I got an error when user turn off their device location service. Anyone could help on this
