### ISSUE TITLE
Request Service Method doesn't give callback 

### ISSUE THREAD

**Issue by rajatjain2802** [Lyokone/flutterlocation#425]
Here is My Code, 

 bool isServiceEnabled = await _location.requestService();
        if (isServiceEnabled != null && isServiceEnabled) {
          LocationData location = await Location().getLocation();

//positionData is My Local Class 
          positionData = new position.Location();
          positionData.latitude = location.latitude;
          positionData.longitude = location.longitude;
        } else {
          positionData = null;
        }

When Dialog is Open And I click on Ok Then Nothing to work, please check

**Comment by boeingjr** [comment]
I'm seeing the same issue as well, requestService() does not return on Android.  On iOS it returns instantly, and also pops up a dialog explaining how to turn it on.
