### ISSUE TITLE
Error when building app for Android

### ISSUE THREAD

**Issue by luccascorrea** [Lyokone/flutterlocation#43]
When I try to run the app, I get the following messages:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-base' has different version for the compile (11.8.0) and runtime (15.0.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle build failed: 1
```

I saw [here](https://stackoverflow.com/a/47066325/2343626) that, in order to fix this, all you have to do is change the GMS dependency from "implementation" to "api" in the library's build.gradle file. 

I did it and it worked. I am just posting this issue to let you guys know so that someone can fix it. Thanks.

**Comment by Lyokone** [comment]
Hi,
I've changed it, hope it will solve this problem for good 👍 Thank you
