### ISSUE TITLE
where and how?

### ISSUE THREAD

**Issue by ridharezzag** [Lyokone/flutterlocation#430]
Hi thanks for the package
i hope you explain  how exactly to add this 

iOS 
And to use it in iOS, you have to add this permission in Info.plist :

NSLocationWhenInUseUsageDescription
NSLocationAlwaysUsageDescription

------
that step its not clear if we just threw those line anywhere in   Info.plist
but it does not seems right, please consider that there is developers who never worked on IOS, and there is beginners

**Comment by eti88** [comment]
Hi, yes the documentation is not very clear but just check the sample project. Just check [here](https://github.com/Lyokone/flutterlocation/blob/master/location/example/ios/Runner/Info.plist) and find your answer.
