### ISSUE TITLE
Issue in retrive the status of location service - XIAOMI Android 9  

### ISSUE THREAD

**Issue by CristianTorrado** [Lyokone/flutterlocation#434]
#  Tested in - Android, API Level 28 . android 9 pkq1 -  xiaomi , xiaomi MI9T 

# Description of the error
In the device target reported, the  LocationPlatform.instance.serviceEnabled() returns true when the location service is disabled.

Apart of this wrong  behavior after check and recibe the wrong status value. 

I call  the LocationPlatform.instance.getLocation() method and the Future returned by the method never ended, i thinks is because the locations service is disabled. 

# Expected behavior

LocationPlatform.instance.serviceEnabled() returns false when the location service is disabled. 

LocationPlatform.instance.getLocation() return an error or result null when the location service is disabled

**Comment by CristianTorrado** [comment]
Hi any update of this issue ?

**Comment by Lyokone** [comment]
Hi ! I do not have any Xiaomi device to test that :/ Can you try with 3.1.0 ?

**Comment by xalanq** [comment]
same here
Android Version: 10
Security Patch Level: 2020-08-01
MIUI version: MIUI 12.0.6Stable 12.0.6.0(QJACNXM)

**Comment by zxydream** [comment]
I also encountered this problem.
I think the reason for this problem is that Xiaomi devices do not support Google Play Store.
I noticed this message: 
W/GooglePlayServicesUtil(28469): Google Play Store is missing.
E/GoogleApiAvailability(29476): Google Play services is invalid. Cannot recover.
