### ISSUE TITLE
flutter-web: get location on web by Location plugin

### ISSUE THREAD

**Issue by tazik561** [Lyokone/flutterlocation#435]
I have old flutter project, I added web support to it, Now ,I am trying to get my Location in flutter web , So i added [location][1] to my page.
this is my code:

      @override
      void initState() {
        super.initState();
        _getLocation();
      }
    
      Future _getLocation() async {
        Location location = new Location();
    
        var _permissionGranted = await location.hasPermission();
        _serviceEnabled = await location.serviceEnabled();
    
        if (_permissionGranted != PermissionStatus.granted || !_serviceEnabled) {
          _permissionGranted = await location.requestPermission();
          _serviceEnabled = await location.requestService();
        } else {
          print("-----> $_serviceEnabled");
    
          setState(() {
            _serviceEnabled = true;
            _loading = false;
          });
        }
    
        try {
          final LocationData currentPosition = await location.getLocation();
          setState(() {
            longitude = currentPosition.longitude.toString();
            latitude = currentPosition.latitude.toString();
            print(
                '${widget.url}?BranchName=&latitude=${latitude}&longitude=${longitude}');
            _loading = false;
          });
        } on PlatformException catch (err) {
          _loading = false;
          print("-----> ${err.code}");
        }
      }

After getting Location permission by chrome,

[![enter image description here][2]][2]

 Nothing happening!
In vsCode console i just got this error:

    Error: [object GeolocationPositionError]
    
    
        at Object.createErrorWithStack (http://localhost:43705/dart_sdk.js:4351:12)
        at Object._rethrow (http://localhost:43705/dart_sdk.js:37962:16)
        at async._AsyncCallbackEntry.new.callback (http://localhost:43705/dart_sdk.js:37956:13)
        at Object._microtaskLoop (http://localhost:43705/dart_sdk.js:37788:13)
        at _startMicrotaskLoop (http://localhost:43705/dart_sdk.js:37794:13)
        at http://localhost:43705/dart_sdk.js:33303:9

**USING @JS('navigator.geolocation')

I also [try this][3], but never `success` method called and nothing heppen.

  [1]: https://pub.dev/packages/location
  [2]: https://i.stack.imgur.com/FVb85.png
  [3]: https://stackoverflow.com/questions/60209381/get-users-location-for-flutter-web

**Comment by shatanikmahanty** [comment]
Hi this plugin is not working for flutter web in Ios safari. Are you using an apple device too?

**Comment by shatanikmahanty** [comment]
https://github.com/Lyokone/flutterlocation/issues/423#issue-705066149 I found the solution to IOS bug here

**Comment by Hardeepsingh980** [comment]
Hi i am getting the same exact error using web on windows 10. I have used the example code from location package. Please help someone

**Comment by shatanikmahanty** [comment]
> Hi i am getting the same exact error using web on windows 10. I have used the example code from location package. Please help someone

Check out the issue mentioned in my comment above. It has the solution. Basically for IOS you should not request permission using plugin. Just make the location request and it would work fine
