### ISSUE TITLE
`getLocation()` never completes when a second call to `getLocation()` is made before the first call completes

### ISSUE THREAD

**Issue by lauweijie** [Lyokone/flutterlocation#438]
**Describe the bug**
`getLocation()` never completes when a second call to `getLocation()` is made before the first call completes.

```dart
final location = Location();
final loc1 = location.getLocation();
final loc2 = location.getLocation();
print(await loc2);
print(await loc1);
```

**Expected behavior**
Both futures (`loc1` and `loc2`) should complete.

**Actual behavior**
Only `loc2` completes.

**Tested on:**
 - Android

---

https://github.com/Lyokone/flutterlocation/blob/master/location/android/src/main/java/com/lyokone/location/MethodCallHandlerImpl.java#L98

```
    private void onGetLocation(Result result) {
        location.getLocationResult = result;
        if (!location.checkPermissions()) {
            location.requestPermissions();
        } else {
            location.startRequestingLocation();
        }
    }
```

In the above method, getLocationResult is being replaced with the new result.

`Result getLocationResult` should be changed to `List<Result> getLocationResults` so that previous requests are not overriden.

**Comment by mehmetf** [comment]
Keeping track of all Result's would also require you to keep the link between the request and the result somehow. That makes plugin code more complex than needed. 

There's no need for multiple location requests to be active at the same time. You should instead consider keeping the same Future in Dart and returning it if it is requested again. You should also make sure the Future is being requested in the same Zone (by checking `Zone.current`).

**Comment by YunkeTang** [comment]
It is actually a Flutter plugin bug. See the other posts for this:
https://github.com/Lyokone/flutterlocation/issues/396
https://github.com/Lyokone/flutterlocation/issues/169

The reason we should fix this in the Flutter side:
1. It's hard to make sure all features in the app are keeping track of the same Future to the getLocation().
2. If GPS signal is weak, even the two calls are not that close (e.g. 5 seconds in between), we may still get this issue.

**Comment by mehmetf** [comment]
@YunkeTang I am saying the same thing. The following comment refers to plugin Dart code rather than application code. The plugin would return you the same future if it has not completed yet (and it is being called from the same `Zone`):

> There's no need for multiple location requests to be active at the same time. You should instead consider keeping the same Future in Dart and returning it if it is requested again. You should also make sure the Future is being requested in the same Zone (by checking Zone.current).

**Comment by lauweijie** [comment]
@mehmetf can you help to reopen this issue? I think it still needs fixing on the plugin Dart code side as you suggested.
