### ISSUE TITLE
Failed to get location

### ISSUE THREAD

**Issue by alexjuniodev** [Lyokone/flutterlocation#44]
I'm getting the error when it calls  

**.invokeMethod('getLocation')** 

  Future<Map<String, double>> get getLocation => _channel
      .invokeMethod('getLocation')
      .then((result) => result.cast<String, double>());

**inside location.dart.** 

The message error is "Failed to get location"
The app asks for permition.

=============================================
(build.gradle)

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.1.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4'
    }
}

============================================
(pubspec.yaml)

dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.4.1
  google_sign_in: 3.0.2
  firebase_analytics: 0.3.3
  firebase_auth: 0.5.5
  firebase_database: 0.4.6
  firebase_storage: 0.3.0
  cached_network_image: "^0.4.1"
  rxdart: ^0.16.7
  cupertino_icons: ^0.1.0
  photo_view: 0.0.2
  flutter_map: ^0.0.1
  location: 1.3.3
  geohash: 0.1.1

==============================================
(messages)
```
Reloaded 3 of 651 libraries in 1.025ms.
E/flutter ( 8349): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 8349): PlatformException(ERROR, Failed to get location., null)
E/flutter ( 8349): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter ( 8349): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 8349): <asynchronous suspension>
E/flutter ( 8349): #2      Location.getLocation (package:location/location.dart:12:8)
E/flutter ( 8349): #3      new ControllerLocation (package:flutter_chat/utils/geographic/ControllerLocation.dart:17:15)
E/flutter ( 8349): #4      _MyMapWidgetState.build (package:flutter_chat/pages/map_screen.dart:96:30)
E/flutter ( 8349): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
E/flutter ( 8349): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
E/flutter ( 8349): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 8349): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
E/flutter ( 8349): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
E/flutter ( 8349): #11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
E/flutter ( 8349): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 8349): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 8349): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
E/flutter ( 8349): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 8349): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 8349): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
E/flutter ( 8349): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #21     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
E/flutter ( 8349): #22     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
E/flutter ( 8349): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 8349): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 8349): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
E/flutter ( 8349): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 8349): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 8349): #30     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
E/flutter ( 8349): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 8349): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 8349): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
E/flutter ( 8349): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
E/flutter ( 8349): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 8349): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 8349): #40     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
E/flutter ( 8349): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
E/flutter ( 8349): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
E/flutter ( 8349): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 8349): #45     Element.rebuild (package:flutter/src/widge
```

**Comment by AlexandreRoba** [comment]
I'm having the same error... Any update on this?

**Comment by aslamzee** [comment]
Any update on this issue ?

**Comment by vagrantrobbie** [comment]
Same here. I am accepting the permission request but PERMISSION_DENIED is always thrown and returns location null

**Comment by vagrantrobbie** [comment]
Strangely, the onLocationChanged Stream works

**Comment by philseeley** [comment]
Bit more info... I've two apps, one that uses the onLocationChanged listener and one that simply calls getLocation once. On a fresh phone boot I get the same error calling getLocation. If I then run the other app that uses the onLocationChanged listener, then the first app's call to getLocation starts working.

**Comment by MarcoLude** [comment]
Same here. I started having the problem after I had added the image_picker dependecy which made me accept the permission request to use location for pictures.
Don't know why

**Comment by andersonmadeira** [comment]
Same here, any update?

**Comment by ibrierley** [comment]
Someone want to put up an example that can be used to test that fails ? May be good to isolate if it's a problem with the package, or some phones or whatever/

**Comment by jibbers42** [comment]
I get this issue if I disable wifi in the simulator. I wanted to test my app at different network speeds and latencies, but it won't start with wifi off due to this error when calling `getLocation()`. I'm also using image_picker (if that's related).

**Comment by vagrantrobbie** [comment]
Does pubspec order dependency matter? What happens if 'location' is included before 'image_picker'?

**Comment by jibbers42** [comment]
'location' was already before 'image_picker', but I didn't think to try switching them the other way. I've changed to 'geolocator' which seems to be working fine initially - time will tell. I'll update if I decide to try switching them around.

**Comment by myleswh** [comment]
'getLocation' uses 'getLastLocation()' on Android which can return null in a number of scenarios. 
https://developer.android.com/training/location/retrieve-current 

I had a attempt at fixing this here https://github.com/Lyokone/flutterlocation/pull/105/commits/6666cf8f11c41080aa1f36d485e55ac262d4d4a4
but closed the PR as I couldn't get it working for all scenarios (If location is off or unavailable 'await getLocation' will never return).

**Comment by myleswh** [comment]
I've updated https://github.com/Lyokone/flutterlocation/commit/6666cf8f11c41080aa1f36d485e55ac262d4d4a4 and it seems to be working fine. 

Anyone who wants to test can use 

`dependencies:
   location:
      git: https://github.com/myleswh/flutterlocation.git`

**Comment by wagnerdelima** [comment]
Will there be any update on this?

**Comment by Lyokone** [comment]
Hey, its supposed to be corrected in the last version, pls check [this](https://github.com/Lyokone/flutterlocation/issues/117#issuecomment-464789871).

**Comment by wagnerdelima** [comment]
@Lyokone I tried your suggestions. Yet it doesn't work. 

My dependencies on android/build.gradle are
`dependencies {

        classpath 'com.android.tools.build:gradle:3.3.0'

        classpath 'com.google.gms:google-services:4.2.0'
    }
`

My Gradle.properties on android/gradle.properties are:
`
org.gradle.jvmargs=-Xmx1536M

android.useAndroidX=true

android.enableJetifier=true
`

Is there any other way?

**Comment by wagnerdelima** [comment]
@Lyokone the only thing I get is **PlatformException(ERROR, Failed to get location., null)** exception

Any idea?

**Comment by Lyokone** [comment]
Are you compiling against the version 28 of the SDK ? 
`compileSdkVersion 28``

Do you also have added all the permission the application needs ?

**Comment by wagnerdelima** [comment]
`
compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "maidsimple.app.msapp"
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }`

And this:
```
<uses-permission android:name="android.permission.INTERNET"/>

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

 ```
<meta-data android:name="com.google.android.geo.API_KEY"
            android:value="my key is here"/>
```

I think I am all set

**Comment by wagnerdelima** [comment]
@Lyokone above as depicted

**Comment by wagnerdelima** [comment]
Any news on this, anybody?

**Comment by adisiji** [comment]
I surrender with this error, and change it to [this](https://github.com/BaseflowIT/flutter-geolocator) + permission library

**Comment by Lyokone** [comment]
Hey, version 2.1 should help you get more consistent results, pls check it out and reopen if its still not fixed.

**Comment by DorIndivo** [comment]
i just updated to the 2.1.0 version and i still have this problem on my android emulator

**Comment by uzairamer** [comment]
It's still an ongoing issue. Even the documentation is misleading.

**Comment by Karlheinzniebuhr** [comment]
Same error, any solution yet?

**Comment by Shahmirzali-Huseynov** [comment]
any progress? update? same error
