### ISSUE TITLE
Reply already submitted

### ISSUE THREAD

**Issue by GauthamAsir** [Lyokone/flutterlocation#443]
Caused by: java.lang.IllegalStateException: Reply already submitted

This occurs when i try to request service. The request service dialog is not dismissed, so when its clicked again this message popus up "Reply already submitted"

**Tested on:**
 - Android, API 27 simulator
 - Android API 29 real device Redmi k20 pro (MIUI)

**Additional logs**
[Full Log](https://del.dog/oppycreran.txt)

**Comment by noordawod** [comment]
This is a new issue, it wasn't there just few days ago. Changes in Flutter embedder maybe?

**Comment by GauthamAsir** [comment]
> This is a new issue, it wasn't there just few days ago. Changes in Flutter embedder maybe?

No ig

**Comment by wilsoncastiblanco** [comment]
I was using version `2.5.0` and it is happening on that version, then upgraded to `3.0.2` and still happening.

**Comment by Tumist76** [comment]
Pushed our app into testing phase, issue popped up for ~11% of users.

Happening at least on Samsung Galaxy A50, Redmi Note 8T and HUAWEI P smart 2019.

**Comment by yurisasc** [comment]
Happened to me as well when opening the app with location service turned off, and selected "No thanks" when prompted to turn on location service.

**Comment by Tumist76** [comment]
> Happened to me as well when opening the app with location service turned off, and selected "No thanks" when prompted to turn on location service.

As it turned out, that is the case. I removed the request to turn on location service from the app and everything works now.
