### ISSUE TITLE
Need to control when permission prompt shows

### ISSUE THREAD

**Issue by acudworth** [Lyokone/flutterlocation#45]
At the moment, on iOS (haven't tested on Android), the permission dialog appears immediately on app load despite not calling any `Location()` funcs..

This is an absolute must - being able to control when the permission prompt shows

**Comment by Lyokone** [comment]
It sure is a problem, hadn't realise it behave like that. I'll change it as soon as possible !

**Comment by yathit** [comment]
@Lyokone have time on this? It is very important.

**Comment by Lyokone** [comment]
Hey ! There is a requestPermission method now in 2.1 :)
