### ISSUE TITLE
Please Add MockLocation flag in LocationData

### ISSUE THREAD

**Issue by sunnykinger** [Lyokone/flutterlocation#452]
**Is your feature request related to a problem? Please describe.**
Yes, I have an application which takes a user's precise location, and the user is able to manipulate it,
**Describe the solution you'd like**
A simple solution is that I should be able to know if the location is mocked or not. 

**Describe workarounds you've considered**
To use the additional library, but then it takes its own time to get location and signal me if the location is fake or not.

**Comment by Lyokone** [comment]
Hi ! 
I had tried to add simple mock detection, but adding mock always seems to produce no response from the native part on Android.
I'll have to see if it's something only on my device.

If you want to test on your device by modifying your pubspec.yaml to this branch : https://github.com/Lyokone/flutterlocation/pull/464

**Comment by sunnykinger** [comment]
I reviewed the code and it seems to me that everything is correct because it was just a small flag that was needed. I think it should work fine. 

What was your experience with it while testing mock location? Does it give any location or it doesn't give any location at all?

**Comment by Lyokone** [comment]
My experience was that on my OnePlus 7 Pro, it would never give a location. 
I've tried 2 mocking apps, enabling them in the Developer Options, but the example app would stop receiving LocationData.
Not sure why tho

**Comment by sunnykinger** [comment]
That is very strange, so if you comment those flag lines, it starts giving you location? 
Maybe use the stable version of the library and enable mock location using those apps and see if you still get a location or not. Because from what I think, it is not giving you location if location is mocked, rest you can tell better. 
I wanted to test myself, but very busy these days.

**Comment by Lyokone** [comment]
Was added in 4.2.0

**Comment by VoronovAlexander** [comment]
> My experience was that on my OnePlus 7 Pro, it would never give a location.
> I've tried 2 mocking apps, enabling them in the Developer Options, but the example app would stop receiving LocationData.
> Not sure why tho

Hi! I also have this problem on my Xiaomi mi 9, and I see many changes AppLifecycleState when I try use fake gps, app begin to work very slowly.
Somebody know how solve this problem?

![image](https://user-images.githubusercontent.com/32374709/135622928-4252ab81-2d82-4c9f-a07d-01b4e9d386b0.png)

**Comment by Priyantha-Kingslake** [comment]
Using `location: ^8.0.0` and still face this issue where location data is not received when using mock locations for testing purposes. I also noticed that if I start listening to location before starting the mock locations, then it does get the location updates, but if I start mock locations before listening, then I don't get updates
