### ISSUE TITLE
My App will be crash with plugin Map View

### ISSUE THREAD

**Issue by lunvjp** [Lyokone/flutterlocation#46]
I don't know why it happended like this. it will be OK if I remove 1 in 2 plugin: Map View and Location package.
Can you guys have a look with this? Right now, we need "getSpeed" from your package and we also need Google Native Map from Map View Package? 
Let me know if I can help you to do your work. Thanks for your time.
![image](https://user-images.githubusercontent.com/23715737/40827487-e178cc0a-65a7-11e8-8076-308e2fe89e01.png)

**Comment by Asoseil** [comment]
Should be a problem related to gradle and the play services version

**Comment by lunvjp** [comment]
@Asoseil Would you mind giving me a example app that included in GeoLocation and MapView package? In these days, I spent my time doing it but nothing happens.
Thanks

**Comment by diogoribeiro23** [comment]
Hey @lunvjp ! I had the exact same problem and after 2 days of trying i found a solution :)
Put this into your dependencies in app/src/build.gradle : 
`implementation 'com.google.android.gms:play-services-base:+'
 implementation 'com.google.android.gms:play-services-maps:+'`
and it should work! 
I think @Lyokone can provide a better future solution in the plugin so you don't have to put that into your code, I'm pretty rookie still in mobile sooo.. 
P.S.: FYI the problem starts from version 1.2.0 to 1.3.0.

**Comment by Lyokone** [comment]
Should be fixed in new version :)
