### ISSUE TITLE
Error during app closing on android

### ISSUE THREAD

**Issue by carlosfiori** [Lyokone/flutterlocation#466]
**Describe the bug**
I'm getting the error below when I close my app.

**Tested on:**
 - Android, API Level 29, simulator and real device

**Other plugins:**
 - None, tested on new project with location version 3.2.1

**Error::**
``` shell
E/AndroidRuntime( 5891): java.lang.RuntimeException: Unable to destroy activity {com.example.teste/com.example.teste.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
E/AndroidRuntime( 5891):        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4941)
E/AndroidRuntime( 5891):        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970)
E/AndroidRuntime( 5891):        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
E/AndroidRuntime( 5891):        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime( 5891):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime( 5891):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime( 5891):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 5891):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 5891):        at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 5891):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5891):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 5891):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 5891): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
E/AndroidRuntime( 5891):        at com.lyokone.location.FlutterLocationService.setActivity(Unknown Source:2)
E/AndroidRuntime( 5891):        at com.lyokone.location.LocationPlugin.deinitialize(LocationPlugin.java:121)
E/AndroidRuntime( 5891):        at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime( 5891):        at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java:69)
E/AndroidRuntime( 5891):        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(FlutterEnginePluginRegistry.java:346)
E/AndroidRuntime( 5891):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:512)
E/AndroidRuntime( 5891):        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime( 5891):        at android.app.Activity.performDestroy(Activity.java:8048)
E/AndroidRuntime( 5891):        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1334)
E/AndroidRuntime( 5891):        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4926)
E/AndroidRuntime( 5891):        ... 11 more```

**Comment by anisalibegic** [comment]
I'm having the same problem:

```
java.lang.RuntimeException: Unable to destroy activity {se.digiqal.yumeets/se.digiqal.yumeets.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method f.s.c.f.c, parameter activity
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5034)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5063)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method f.s.c.f.c, parameter activity
	at com.lyokone.location.FlutterLocationService.a(Unknown Source:2)
	at com.lyokone.location.b.a(Unknown Source:51)
	at com.lyokone.location.b.b(Unknown Source:0)
	at com.lyokone.location.b.onDetachedFromActivity(Unknown Source:0)
	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(Unknown Source:52)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(Unknown Source:58)
	at io.flutter.embedding.android.FlutterActivity.onDestroy(Unknown Source:10)
	at android.app.Activity.performDestroy(Activity.java:8180)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5019)
	... 11 more
```

**Comment by tronghuy5555** [comment]
Try to upgrade Flutter SDK stable version

**Comment by anisalibegic** [comment]
It's already on latest version :\.

**Comment by vannevar-morgan** [comment]
I'm also seeing this error when pressing the back button to exit the app.  It happens simply by including the location package.

```
E/AndroidRuntime(23002): java.lang.RuntimeException: Unable to destroy activity {com.eliza.test_location/com.eliza.test_location.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
E/AndroidRuntime(23002): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
E/AndroidRuntime(23002): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
E/AndroidRuntime(23002): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
E/AndroidRuntime(23002): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
E/AndroidRuntime(23002): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(23002): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(23002): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime(23002): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23002): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(23002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime(23002): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
E/AndroidRuntime(23002): 	at com.lyokone.location.FlutterLocationService.setActivity(Unknown Source:2)
E/AndroidRuntime(23002): 	at com.lyokone.location.LocationPlugin.deinitialize(LocationPlugin.java:121)
E/AndroidRuntime(23002): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime(23002): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java:69)
E/AndroidRuntime(23002): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(FlutterEnginePluginRegistry.java:346)
E/AndroidRuntime(23002): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:512)
E/AndroidRuntime(23002): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime(23002): 	at android.app.Activity.performDestroy(Activity.java:7522)
E/AndroidRuntime(23002): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
E/AndroidRuntime(23002): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)
E/AndroidRuntime(23002): 	... 9 more
```

Easy to reproduce:

- Create a new flutter application in android studio.
- add dependency: location: ^3.2.1
- (this step is probably not necessary) add NSLocationWhenInUseUsageDescription, NSLocationAlwaysUsageDescription to Info.plist
- run the app
- press back button to exit
- app will crash with this error

I found this which seems similar but it's on startup - not on exit:
https://stackoverflow.com/questions/50454656/flutter-android-app-crashes-upon-startup-if-i-include-a-certain-package?rq=1

Suggested fix is to add "multiDexEnabled true" to build.gradle but it doesn't work for me.

[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/vann/development/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

**Comment by anisalibegic** [comment]
> I'm also seeing this error when pressing the back button to exit the app. It happens simply by including the location package.
> 
> ```
> E/AndroidRuntime(23002): java.lang.RuntimeException: Unable to destroy activity {com.eliza.test_location/com.eliza.test_location.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
> E/AndroidRuntime(23002): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4605)
> E/AndroidRuntime(23002): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4623)
> E/AndroidRuntime(23002): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
> E/AndroidRuntime(23002): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
> E/AndroidRuntime(23002): 	at android.os.Handler.dispatchMessage(Handler.java:105)
> E/AndroidRuntime(23002): 	at android.os.Looper.loop(Looper.java:164)
> E/AndroidRuntime(23002): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
> E/AndroidRuntime(23002): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(23002): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> E/AndroidRuntime(23002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> E/AndroidRuntime(23002): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
> E/AndroidRuntime(23002): 	at com.lyokone.location.FlutterLocationService.setActivity(Unknown Source:2)
> E/AndroidRuntime(23002): 	at com.lyokone.location.LocationPlugin.deinitialize(LocationPlugin.java:121)
> E/AndroidRuntime(23002): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
> E/AndroidRuntime(23002): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java:69)
> E/AndroidRuntime(23002): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(FlutterEnginePluginRegistry.java:346)
> E/AndroidRuntime(23002): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:512)
> E/AndroidRuntime(23002): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
> E/AndroidRuntime(23002): 	at android.app.Activity.performDestroy(Activity.java:7522)
> E/AndroidRuntime(23002): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
> E/AndroidRuntime(23002): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4592)
> E/AndroidRuntime(23002): 	... 9 more
> ```
> 
> Easy to reproduce:
> 
> * Create a new flutter application in android studio.
> * add dependency: location: ^3.2.1
> * (this step is probably not necessary) add NSLocationWhenInUseUsageDescription, NSLocationAlwaysUsageDescription to Info.plist
> * run the app
> * press back button to exit
> * app will crash with this error
> 
> I found this which seems similar but it's on startup - not on exit:
> https://stackoverflow.com/questions/50454656/flutter-android-app-crashes-upon-startup-if-i-include-a-certain-package?rq=1
> 
> Suggested fix is to add "multiDexEnabled true" to build.gradle but it doesn't work for me.
> 
> [✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
> • Flutter version 1.22.5 at /home/vann/development/flutter
> • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
> • Engine revision ae90085a84
> • Dart version 2.10.4

Identical.

**Comment by krishna700** [comment]
Same issue.

MultiDexEnabled is true

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.17.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.1)
[!] Connected device
    ! No devices available

Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.******.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method f.c.a.b.b, parameter activity
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5456)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5493)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by rohnsht** [comment]
Getting the same error after version 3.2.0

**Comment by bluewis777** [comment]
facing this issue too, even when using 3.0.x and 3.1.x

**Comment by sarbogast** [comment]
I have the same issue

**Comment by waelalameen** [comment]
Any solution found for this issue ?

**Comment by danielgomezrico** [comment]
@Lyokone it looks like there's already a merged commit to fix this https://github.com/Lyokone/flutterlocation/commit/8a862cce5550d58825e6a06407641182c999e64b, can we generate a release with that?

**Comment by sarbogast** [comment]
Yes, please a release! This stains my crash report

**Comment by Coder-Manuel** [comment]
Am getting the same error...
Using the flutter 1.22.5 stable
Any Fix Available ?

E/AndroidRuntime( 2283): java.lang.RuntimeException: Unable to destroy activity {com.eeneomap.app/com.example.eeneo.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
E/AndroidRuntime( 2283): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4589)
E/AndroidRuntime( 2283): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4611)
E/AndroidRuntime( 2283): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
E/AndroidRuntime( 2283): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime( 2283): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime( 2283): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
E/AndroidRuntime( 2283): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2283): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 2283): 	at android.app.ActivityThread.main(ActivityThread.java:6819)
E/AndroidRuntime( 2283): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2283): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/AndroidRuntime( 2283): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
E/AndroidRuntime( 2283): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
E/AndroidRuntime( 2283): 	at com.lyokone.location.FlutterLocationService.setActivity(Unknown Source:2)
E/AndroidRuntime( 2283): 	at com.lyokone.location.LocationPlugin.deinitialize(LocationPlugin.java:121)
E/AndroidRuntime( 2283): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime( 2283): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java:69)
E/AndroidRuntime( 2283): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(FlutterEnginePluginRegistry.java:346)
E/AndroidRuntime( 2283): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:512)
E/AndroidRuntime( 2283): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
E/AndroidRuntime( 2283): 	at android.app.Activity.performDestroy(Activity.java:7395)
E/AndroidRuntime( 2283): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
E/AndroidRuntime( 2283): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4574)
E/AndroidRuntime( 2283): 	... 11 more

**Comment by danielgomezrico** [comment]
@mehmetf can you do a release? 
I made a fork and I will deploy from there until this is deployed but 

You can get a dependency from github with `pubspec` with:

```YAML
 location:
    git:
      url: fork-url
      ref: branch-or-tag
      path: location
```

**Comment by mehmetf** [comment]
Unfortunately, I don't have the permissions to publish the location package.

**Comment by NarHakobyan** [comment]
Hey guys, the issue still exists.

**Comment by Lyokone** [comment]
Sorry for the delay, i'm publishing the new version with the fix now. Should be in 3.2.3.

**Comment by danielgomezrico** [comment]
@Lyokone Be careful, current master code have a serious bug: https://github.com/Lyokone/flutterlocation/issues/490

**Comment by vannevar-morgan** [comment]
updated to 3.2.4 and unable to recreate, this looks fixed.
