### ISSUE TITLE
Running Gradle task 'assembleDebug'... Plugin project :location_web not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by jordantsap** [Lyokone/flutterlocation#467]
Solution reference:

https://github.com/flutter/flutter/issues/57777

**Comment by danielgomezrico** [comment]
Im having the same issue here

**Comment by jordantsap** [comment]
> Im having the same issue here

just follow https://github.com/flutter/flutter/issues/57777#issuecomment-632609059

**Comment by danielgomezrico** [comment]
Sounds good as a temporal fix, thanks
