### ISSUE TITLE
Location service requested multiple times

### ISSUE THREAD

**Issue by adamshamsudeen** [Lyokone/flutterlocation#468]
**Describe the bug**
The location service is requested twice; 
when we enable the location on the first service request, another request popup right after. And the app crashes right after that.

**Tested on:**
 - Android, API Level 29, The error happens only in the production release.
 - The crash is reported in Crashlytics.

**Additional logs**

``` shell
Caused by java.lang.IllegalArgumentException
Parameter specified as non-null is null: method g.j.b.d.d, parameter activity
com.lyokone.location.FlutterLocationService.a (FlutterLocationService.java:2)
com.lyokone.location.LocationPlugin.a (LocationPlugin.java:51)
com.lyokone.location.LocationPlugin.detachActivity (LocationPlugin.java)
com.lyokone.location.LocationPlugin.onDetachedFromActivity (LocationPlugin.java)
io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity (FlutterEnginePluginRegistry.java:52)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:58)
io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:10)
android.app.Activity.performDestroy (Activity.java:8242)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:981)
```

**Comment by adamshamsudeen** [comment]
Solved the issue. The widget was rebuilding because of a setstate in another function.

**Comment by adamshamsudeen** [comment]
The issue still persists. Any help is appreciated.

<img width="1002" alt="Screenshot 2021-01-01 at 8 30 03 PM" src="https://user-images.githubusercontent.com/13180406/103440956-24a87500-4c70-11eb-803e-41b0dd0589c1.png">

**Comment by DevPistoul** [comment]
Hello, Same Here

**Comment by adamshamsudeen** [comment]
I just switched to a different library because of this issue.

**Comment by DevPistoul** [comment]
Hello, In my case.
This error occurs when the app is in the background and you close it.
With location.enableBackgroundMode(enable: true) set.
maybe enableBackgroundMode(enable: false) when onDestroy (LifeCycle).
I must try.
Sorry for my english :)

**Comment by Lyokone** [comment]
Hi, let me know if it still happening on the 4.2.0 :) I fixed a bunch of Android stuffs.
