### ISSUE TITLE
Android Compilation issue: Unresolved reference: createNotificationChannel

### ISSUE THREAD

**Issue by fvisticot** [Lyokone/flutterlocation#470]
**Describe the bug**
Compilation issue:
`location-3.2.1/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (122, 37): Unresolved reference: createNotificationChannel`

**Expected behavior**
Compilation OK

**Tested on:**
 Android
Migration done with https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by Dhaval2404** [comment]
Facing a similar issue 😢

**Comment by Dhaval2404** [comment]
I had a resolutionStrategy in my project build.gradle file.  **createNotificationChannel** method is added in 1.1.0 onwards So Make sure you upgrade the version in resolutionStrategy.
 
 ``` 
configurations.all {
        resolutionStrategy {
                 "androidx.core:core:1.0.2"  //Update to "androidx.core:core:1.1.0"
        }
    }

**Comment by zibellon** [comment]
> I had a resolutionStrategy in my project build.gradle file. **createNotificationChannel** method is added in 1.1.0 onwards So Make sure you upgrade the version in resolutionStrategy.
> 
> ```
> configurations.all {
>        resolutionStrategy {
>                 "androidx.core:core:1.0.2"  //Update to "androidx.core:core:1.1.0"
>        }
>    }
> ```

YOU ARE THE BEST!!!
It help me!!!
