### ISSUE TITLE
 warning: 'allowsBackgroundLocationUpdates' is only available on iOS 9.0

### ISSUE THREAD

**Issue by heshesh2010** [Lyokone/flutterlocation#476]
i'm using latest plugin version 

Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/hesham/.pub-cache/hosted/pub.dartlang.org/location-3.2.1/ios/Classes/LocationPlugin.m:86:43: warning: 'allowsBackgroundLocationUpdates' is only available on iOS 9.0 or newer [-Wunguarded-availability]
                result(self.clLocationManager.allowsBackgroundLocationUpdates ? @1 : @0);
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'CoreLocation' imported from /Users/hesham/.pub-cache/hosted/pub.dartlang.org/location-3.2.1/ios/Classes/LocationPlugin.m:4:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLLocationManager.h:337:35: note: 'allowsBackgroundLocationUpdates' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    @property(assign, nonatomic) BOOL allowsBackgroundLocationUpdates API_AVAILABLE(ios(9.0), macos(10.15), watchos(4.0)) API_UNAVAILABLE(tvos);
                                      ^
    /Users/hesham/.pub-cache/hosted/pub.dartlang.org/location-3.2.1/ios/Classes/LocationPlugin.m:86:43: note: enclose 'allowsBackgroundLocationUpdates' in an @available check to silence this warning
                result(self.clLocationManager.allowsBackgroundLocationUpdates ? @1 : @0);
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/hesham/.pub-cache/hosted/pub.dartlang.org/location-3.2.1/ios/Classes/LocationPlugin.m:93:36: warning: 'setAllowsBackgroundLocationUpdates:' is only available on iOS 9.0 or newer [-Wunguarded-availability]
                self.clLocationManager.allowsBackgroundLocationUpdates = enable;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'CoreLocation' imported from /Users/hesham/.pub-cache/hosted/pub.dartlang.org/location-3.2.1/ios/Classes/LocationPlugin.m:4:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLLocationManager.h:337:35: note: 'setAllowsBackgroundLocationUpdates:' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    @property(assign, nonatomic) BOOL allowsBackgroundLocationUpdates API_AVAILABLE(ios(9.0), macos(10.15), watchos(4.0)) API_UNAVAILABLE(tvos);
                                      ^
    /Users/hesham/.pub-cache/hosted/pub.dartlang.org/location-3.2.1/ios/Classes/LocationPlugin.m:93:36: note: enclose 'setAllowsBackgroundLocationUpdates:' in an @available check to silence this warning
                self.clLocationManager.allowsBackgroundLocationUpdates = enable;
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/hesham/.pub-cache/hosted/pub.dartlang.org/location-3.2.1/ios/Classes/LocationPlugin.m:94:36: warning: 'setShowsBackgroundLocationIndicator:' is only available on iOS 11.0 or newer [-Wunguarded-availability-new]
                self.clLocationManager.showsBackgroundLocationIndicator = enable;

**Comment by anisalibegic** [comment]
I'm having these warning + error even tho my deployment target is 10.0.

**Comment by Lyokone** [comment]
Hi, let me know if it still happening on the 4.2.0 :) I fixed this iOS code.
