### ISSUE TITLE
await location.requestService(); crashes the app giving AndroidRuntime exception

### ISSUE THREAD

**Issue by Atominac** [Lyokone/flutterlocation#477]
**Describe the bug**
When asking for location service the app crashes.

**Expected behavior**
Should not crash

**Tested on:**
 - Android, Real device PIXEL 4A, ONE PLUS NORD
 - iOS Worked fine

**Additional logs**

E/AndroidRuntime(14321): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4097, result=-1, data=Intent { (has extras) }} to activity {com.kmguardini.guardini/com.example.guardini.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property plugin has not been initialized
E/AndroidRuntime(14321): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5009)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
E/AndroidRuntime(14321): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(14321): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14321): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14321): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14321): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14321): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime(14321): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14321): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14321): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(14321): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property plugin has not been initialized
E/AndroidRuntime(14321): 	at com.example.guardini.MainActivity.onActivityResult(MainActivity.kt:22)
E/AndroidRuntime(14321): 	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
E/AndroidRuntime(14321): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
E/AndroidRuntime(14321): 	... 11 more

**Comment by Lyokone** [comment]
Hi, let me know if it still happening on the 4.2.0 :) I fixed a bunch of Android stuffs.
