### ISSUE TITLE
Android: PlatformException(CHANGE_SETTINGS_ERROR, An unexcepted error happened during location settings change:Attempt to read from field 'android.util.SparseArray com.lyokone.location.FlutterLocation.mapFlutterAccuracy' on a null object reference, null, null)

### ISSUE THREAD

**Issue by qaiumhossain** [Lyokone/flutterlocation#478]
On Android, I am getting this exception: 

PlatformException(CHANGE_SETTINGS_ERROR, An unexcepted error happened during location settings change:Attempt to read from field 'android.util.SparseArray com.lyokone.location.FlutterLocation.mapFlutterAccuracy' on a null object reference, null, null)

I/flutter ( 3335): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter ( 3335): The following PlatformException was thrown while activating platform stream on channel
I/flutter ( 3335): lyokone/locationstream:
I/flutter ( 3335): PlatformException(error, Attempt to write to field 'io.flutter.plugin.common.EventChannel$EventSink
I/flutter ( 3335): com.lyokone.location.FlutterLocation.events' on a null object reference, null, null)

Please let me know if anyone can help me resolving this issue.

Here is the information about my project:

Response from 'flutter doctor -v':

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BD)
    • Flutter version 1.22.5 at /Users/Shared/Relocated/Security/Softwares/Flutter/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Shared/Relocated/Security/Softwares/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • XP8800 (mobile) • 9362c4b5 • android-arm64 • Android 7.1.1 (API 25)

• No issues found!

pubspec.yml:

dependencies:
   location: ^3.2.1

Android compileSdkVersion and targetSdkVersion: 29

Gradle version: distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.3-all.zip

Android build.gradle: 

dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'

        // Google Services plugin
        classpath 'com.google.gms:google-services:4.3.3'
    }

Android gradle.properties: 

android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true

**Comment by qaiumhossain** [comment]
Can anyone please help me to resolve this crash?

**Comment by Lyokone** [comment]
Hi, let me know if it still happening on the 4.2.0 :) I fixed a bunch of Android stuffs.

**Comment by Saikiran24** [comment]
Yes I am also getting this, please fix this issue
