### ISSUE TITLE
Question: How to cancel the subscription, and does this switch off the location updates

### ISSUE THREAD

**Issue by agreensh** [Lyokone/flutterlocation#481]
I want to cancel the subscription (listen) after I have received a number of updates.
Can I do that?
If I do, does that stop the native location from updating (if it doesn't then that will drain the battery).

Any feedback?

**Comment by neoacevedo** [comment]
From the dispose method you can invoce your location subscription property and invoke the cancel method, after that you can set null such property.

But, in my experience, this is not enough due of the location service is still runing after the app is closed and only killing the app this service is stoped.

**Comment by Lyokone** [comment]
Hi, if you are properly cancelling all the StreamSubscription, (as displayed here https://github.com/Lyokone/flutterlocation/blob/master/packages/location/example/lib/listen_location.dart) the location request will stop.
