### ISSUE TITLE
Android notification title change parameter

### ISSUE THREAD

**Issue by AdrianKlm** [Lyokone/flutterlocation#483]
It would be good to see a config parameter to change the title of the notification....
<string name="notification_title">Background location service running</string>.

**Comment by jordantsap** [comment]
You can use AlertDialog for that, i don't think that you can do it natively on android

**Comment by Poweranimal** [comment]
@jordantsap AlertDialog doesn't solve the issue.
@magicznyadrian It is possible to change the content and icon, but it must be supported by the project.
You can find the part that must be changed in the android plugin [here](https://github.com/Lyokone/flutterlocation/blob/439ae1b49375ccf9016086206e3c344ff04ee230/location/android/src/main/java/com/lyokone/location/FlutterLocationService.kt#L125)

**Comment by maciejpigulski** [comment]
Yes, this could be done as an improvement.

**Comment by kevlatus** [comment]
so, is there any work on making the notification customizable from the Flutter side?

If there is not, I'd try to build on @Poweranimal 's answer and submit a pull request.

**Comment by Poweranimal** [comment]
@kevlatus That would be great.
I'd like to implement it myself, too, but currently I have a lot to do at work and have no spare time for other things :/
If it helps you, I've once written a similar implementation for it:

**Android Part:**
- Service -
```
...
    companion object {
        const val NOTIFICATION_ID = 1001
        const val CHANNEL_ID = "LocatorForegroundServiceChannel"

        const val TITLE_KEY = "Title"
        const val CONTENT_KEY = "Content"
        const val ICON_NAME_KEY = "IconName"
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        val bundle = intent!!.extras!!

        createNotificationChannel(bundle.getString(TITLE_KEY)!!)

        val pm = applicationContext.packageManager
        val notificationIntent = pm.getLaunchIntentForPackage(applicationContext.packageName)
        val pendingIntent = PendingIntent.getActivity(this, 0, notificationIntent, 0)

        val iconName = bundle.getString(ICON_NAME_KEY)
        var icon = android.R.drawable.ic_menu_compass

        iconName?.let {
            icon = applicationContext.resources.getIdentifier(it, "drawable", applicationContext.packageName)
        }

        val notification = NotificationCompat.Builder(this, CHANNEL_ID)
                .setOngoing(true)
                .setPriority(NotificationCompat.PRIORITY_MAX)
                .setContentTitle(bundle.getString(TITLE_KEY))
                .setContentText(bundle.getString(CONTENT_KEY))
                .setSmallIcon(icon)
                .setContentIntent(pendingIntent)
                .build()

        startForeground(NOTIFICATION_ID, notification)

        return START_STICKY
    }
...
```

- Plugin -
```
    override fun onMethodCall(call: MethodCall, result: Result) {
      when {
          ...
          call.method == "setForegroundNotificationStyle" -> {
              val input = Json.decodeFromString(ForegroundNotificationStyle.serializer(), call.arguments as String)
              eventChannelLocationHandler.style = input
              result.success("")
          }
          ...
      }
    }
```

**Flutter part:**
```
...
  // only has effect on Android phones
  Future<void> setForegroundNotificationStyle(ForegroundNotificationStyle style) async {
    if (Platform.isAndroid) {
      final methodInput = jsonEncode(style);
      await _channel.invokeMethod('setForegroundNotificationStyle', '$methodInput');
      return;
    } else {
      developer.log('The method \'setForegroundNotificationStyle\' is only available on Android. Current platform: ${Platform.operatingSystem}', name: 'com.example.app');
      return;
    }
  }
```

The code of course requires improvement, but maybe it helps you.

**Comment by kevlatus** [comment]
@Poweranimal thanks for your hint about finding drawables by name! Definitely saved me from searching for a solution. I just opened #516 hoping that I haven't overlooked anything

**Comment by Lyokone** [comment]
It has landed on pub.dev so I'm closing this. Thanks for the team effort :D

**Comment by DarkMikey** [comment]
@Lyokone This should be in the docs please!
