### ISSUE TITLE
Crash on getLocation

### ISSUE THREAD

**Issue by Stewioie** [Lyokone/flutterlocation#490]
ava.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(com.google.android.gms.location.LocationRequest, com.google.android.gms.location.LocationCallback, android.os.Looper)' on a null object reference
E/AndroidRuntime( 8278): 	at com.lyokone.location.FlutterLocation$6.onSuccess(FlutterLocation.java:390)
E/AndroidRuntime( 8278): 	at com.lyokone.location.FlutterLocation$6.onSuccess(FlutterLocation.java:384)
E/AndroidRuntime( 8278): 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
E/AndroidRuntime( 8278): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8278): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8278): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8278): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 8278): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8278): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8278): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by DevPistoul** [comment]
Hello, same crash for me

**Comment by markusrambarkus** [comment]
Seeing it here on the onSuccess override in the startRequestingLocation() method

**Comment by cdmunoz** [comment]
When you are trying to autolocate a second time, is when it crashes... it's always happening on Android. On iOS is working as expected.

**Comment by caiusCitiriga** [comment]
> When you are trying to autolocate a second time, is when it crashes... it's always happening on Android. `FusedLocationProviderClient` is null.
> On iOS is working as expected.

Exactly, every time happens in android, but iOS works. Any workaround from anyone except for the watchLocation? 😊

**Comment by jonbhanson** [comment]
I reverted to version 3.2.1 and the crashes stopped. 👍🏻
