### ISSUE TITLE
app getting crashed when I call location.getLocation for the second time..

### ISSUE THREAD

**Issue by RashidaBegamShaik** [Lyokone/flutterlocation#494]
**Describe the bug**

**Expected behavior**

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device
 - iOS, Version XX [e.g. 10], simulator or real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by MykhailoYarushevskyi** [comment]
Describe the bug:
  If the "location.getLocation()" operation runs for the first time, all work well.
But for the second time, the app crashes.

-IDE VSCode, Windows.
-Flutter 1.22.5
-Tested on:
1)Phone: Redmi Note 8 Pro (Android: 10QP1A.190711.020)
2)Flutter Emulator
The behavior is the same, as on the real device as on the emulator.
-Packages:
for the pubspec.yaml: location: ^3.0.0 or  location: ^3.2.4 - result the same.
Other plugins:
other packeges in pubspec.yaml:
  provider: ^4.3.2+3
  image_picker: ^0.6.7+21
  path_provider: ^1.6.27
  path: ^1.7.0
  sqflite: ^1.3.2+2

Before a performance of the operation below:
_serviceEnabled is true.
_permissionGranted is PermissionStatus.granted.
_locationData is not null.

During the performance of the operation (for the second time)

_locationData = await location.getLocation();

the app crashes and  in Debug Console shows next:

D/AndroidRuntime( 9189): Shutting down VM
E/AndroidRuntime( 9189): FATAL EXCEPTION: main
E/AndroidRuntime( 9189): Process: com.example.great_places, PID: 9189
E/AndroidRuntime( 9189): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(com.google.android.gms.location.LocationRequest, com.google.android.gms.location.LocationCallback, android.os.Looper)' on a null object reference
E/AndroidRuntime( 9189): 	at com.lyokone.location.FlutterLocation$6.onSuccess(FlutterLocation.java:390)
E/AndroidRuntime( 9189): 	at com.lyokone.location.FlutterLocation$6.onSuccess(FlutterLocation.java:384)
E/AndroidRuntime( 9189): 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
E/AndroidRuntime( 9189): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 9189): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9189): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 9189): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 9189): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9189): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9189): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 9189): Sending signal. PID: 9189 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by NarHakobyan** [comment]
same here

**Comment by Atominac** [comment]
Same

**Comment by MykhailoYarushevskyi** [comment]
At least since 2021-01-27, I have no location's package related errors. The program working well with the location package.

Flutter version: 1.22.5

packeges in pubspec.yaml:
  provider: ^4.3.2+3
  image_picker: ^0.6.7+21
  path_provider: ^1.6.27
  path: ^1.7.0
  sqflite: ^1.3.2+2
  location: ^3.2.4
  google_maps_flutter: ^1.1.1

**Comment by dfourcfive** [comment]
same
