### ISSUE TITLE
Background location service notification blank icon

### ISSUE THREAD

**Issue by abdlulu** [Lyokone/flutterlocation#495]
The notification that shows up in the notifications system has a blank icon.
Is this the expected behavior?
I've been testing on a physical redmi note 8 pro

![WhatsApp Image 2021-01-27 at 12 27 29 PM (1)](https://user-images.githubusercontent.com/28248838/105978627-6e338680-609b-11eb-8fe2-90c635635e0d.jpeg)
![WhatsApp Image 2021-01-27 at 12 27 29 PM](https://user-images.githubusercontent.com/28248838/105978632-6f64b380-609b-11eb-84d0-5dd3b5db9792.jpeg)

**Comment by SilverCrow11** [comment]
Refer #483 for more details

**Comment by TheauLep** [comment]
did u find a solution for this ?

**Comment by abdlulu** [comment]
@TheauLep Yes as stated above

Refer https://github.com/Lyokone/flutterlocation/issues/483 for more details. Check Poweranimal's answer.
