### ISSUE TITLE
Android Compilation issue: The plugin location requires your app to be migrated to the Android embedding v2.

### ISSUE THREAD

**Issue by OlalKeith** [Lyokone/flutterlocation#496]
**Describe the bug**
 Compilation issue:
`The plugin ``location`` requires your app to be migrated to the Android embedding v2`.

**Expected behavior**
compile successfully 

**Tested on:**
 - Android
Tried migration:  [https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects](url)

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by Lyokone** [comment]
Hi, I'm closing this since the error is pretty self explanatory. Migrating to the new embedding will me mandatory for a lot of plugins :)
