### ISSUE TITLE
Please add Distance calculator between two location

### ISSUE THREAD

**Issue by rikun5989** [Lyokone/flutterlocation#497]
I have solution for direct distance between two point. It would be better if you add this feature in plugin.

import 'dart:math';
double calculateDistance(lat1, lon1, lat2, lon2)  {
    var p = pi / 180;
    var a = 0.5 - cos((lat2 - lat1) * p) / 2 + cos(lat1 * p) * cos(lat2 * p) * (1 - cos((lon2 - lon1) * p)) / 2;
    return 12742 * asin(sqrt(a)) * 1000;
  }

**Comment by Lyokone** [comment]
Hi, if you feel like adding this to the LocationData class, I would totally accept the PR :)

**Comment by rikun5989** [comment]
Hey, I have already posted code for distance calculate, so you can add it in your code.
