### ISSUE TITLE
location package  have error in flutter

### ISSUE THREAD

**Issue by masoudpaidar** [Lyokone/flutterlocation#498]
when i add the location package in my dependencies and when i Run my project i have a error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     G:\flutterproject\green_doctor\marketer\marketer\build\location\intermediates\library_manifest\debug\AndroidManifest.xml:11:9-15:56: AAPT: error: attribute android:foregroundServiceType not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin location...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin location_web...
Running Gradle task 'assembleAarRelease'...

F:\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.1\android\src\main\java\com\lyokone\location_web\LocationWebPlugin.java:3: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
F:\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.1\android\src\main\java\com\lyokone\location_web\LocationWebPlugin.java:15: error: cannot find symbol
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) { }
                                  ^
  symbol:   class NonNull
  location: class LocationWebPlugin
F:\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.1\android\src\main\java\com\lyokone\location_web\LocationWebPlugin.java:20: error: cannot find symbol
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) { }
                                    ^
  symbol:   class NonNull
  location: class LocationWebPlugin
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

Exception: The plugin location_web could not be built due to the issue above.

my flutter version is Flutter 1.22.0 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7ec2d360bc (6 months ago) • 2020-07-29 23:25:38 -0700
Engine • revision a9910e409c
Tools • Dart 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

and here my flutter doctor:

G:\flutterproject\green_doctor\marketer\marketer>flutter doctor
Error: PowerShell executable not found.
       Either pwsh.exe or PowerShell.exe must be in your PATH.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.22.0, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by Pawelek55** [comment]
In my case, the solution was upgrade in file buil.gradle ([your_project]\android\app\build.gradle) compileSdkVersion and targetSdkVersion. I upgraded from 28 to 29.

I hope that I helped
