### ISSUE TITLE
Get heading/direction not working in IOS

### ISSUE THREAD

**Issue by hussamDana92** [Lyokone/flutterlocation#500]
Hi, 
get heading/direction not working in IOS, I getting always " -1 "

Knowing that I added in permission in Info.plist :

NSLocationWhenInUseUsageDescription
NSLocationAlwaysUsageDescription

any solution for this issue?

**Comment by Lyokone** [comment]
Hi, according to iOS documentation a negative value means that the course is not valid. Not a lot I can do here. HAve you tried on a real device ?

**Comment by teganscott** [comment]
@hussamDana92 Did you ever figure out a solution to this problem? I am testing on a real device.
