### ISSUE TITLE
Why not have a Stream for PermissionStatus and serviceEnabled?

### ISSUE THREAD

**Issue by realrk95** [Lyokone/flutterlocation#501]
Pretty self-explanatory. I'm using several providers in my app. Sadly converting the above-mentioned future to stream (asStream()), stops working after the first render. Any way to do this in a better way?

**Comment by rikun5989** [comment]
Hope this code can help you

	bool _serviceEnabled = await _location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await _location.requestService();
    }

    PermissionStatus _permissionGranted = await _location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await _location.requestPermission();
    }

    if (_serviceEnabled != true || _permissionGranted != PermissionStatus.granted) {
      showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: new Text("Location Permission"),
            content: new Text("Please allow location Permission and enabled location Services."),
            actions: <Widget>[
              new FlatButton(
                child: new Text("OK"),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ],
          );
        },
      );
    }

**Comment by realrk69** [comment]
@rikun5989 thanks for your answer. But I'm looking for a stream to continuously listen to and make a change in case the event equates to a specific PermissionStatus and/or serviceEnabled (true/false). I tried your approach and it works, but does not reflect changes in the UI once the widgets have finished rendering

**Comment by Lyokone** [comment]
Hi, It does not seem possible on the underlying platforms https://stackoverflow.com/questions/51327285/how-can-we-listen-for-location-permission-changes-in-android-without-triggering
