### ISSUE TITLE
Location and 2 other flutter plugins seem to not work on XIAOMI MIUI 12 device

### ISSUE THREAD

**Issue by Jossnaz** [Lyokone/flutterlocation#502]
just not location received when running it on a physical device redmi note 7

this plugin doesn't work, neither do 2 others. So I'd assume its a config issue of the xiaomi device

anyone knows maybe something?

**Comment by Jossnaz** [comment]
ok...

so I'm sure if people using your library leave negative reviews on xiaomi devices here is the reason:

to make it work, you need to go (in MIUI 12)
```
security -> battery optimization -> APP BATTERY SAVER (not battery saver! **APP** BATTERY SAVER) -> LONG PRESS APP -> ... MORE -> **No restrictions**
```
xiaomi puts all apps into the default "battery saver APP mode" even if battery saver is disabled

then I'm able to get coordinates.


 Did NOT work with a gps mock location app together so far, but hey, one step at a time.

**Comment by Jossnaz** [comment]
alternatively you can go to "manage apps" and set the battery safer option as well to no restrictions. Has the advantage, that you can reset data as well (resets permissions as well afaik)

**Comment by AshishInnovantes** [comment]
In my case its fetching last location sometimes on all Redmi devices. Also setting to restrictions in  "battery saver APP mode" setting doesn't resolve the issue.

**Comment by brutalzinn** [comment]
in my case, i need to change the app to unresctrict battery saver and restart my phone. Now is working.
