### ISSUE TITLE
The method 'isBackgroundModeEnabled' isn't defined for the type 'Location'.

### ISSUE THREAD

**Issue by neoacevedo** [Lyokone/flutterlocation#506]
I'm following the example code, but I'm gettin the error 
> The method 'isBackgroundModeEnabled' isn't defined for the type 'Location'.
Try correcting the name to the name of an existing method, or defining a method named 'isBackgroundModeEnabled'.

Is this method still available or the example is outdated?

**Comment by DavidSmekal** [comment]
I still see it in 3.2.4.

**Comment by SilverCrow11** [comment]
It might be due to the plugin version you guys have wasnt updated. Remove the dependency Location from your pubspec.yaml file, run pub get, and then add Location: ^3.2.4 and run pub get again. Now you should have downloaded the latest plugin version and will be able to use the background mode

**Comment by neoacevedo** [comment]
I already did it but I still get the same problem.

**Comment by Lyokone** [comment]
Hi, maybe a `flutter clean` can do it ?

**Comment by neoacevedo** [comment]
The method is present now.
