### ISSUE TITLE
Unresolved reference: createNotificationChannel

### ISSUE THREAD

**Issue by mukkulsingh** [Lyokone/flutterlocation#508]
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.2.4\android\src\main\java\com\lyokone\location\FlutterLocationService.kt: (122, 37): Unresolved reference: createNotificationChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 40s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by happrdeveloper** [comment]
I've also experienced this issue for sometime. Have you found a solution yet?

**Comment by Lyokone** [comment]
Hi :) 
I've answered on #520, let me know what you think :)
