### ISSUE TITLE
Finished with error: Exit code 1 from: 

### ISSUE THREAD

**Issue by macbroadcast** [Lyokone/flutterlocation#51]
Hello

anyone know why this class is missing or cant be loadet in the project ?

`Finished with error: Exit code 1 from: /Users/memyself/Desktop/flutterlocation/example/android/gradlew -v:
Error: Mainclass org.gradle.wrapper.GradleWrapperMain could not be found or loadet.`

**Comment by Lyokone** [comment]
I'll close this, I hope its fixed.
