### ISSUE TITLE
Background mode doesn't works when the app is closed.

### ISSUE THREAD

**Issue by themisir** [Lyokone/flutterlocation#510]
I've previously using a package called `background_locator` to track location updates in background for our delivery tracking application. Now wanted to migrate to this package but I thought background mode would work in background when the app is closed (swiped away from quick access app list). But it didn't. It registers successfully, foreground notification displays but the service is killed when the app is closes.

Do I have to explicitly disable killing service on quit or it's not supported yet?

**Comment by SilverCrow11** [comment]
Support to background mode, here, means that you can get location updates as long as the app is still running in the background. If the application is closed from the recent tray, It will stop those updates

**Comment by TheMisir** [comment]
> Support to background mode, here, means that you can get location updates as long as the app is still running in the background. If the application is closed from the recent tray, It will stop those updates

But I think it's still possible to get updates even when the application is closed. Alternative plugins already supports that feature.

**Comment by thekavak** [comment]
> > Support to background mode, here, means that you can get location updates as long as the app is still running in the background. If the application is closed from the recent tray, It will stop those updates
> 
> But I think it's still possible to get updates even when the application is closed. Alternative plugins already supports that feature.

Hi, I also try to pull the location when the application is closed by the user, but I still haven't found a solution. Could you find it?

**Comment by TheMisir** [comment]
> > > Support to background mode, here, means that you can get location updates as long as the app is still running in the background. If the application is closed from the recent tray, It will stop those updates
> > 
> > 
> > But I think it's still possible to get updates even when the application is closed. Alternative plugins already supports that feature.
> 
> Hi, I also try to pull the location when the application is closed by the user, but I still haven't found a solution. Could you find it?

I previously used [background_locator](https://pub.dev/packages/background_locator) for that purpose which worked es expected.

**Comment by dasmobile** [comment]
@TheMisir If you don't mind me asking, what made you switch from background_locator?

**Comment by Lyokone** [comment]
Hi :) The implementation here https://github.com/Lyokone/flutterlocation/wiki/Background-Location-Updates was working even when the app is closed, but was not using a finished interface. Would be curious to see your implementation :)

**Comment by TheMisir** [comment]
> Hi :) The implementation here https://github.com/Lyokone/flutterlocation/wiki/Background-Location-Updates was working even when the app is closed, but was not using a finished interface. Would be curious to see your implementation :)

Sorry for very late reply, my implementation is a bit simple than general use case. I moved the callback logic into native itself so I don't have to deal with dart isolates. (My logic was simply sending location to http server with a token, so I pass the token using method channels to the background service and send http request there when needed). I can't share the code cause as I said I moved background callback to native side to make it a bit more reliable so it does contains internal code.

But simply on android it does starts a service which itself starts a foreign service with a sticky notification and uses supported location provider (fused or location provider) and listens for updates. On ios I used CLLocation api and followed the guide [here](https://www.hackingwithswift.com/example-code/location/how-to-read-the-users-location-while-your-app-is-in-the-background) to implement the rest. It's not reliable with the app has to be keep open on recent apps list on ios.

**Comment by TheoLassonder** [comment]
Perhaps there's a simpler way to do this, which I'm trying in production now. The idea is simply to *not* have Flutter exit when the user backs out by capturing the Android back button with `WillPopScope`, and then moving the app task to the background with [move_to_background](https://pub.dev/packages/move_to_background) library (in effect minimising the app). The app will stay alive because there's a `ForegroundService` notification. So you can just write your logic in Dart and not worry about isolates.

**Comment by Yukams** [comment]
@themisir so did you just keep using [background_locator](https://pub.dev/packages/background_locator) ?

**Comment by themisir** [comment]
> @themisir so did you just keep using [background_locator](https://pub.dev/packages/background_locator) ?

Not really, I reimplemented it myself and wrote background handler in kotlin & swift instead of dart, so I don't have to deal with dart runtime or 3rd party library issues. Might not be suitable for your use case but on mine I just needed a way to poll location and send it to remote server which was just a few lines of code to implement in both kotlin and swift. For getting location updates on background you can look into this package or background_locator package platform source code for reference (check if license permits it). If you're new to android, ios native development it might be tricky to work with so in that case I would suggest you to use existing packages instead of rewriting.
