### ISSUE TITLE
Add accuracy paramter to getLocation API

### ISSUE THREAD

**Issue by yuwen-yan** [Lyokone/flutterlocation#511]
**Is your feature request related to a problem? Please describe.**
Given the current api `changeSettings`, It's hard to control the location accuracy in async flow.

**Describe the solution you'd like**
N/A

**Describe workarounds you've considered**
N/A

**Additional context**
Add any other context or screenshots about the feature request here. Ex: do you know any Android of iOS sample code that could be used to develop this feature ?

**Comment by Lyokone** [comment]
Hi, I'm not planning of changing this API, it's quite useful to change both getLocation and onLocationChanged.
