### ISSUE TITLE
Location not getting when internet not connected in location package.

### ISSUE THREAD

**Issue by SohanBhadra** [Lyokone/flutterlocation#513]
location 3.2.4 

mixin CurrentLocationManager implements CurrentLocationCallBack {
  Location _location = Location();

  Future<PermissionStatus> _checkPermission() async {
    return await _location.hasPermission();
  }

  Future<PermissionStatus> _ask() async {
    return await _location.requestPermission();
  }

  _getLocation() async {
    try {
      final position = await _location.getLocation();
      log('getLocation : $position');
      await PrefUtils.registerLat(position.latitude.toString());
      await PrefUtils.registerLong(position.longitude.toString());
      onCurrentLocation(position);
    } catch (e) {
      print(e);
    }
  }

  Future<bool> _isLocationEnable() async {
    return await _location.serviceEnabled();
  }

  _askAndInit() async {
    final locationPermission = await _checkPermission();
    if (locationPermission == PermissionStatus.granted ||
        locationPermission == PermissionStatus.grantedLimited) {
      _getLocation();
    } else {
      final locationPermission = await _ask();
      if (locationPermission == PermissionStatus.granted ||
          locationPermission == PermissionStatus.grantedLimited) {
        _getLocation();
      } else if (locationPermission == PermissionStatus.deniedForever) {
        _jumpToSettings();
      } else {
        _askAndInit();
      }
    }

    final permission = await _ask();
    if (permission == PermissionStatus.granted ||
        permission == PermissionStatus.grantedLimited) {
      _getLocation();
    } else {
      _askAndInit();
    }
  }

  void currentLocation(BuildContext context) async {
      final serviceEnable = await _isLocationEnable();
      log('Location Service Enable : $serviceEnable');
      if (serviceEnable) {
        _askAndInit();
      } else {
        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (_) => WillPopScope(
            onWillPop: () async => false,
            child: AlertDialog(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(16.0)),
              ),
              title: Text("Alert"),
              content: Text("Your GPS seems disabled, please enable"),
              actions: <Widget>[
                OutlineButton(
                  onPressed: () => {Navigator.of(_).pop(), _jumpToSettings()},
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.all(
                      Radius.circular(8.0),
                    ),
                  ),
                  child: Text("Settings"),
                )
              ],
            ),
          ),
        );
      }
  }

  _jumpToSettings() async {
    await _location.requestService();
  }
}

class CurrentLocationCallBack {
  void onCurrentLocation(LocationData curLocation) {}
}

i have created a location based application which getting location when i need and perform a task, its working when device connected to internet (mobile data/ wifi) but the problem is that when internet is not connected it doen't getting location on it.

**Comment by Lyokone** [comment]
Hi :) It works fine on my OnePlus 7 Pro, so it might me device related.

**Comment by saulrmzlpz** [comment]
Same issue in Poco X4 Pro, Location Package version: ^4.4.0
