### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by torlarse** [Lyokone/flutterlocation#514]
**Is your feature request related to a problem? Please describe.**
I would like to ask questions about for example the null-safety branch etc., without submitting new issues.

**Describe the solution you'd like**
Enable GitHub Discussions. Most likely this is a setting located in the Features section of the general repo settings.

**Comment by Lyokone** [comment]
Hi, I've enabled GitHub discussions, I wasn't aware of it, thanks :)
