### ISSUE TITLE
Update location_platform_interface >=2.0.0-nullsafety.0 dependency plugin_platform_interface ^1.1.0-nullsafety

### ISSUE THREAD

**Issue by n0tc0ding** [Lyokone/flutterlocation#519]
**Describe the bug**
Conflict with firebase_core null safety using plugin_platform_interface: ^2.0.0

**Expected behavior**
Updated package with null safety

**Tested on:**
-Visual Studio Code

**Other plugins:**
 - firebase_messaging
 - firebase_core

**Additional logs**

Because location_platform_interface >=2.0.0-nullsafety.0 depends on plugin_platform_interface ^1.1.0-nullsafety and pedidosapp depends on plugin_platform_interface ^2.0.0, location_platform_interface >=2.0.0-nullsafety.0 is forbidden.

**Comment by Lyokone** [comment]
Hi :) The version 4.0.0 was released and has the proper dependencies, now. Should it happen again (for another package) i recommend you to do the following (I've been doing that for my own projet) 
```
dependency_overrides:
  plugin_platform_interface: ^2.0.0
```

**Comment by n0tc0ding** [comment]
Thank you @Lyokone I didnt know that one (dependency_overrides).
