### ISSUE TITLE
Crash of the pub get

### ISSUE THREAD

**Issue by gedolaszlo** [Lyokone/flutterlocation#523]
It requires >=2.12.0 dart SDK version when my Dart SDK version is 2.12.0-259.16.beta
**Describe the bug**
I couldn't upgrade this package to null safety. My pub get fails. It requires dart sdk version >=2.12.0 <3.0.0 and I use 2.12.0-259.16.beta Dart version.

**Expected behavior**
It works to upgrade if I use the required version 2.12.0-259.16.beta.

**.Log **
Running "flutter pub get" in project-app...                     
The current Dart SDK version is 2.12.0-259.16.beta.

Because project-app depends on location >=4.0.0 which requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because project-app depends on location >=4.0.0 which requires SDK version >=2.12.0 <3.0.0, version solving failed.)

**Comment by badjio** [comment]
`flutter upgrade` will fix the error

**Comment by Lyokone** [comment]
Yes since the release of the Flutter 2 release, the dart SDK version is locked on 2.12.0 not beta version.
