### ISSUE TITLE
Exception: The plugin location could not be built due to the issue above

### ISSUE THREAD

**Issue by WijdanMTak** [Lyokone/flutterlocation#525]
**Describe the bug**
Hi,
I am trying to use this package with android SDK 28, but it throws an exception, although its works with the higher Android SDK...
I will be grateful if you guide me to make it work arround with this SDK,

**Expected behavior**

> FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/wijdan/AndroidStudioProjects/with_New_Flutter/flutter_app/Mr Builder/t/location_test/build/app/intermediates/packaged_manifests/debug/AndroidManifest.xml:65: AAPT: error: attribute android:foregroundServiceType not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
✏️  Creating `android/settings_aar.gradle`...
✓ `android/settings_aar.gradle` created successfully.
Building plugin location...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type FileAccessTimeJournal using GradleUserHomeScopeServices.createFileAccessTimeJournal().
> Timeout waiting to lock journal cache (/home/wijdan/.gradle/caches/journal-1). It is currently in use by another Gradle instance.
  Owner PID: 8767
  Our PID: 11766
  Owner Operation: 
  Our operation: 
  Lock file: /home/wijdan/.gradle/caches/journal-1/journal-1.lock

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s

Exception: The plugin location could not be built due to the issue above.

**Tested on:**
 - Android, API Level 28  real device

**Comment by Lyokone** [comment]
Hi, have you tried to add `android:foregroundServiceType="location"` to your Android manifest ? Not sure why you wouldn't want to compile with the latest SDK version. It doesn't upgrade your minSDKVersion.

**Comment by talhakhan1297** [comment]
I just upgraded flutter and this package to their latest versions and I got the same exception.

**Comment by talhakhan1297** [comment]
> I just upgraded flutter and this package to their latest versions and I got the same exception.

I got it fixed by changing compileSdkVersion to 29 and targetSdkVersion to 29
