### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Buba98** [Lyokone/flutterlocation#527]
As soon as I updated the dependencies to 4.1.0 from 4.0.2 I'm not able to run the app anymore

e: /home/buba98/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.1.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (30, 48): Expecting a parameter declaration
e: /home/buba98/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.1.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (36, 41): Expecting a parameter declaration

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1

Strangely even after a downgrade to the 4.0.2 and a flutter clean the error is still the same and correlated to version 4.1.0

Note: /home/buba98/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_compass-0.5.1/android/src/main/java/com/hemanthraj/fluttercompass/FlutterCompassPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /home/buba98/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.1.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (30, 48): Expecting a parameter declaration
e: /home/buba98/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.1.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (36, 41): Expecting a parameter declaration

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Gramatton** [comment]
There is a bug in the 4.1.0 version. There are extra commas on the 30th and 36th lines. We need to wait until the bug is fixed by the author. Or you can fix the bug by yourself while waiting for the updated version. Just edit your local `FlutterLocationService.kt` file and remove commas at the end of the 30th and 36th lines:

```kotlin
data class NotificationOptions(
        val channelName: String = kDefaultChannelName,
        val title: String = kDefaultNotificationTitle,
        val iconName: String = kDefaultNotificationIconName,
        val subtitle: String? = null,
        val description: String? = null,
        val color: Int? = null,
        val onTapBringToFront: Boolean = false // <-- remove the comma here
)

class BackgroundNotification(
        private val context: Context,
        private val channelId: String,
        private val notificationId: Int  // <-- remove the comma here
){
```

**Comment by JaffaKetchup** [comment]
I have the same issue, and thanks to @Gramatton, I have temporarily fixed it.

**Comment by Lyokone** [comment]
Hi, 4.1.1 should fix that, thanks for catching this, I should improve CI to catch that, didn't show up in my manual testing :/

**Comment by Buba98** [comment]
Ok, thanks I've seen that now everything works properly.
