### ISSUE TITLE
[Android] First time retrieving location never returns

### ISSUE THREAD

**Issue by mkieres** [Lyokone/flutterlocation#53]
When trying to retrieve location with `getLocation` getter and permissions not yet granted, the getter never returns nor it throws an exception. It looks like the `MethodChannel.Result` has been "lost" somewhere on the way and `result.success()` or `result.error()` methods has never been called.

The scenario goes like this:

1. Call `getLocation` (permissions not granted at this stage)
2. User gets a prompt about permissions
3. Accept permissions
4. The `getLocation` never returns or throws exception

By the looks of the source code, the above might be connected to the part in the `onRequestPermissionsResult` (that's a wild guess though), where the `MethodChannel.Result` might be null

` if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                        if (result != null) {
                            getLastLocation(result);
                        } else if (events != null) {
                            getLastLocation(null); <-- this here
                        }`

You could have a look at how these kind of scenarios (with asking about permissions) are handled in other flutter plugins, such as [device calendar](https://github.com/builttoroam/flutter_plugins/blob/722f24a06e8cb13823a3e0a753929c95873b72f7/device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt#L75) or [image picker](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L320).

NOTE: I haven't tested this on iOS

**Comment by leslieharland** [comment]
Same issue here

**Comment by Lyokone** [comment]
Hey ! Pls look into the new demo if you're still having this issue :)
