### ISSUE TITLE
Function getLocation doesn't work and timeout

### ISSUE THREAD

**Issue by gustavodev91** [Lyokone/flutterlocation#532]
When i call getLocation() doesn't work
i have all permissions and the service is enabled.

For instance:
location
        .getLocation()
        .then((value) => print('DONE'))
        .onError((error, stackTrace) => print('ERROR'))
        .timeout(Duration(seconds: 5), onTimeout: () => print('TIME'));

the result is:
I/flutter (20872): TIME

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  image_picker: ^0.7.2
  firebase_storage: ^8.0.0
  firebase_messaging: ^9.0.0
  location: ^4.0.2
  cloud_functions: ^1.0.0

**Comment by hyouuu** [comment]
Same issue. Any updates? Or anyone could recommend another lib?

**Comment by Lyokone** [comment]
Hi, does this still happen on 4.2.0. A nice bug report would have contain the device / OS on which this error happens :/

**Comment by ToniTornado** [comment]
I was following this issue and I'm pretty sure it happened to me (only?) on Android Emulator. I will verify with 4.2.0 though.

**Comment by abumoallim** [comment]
I am facing the same issue Suddenly.
I am using this package for 1 year but suddenly this issue started coming.
I tried updating the location package 4.2.0 but still, it goes into an infinite loop.

**Comment by Lyokone** [comment]
Could you provide a reproductible example ?

**Comment by abumoallim** [comment]
Was previously using
  location: ^2.3.0
     
This is my code:
As soon it reaches getLocation it doesn't move forward and the build method is getting hit multiple times (infinite).
I tried debugging too but nothing is being called and no errors.

bool serviceStatus = await _locationService.serviceEnabled();
      if (serviceStatus) {
        _permission = (await _locationService.requestPermission()) ;
        if (_permission == locationPackage.PermissionStatus.granted) {
          widget.onServiceOpenWithDefaultLocation(false);

          log("Permission Granted");
          location = await _locationService.getLocation();

          //Add Marker
          _goToMarker(LatLng(location.latitude, location.longitude));
        }

**Comment by abumoallim** [comment]
I recently updated my firebase_messaging & firebase_core libraries
That's all I did but it was working then too.

**Comment by mckensi** [comment]
Hi!

if you check the status before use the get location data the response good.

You can do something like this:
 
final Location _location;

final permissionStatus = await _location.hasPermission();

        if (permissionStatus == PermissionStatus.granted || permissionStatus == PermissionStatus.grantedLimited) {
            _locationData = await _location.getLocation().timeout(const Duration(seconds: kRequestLocationTimeoutSeconds));
        }

return _locationData;

**Comment by FMorschel** [comment]
> This is my code: As soon it reaches getLocation it doesn't move forward and the build method is getting hit multiple times (infinite). I tried debugging too but nothing is being called and no errors.

Same happening to me, although only when there is no internet data. With data everything works just fine. Even if the data comes back and I'm using `onLocationChanged.first` nothing happens. 

My app is on production and I've received reports about this, found out only that the devices are Samsung running Android 11 (only published to Google Play), and I've tested on a Samsung Galaxy S20 FE with Android 12.

Any thoughts?

location: ^4.3.0

**Comment by Myzel394** [comment]
@FMorschel did you find a solution to this? Facing the same issue :/

**Comment by FMorschel** [comment]
I've not found a solution. Only added an agreed timeout and moved on. My app is not focused on location, so to me it was not my main concern.
