### ISSUE TITLE
Location throws exception when second time running

### ISSUE THREAD

**Issue by dfourcfive** [Lyokone/flutterlocation#537]
**Describe the bug**
everything works perfectly first time lunching the screen that has the location business code 
but when i got back and to another screen and try to lunch the tracking screen again
it throws an expectation  

``` shell
E/flutter ( 4135): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The setter 'location=' was called on null.
```

**Comment by Lyokone** [comment]
Hi, can you try again on 4.2.0 ?
