### ISSUE TITLE
FlutterLocation.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by 4F2E4A2E** [Lyokone/flutterlocation#546]
**Describe the bug**
```bash
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
Note: FlutterLocation.java uses or overrides a deprecated API.
```

**Expected behavior**
No use of deprecated API

**Tested on:**
 - Android, API Level 30, simulator

Using flutter v2.04 stable and location v4.1.1

**Comment by Lyokone** [comment]
Hi, I've updated master to not use those APIs anymore, I will publish this soon :)

**Comment by 4F2E4A2E** [comment]
Thank you sir!
