### ISSUE TITLE
Extend LocationData class with more location data

### ISSUE THREAD

**Issue by avkonst** [Lyokone/flutterlocation#552]
**Is your feature request related to a problem? Please describe.**
Lack of some of the location data attributes limits development of more advanced location-based apps (including mine).

**Describe the solution you'd like**
I would like LocationData class to be extended with the following data available on Android at least and anything what is possible on iOS:

* headingAccuracy - corresponds to https://developer.android.com/reference/android/location/Location#getBearingAccuracyDegrees()
* elapsedRealtimeNanos - corresponds to https://developer.android.com/reference/android/location/Location#getElapsedRealtimeNanos()
* elapsedRealtimeUncertaintyNanos - corresponds to https://developer.android.com/reference/android/location/Location#getElapsedRealtimeUncertaintyNanos()
* satelitesCount - corresponds to satelites field from the https://developer.android.com/reference/android/location/Location#getExtras()
* provider - corresponds to https://developer.android.com/reference/android/location/Location#getProvider()
* verticalAccuracy - corresponds to https://developer.android.com/reference/android/location/Location#getVerticalAccuracyMeters()
* isFromMock - corresponds to https://developer.android.com/reference/android/location/Location#isFromMockProvider()

**Describe workarounds you've considered**
I have considered to switch to raw GNSS measurements but it is an overkill (at least at this stage) with math computation and drains battery on compute of a position.

**Additional context**

The motivation for this request is to give applications access to more accuracy data. Since fused location data arrives from GNSS on-chip computation, it has got errors and it is important to know these errors (or degree of accuracy) to advice end-user how much to rely on these computations.

ElapsedNanos is absolutely necessary as the provided `time` field is in UTC and UTC time drifts due to Android's projection and leap seconds. ElapsedNanos are guaranteed to be monotonically increasing.  `time` field does not guarantee this and time can jump backwards. elapsedRealtimeUncertaintyNanos is necessary to estimate an accuracy of the measured `time` field and ElapsedNanos.

satelitesCount is another piece of useful information which allows an application to filter out measurements with low count, for example, as these tend to be worse.

isFromMock is necessary for an app to detect when a user is cheating with location (for example, if measurements are used for sport competitions).

**Comment by avkonst** [comment]
Do not close.

**Comment by Lyokone** [comment]
Hi,
Sorry for the late response.
Thanks for the detailed feature request. `isMock` information is on master and should be release soon. I'll see to add the other datas.

**Comment by avkonst** [comment]
Thank you very much!
