### ISSUE TITLE
Android release build hangs on 'Binding to location service.' 

### ISSUE THREAD

**Issue by koltai75** [Lyokone/flutterlocation#554]
Everything works fine with iOS release / debug and Android debug builds, but Android release build hangs on startup at this point:
```shell
D/FlutterLocationService(24697): Creating service.
D/FlutterLocationService(24697): Binding to location service.
```
I found some hints that it might be a problem with null safety so I tried to build without sound null safety but the result is same. Thank you in advance, I am struggling with this for days now.

**Tested on:**
 - Android, API 30, Samsung SM J530F
 - iOS, Version 12, simulator and iPhone 11

**Flutter doctor:**

``` shell
[✓] Flutter (Channel master, 2.3.0-1.0.pre.201, on macOS 11.3 20E232 darwin-x64, locale en-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)
```

**relevant Android manifest settings:**
``` xml
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-feature android:name="android.hardware.location" />
  <uses-feature android:name="android.hardware.location.gps" />
  <uses-feature android:name="android.hardware.location.network" />
  <application
        <service
            android:name="myLocation"
            android:foregroundServiceType="location">
            <!-- Any inner elements would go here. -->
        </service>       
```

**Comment by anilraok** [comment]
@koltai75 What did you do to fix the issue?

**Comment by koltai75** [comment]
> @koltai75 What did you do to fix the issue?

I switched to this package: [https://pub.dev/packages/geolocator](https://pub.dev/packages/geolocator)
