### ISSUE TITLE
Documentation listen() needs  cancel() example

### ISSUE THREAD

**Issue by d-silveira** [Lyokone/flutterlocation#56]
In order to avoid heavy resources consumption, keeping location gathering on, the documentation example with the ``listen()``, should include a ``cancel()`` on dispose

**Comment by vladaman** [comment]
Any way to cancel the listening stream now?

**Comment by ocomsoft** [comment]
I added this to dispose but it ended up that I no longer get a location in other widgets that were subscribed.

**Comment by Lyokone** [comment]
Hey, you're right i'll add this :)

**Comment by Lyokone** [comment]
I've added the proper example in the form of a FAB button to cancel location tracking.

**Comment by quetool** [comment]
@Lyokone Hi! What you have done in it, it is not a real stream cancelling, You instantiated a StreamSubscription `StreamSubscription<LocationData>`, asociated it to your listener onLocationChanged() wich is a `Stream<LocationData>`, and on dispose() you are cancelling the `StreamSubscription` not the listener, listener is still being called after widget dispose... You can check it by uncommenting `if(mounted){` on https://github.com/Lyokone/flutterlocation/blob/master/example/lib/main.dart#L71
