### ISSUE TITLE
Altitude Source and Heading Units

### ISSUE THREAD

**Issue by DooRooSA** [Lyokone/flutterlocation#560]
Good morning,

Two questions (hint: please add this to the documentation):

1. Is the altitude sourced barometrically or is it GPS derived information?
2. Is the heading a magnetic heading or a true heading?

Keep up the good work with this package guys and gals!

**Comment by Lyokone** [comment]
Hi :) 
I've added the source of the altitude in the documentation of LocationData.
Not sure how to find the answer for your second question. It is not stated in the Google Services Documentation :/
