### ISSUE TITLE
What affects/determines the minimum interval of location updates?

### ISSUE THREAD

**Issue by Dealerpriest** [Lyokone/flutterlocation#562]
Hello! This question refers primarily to android.
I've tried to set the interval to as low as 500ms (and distancefilter to 0) but I never receive updates more often than about 5 seconds.
Which parameters affect the (minimum) interval pf the location updates?
- The size/execution time of the callback function?
- The Android OS?

Is it possible to adjust settings in the phone to make the callback trigger more often?

Any advice or ideas are welcome!

**Comment by Lyokone** [comment]
Hi, you might need to restart the onLocationChanged call to have the settings properly applied. I've changed that on master and I should be releasing that shortly.

**Comment by Dealerpriest** [comment]
To be clear, It does work for you to get updates as frequent as 500ms?
