### ISSUE TITLE
Multiple callbacks after hot restart

### ISSUE THREAD

**Issue by Dealerpriest** [Lyokone/flutterlocation#563]
**Describe the bug**
If I hot restart (*not* hot reload) my app the onLocationChanged gets triggered an extra time when it is fired. I gather this is related to the old callback still being active in some way. For each time i hot restart, the number of triggered callbacks is increased.
Why is this happening? What could I do to mitigate it?

**Expected behavior**
The old callback is "disposed"/cleared.

**Tested on:**
 - Android, API Level 29, on real device

**Other plugins:**
 - googlemaps

**Comment by Lyokone** [comment]
Hi, you should always cancel your StreamSubscriptions. You can add
```
  @override
  void dispose() {
    _locationSubscription?.cancel();
    _locationSubscription = null;
    super.dispose();
  }
```
to your widget.

You can also add the `cancel_subscriptions` rule to help you with this :)

**Comment by Dealerpriest** [comment]
From chatting in the flutter discord server I was informed that the dispose function of a Widget isn't called on a hot restart. So my understanding is that your suggestion won't work.

Also in my case, the logic handling the location-plugin is inside a singleton dart class (not a widget), so there is actually no dispose method available for me to override.
From my understanding the core problem is that there is no way for native code to be notified of hot restarts and thus dispose/cleanup resources?

Perhaps I've misunderstood?

**Comment by guigzp** [comment]
I'm facing the same issue, I'm using a Cubit to handle the location stream and its emiting duplicated states after hot restart :(
Any fix to this?

PS: the cubit close method is not being called in hot restart cause Flutter does not close a Widget when restarting

**Comment by dsgriffin** [comment]
anyone find a solution to this?
