### ISSUE TITLE
Save location permission not working

### ISSUE THREAD

**Issue by steve-cahn** [Lyokone/flutterlocation#564]
**Describe the bug**
After a user allows the location permission, it doesn't seems like it saves it. But instead, everytime I run the app it reasks for location permission. Here's my code:
```dart
Future<bool> getLocationPermission() async {
  Location location = new Location();
  await location.requestService();
  bool _serviceEnabled = await location.serviceEnabled();
  if (!_serviceEnabled) {
    _serviceEnabled = await location.requestService();
    if (!_serviceEnabled) {
      return false;
    }
  }

  PermissionStatus _permissionGranted = await location.hasPermission();
  if (_permissionGranted == PermissionStatus.denied) {
    _permissionGranted = await location.requestPermission();

    if (_permissionGranted != PermissionStatus.granted) return false;
  }

  return true;
}
```

**Expected behavior**
Should ask for permission once and save the info.

**Tested on:**
 - iOS, 11, real device

**Comment by profiteroles** [comment]
I'm running into same issue and seems like they haven't updated their API. that code is for version 3.0.0 Hopefully they will some time soon.

**Comment by Lyokone** [comment]
Hi, if you choose `while using the app` on the dialog it's properly saved.
The permission is not "saved" by the app or the plugin but only managed by the OS (the user can remove the permission outside of the app)
