### ISSUE TITLE
[Android] Cancelling the subscription on onLocationChanged doesn't seem to stop the location service.

### ISSUE THREAD

**Issue by actow** [Lyokone/flutterlocation#567]

**Comment by Lyokone** [comment]
Related to calling onLocationChanged multiple times, see #462

**Comment by Lyokone** [comment]
After investigation, you are probably not cancelling all the StreamSubscription.

**Comment by obisiscom** [comment]
import 'dart:async';
StreamSubscription<LocationData> locationSubscription;

locationSubscription = location.onLocationChanged().listen((LocationData currentLocation)
{
  //Your code
});

locationSubscription.cancel();

**Comment by obisiscom** [comment]
import 'dart:async';

StreamSubscription<LocationData> locationSubscription;

locationSubscription = location.onLocationChanged().listen((LocationData currentLocation)
{
  //Your code
});

locationSubscription.cancel();
