### ISSUE TITLE
Location package generates platform exception on call to serviceEnabled()

### ISSUE THREAD

**Issue by abhlabs** [Lyokone/flutterlocation#568]
Flutter 2.0.6, Location package 4.1.1.

This snippet of code...

~~~
  try {
    _serviceEnabled = await location.serviceEnabled();
  } on PlatformException catch (err) {    
    print ("Platform exception calling serviceEnabled(): $err");
    _serviceEnabled = false; 
  }
~~~
Generates: "Platform exception calling serviceEnabled(): PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null, null)"

But here's the interesting part: this error _only_ comes up when I run a release build on my Samsung Galaxy S8. If I run a debug build on the S8, or if I run either a release or a debug build on an android emulator, no error is thrown. I've tried a few different emulator configurations, specifically one configured as closely to the S8 -- Android version 9 (SDK 28), and same screen size.

Any suggestions for how to investigate why this is happening would be greatly appreciated.

**Comment by Lyokone** [comment]
Hi, 
Which version of gradle are you using for your app ? Can you see if you can match the gradle version of the example app and still reproduce ?

**Comment by hello-deepak** [comment]
@Lyokone 

I also get the same error.

![image](https://user-images.githubusercontent.com/7577697/121165165-c9f2f500-c86f-11eb-86b9-c2a5ee0a5fd3.png)

**Comment by abhlabs** [comment]
Updated to the 4.3.0 version of location package, and modified build.gradle as follows:

`
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
    }`

This gave me a build error with the suggestion to upgrade the gradle-wrapper as follows:

`
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
`

Program now builds and runs, but I still get the same platform exception:

`
(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null, null)
`

As before, when I run the debug version on the same device, it works fine.

**Comment by PatrikPenta-Axatel** [comment]
Hi,
I found this solution:

```
initLocation() async {
        try {
          _serviceEnabled = await location.serviceEnabled();
        } on PlatformException catch (err) {
          print("Platform exception calling serviceEnabled(): $err");
          _serviceEnabled = false;

          // location service is still not created

          initLocation(); // re-invoke himself every time the error is catch, so until the location service setup is complete
        }
}
```

I think that problem is related with some Android timeout process, because watching my log I see the following:

1. `serviceEnabled()` is executed, but location service is not initialized, so appear the following error: `(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null, null)`
2. `Creating service`  this is the service creation step
3. `Binding to location service` service setup has been completed

As you can see, you have to add the 4th step for running correctly `serviceEnable()` and other location's permission, which you can find in my code above.

**Comment by yamidnozu** [comment]
@PatrikPenta-Axatel Podrías indicarme que versión tenias? o si puedes el fragmento de código completo?

**Comment by PatrikPenta-Axatel** [comment]
> @PatrikPenta-Axatel Podrías indicarme que versión tenias? o si puedes el fragmento de código completo?

Version: location: ^4.3.0

You can call initLocation() from the initState({}) for example and the code is completed

**Comment by TheoLassonder** [comment]
Exactly the same problem in our app. Happens on version 4.3.0 on a Pixel 4. With Gradle 6.7 if that's relevant.

@PatrikPenta-Axatel Thanks for the work around!

**Comment by deakjahn** [comment]
@PatrikPenta-Axatel Same here on a Huawei P30 Pro. Release only.

I'm not terribly fond of the recursive nature of your workaround :-). Did you find another one, or any problems with this one?

**Comment by OvaisKhanday** [comment]
**I think a better approach exists, if we talk of getting it in a way that is not robust. **

```
 Future<bool> _requestService({int limit = 20}) async {
    for (var i = 0; i < limit; i++) {
      try {
        return await location.serviceEnabled();
      } catch (e) {
        // do nothing, if there is an exception
      }
    }
    return false;
  }
```

**Explanation**: If the service is not enabled then the function returns false, if the service is enabled then "go ahead", or if there is an error then try again 20 times (default) in a row.

**Comment by komaxx** [comment]
This issue still appears in my logs. 
Is there any official solution in the pipeline, or are we really supposed to just retry until it maybe works?
