### ISSUE TITLE
Foreground Service 'Background Location Service' Not working for IOS

### ISSUE THREAD

**Issue by fdarsot** [Lyokone/flutterlocation#569]
Hi there, i have an app which makes use of this package's "enableBackgroundMode"

currently i have it so when the flutter app is minimized (but not terminated) it enables the background mode so that i continue to receive location updates.

This is working for android when Location permission level is set to "Allow Always" and i see a little constant notification saying the "background location service is running" i.e the foreground service.

However this is not working for iOS. I'm testing on 2 iOS devices one has iOS13 and the other has iOS 14. I do not see the little blue badge that indicates that background location services are running.

any assistance?

**Comment by Lyokone** [comment]
Hi,
In order to have the blue badge, you have to use the `onLocationChanged` method after having activate the `enableBackgroundMode`.
Let me know if it helps you

**Comment by fdarsot** [comment]
Hi yes this is correct and is working. closing this ticket.

thank you
