### ISSUE TITLE
When the location service permission is given the LocationData doesn't seem to provide any data .

### ISSUE THREAD

**Issue by Afsal102** [Lyokone/flutterlocation#572]
- When Location service dialog is shown and the user gives the permission even though the stream is being listened there is not data sent through the stream (no  LocationData).
- when the subscription is cancelled its doesn't unbind the location 
-

**Comment by iandis** [comment]
This just happened to me today (the 'no LocationData' thing). So what happened was I asked user to enable location service via requestService() and user granted it, but the getLocation() hangs my method that calls it. So, I ended up using **timeout** after **getLocation()**. I set the timeout to be 5 seconds to prevent getLocation() from hanging my method for too long. It worked, but I have to ask user to refresh the page. Here's my code:
`
  /// gets current location of user.
  /// * returns `null` if permission is denied.
  /// * returns `List<null>` if failed to get user's latitude or longitude.
  /// * returns `List<double>` with 2 data, where [0] is latitude, and [1] is longitude.
  /// * throws `Unknown error occurred. Please reload.` if timeout.
  /// * throws `This feature requires high accuracy. Please set your GPS to high accuracy in your settings.` if location service is not enabled.
  @override
  Future<List<double?>?> getCurrentCoordinates() async {
    final permStatus = await Permission.locationWhenInUse.request();
    if (!permStatus.isGranted){
      return null;
    }else if(permStatus.isLimited){
      if (!await _location.serviceEnabled()){
        final requestService = await _location.requestService().timeout(
          Duration(seconds: 5), 
          onTimeout: () => throw 'Unknown error occurred. Please reload.',
        );

        if(!requestService){
          throw 'This feature requires high accuracy. Please set your GPS to high accuracy in your settings.';
        }
      }
      
    }
    
    
    final getLocation = await _location.getLocation()
      .timeout(
        Duration(seconds: 5), 
        onTimeout: () => throw 'Unknown error occurred. Please reload.',
      );  
    return [getLocation.latitude, getLocation.longitude];
  }
`

**Comment by iandis** [comment]
This just happened to me today (the 'no LocationData' thing). So what happened was I asked user to enable location service via requestService() and user granted it, but the getLocation() hangs my method that calls it. So, I ended up using **timeout** after **getLocation()**. I set the timeout to be 5 seconds to prevent getLocation() from hanging my method for too long. It worked, but I have to ask user to refresh the page. Here's my code:
```@override
  Future<List<double?>?> getCurrentCoordinates() async {
    final permStatus = await Permission.locationWhenInUse.request();
    if (!permStatus.isGranted){
      return null;
    }else if(permStatus.isLimited){
      if (!await _location.serviceEnabled()){
        final requestService = await _location.requestService().timeout(
          Duration(seconds: 5), 
          onTimeout: () => throw 'Unknown error occurred. Please reload.',
        );

        if(!requestService){
          throw 'This feature requires high accuracy. Please set your GPS to high accuracy in your settings.';
        }
      }
      
    }
    
    
    final getLocation = await _location.getLocation()
      .timeout(
        Duration(seconds: 5), 
        onTimeout: () => throw 'Unknown error occurred. Please reload.',
      );  
    return [getLocation.latitude, getLocation.longitude];
  }```

**Comment by Afsal102** [comment]
@iandis  Future works but i am talking about the stream when listened it doesn't provide the location changes even though its subscribed !

**Comment by iandis** [comment]
@Afsal102 I think you can request user to reload after **requestService()** as a workaround.
Probably something like:
```dart
///...
Future<StreamSubscription<location.LocationData>?> getLocationStream(void Function(location.LocationData)? onLocationChanged) async{
    if (await _location.hasPermission() == location.PermissionStatus.grantedLimited){
      if (!await _location.serviceEnabled()){
        final requestService = await _location.requestService().timeout(
          Duration(seconds: 5), 
          onTimeout: () => throw 'Unknown error occurred. Please reload.',
        );

        if(!requestService){
          throw 'This feature requires high accuracy. Please set your GPS to high accuracy in your settings.';
        }
      }
      return null;
    }else{
      return _location.onLocationChanged.listen(onLocationChanged);
    }
  }

  final locationStream = await getLocationStream((location) { 
    /// ...
    /// your code here
    /// ...
  });
  
  if(locationStream == null){
    /// request user to reload
  }else{
    /// ...
  }
```

**Comment by Afsal102** [comment]
@iandis  that was my previous implementation . It's gonna show two dialogs thats what i don't like about it 
1. when the listen is called there will a dialog
@. when i manually call it
Anyways thanks for answering out .

**Comment by TalebRafiepour** [comment]
Same issue.

**Comment by Lyokone** [comment]
Hi thanks for the report, I'm going to have a look at it :)

**Comment by Xellly** [comment]
Has been happening to me for quite some time, the future is always "waiting". Never returns anything after previously working fine.

**Comment by Lyokone** [comment]
Can you try 4.2.1 to see if it still happens ? On which platform does it happen ?

**Comment by Xellly** [comment]
> Can you try 4.2.1 to see if it still happens ? On which platform does it happen ?

I was previously on 4.0.2, I tried updating cleaning and rebuilding but it was the same. Nothing happens after I called _locationData = await location.getLocation();. The widget stops there, and if I put it in a futurebuilder it's always in the waiting state.

**Comment by Lyokone** [comment]
If you can provide a small example on which this error happens, it could help resolve this.
On which Android device are you testing ?

**Comment by Xellly** [comment]
> If you can provide a small example on which this error happens, it could help resolve this.
> On which Android device are you testing ?

My customers took quite a while to say there's an actual issue, I just tried removing my android manifest and remaking it and for some reason it started working. A permission issue? I'll put back the broken manifest and try another location package to see if it was from it and not your package

**Comment by ch-muhammad-adil** [comment]
I have faced same issue after upgrading to `flutter 2.2.1` and in latest version `location: 4.2.1`

Downgraded it back to  `location: 4.0.0` and it has started working for me.

**Comment by Lyokone** [comment]
In the iOS simulator, you can have a laggy response. Try to switch to "City Run" in the Features/Location menu.

**Comment by Afsal102** [comment]
its in real device @Lyokone older versions are working , i switched to null safety with latest version then only i found this . Also was in production. Would be better if there was a fix quick

**Comment by giorgio79** [comment]
Same bug  for iOS 14 on iOS Simulator! My app was rejected because of this issue in app store.

**Comment by giorgio79** [comment]
Downgraded to Location 4.0.0 for now.  That works fine and the app was approved by iOS store
