### ISSUE TITLE
onLocationChanged() not returning on M1 Android Studio Emulator - works fine on x86 

### ISSUE THREAD

**Issue by ldbellamy** [Lyokone/flutterlocation#573]
**Describe the bug**

I really don't know if I should be lodging this bug with you or with google, but on Android Studio (4.2.1) Android Emulator (Android 11 arm build) on an M1 Macbook Air, onLocationChanged never returns. This behaviour seems to occur with location version 2.5.4 right through to 4.1.1 

Same codebase, same version of flutter (2.0.2), same version of android studio, same android image version on a Windows PC running x86 emulator, onLocationChanged works without issue. I have not tested on a real device but I suspect that it would also work without issue. 

Given how flakey Android studio / emulator support is for M1 macs at the moment, I'm not sure how seriously i should be taking this .... 

**Expected behavior**
Run it on an android emulator, and onLocationChanged() returns.

**Tested on:**
 - Android emulator, API Level 30, simulator on mac M1 (doesnt work)
 - Android emulator, API Level 30, simulator on x86 PC

**Other plugins:**
 - N/A

**Additional logs**
N/A

``` shell
N/A
```

**Comment by Lyokone** [comment]
Hi, I don't currently have a m1 mac to test that, but it definitely seems related to the Simulator

**Comment by anilraok** [comment]
Issue looks similar to this issue. [https://github.com/Lyokone/flutterlocation/issues/590](url)
It doesn't have anything to do with M1. Happening in Android API 30
