### ISSUE TITLE
App crashes when asking for permission

### ISSUE THREAD

**Issue by austinn** [Lyokone/flutterlocation#577]
**Describe the bug**
After upgrading from 4.1.1 to 4.2.0+, when requesting location permissions the app crashes with the following error message `Neither user 10470 nor current process has android.permission.ACCESS_FINE_LOCATION.` 

**Expected behavior**
The "Allow APP_NAME to access this device's location?" dialog appears on 4.1.1, but not 4.2.0+

**Tested on:**
 - Android, API Level S (Android 12 beta 1), real device

**Additional logs**
```
E/AndroidRuntime( 8699): java.lang.SecurityException: Neither user 10470 nor current process has android.permission.ACCESS_FINE_LOCATION.
E/AndroidRuntime( 8699):        at android.os.Parcel.createExceptionOrNull(Parcel.java:2418)
E/AndroidRuntime( 8699):        at android.os.Parcel.createException(Parcel.java:2402)
E/AndroidRuntime( 8699):        at android.os.Parcel.readException(Parcel.java:2385)
E/AndroidRuntime( 8699):        at android.os.Parcel.readException(Parcel.java:2327)
E/AndroidRuntime( 8699):        at android.location.ILocationManager$Stub$Proxy.registerGnssNmeaCallback(ILocationManager.java:1879)
E/AndroidRuntime( 8699):        at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:2905)
E/AndroidRuntime( 8699):        at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:2895)
E/AndroidRuntime( 8699):        at com.android.internal.listeners.ListenerTransportManager.addListener(ListenerTransportManager.java:70)
E/AndroidRuntime( 8699):        at android.location.LocationManager.addNmeaListener(LocationManager.java:2415)
E/AndroidRuntime( 8699):        at android.location.LocationManager.addNmeaListener(LocationManager.java:2396)
E/AndroidRuntime( 8699):        at com.lyokone.location.FlutterLocation.lambda$startRequestingLocation$2$FlutterLocation(FlutterLocation.java:421)
E/AndroidRuntime( 8699):        at com.lyokone.location.-$$Lambda$FlutterLocation$GtSSUe8dBDBBQxv83CuVjKNJ2RM.onSuccess(Unknown Source:4)
E/AndroidRuntime( 8699):        at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
E/AndroidRuntime( 8699):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 8699):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8699):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8699):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8699):        at android.app.ActivityThread.main(ActivityThread.java:7727)
E/AndroidRuntime( 8699):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8699):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8699):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/AndroidRuntime( 8699): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 8699):        at android.app.ContextImpl.enforce(ContextImpl.java:2130)
E/AndroidRuntime( 8699):        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2158)
E/AndroidRuntime( 8699):        at com.android.server.location.gnss.GnssManagerService.registerGnssNmeaCallback(GnssManagerService.java:177)
E/AndroidRuntime( 8699):        at com.android.server.location.LocationManagerService.registerGnssNmeaCallback(LocationManagerService.java:903)
E/AndroidRuntime( 8699):        at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:839)
```

``` shell
some logs
```

**Comment by Lyokone** [comment]
Hi, thanks for the report. Looks like a Manifest permission issue. Is the ACCESS_FINE_LOCATION permission in your manifest ? Can you try `flutter clean` if the permission is already in your manifest ?

**Comment by austinn** [comment]
@Lyokone I do have `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` in my manifest. I tried `flutter clean` and also upgrading to 4.2.2, but still crashes with the same stacktrace

**Comment by Lyokone** [comment]
Okay thanks for trying that. Just to clarify, does it happen only on Android 12 or also lower version of Android ?

**Comment by percula** [comment]
I have the exact same issue, also on Flutter 4.2.2. I thought it might just be an Android 12 issue, but it is also happening on Android 11 and Android 9. What's weird is that the app crashes (same stacktrace as posted above) and then the dialog shows up:

![Screenshot_20210615-192638](https://user-images.githubusercontent.com/16809252/122136111-d21ed780-ce0f-11eb-8ec3-487d43840be2.png)

**Comment by PrinzKenny1** [comment]
Hey I`ve fixed it with the following code (note the Permission request comes from the permission_handler package):

```
    if (!await Permission.location.request().isGranted) {
      return false;
    }

    final Location location = new Location();
    location.changeSettings(accuracy: LocationAccuracy.high);

    bool _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        return false;
      }
    }

    final LocationData _locationData = await location.getLocation();
```

**Comment by AmareeshBP** [comment]
Same issue, the app crashes after upgrading to **4.3.0** from **4.1.1**

**Crash Log:**
```
D/AndroidRuntime(19901): Shutting down VM
E/AndroidRuntime(19901): FATAL EXCEPTION: main
E/AndroidRuntime(19901): Process: com.pageslokator.android.dev, PID: 19901
E/AndroidRuntime(19901): java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
E/AndroidRuntime(19901): 	at android.os.Parcel.readException(Parcel.java:1942)
E/AndroidRuntime(19901): 	at android.os.Parcel.readException(Parcel.java:1888)
E/AndroidRuntime(19901): 	at android.location.ILocationManager$Stub$Proxy.registerGnssStatusCallback(ILocationManager.java:826)
E/AndroidRuntime(19901): 	at android.location.LocationManager.addNmeaListener(LocationManager.java:1787)
E/AndroidRuntime(19901): 	at com.lyokone.location.FlutterLocation.lambda$startRequestingLocation$2$FlutterLocation(FlutterLocation.java:425)
E/AndroidRuntime(19901): 	at com.lyokone.location.-$$Lambda$FlutterLocation$RtFo0ovM_N9dgwZfpocA94uX3MY.onSuccess(Unknown Source:4)
E/AndroidRuntime(19901): 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
E/AndroidRuntime(19901): 	at android.os.Handler.handleCallback(Handler.java:789)
E/AndroidRuntime(19901): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime(19901): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(19901): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AndroidRuntime(19901): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19901): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(19901): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by agetman-gh** [comment]
have this error when starting release app. Works fine on debug app.

**Comment by shah-xad** [comment]
Facing the same issue.

**Comment by hpop** [comment]
> Crash occurs if **changeSettings** is called before confirming the permissions

Thanks! This was the fix for me.

**Comment by dsgriffin** [comment]
This happens if you press `deny` on an Android device, too. Any more updates on a fix?

**Comment by PrinzKenny1** [comment]
@dsgriffin I don't know if this bug is currently the same as a couple of months ago, but if, you can try my workaround. Maybe it fixes your bug:

https://github.com/Lyokone/flutterlocation/issues/577#issuecomment-864588880

**Comment by Amanullahgit** [comment]
its because calling  `location.changeSettings(accuracy: loc.LocationAccuracy.high);` or any other assignments on location before asking for permission.

` getlocation() async {
    bool _serviceEnabled;
    PermissionStatus _permissionGranted;
    LocationData _locationData;

//remove it from here
// location.enableBackgroundMode(enable: true);
// location.changeSettings(accuracy: loc.LocationAccuracy.high);

    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        return;
      }
    }

    _permissionGranted = await location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {
        return;
      }
    }
//add it here
    location.enableBackgroundMode(enable: true);
    location.changeSettings(accuracy: loc.LocationAccuracy.high);
    _locationData = await location.getLocation();
  }`
