### ISSUE TITLE
App crashes when using Android emulator API 27

### ISSUE THREAD

**Issue by ElixirMike** [Lyokone/flutterlocation#579]
I am using version location: ^4.2.0  (also tried location: ^4.2.1)
When trying to access getLocation(), it initially asks for permission, I click "Allow", and the app crashes. 

Future<void> _getCurrentUserLocation() async {
    final locData =  await Location().getLocation();
    print(locData.latitude);
    print(locData.longitude);
  }

The error is : "java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference"

If I try the exact same thing using Android emulator API 28, it works ok.
Is there a way to make this work with earlier versions?

**Comment by Lyokone** [comment]
Thanks for the report, should be fixed in 4.2.2.
