### ISSUE TITLE
 Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution

### ISSUE THREAD

**Issue by binay-sisc** [Lyokone/flutterlocation#58]
I just used this flutter package location and the application was fine before i add the package but as soon as i installed from pubspec then immediately shows ` Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution` as error

**Comment by jmh** [comment]
I was having the same issue and found adding this to `build.gradle` fixed it for me.

```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }
        }
    }
}
```

Solution found here: ['com.android.support:appcompat-v7' has different version for the compile (26.1.0) and runtime (27.0.1) classpath](https://github.com/flutter/flutter/issues/14020)

**Comment by alexlovar** [comment]
solution for me:
Addthe follow line in app/src/build.gradle in dependencies section:
implementation "com.android.support:appcompat-v7:27.1.0" 
or :27.1.1 in my case

**Comment by Lyokone** [comment]
Hey, thank you to everyone who have helped ! :)
