### ISSUE TITLE
FlutterLocation.checkPermissions() null object reference when on background

### ISSUE THREAD

**Issue by dtheodor79** [Lyokone/flutterlocation#581]
**Describe the bug**
When trying to get the location on the background (task fires on background with the [background_fetch](https://pub.dev/packages/background_fetch) package successfully), I get:

`Attempt to invoke virtual method 'boolean com.lyokone.location.FlutterLocation.checkPermissions()' on a null object reference`

This is the dart task that runs on the background:

```
doBackgroundWork(String taskId) async {
  WidgetsFlutterBinding.ensureInitialized();
  final Location location = Location();
  LocationData _locationData;

  PermissionStatus _permissionGranted = await location.hasPermission();
  if (_permissionGranted == PermissionStatus.granted) {

    bool isBackgroundModeEnabled = await location.enableBackgroundMode(enable: true);

    if (isBackgroundModeEnabled) {
      _locationData = await location.getLocation();
    }
  }
  else {
    appUtils.myLog(appConst.LOG_WARNING,'[doBackgroundWork] location permission not granted');
  }

}
```
I also tried to run first enabling background location:

`await location.enableBackgroundMode(enable: true);`

and then check for permission, 

`PermissionStatus _permissionGranted = await location.hasPermission();`

which returned that isBackgroundModeEnabled = false, and then again crashed.

I should note that when the doBackgroundWork runs when the app is on the foreground, it runs successfully.

**Expected behavior**
Expected to check if the user has provided access to location and, if yes, read the current location (when the app is closed).

**Tested on:**
 - Android, API Level 27, real device Moto G5
 - Android, API Level 29, simulator Pixel 2

**Other plugins:**
 [background_fetch](https://pub.dev/packages/background_fetch)

**Comment by Lyokone** [comment]
Hi, thanks for the report. I'm not familiar with the background_fetch plugin. But trying to get Location in the background is heavily controlled operation by both iOS and Android. I'm not sure that It would work with the current state of feature of the plugin.

**Comment by dtheodor79** [comment]
OK, thank you for the quick reply!

**Comment by Lyokone** [comment]
The background mode is only when your app is still running but minimised by the user (Google Maps).
In this case the onLocationChanged is executed normally :)

**Comment by dtheodor79** [comment]
OK, now I got it :) Thanks a lot for the explanation.
