### ISSUE TITLE
How can I get location info(getLocation()) without Google Play Service?

### ISSUE THREAD

**Issue by huangsir0** [Lyokone/flutterlocation#582]
Too many Android mobile user have no Google Play Service,and too many user can't download Google Play Service,In this case,How should I do? .

**Comment by selankon** [comment]
I have the same problem, is there a way to work without google services using [LocationManager](https://stackoverflow.com/questions/17726728/get-location-without-google-play-services-android), for example?

**Comment by Lyokone** [comment]
Hi, thanks for the report. I'm not sure if I can implement a plugin that both use Google Play services and fallback to LocationManager 🤔 I would need to investigate this

**Comment by selankon** [comment]
Hi, I have different native apps that work with geolocation without play services, for example Osmand or the geolocation of some other like TelegramFOSS, SatSat etc... So modifying the plugin we should manage to let it working.

Without play services you could still get geolocation from GPS and if you have other Location Services configured in your device (like Mozilla UnifiedNlp Backend), the system should use it to get phone cell or wifi based location. This is working for me in my LineageOs without Play Services from many apps.

I'm not sure if they fix it but for plugin flutter-geolocator they also handle this situation: https://github.com/Baseflow/flutter-geolocator/issues/473

**Comment by zmGitHub** [comment]
GeolocatorGeolocator

> Hi, I have different native apps that work with geolocation without play services, for example Osmand or the geolocation of some other like TelegramFOSS, SatSat etc... So modifying the plugin we should manage to let it working.
> 
> Without play services you could still get geolocation from GPS and if you have other Location Services configured in your device (like Mozilla UnifiedNlp Backend), the system should use it to get phone cell or wifi based location. This is working for me in my LineageOs without Play Services from many apps.
> 
> I'm not sure if they fix it but for plugin flutter-geolocator they also handle this situation: [Baseflow/flutter-geolocator#473](https://github.com/Baseflow/flutter-geolocator/issues/473)

me to

**Comment by lvpidadiao** [comment]
this is a necessary feature

**Comment by filipenanclarez** [comment]
Me too ... Geolocator plugin have this, but not work on background ... i need both features. ...
