### ISSUE TITLE
Example app fails

### ISSUE THREAD

**Issue by josh-gree** [Lyokone/flutterlocation#584]
**Describe the bug**
The following error is given in debug mode (android studio) when running the example app (https://github.com/Lyokone/flutterlocation/tree/master/packages/location/example) upon clicking `Get` in the `GetLocationWidget`;

```
_TypeError (type 'int' is not a subtype of type 'String')
``` 

**Expected behavior**
For the app to succeed and return the location

**Tested on:**
 - Android simulator (Not sure what API level...)

**Additional logs**

``` shell
E/flutter ( 4485): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'int' is not a subtype of type 'String'
E/flutter ( 4485): #0      new LocationData.fromMap
package:location_platform_interface/src/types.dart:42
E/flutter ( 4485): #1      MethodChannelLocation.getLocation
package:location_platform_interface/src/method_channel_location.dart:94
E/flutter ( 4485): <asynchronous suspension>
E/flutter ( 4485): #2      _GetLocationState._getLocation
package:location_example/get_location.dart:26
E/flutter ( 4485): <asynchronous suspension>
E/flutter ( 4485):
```

**Comment by josh-gree** [comment]
After a little bit of digging this actually seems to occur here;

https://github.com/flutter/flutter/blob/02c026b03cd31dd3f867e5faeb7e104cce174c5f/.pub-cache/hosted/pub.dartlang.org/location_platform_interface-2.2.0/lib/src/types.dart#L41-L43

```dart
      dataMap['satelliteNumber'] != null
          ? int.parse(dataMap['satelliteNumber'])
          : null
```

I believe because `dataMap['satelliteNumber']` is already an int and thus the parse fails?

I changed the above line to;

```
      dataMap['satelliteNumber'] != null
          ? dataMap['satelliteNumber']
          : null
```

And the example app seems to get past this issue.

**Comment by josh-gree** [comment]
And I see this has actually been changed here -> https://github.com/Lyokone/flutterlocation/commit/b982074b1c907c64c00573246c814569fe8f86ce

So will close this! I assume just need to wait for a release?

**Comment by Lyokone** [comment]
Hi, yes I will publish the new version soon. Sorry for the trouble :)

**Comment by josh-gree** [comment]
@Lyokone Any way for me to work with master in the meantime? Tried;

```
  location:
    git:
      url: https://github.com/Lyokone/flutterlocation.git
```

But doesn't seem to work - I think cos of the multiple packages in the single repo?

**Comment by Lyokone** [comment]
Can this answers help you : https://stackoverflow.com/a/53760890

With packages/location

**Comment by josh-gree** [comment]
Yeah I thought of this but location pakages `pubspec.yml` points directly to the non master versions of the child packages and the code at question is in `location_platform_interface` I need the master version of that too - so not really sure how to deal with that...

**Comment by josh-gree** [comment]
@Lyokone  Sorry I am being a pain - don't worry about it will just make the change locally and wait for a release! Have a nice Sunday!

**Comment by Lyokone** [comment]
Should be fine now with latest version on pub.dev
