### ISSUE TITLE
How to solve the error ’location/LocationPlugin.h' file not found ?

### ISSUE THREAD

**Issue by akjesto** [Lyokone/flutterlocation#59]
I am new to the mobile app development using Flutter.This app mainly used for fetching location.
In my iOS simulator its working properly but cannot run the app in my iOS device.I always got the error like  _**’location/LocationPlugin.h' file not found**_ .This error happens when I tried to build app using **Xcode10.0 beta**. How to solve this issue?

**Comment by Lyokone** [comment]
I'll close this, dont hesitate to reopen if you still got the problem with new versions.
