### ISSUE TITLE
enableBackgroundMode(enable: false) is not working

### ISSUE THREAD

**Issue by Trteich** [Lyokone/flutterlocation#597]
After setting enableBackgroundMode(enable: false) app still receives location updates in onLocationChanged.listen during beeing in background. 

```
await _locationInstance.enableBackgroundMode(enable: false);
 await _locationInstance.changeSettings(accuracy: LocationAccuracy.navigation, distanceFilter: 30, interval: 3);

 _locationInstance.onLocationChanged.listen((result) {...}
```

**Library version:** 4.3.0

**Comment by nayefradwi** [comment]
the interval is in milliseconds, so probably 3 msec is too fast

**Comment by khamidjon** [comment]
mine is 8000 (which is 8 seconds) still can't stop receiving location.
