### ISSUE TITLE
Get oneshot updated location :)

### ISSUE THREAD

**Issue by Alexays** [Lyokone/flutterlocation#6]
Can you implement a way to get oneshot updated location, currently getLocation retrieves the last known location not an updated :/ and i don't want to use a listener.
thx :)

**Comment by reneky** [comment]
onLocationChanged is a Stream, so using single should work:

Future<Map<String, double>> location = new Location().onLocationChanged.single;

https://api.dartlang.org/stable/1.24.2/dart-async/Stream-class.html

**Comment by Alexays** [comment]
Yeah i know but it produce an error ;/

**Comment by Alexays** [comment]
My bad it's working now, a little build clean and it's work now :)

**Comment by Alexays** [comment]
`Failed to open event stream
E/EventChannel#lyokone/locationstream( 3337): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.requestLocationUpdates(com.google.android.gms.location.LocationRequest, com.google.android.gms.location.LocationCallback, android.os.Looper)' on a null object reference
E/EventChannel#lyokone/locationstream( 3337): 	at com.lyokone.location.LocationPlugin.onListen(LocationPlugin.java:190)
E/EventChannel#lyokone/locationstream( 3337): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:167)
E/EventChannel#lyokone/locationstream( 3337): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:155)
E/EventChannel#lyokone/locationstream( 3337): 	at io.flutter.view.FlutterView.handlePlatformMessage(FlutterView.java:678)
E/EventChannel#lyokone/locationstream( 3337): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#lyokone/locationstream( 3337): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/EventChannel#lyokone/locationstream( 3337): 	at android.os.Looper.loop(Looper.java:136)
E/EventChannel#lyokone/locationstream( 3337): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/EventChannel#lyokone/locationstream( 3337): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#lyokone/locationstream( 3337): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/EventChannel#lyokone/locationstream( 3337): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)`

**Comment by Lyokone** [comment]
I'm back from holidays, I'm going to look into it.

**Comment by Alexays** [comment]
Nice, i guess the error is caused by the fact that it is never closed
```The following PlatformException was thrown while activating platform stream on channel
I/flutter ( 3650): lyokone/locationstream:
I/flutter ( 3650): PlatformException(error, Stream already active, null)
I/flutter ( 3650): 
I/flutter ( 3650): When the exception was thrown, this was the stack:
Restarted app in 714ms.
I/flutter ( 3650): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
I/flutter ( 3650): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
I/flutter ( 3650): <asynchronous suspension>
I/flutter ( 3650): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:288:29)```

**Comment by Alexays** [comment]
@Lyokone So did you find anything why stream is never closed ?

**Comment by Lyokone** [comment]
@Alexays No I've tried several things but the result seem a little bit random ...

**Comment by tensafefrogs** [comment]
I also have a need for oneshot location - ideally I'd like lower accuracy as well, so a way to pass in the desired accuracy would be useful for me.

I came across this iOS code that checks the info.plist for permission keys present and only prompts for the permission used - could also be really useful in this plugin so we don't have to ask for unnecessary permissions if we only want location during app use.

https://github.com/icanzilb/OneShotLocationManager/blob/master/OneShotLocationManager.swift

Here's the relevant example:

`        //check for description key and ask permissions
        if (NSBundle.mainBundle().objectForInfoDictionaryKey("NSLocationWhenInUseUsageDescription") != nil) {
            locationManager!.requestWhenInUseAuthorization()
        } else if (NSBundle.mainBundle().objectForInfoDictionaryKey("NSLocationAlwaysUsageDescription") != nil) {
            locationManager!.requestAlwaysAuthorization()
        } else {
            fatalError("To use location in iOS8 you need to define either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in the app bundle's Info.plist file")
        }`
