### ISSUE TITLE
Moving out of JCenter/Bintray

### ISSUE THREAD

**Issue by duduBaiao** [Lyokone/flutterlocation#604]
Hi y'all,

Don't you plan to move out from JCenter/Bintray?

https://www.jfrog.com/confluence/display/JFROG/JFrog+Bintray+Migration+Guide

Today, I am unable to build my app because the "location" plugin (4.3.0) still relies on a dependency hosted on bintray.

```
[+20614 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:compileDevDebugJavaWithJavac'.
[        ] > Could not resolve all task dependencies for configuration ':app:devDebugCompileClasspath'.
[        ]    > Could not resolve com.google.android.gms:play-services-location:16.+.
[        ]      Required by:
[        ]          project :app > project :location
[        ]       > Failed to list versions for com.google.android.gms:play-services-location.
[        ]          > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
[        ]             > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
[        ]                > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 403 from server: Forbidden
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 23s
[ +439 ms] Exception: Gradle task assembleDevDebug failed with exit code 1
```

It was working fine until yesterday.

**Comment by datttran** [comment]
Hi, I had the same issue. Does anyone know any workaround on this? 
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 403 from server: Forbidden`

**Comment by duduBaiao** [comment]
@datttran Since we couldn't wait, the workaround was to use another plugin:

https://pub.dev/packages/geolocator

**Comment by willbryant** [comment]
https://stackoverflow.com/questions/66641552/could-not-resolve-com-google-android-gmsplay-services-location16

**Comment by dsgriffin** [comment]
still having this issue now
