### ISSUE TITLE
Is it working on Wear Os ?

### ISSUE THREAD

**Issue by weissloic** [Lyokone/flutterlocation#610]
I'm trying to use this package on my Wear OS, but I always get a message which indicate me "It's not implemented on this platform "

Someone has already use this one for this OS ?

**Comment by DanielMartini** [comment]
Same problem, did someone achieve it to make it work on a wear os device?

**Comment by talhazengin** [comment]
So, no updates?

**Comment by FrancescoZanella** [comment]
I have the same problem, getLocation throws [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(UNEXPECTED_ERROR, 10: Not implemented on this platform., null, null) on wearOs
