### ISSUE TITLE
Location not getting

### ISSUE THREAD

**Issue by usamanaeem9040** [Lyokone/flutterlocation#613]
solved

**Comment by misaelriojasftf** [comment]
same issue here

**Comment by misaelriojasftf** [comment]
for ios doesn't work

**Comment by TaiTrien** [comment]
Same issue on iOS

**Comment by VarmaTech** [comment]
java/io/flutter/plugins/GeneratedPluginRegistrant.java:29: error: cannot find symbol
     flutterEngine.getPlugins().add(new com.lyokone.location.LocationPlugin());
                                                           ^
    symbol:   class LocationPlugin
    location: package com.lyokone.location

**Comment by aliazimoshan** [comment]
I use 
``` location: 4.3.0```
doesn't work in ios.

**Comment by Zeehshan** [comment]
same issue on mine side, butt also not working in android

**Comment by cchamm** [comment]
Not working in Huawei P20.

**Comment by AbhideepChakravarty** [comment]
It is not working in deployed mode for web. While development everything seems working as expected. The moment I packaged and deployed the application and tried testing it, suddenly it is not able to fetch the location. What might be going wrong?

**Comment by SamoilovEA** [comment]
Hi guys. I managed to solve the problem.
What was the problem:
When the application was debugged, everything worked as expected. But if you create an .apk file and open it, then nothing happened. I also noticed that not all devices have this problem. For example, Android Emulators do not have this problem, so I was at a loss why my Google Play users complain that nothing works for them! :(

But I noticed that if you reload the `Class` that is responsible for this, then everything works! I have little experience with Flutter, but here's how I solved the problem: 

`class _MyAppState extends State<MyApp> {
  Location location = Location();
  LocationData? _locationData;
  bool? _serviceEnabled;
  @override
  void initState() {
    super.initState();
    timerLocationData();
  }

  timerLocationData() {
    Timer.periodic(
      Duration(seconds: 2),
      (timer) {
        vPermissionGranted();
        if (_locationData != null) {
          timer.cancel();
          setState(() {});
        }
      },
    );
  }

  void vPermissionGranted() async {
    PermissionStatus _permissionGranted;
    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled!) {
      _serviceEnabled = await location.requestService();
    }
    _permissionGranted = await location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {}
    }
    if (_locationData == null) {
      _locationData = await location.getLocation();
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: _locationData != null
          ? HomePage(locationData: _locationData!)
          : const Center(
              child: CircularProgressIndicator(),
            ),
    );
  }
}
`

As I said, I have little experience, so I hope there is an easier way to fix this.
