### ISSUE TITLE
NoSuchMethodError: method not found: 'gGs' (m.gGs is not a function)

### ISSUE THREAD

**Issue by AbhideepChakravarty** [Lyokone/flutterlocation#618]
**Describe the bug**
Once we do *flutter build web* and deploy the application (in my case to Firebase Hosting), while running the web application, the error comes on browser console saying : NoSuchMethodError: method not found: 'gGs' (m.gGs is not a function)

This happens when location.getLocation() is triggered. 

The error does not come when we are in the development mode i.e. writing the code and testing using VS Code. It only happens after doing a build and deploy.

**Expected behavior**
Location result should have come.

**Tested on:**
 - Edge and Chrome browser

**Comment by DasTobbel** [comment]
Having the same issue on my project.

Tested on firefox, chrome, safari
package version: 4.3.0

Used code like this
` 
   Location location = new Location();

    bool _serviceEnabled;
    PermissionStatus _permissionGranted;
    LocationData _locationData;

    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        return;
      }
    }

    _permissionGranted = await location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {
        return;
      }
    }

    _locationData = await location.getLocation();
`

flutter doctor:
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!

`

**Comment by jasonJamEther** [comment]
I am also having the same issue. I put print statements through my code and the error is being thrown when trying to run _locationData = await location.getLocation(); . It seems like this broke with the latest release of flutter and not a package update but I could be wrong.

**Comment by jasonJamEther** [comment]
I did a little digging and see this issue is also affecting other geo location packages. Sounds like it is fixed in the dev flutter branch. I see others saying if they run non null safety it works though i didn't want to adjust my code to test that.

**Comment by AbhideepChakravarty** [comment]
Current workable solution is building the web app without null safety.

flutter build web --no-sound-null-safety

This would work. But this just work around.
