### ISSUE TITLE
serviceEnabled() returns true on MacOS when system location service is disabled

### ISSUE THREAD

**Issue by MatthewPatience** [Lyokone/flutterlocation#624]
**Describe the bug**
When calling `location.serviceEnabled()` on MacOS (currently testing with Chrome), it returns true even if the system location service is disabled. Chrome does however display a message in the URL bar that location is disabled and gives the option to open System Preferences to enable it.

**Expected behavior**
`location.serviceEnabled()` should return false if the system location service is disabled.

**Tested on:**
 - MacOS 11.5.2, Chrome 92.0.4515.159 (Official Build) (x86_64)

**Other plugins:**
 I am using the Mapbox Flutter plugin, however it does not offer location capabilities for web, so I assume it should not be interfering.

**Additional logs**
Calling `location.onLocationChanged.listen` appears to log the following when system location service is disabled.

``` shell
null
Error: [object GeolocationPositionError]
 
 
     at Object.createErrorWithStack (http://localhost:56565/dart_sdk.js:5362:12)
     at Object._rethrow (http://localhost:56565/dart_sdk.js:39548:16)
     at async._AsyncCallbackEntry.new.callback (http://localhost:56565/dart_sdk.js:39542:13)
     at Object._microtaskLoop (http://localhost:56565/dart_sdk.js:39374:13)
     at _startMicrotaskLoop (http://localhost:56565/dart_sdk.js:39380:13)
     at http://localhost:56565/dart_sdk.js:34887:9
```

**Comment by vrman** [comment]
same problem with android , it return always true
