### ISSUE TITLE
onLocationChanged interval less to 1000ms

### ISSUE THREAD

**Issue by albanodev** [Lyokone/flutterlocation#626]
Hi, i develop a geolation app and i need refresh speed less to 1000ms, is posible?
i used this config in changeSettings
`await location.changeSettings(accuracy: LocationAccuracy.high, interval: 1, distanceFilter: 0.1);`
but refresh every 1000ms aprox.
I tested in iPhone 6s and Xiaomi MIA3.

Thanks!

**Comment by phantuanphong** [comment]
Hi guy,
 On android limit refresh rate of location service is 5000ms. You can not increase refresh rate to 1000ms

**Comment by albanogamesdev** [comment]
i don't thing so, look this data:
```json 
{
 "latitude": -31.402519303063578,
 "longitude": -58.016828795906065,
 "time_stamp": 1630615973303
},{
   "latitude": -31.402333984123548,
   "longitude": -58.01683939711569,
   "time_stamp": 1630615974325
}
```
1630615974325-1630615973303=1022
1022ms between timestamp
