### ISSUE TITLE
 Attempt to write to field 'e.a.c.a.j$d com.lyokone.location.f.p' on a null object reference

### ISSUE THREAD

**Issue by Do-Repo** [Lyokone/flutterlocation#628]
**Describe the bug**
 This was not the case 30 min ago, and now happens on all my apps that use location even those which have not been edited for days
Note that the apps work fine in debug mode

I/flutter ( 2918): PlatformException(error, Attempt to write to field 'e.a.c.a.j$d com.lyokone.location.f.p' on a null object reference, null, java.lang.NullPointerException: Attempt to write to field 'e.a.c.a.j$d com.lyokone.location.f.p' on a null object reference
I/flutter ( 2918):      at com.lyokone.location.h.f(Unknown Source:2)
I/flutter ( 2918):      at com.lyokone.location.h.a(Unknown Source:149)
I/flutter ( 2918):      at e.a.c.a.j$a.a(Unknown Source:17)
I/flutter ( 2918):      at io.flutter.embedding.engine.e.b.d(Unknown Source:57)
I/flutter ( 2918):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
I/flutter ( 2918):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 2918):      at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter ( 2918):      at android.os.Looper.loop(Looper.java:183)
I/flutter ( 2918):      at android.app.ActivityThread.main(ActivityThread.java:7592)
I/flutter ( 2918):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 2918):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
I/flutter ( 2918):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Expected behavior**

**Tested on:**
 - Android, API Level 28  real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by maxamin** [comment]
hello can you provide additional information like what packages you are including i or a piece of code that you are working on. the error says  it is a null pointer exception Null pointer occurs if you access any method/variable of a class without initializing
you can read more about null pointers
https://en.wikipedia.org/wiki/Null_pointer
its pretty hard to determine  what actually is going on from just what you provided. thanks
