### ISSUE TITLE
requestService() error at Android 11

### ISSUE THREAD

**Issue by alfaruqrizqi18** [Lyokone/flutterlocation#632]
I've got error like this when I try to request service on Android 11

E/MethodChannel#lyokone/location(10394): Failed to handle method call
E/MethodChannel#lyokone/location(10394): android.content.ActivityNotFoundException
E/MethodChannel#lyokone/location(10394): 	at com.lyokone.location.FlutterLocation.requestService(FlutterLocation.java:375)
E/MethodChannel#lyokone/location(10394): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:55)
E/MethodChannel#lyokone/location(10394): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#lyokone/location(10394): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#lyokone/location(10394): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#lyokone/location(10394): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#lyokone/location(10394): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#lyokone/location(10394): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#lyokone/location(10394): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E/MethodChannel#lyokone/location(10394): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#lyokone/location(10394): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/MethodChannel#lyokone/location(10394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/DartMessenger(10394): Uncaught exception in binary message listener
E/DartMessenger(10394): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(10394): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/DartMessenger(10394): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253)
E/DartMessenger(10394): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(10394): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/DartMessenger(10394): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(10394): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/DartMessenger(10394): 	at android.os.Looper.loop(Looper.java:193)
E/DartMessenger(10394): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
E/DartMessenger(10394): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(10394): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/DartMessenger(10394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (10394): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(MISSING_ACTIVITY, You should not requestService activation outside of an activity., null, null)

**Comment by nirajjoshi** [comment]
We are also facing this issue.

**Comment by lailai0715** [comment]
> I've got error like this when I try to request service on Android 11
> 
> E/MethodChannel#lyokone/location(10394): Failed to handle method call E/MethodChannel#lyokone/location(10394): android.content.ActivityNotFoundException E/MethodChannel#lyokone/location(10394): at com.lyokone.location.FlutterLocation.requestService(FlutterLocation.java:375) E/MethodChannel#lyokone/location(10394): at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:55) E/MethodChannel#lyokone/location(10394): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233) E/MethodChannel#lyokone/location(10394): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85) E/MethodChannel#lyokone/location(10394): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818) E/MethodChannel#lyokone/location(10394): at android.os.MessageQueue.nativePollOnce(Native Method) E/MethodChannel#lyokone/location(10394): at android.os.MessageQueue.next(MessageQueue.java:335) E/MethodChannel#lyokone/location(10394): at android.os.Looper.loop(Looper.java:193) E/MethodChannel#lyokone/location(10394): at android.app.ActivityThread.main(ActivityThread.java:7889) E/MethodChannel#lyokone/location(10394): at java.lang.reflect.Method.invoke(Native Method) E/MethodChannel#lyokone/location(10394): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600) E/MethodChannel#lyokone/location(10394): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) E/DartMessenger(10394): Uncaught exception in binary message listener E/DartMessenger(10394): java.lang.IllegalStateException: Reply already submitted E/DartMessenger(10394): at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155) E/DartMessenger(10394): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253) E/DartMessenger(10394): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85) E/DartMessenger(10394): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818) E/DartMessenger(10394): at android.os.MessageQueue.nativePollOnce(Native Method) E/DartMessenger(10394): at android.os.MessageQueue.next(MessageQueue.java:335) E/DartMessenger(10394): at android.os.Looper.loop(Looper.java:193) E/DartMessenger(10394): at android.app.ActivityThread.main(ActivityThread.java:7889) E/DartMessenger(10394): at java.lang.reflect.Method.invoke(Native Method) E/DartMessenger(10394): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600) E/DartMessenger(10394): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) E/flutter (10394): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(MISSING_ACTIVITY, You should not requestService activation outside of an activity., null, null)

May I know which model of real device that you're using?

**Comment by alfaruqrizqi18** [comment]
> May I know which model of real device that you're using?

I'm using Poco X3

**Comment by shahpasandar** [comment]
This is a serious issue and it's been reporting several times but all of them are closed by the bot!
