### ISSUE TITLE
await location.getLocation() working slow on Android real devices

### ISSUE THREAD

**Issue by behlsoft** [Lyokone/flutterlocation#636]
_locationData = await location.getLocation(); 
Taking 1.4 second in android and blocking UI too and 100ms on iphone(perfect)

**Tested on:**
 - 2 Android 11 real devices (Samsung and oneplus 9)
 - iOS, Version 14  real device

I need to print lat long on every photo user capture .. i dont know why its taking that much time.. please suggest

**Comment by Shahmirzali-Huseynov** [comment]
taking 5,6 seconds on my real android device. can you resolve this problem?

**Comment by wahyu-handayani** [comment]
@behlsoft and @Shahmirzali-Huseynov I got the same case like yours guys. did you find any solution ?

**Comment by achalkias** [comment]
I can confirm its still slow
Version: location: ^4.4.0
Device Model: Samsung SM-G925F
Android: 7.0
