### ISSUE TITLE
Stop the background mode when user signout of the application

### ISSUE THREAD

**Issue by Lyba97** [Lyokone/flutterlocation#646]
Hi, I have a feature required in my application to stop working the background location when the user sign out. I am doing this when the signout button is pressed but it does not work and the service can still be seen in the notification bar

stopBackgroundtask(){
    location.enableBackgroundMode(enable: false);
    location.isBackgroundModeEnabled().then((value) => print("ON VALUE "
        "$value"));
  }

**Comment by cesarcamps** [comment]
hi!!!! I am in the same situation :(, somebody could help us??

**Comment by hardikamal** [comment]
@Lyba97 @cesarcamps @Lyokone Any solution to this?

**Comment by Lyba97** [comment]
> @Lyba97 @cesarcamps @Lyokone Any solution to this?

No, I didn't find any till now.
