### ISSUE TITLE
Android 11 Enable background Mode exception

### ISSUE THREAD

**Issue by Sachinsowri** [Lyokone/flutterlocation#650]
i am using location :^4.3.0
And Oneplus 7T (Android 11) sdk 30
when i enable backgroud mode it always throw "Background location permission denied forever - please open app settings" even if i give Allow all time permission..

**Comment by chentianxin** [comment]
> i am using location :^4.3.0 And Oneplus 7T (Android 11) sdk 30 when i enable backgroud mode it always throw "Background location permission denied forever - please open app settings" even if i give Allow all time permission..

+1
Oneplus 7Pro(Android 11)

**Comment by jsanz1209** [comment]
+1
Xioami Redmi Note Pro (Android 11)
if I always allow it in the app permissions, it does work.

**Comment by AhmedLSayed9** [comment]
Still no fix on this?
