### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by n0tc0ding** [Lyokone/flutterlocation#653]

**Comment by zerox1212** [comment]
Does not seem very active. I'm looking at changing to flutter geolocator.

**Comment by n0tc0ding** [comment]
Maybe something happened to @Lyokone. I find this package better and faster than geolocator but it has not new updates for newer android versions

**Comment by Wackymax** [comment]
@Lyokone is still active on other repo's. Not sure if this repo was handed over to someone else maybe?
