### ISSUE TITLE
Can not get current location with Flutter Web App  on Safari

### ISSUE THREAD

**Issue by Limvunhoy** [Lyokone/flutterlocation#659]
**Describe the bug**
I uploaded my application to a web server, I can get the location using the Google Chrome browser on pc, but when I use Safari on a phone, it doesn't work and just charges.

**Expected behavior**
It should show permission request dialog like running on Flutter App.

**Tested on:**
 - iOS, Version 15.1, real device

**Additional logs**

<img width="784" alt="Screen Shot 2021-11-12 at 11 01 39 AM" src="https://user-images.githubusercontent.com/39089099/141418566-914a2df2-87cf-46a7-ae9f-e65e280ecd2a.png">
``` shell
some logs
```

**Comment by MohamedYousof** [comment]
same on ios 15.3 with chrome and safari
