### ISSUE TITLE
getLocation is very unreliable.

### ISSUE THREAD

**Issue by jiachen247** [Lyokone/flutterlocation#66]
When location is turned on and app is open, getLocation sucessfully gets the location.

However, if i decide to turn off my location and then back on again while in the app, the getLocation never works again until i fully restart the app.

Is this an issue with the library.
Please advise.

**Comment by jiachen247** [comment]
can i ask if this is a lib problem or a flutter one?

I dont remember having such problems when writing native andriod in java/kotlin

**Comment by jiachen247** [comment]
hi everyone, i switch over to this package instead. From testing on andriod it seems to be alot more stable as compared to this one.

https://pub.dartlang.org/documentation/geolocation/latest/

**Comment by timtraversy** [comment]
That library is now incompatible with Dart 2.

**Comment by dadmad817** [comment]
yes this library is not compatible so what is the solution???

**Comment by timtraversy** [comment]
This is probably something the core flutter team will eventually build as a package. They already have this one: https://github.com/flutter/plugins/tree/master/packages/location_background.

That only supports iOS currently but probably will eventually support Android

**Comment by Lyokone** [comment]
Hey ! It should be more reliable with version 2.1, please check it out.
