### ISSUE TITLE
location moves without me doing anything

### ISSUE THREAD

**Issue by nyck33** [Lyokone/flutterlocation#670]
![image](https://user-images.githubusercontent.com/25189545/145336629-00d71b24-328a-4067-b28d-991d5fd5900f.png)

I haven't moved at all but sometimes it goes even farther than that maybe 1 km or more.  And it changes every 10 seconds or so.

**Comment by nyck33** [comment]
That was on my crappy Alcatel 1B but on my older but better LG K-210 it takes forever to get that initial position.  But the location does not move around.  Thus am I right in assuming it's a device issue?  If I have a newer good phone then this package works no problem?

**Comment by Lyokone** [comment]
Hi, 
During initial lock of position the location will move, especially if you're inside.
On newer devices with better hardware, the location is picked up faster.
