### ISSUE TITLE
Getting permission denied forever when user selects approximate location in API 31

### ISSUE THREAD

**Issue by RodXander** [Lyokone/flutterlocation#672]
**Describe the bug**
When requesting the location permission if the user selects the approximate location it always returns denied forever.
Notably when the precise location is selected the plugin works as expected.

**Expected behavior**
It should return the correct selection of the user.

**Tested on:**
 - Android, API Level 31, emulator ARM64 V8a in MAC M1

**Comment by marslannasr7koncepts** [comment]
Same issue facing as well!

Please Update it if it fixed!

**Comment by readyiman** [comment]
Also are there option so user can only choose precise location?
