### ISSUE TITLE
how i get current location every 1 min  and how i can stop this Service   

### ISSUE THREAD

**Issue by osama450** [Lyokone/flutterlocation#679]
how i get current location every 1 min  and how i can stop this Service

**Comment by canibal1** [comment]
> how i get current location every 1 min and how i can stop this Service

  getLocation() async {
    bool _serviceEnabled;
    PermissionStatus _permissionGranted;
    LocationData _locationData;

    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        return;
      }
    }

    _permissionGranted = await location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {
        return;
      }
    }

    _locationData = await location.getLocation();

    Map<String, double?> personLocation = {
      "longitude": _locationData.longitude,
      "latitude": _locationData.latitude,
    };
    return personLocation;
  }


  @override
  void onInit() {
    super.onInit();
    timer = Timer.periodic(Duration(minutes:1), (Timer t) => getLocation());
 }

This is a timer. 
And this code just run one time and it will be closed` _locationData = await location.getLocation();` 
You can customize getLocation() method.
Good Luck.
