### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method serviceEnabled on channel lyokone/location)

### ISSUE THREAD

**Issue by Limvunhoy** [Lyokone/flutterlocation#680]
**Describe the bug**
I got this error when adding Flutter into existing iOS App (build iOS-framework)

**Expected behavior**
- I wanted to get current location from Flutter App in iOS project 

**Tested on:**
 - iOS, Version 13.0, 15.2, simulator

**Comment by schehata** [comment]
I am having the same issue on android,  how did you solve it?

**Comment by lakhanpal-mohit** [comment]
Same Issue on Android, any luck?
