### ISSUE TITLE
onLocationChanged StreamSubscription.cancel() not stopping currentLocation service

### ISSUE THREAD

**Issue by HugoHeneault** [Lyokone/flutterlocation#685]
**Describe the bug**

Here's my code:
```dart
locationChangesListener =
        location.onLocationChanged.listen((LocationData currentLocation) {
      state = LocationState.locationAvailable(currentLocation);
    });
```

Then I later call in my provider:

```
await locationChangesListener?.cancel();
```

I keep getting logs
```
currentLocation is <+45.xxx,+5.xxx> +/- 92.58m (speed 0.00 mps / course -1.00) @ 14/01/2022 08:25:19 Central European Standard Time
```

and my `listen` callback keeps getting called.

There are multiple issues (#205, #379,  #567) documenting this behavior, none of them has solution, all of them have been closed for inactivity. 

**Expected behavior**
Calling `StreamSubscription.cancel()` should stop the location service and updates.

**Tested on:**
 - iOS, Version 14.8.1, iPhone 11 Pro

**Other plugins:**
 - [flutter_map](https://pub.dev/packages/flutter_map)
 - [flutter_compass](https://pub.dev/packages/flutter_compass)

**Comment by kaff-oregonstate** [comment]
@HugoHeneault I was having this same issue. The culprit for me turned out to be that I was calling "drain()" on the stream before subscribing to it, in an attempt to eliminate stale data from previous location tracking. I believe this created a second subscription. Not sure if you've done anything similar, but hopefully if so this will help.

**Comment by kaff-oregonstate** [comment]
I also switched to the comparable package "geolocator" before discovering the bug I had created. If I find time to switch back to this package I will comment and confirm that my bug was the sole source of this issue in my project.
