### ISSUE TITLE
Crash on bluiding in android api 27

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [Lyokone/flutterlocation#69]
When i run it it gives me this error, yesterday was fine!

> Could not resolve com.google.android.gms:play-services-location:15.+.
  Required by:
      project :app > project :location
   > Could not resolve com.google.android.gms:play-services-location:15.+.
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > dl.google.com: nodename nor servname provided, or not known

**Comment by Lyokone** [comment]
I'll close this since installation process have been changed with 2.X update to AndroidX.
