### ISSUE TITLE
deprecated API.

### ISSUE THREAD

**Issue by patthipati** [Lyokone/flutterlocation#694]
**Describe the bug**

Getting some deprecated API errors in FlutterLocation.java]()  

**Expected behavior**
 should not use any deprecated API
 
 
``` shell
flutter\.pub-cache\hosted\pub.dartlang.org\location-4.3.0\android\src\main\java\com\lyokone\location\FlutterLocation.java uses or overrides a deprecated API.
```

**Comment by ItsYasser** [comment]
same issue , they should fix this soon
