### ISSUE TITLE
how can i stop or kill onLocationChanged listener ?

### ISSUE THREAD

**Issue by monikkacha** [Lyokone/flutterlocation#709]
Hey man , 

you have developed really good plugin and like to use it on my projects . 

the one thing which noticed very recently is that how can i stop the onLocationChanged listener , the thing is that i need to collect data for the movement for the particular time , let's say 15 mins , after than it is required to stop getting location of the user as it is not necessary for the application to have the data of the user location . 

Scenario : 
in the app , i have two button , one for starting the tracking of the location , other is to stop the location tracking .

able to start location tracking but how to stop it , one way to stop is to set null the object of the location but need the same object in few minutes and reassigning is not good choice . 

please let me know , if there is any such a feature available or hidden behind the hood , read the docs and codes as well but didn't find a way to overcome the scenario . 

Thanks , Have a nice day .

**Comment by jabguru** [comment]
What you can do is save the listener in a variable.

```
StreamSubscription<LocationData>? locationSubscription = _location.onLocationChanged
        .listen((location.LocationData currentLocation) {
      Map _data = {
        'latitude': currentLocation.latitude,
        'longitude': currentLocation.longitude,
      };
      }
    });
```
    
 Then if you want to kill it:
` locationSubscription?.cancel()`


@monikkacha

**Comment by birimkulov951** [comment]
> What you can do is save the listener in a variable.
> 
> ```
> StreamSubscription<LocationData>? locationSubscription = _location.onLocationChanged
>         .listen((location.LocationData currentLocation) {
>       Map _data = {
>         'latitude': currentLocation.latitude,
>         'longitude': currentLocation.longitude,
>       };
>       }
>     });
> ```
> 
> Then if you want to kill it: ` locationSubscription?.cancel()`
> 
> @monikkacha

Thank you!

**Comment by monikkacha** [comment]
Thanks for the help

**Comment by AyeshaIftikhar** [comment]
> What you can do is save the listener in a variable.
> 
> ```
> StreamSubscription<LocationData>? locationSubscription = _location.onLocationChanged
>         .listen((location.LocationData currentLocation) {
>       Map _data = {
>         'latitude': currentLocation.latitude,
>         'longitude': currentLocation.longitude,
>       };
>       }
>     });
> ```
> 
> Then if you want to kill it: ` locationSubscription?.cancel()`
> 
> @monikkacha

Does not work in my case. location.onLocationChanged did not get removed from the memory and keep fetching data and causing memory leak.

**Comment by jabguru** [comment]
> 

Might be how you're handling it.
What happens when you call cancel()? Does it throw an error?
Can you share a snippet?
