### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by giorgio79** [Lyokone/flutterlocation#715]
Issues seem to be piling up

**Comment by RobertoGab** [comment]
Uhm, I had troubles using latest version of plugin too, but found 4.2.3 to be quite stable.
What problem are you encountering ?
Also, do you know if the author accepts merge requests ? I should be quite easy to fix the issues on this plugin (at least Android wise, I know nothing about iOS)

**Comment by kevincherryholme** [comment]
This is the only plugin that I've implemented to successfully gets location data even when the app is minimized or the phone is locked. No other plugin continues listening to the location updates. I really hope this plugin is maintained!

**Comment by RobertoGab** [comment]
> This is the only plugin that I've implemented to successfully gets location data even when the app is minimized or the phone is locked. No other plugin continues listening to the location updates. I really hope this plugin is maintained!

If not maintained you could fork the project, so you can maintain it by yourself and with other's help

**Comment by bartekpacia** [comment]
It is not!

See https://github.com/Lyokone/flutterlocation/issues/812#issuecomment-1627538323 :)
