### ISSUE TITLE
Compile error around onRequestPermissionsResult

### ISSUE THREAD

**Issue by andy130342** [Lyokone/flutterlocation#717]
Hi,
I am gettign the following compile error 
e: C:\Users\xxx\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.3.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt: (124, 1): Class 'FlutterLocationService' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: C:\Users\xxx\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.3.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt: (258, 5): 'onRequestPermissionsResult' overrides nothing

This error and a possible fix is described in: https://stackoverflow.com/questions/71936711/andorid-studio-lass-flutterlocationservice-is-not-abstract-and-does-not-implem

Regards
Andy

**Comment by RobertoGab** [comment]
Can you even run 4.3.0 ? When I used it I found out the FlutterLocation java class is completely commented out, so not usable at all. Had to switch to 4.2.3.

**Comment by fatalcaron** [comment]
It's fixed in the version 4.4.0
