### ISSUE TITLE
[4.4.0] FlutterLocation.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by alexrosabr** [Lyokone/flutterlocation#726]
**Describe the bug**
location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocation.java uses or overrides a deprecated API.

**Expected behavior**
The package shoud NOT use deprecated APIs.

**Tested on:**
 - Android, API Level 31, real device

**Additional logs**

``` shell
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/XXX/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocation.java uses or overrides a deprecated API.
```

**Comment by Samrat555** [comment]
Same issue faced tested on API level 31 real device

`Note: /Users/xxx/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
`

**Comment by kenaitian** [comment]
Same here:

Note: /Users/ken/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by arifikhsan** [comment]
any update?

**Comment by Lyokone** [comment]
Hello :) 
Yes please use Location 5 :)

**Comment by arifikhsan** [comment]
> Hello :) Yes please use Location 5 :)

did you mean version 5? when will it be released?

**Comment by marcoabat** [comment]
Any fix for this? It's been a year and there still doesn't seem to be a fix for this.

**Comment by Brikas** [comment]
Hi, this issue is persisting on version 5 as well. I have been trying this with multiple Kotlin versions. It still persists.
