### ISSUE TITLE
pubspec.yaml explicit environment required

### ISSUE THREAD

**Issue by jobel-code** [Lyokone/flutterlocation#73]
Hej,
It would be good if you can add the environment range of the plugin in the pubspec.yaml

```
environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
```
This would avoid the following error when working with the flutter master channel.

```

The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7.

Because myapp depends on location >=1.0.1 which requires SDK version <2.0.0, version solving failed.

```

**Comment by Lyokone** [comment]
Hey !

I've pushed this change as of version 1.4.1 ;)
Thanks for your help
