### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by GhazarArm** [Lyokone/flutterlocation#731]
**Describe the bug**
Can not build after flutter upgrade

e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (19, 11): Conflicting declarations: public const val kDefaultChannelName: String, public const val kDefaultChannelName: String
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (20, 11): Conflicting declarations: public const val kDefaultNotificationTitle: String, public const val kDefaultNotificationTitle: String
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (21, 11): Conflicting declarations: public const val kDefaultNotificationIconName: String, public const val kDefaultNotificationIconName: String
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (23, 12): Redeclaration: NotificationOptions
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (24, 35): Overload resolution ambiguity: 
public const val kDefaultChannelName: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultChannelName: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (25, 29): Overload resolution ambiguity: 
public const val kDefaultNotificationTitle: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultNotificationTitle: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (26, 32): Overload resolution ambiguity: 
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (33, 7): Redeclaration: BackgroundNotification
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (82, 48): Overload resolution ambiguity: 
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (124, 7): Redeclaration: FlutterLocationService
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (19, 11): Conflicting declarations: public const val kDefaultChannelName: String, public const val kDefaultChannelName: String
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (20, 11): Conflicting declarations: public const val kDefaultNotificationTitle: String, public const val kDefaultNotificationTitle: String
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (21, 11): Conflicting declarations: public const val kDefaultNotificationIconName: String, public const val kDefaultNotificationIconName: String
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (23, 12): Redeclaration: NotificationOptions
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (24, 35): Overload resolution ambiguity: 
public const val kDefaultChannelName: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultChannelName: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (25, 29): Overload resolution ambiguity: 
public const val kDefaultNotificationTitle: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultNotificationTitle: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (26, 32): Overload resolution ambiguity: 
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (33, 7): Redeclaration: BackgroundNotification
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (82, 48): Overload resolution ambiguity: 
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
public const val kDefaultNotificationIconName: String defined in com.lyokone.location in file FlutterLocationService.kt
e: /Users/gtk/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (124, 7): Redeclaration: FlutterLocationService

**Comment by Hannan404** [comment]
@GhazarArm Yup, same this issue here... Please share solution if you got anyone. Thanks

**Comment by bartekpacia** [comment]
Not reproducible.
