### ISSUE TITLE
Support wearOS(samsung galaxy watch) and watchOS(apple watch)?

### ISSUE THREAD

**Issue by DDS-VangTA** [Lyokone/flutterlocation#732]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe workarounds you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: do you know any Android of iOS sample code that could be used to develop this feature ?

**Comment by masus04** [comment]
Any updates on this?

I am developing a wearOS app which relies on speed data and so far was unable to find a package that implements this functionality. Are there any plans to support watch platforms in the future?

Do you know of any other packages that do support it?

**Comment by xunreal75** [comment]
Watch is not part of Flutter.

You have to implement channels to communicate between Flutter and Native (Swift ...) Watch code

**Comment by masus04** [comment]
WearOS is quite well supported otherwise and mostly runs like any other android app, so I don't think there's a huge difference, except that some device specific APIs require separate plugin support.

**Comment by masus04** [comment]
Is there any interest in adding wearOS support? I might give it a try if anyone can help me to find out how to do it.

**Comment by talhazengin** [comment]
So, no updates?
