### ISSUE TITLE
Some Java api is  deprecated API Please updated

### ISSUE THREAD

**Issue by krButani** [Lyokone/flutterlocation#737]
Note: G:\AAAInstallation\src\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.4.0\android\src\main\java\com\lyokone\location\FlutterLocation.java uses or overrides a deprecated API

**Comment by EBBozkurt** [comment]
Same here : 

Note: D:\src\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.4.0\android\src\main\java\com\lyokone\location\FlutterLocation.java uses or overrides a deprecated API.

**Comment by kenaitian** [comment]
Same here:

Note: /Users/ken/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/android/src/main/java/com/lyokone/location/FlutterLocation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by arifikhsan** [comment]
same too

**Comment by matt-in-brissy** [comment]
Yep, getting the same deprecated API error.... is this going to get fixed?
