### ISSUE TITLE
PlatformException(UNEXPECTED_ERROR, 17:Error resolution was canceled by the user)

### ISSUE THREAD

**Issue by vineetpandit90** [Lyokone/flutterlocation#743]
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(UNEXPECTED_ERROR, 17: Error resolution was canceled by the user, original error message: CANCELED: null, null, null). Error thrown null.

**Comment by xunreal75** [comment]
What did you do? It looks like a normal exception when user press cancel. Your report is not useful.

**Comment by bartekpacia** [comment]
Not reproducible.
