### ISSUE TITLE
Caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by vineetpandit90** [Lyokone/flutterlocation#744]
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.h()' on a null object reference
com.lyokone.location.LocationPlugin.dispose (LocationPlugin.java:117)
com.lyokone.location.LocationPlugin.detachActivity (LocationPlugin.java:56)
com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges (LocationPlugin.java:74)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivityForConfigChanges (FlutterEngineConnectionRegistry.java:372)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:651)
io.flutter.embedding.android.FlutterFragment.onDetach (FlutterFragment.java:844)
androidx.fragment.app.Fragment.performDetach (Fragment.java:3229)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by xunreal75** [comment]
What did you do.

Please close this issue and use template to report problems.

**Comment by matejhocevar** [comment]
Hey!

I got similar problem like you described. I managed to solve it putting additional permissions to `AndroidManifest.xml` file:

```
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
```

More about how to properly setup Android platform is available in the docs: https://docs.page/Lyokone/flutterlocation/installation/android#background-location

**Comment by zmeid** [comment]
@matejhocevar Unfortunately, adding those permission does not fix the issue.

**Comment by bartekpacia** [comment]
Please follow the bug report template if you want to get any help.
