### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by balkrishanyadav** [Lyokone/flutterlocation#746]
My App is getting crash when i start location track. and log s showing me like this while i have already added below permissions.
uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    uses-permission android:name="android.permission.READ_PHONE_STATE" />
    uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    uses-permission android:name="android.permission.WAKE_LOCK"/>
       uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

Runtime( 7285): Shutting down VM
E/AndroidRuntime( 7285): FATAL EXCEPTION: main
E/AndroidRuntime( 7285): Process: com.example.locationexample, PID: 7285
E/AndroidRuntime( 7285): java.lang.SecurityException: Neither user 10146 nor current process has android.permission.ACCESS_FINE_LOCATION.
E/AndroidRuntime( 7285): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
E/AndroidRuntime( 7285): 	at android.os.Parcel.createException(Parcel.java:2409)
E/AndroidRuntime( 7285): 	at android.os.Parcel.readException(Parcel.java:2392)
E/AndroidRuntime( 7285): 	at android.os.Parcel.readException(Parcel.java:2334)
E/AndroidRuntime( 7285): 	at android.location.ILocationManager$Stub$Proxy.registerGnssNmeaCallback(ILocationManager.java:1921)
E/AndroidRuntime( 7285): 	at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:3012)
E/AndroidRuntime( 7285): 	at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:3002)
E/AndroidRuntime( 7285): 	at com.android.internal.listeners.ListenerTransportManager.addListener(ListenerTransportManager.java:70)
E/AndroidRuntime( 7285): 	at android.location.LocationManager.addNmeaListener(LocationManager.java:2522)
E/AndroidRuntime( 7285): 	at android.location.LocationManager.addNmeaListener(LocationManager.java:2503)
E/AndroidRuntime( 7285): 	at com.lyokone.location.FlutterLocation.lambda$startRequestingLocation$2$com-lyokone-location-FlutterLocation(FlutterLocation.java:425)
E/AndroidRuntime( 7285): 	at com.lyokone.location.FlutterLocation$$ExternalSyntheticLambda3.onSuccess(Unknown Source:4)
E/AndroidRuntime( 7285): 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
E/AndroidRuntime( 7285): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 7285): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7285): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 7285): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7285): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 7285): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7285): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7285): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime( 7285): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 7285): 	at android.app.ContextImpl.enforce(ContextImpl.java:2178)
E/AndroidRuntime( 7285): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2206)
E/AndroidRuntime( 7285): 	at com.android.server.location.gnss.GnssManagerService.registerGnssNmeaCallback(GnssManagerService.java:177)
E/AndroidRuntime( 7285): 	at com.android.server.location.LocationManagerService.registerGnssNmeaCallback(LocationManagerService.java:1018)
E/AndroidRuntime( 7285): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:854)
E/AndroidRuntime( 7285):
I/Process ( 7285): Sending signal. PID: 7285 SIG: 9
Lost connection to device.

Thanks

**Comment by bartekpacia** [comment]
This issue doesn't follow a bug report template.
