### ISSUE TITLE
fix: On flutter web in IOS browsers not working any thing 

### ISSUE THREAD

**Issue by mohamadkenway** [Lyokone/flutterlocation#752]
On flutter web in IOS browsers not working any thing even 5.0.0-dev.8 version

**Comment by fredells** [comment]
Seeing the same

**Comment by MarcBritton** [comment]
I saw the same bug, got an Unreachable exception when trying to use Location on the Web, with iOS / Safari as the cilent web browser.

We switched to the Geolocator package for this reason, which seems to be more actively maintained and does work in iOS/Safari web.

**Comment by ribeiro-gabriel** [comment]
Still not working on iOS 16.3.1 with Safari... It worked on Chrome browser but I will try Geolocator

**Comment by mohamadkenway** [comment]
> Still not working on iOS 16.3.1 with Safari... It worked on Chrome browser but I will try Geolocator

Let me know after using Geolocator

**Comment by bartekpacia** [comment]
Hi, please use the "normal", [latest v5 version](https://pub.dev/packages/location). It doesn't include changes from the old `v5.0.0-dev*` versions (see also #870).

If you encounter problems with `location_web`, please create new issues.
