### ISSUE TITLE
fix: Build error on prerelease

### ISSUE THREAD

**Issue by mateoKutnjak** [Lyokone/flutterlocation#757]
(...)/location_android-5.0.0-dev.3/android/src/main/kotlin/com/lyokone/location/LocationPlugin.kt: (153, 47): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?

**Comment by vrman** [comment]
same here , flutter 3

**Comment by vrman** [comment]
fixed this by update build.gradle to :
classpath 'com.android.tools.build:gradle:7.2.0'

and gradle-wrapper.properties to :
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip

**Comment by bartekpacia** [comment]
Hi, please use the "normal", [latest v5 version](https://pub.dev/packages/location). It doesn't include changes from the old `v5.0.0-dev*` versions.

See also: #870.
