### ISSUE TITLE
fix: No exception when you disable location on mobile , 5.0.0-dev.8

### ISSUE THREAD

**Issue by vrman** [Lyokone/flutterlocation#758]
disable location in your mobile , getLocation show message , " For a better exprerience, turn on device location, which uses Google`s location service. "
and if you click on " No Thanks " nothing happened , no exception no result ... nothing , and app stay in that position if you put await on function.

Tested in 5.0.0-dev.8

**Comment by bartekpacia** [comment]
Please use the "normal", [latest v5 version](https://pub.dev/packages/location).

See also: #870.
