### ISSUE TITLE
Speed is always 0. Also what are the units of speed?

### ISSUE THREAD

**Issue by sahilnsit10** [Lyokone/flutterlocation#76]

**Comment by timtraversy** [comment]
Speed is in meters per second, since this is what is what [CLLocation natively returns.](https://developer.apple.com/documentation/corelocation/cllocation/1423798-speed) Have you actually tried running or driving while fetching location to test the speed?

**Comment by Lyokone** [comment]
Hey, if you're using an Emulator be sure that the given position are close enough from each others :)
