### ISSUE TITLE
Heading

### ISSUE THREAD

**Issue by baruka99** [Lyokone/flutterlocation#763]
In the package documentation the object heading exist but well want to use it in my project I see that the object does not exist in the package... 

I don't know if there was a update! if so can you please tell me how to fix this?

bellow there is a screenshot of my code
![Screenshot 2022-09-17 025404](https://user-images.githubusercontent.com/60386009/190834248-61cc0f28-6a7a-4c88-b43e-2dafa8646aef.png)

**Comment by xunreal75** [comment]
Hi

which version are you using?

in  location (^4.4.0) is (LocationData).heading as double? working.


this is my listener:
....
`_locationSubscription =
        location.onLocationChanged.listen((LocationData loc) {
      _controller.add(loc); //movecontroller for flutterMap as StreamController<LocationData>.broadcast();
      sendLocation(loc);
    });`
....


`void sendLocation(LocationData location) async {
                   var head = location.heading;
                   if (location.latitude == null || location.longitude == null) return;
....
}
`

Please check that your location is Typeof LocationData.

**Comment by baruka99** [comment]
I fixed it, it was because I upgraded the version... 

I used LocationData to get the heading

Thank you
