### ISSUE TITLE
Request permission but and forces the app to close.

### ISSUE THREAD

**Issue by rupert2133** [Lyokone/flutterlocation#77]
Hi, I have this error encountered when I open the app then it will ask me to enable my gps after enbling the gps the app forces to close. Here is the error..

`
D/AndroidRuntime(11958): Shutting down VM
E/AndroidRuntime(11958): FATAL EXCEPTION: main
E/AndroidRuntime(11958): Process: com.example.myapp, PID: 11958
E/AndroidRuntime(11958): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {com.example.myapp/com.example.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(11958):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3554)
E/AndroidRuntime(11958):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3597)
E/AndroidRuntime(11958):        at android.app.ActivityThread.access$1400(ActivityThread.java:147)
E/AndroidRuntime(11958):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1334)
E/AndroidRuntime(11958):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11958):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(11958):        at android.app.ActivityThread.main(ActivityThread.java:5253)
E/AndroidRuntime(11958):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11958):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11958):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
E/AndroidRuntime(11958):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
E/AndroidRuntime(11958): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(11958):        at com.vitanov.multiimagepicker.MultiImagePickerPlugin.finishWithSuccess(MultiImagePickerPlugin.java:154)
E/AndroidRuntime(11958):        at com.vitanov.multiimagepicker.MultiImagePickerPlugin.onActivityResult(MultiImagePickerPlugin.java:147)
E/AndroidRuntime(11958):        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(11958):        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(11958):        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(11958):        at android.app.Activity.dispatchActivityResult(Activity.java:6184)
E/AndroidRuntime(11958):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3550)
E/AndroidRuntime(11958):        ... 10 more
`

Flutter Doctor results:
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.8.3-pre.47, on Microsoft Windows [Version 10.0.17134.285], locale en-PH)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.27.1)
[√] Connected devices (1 available)`

**Comment by Lyokone** [comment]
Hey, should be fixed in newer version. Thank you for submitting this :)
