### ISSUE TITLE
fix: Please update `ext.kotlin_version = '1.4.20'` to at least `1.5.20`

### ISSUE THREAD

**Issue by RoarGronmo** [Lyokone/flutterlocation#778]
**Description**
When building with `location: ^4.0.0` in `pubspec.yaml` and have raised  `classpath 'com.android.tools.build:gradle'` to `7.3.1` the build gives following complaints: 
![image](https://user-images.githubusercontent.com/11217296/201093681-31544839-9a20-46c3-a6c4-d38977659580.png)

The gradle raise is done to remedy this situation: 
![image](https://user-images.githubusercontent.com/11217296/201094013-17e92cbc-537b-4331-81c6-a0ee71410b88.png)

**Expected behavior**
A build without errors

To fix this, the gradle file for this library should be upgraded to `1.5.20` or higher.

**Comment by PlugFox** [comment]
The same issue

**Comment by asaarnak** [comment]
Duplicate issue: #762
