### ISSUE TITLE
fix: changeNotificationOptions(onTapBringToFront: true) do not work

### ISSUE THREAD

**Issue by 1712916** [Lyokone/flutterlocation#779]
Hello
When I get locations in foreground, when I set changeNotificationOptions(onTapBringToFront: true) it do not work when I tap to notifcation.

In Android 12: this have an error when setting:  E/flutter (27232): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, null)
E/flutter (27232): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (27232): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (27232): <asynchronous suspension>
E/flutter (27232): #2      MethodChannelLocation.changeNotificationOptions (package:location_platform_interface/src/method_channel_location.dart:215:9)
E/flutter (27232): <asynchronous suspension>
E/flutter (27232): 

And do not work.

Other it just do not work.

Please help me to fix this issue.

Thank you <3

**Comment by bartekpacia** [comment]
Should be fixed in #877.
