### ISSUE TITLE
fix: Because <my_app> depends on location ^5.0.0 which doesn't match any versions, version solving failed

### ISSUE THREAD

**Issue by SarahGhorbani** [Lyokone/flutterlocation#780]
I'm just updating location ^4.4.0 to the location: ^5.0.0 and get this error:

Because <my_app> depends on location ^5.0.0 which doesn't match any versions, version solving failed.

This is outputs of Flutter doctor:
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.19044.2130], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.73.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by Leffe108** [comment]
This is likely because 5.0.0 has not been released yet. At the time of writing this the latest pre-release version is [5.0.0-dev.8](https://pub.dev/packages/location/versions/5.0.0-dev.8). Try to depend on that one.

This works for me to get 5.0.0-dev.8 via pubspec.yaml:
```yaml
  location: ^5.0.0-dev.8
```

**Comment by fairuzmn** [comment]
> This is likely because 5.0.0 has not been released yet. At the time of writing this the latest pre-release version is [5.0.0-dev.8](https://pub.dev/packages/location/versions/5.0.0-dev.8). Try to depend on that one.
> 
> This works for me to get 5.0.0-dev.8 via pubspec.yaml:
> 
> ```yaml
>   location: ^5.0.0-dev.8
> ```


hey @Leffe108, i tried location ^5.0.0-dev.8 but got this error #829 
any suggestion ?
