### ISSUE TITLE
fix: version 5.0.0-dev.8 getLocation() causes fatal error on android device

### ISSUE THREAD

**Issue by kimhaafi** [Lyokone/flutterlocation#784]
**Description**
Running getLocation using version 5.0.0-dev.8 causes fatal error on Pixel 4 running API 30 android 11

Location permissions: Always

With the error: 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference

Error comes from LocationPlugin.kt line 153:
.setSatellites(location.extras.getInt("satellites").toLong())

Seems to be working if line is commented, however I have not read through the code enough to understand the implications of removing this line.

**Expected behavior**
Expected to recieve the position of the device

**Steps To Reproduce**

Run getLocation() on Android device (API 30 android 11) at any point, with location permission Always granted

**Tested on:**

- Android, API Level 30, simulator

**Additional logs**

D/Location(10166): onPermissionGranted
D/LOCATION(10166): 55.7093464 13.200616
D/AndroidRuntime(10166): Shutting down VM
E/AndroidRuntime(10166): FATAL EXCEPTION: main
E/AndroidRuntime(10166): Process: com.rootpi.time_tracker, PID: 10166
E/AndroidRuntime(10166): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
E/AndroidRuntime(10166): 	at com.lyokone.location.LocationPlugin.onLocationChanged(LocationPlugin.kt:153)
E/AndroidRuntime(10166): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationChanged(GooglePlayServicesLocationProvider.java:119)
E/AndroidRuntime(10166): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLastKnowLocationTaskReceived(GooglePlayServicesLocationProvider.java:211)
E/AndroidRuntime(10166): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource$3.onComplete(GooglePlayServicesLocationSource.java:92)
E/AndroidRuntime(10166): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime(10166): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10166): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10166): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10166): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10166): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10166): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10166): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (10166): Sending signal. PID: 10166 SIG: 9
Lost connection to device.

**Comment by Alystrasz** [comment]
Same error here.
@Lyokone do you have time to investigate this?

**Comment by hw104** [comment]
same error on `onLocationChanged`.

<details>
<summary>logs</summary>
D/AndroidRuntime(31683): Shutting down VM
E/AndroidRuntime(31683): FATAL EXCEPTION: main
E/AndroidRuntime(31683): Process: com.example.location_test, PID: 31683
E/AndroidRuntime(31683): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
E/AndroidRuntime(31683): 	at com.lyokone.location.LocationPlugin.onLocationChanged(LocationPlugin.kt:153)
E/AndroidRuntime(31683): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationChanged(GooglePlayServicesLocationProvider.java:119)
E/AndroidRuntime(31683): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationResult(GooglePlayServicesLocationProvider.java:141)
E/AndroidRuntime(31683): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource.onLocationResult(GooglePlayServicesLocationSource.java:99)
E/AndroidRuntime(31683): 	at com.google.android.gms.internal.location.zzaw.notifyListener(com.google.android.gms:play-services-location@@20.0.0:2)
E/AndroidRuntime(31683): 	at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.0.1:2)
E/AndroidRuntime(31683): 	at com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
E/AndroidRuntime(31683): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(31683): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31683): 	at android.os.Looper.loop(Looper.java:263)
E/AndroidRuntime(31683): 	at android.app.ActivityThread.main(ActivityThread.java:8326)
E/AndroidRuntime(31683): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31683): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/AndroidRuntime(31683): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
D/AudioManager(31683): getStreamVolume packageName=com.example.location_test, index=10, streamType=3
</details>

**Comment by Leffe108** [comment]
It is not unheard of for some phones to not provide number of satellites. So it is probably that the code assumes that satellites is always available and tries to convert null to long.

**Comment by gabrielgiovans** [comment]
same error on getLocation() in android 12

**Comment by abedputra** [comment]
same error...

**Comment by lemohammed** [comment]
Getting the same `NullPointerException`

**Comment by LastxTemplar** [comment]
anyone found a fix for this?

**Comment by bartekpacia** [comment]
Changes from the `5.0.0-dev.8` version are abandoned (at least for now). See also: #870.

Please use the "normal", [latest v5 version](https://pub.dev/packages/location)
