### ISSUE TITLE
fix: Could not get unknown property 'android' for project ':location' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by francbiita** [Lyokone/flutterlocation#792]
A problem occurred configuring project ':location'.
> Could not load compiled classes for build file 'D:\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.4.0\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':location' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':location' of type org.gradle.api.Project.

**Comment by bartekpacia** [comment]
Use the latest v5 versions.
