### ISSUE TITLE
Xcode 9 does not support building or migrating Swift 2.x targets

### ISSUE THREAD

**Issue by tensafefrogs** [Lyokone/flutterlocation#8]
After High Sierra upgrade, I'm seeing this with a project (which built successfully before the upgrade). This is when opening the Runner.xcworspace file in XCode.

> The target “location” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

> Use Xcode 8.x to migrate the code to Swift 3.

Any chance we could get a quick upgrade to Swift 3?

**Comment by Lyokone** [comment]
Hi ! 
Do you have this error when building the actual app for deployment or just when you run your app on a device ? I cannot reproduce this error when using `flutter run` on iOS simulator.

**Comment by tensafefrogs** [comment]
This is just when opening the Runner.xcworkspace in my project which includes this plugin.

I'll try cloning the example app here and see if it happens there as well.

**Comment by tensafefrogs** [comment]
Ok, the example app opens and builds, must be something in my project.

I do see a red flutter error view when running it on an iPhone X simulator, something about an assert failing about children not being null, but perhaps that's another issue.

Cheers!
