### ISSUE TITLE
getLocation() doesn't work

### ISSUE THREAD

**Issue by d1xlord** [Lyokone/flutterlocation#80]
getLocation() doesn't work, and always return with this response

`{speed_accuracy: 0.0, speed: -1.0, latitude: 37.785834, longitude: -122.406417, accuracy: 5.0, altitude: 0.0}`

Tested for iOS.

**Comment by timtraversy** [comment]
Are you testing on a simulator or physical device?

**Comment by ariG23498** [comment]
it actually calls the previous location of the phone, highly unreliable I would say.

**Comment by just-peteking** [comment]
I'm getting a similar thing - using a an android sim, it will only return the first location and that's it, it will never change no matter how many times you create and call getLocation().

I would send a new GPS using the emulator and getLocation() doesn't pick it up, but if I restart it does...

**Comment by Lyokone** [comment]
Hey ! That's really strange, I'll check it out as fast as possible ! 
I perform my tests on physical Android device and iOS simulator and the listening was working the last time I checked, I'll check again

**Comment by Lyokone** [comment]
Hey with 2.1 the behaviour should be more consistent. Let me know if you still got this bug.
