### ISSUE TITLE
com.lyokone.location.FlutterLocation.getLocationResult' on a null object referencefix: 

### ISSUE THREAD

**Issue by AbdrahmanKafo96** [Lyokone/flutterlocation#801]
**Description**
A clear and concise description of what the bug is. Have you tried running `flutter clean` first ?
i got this bug when i try to get current location from android device 
com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference
**Expected behavior**

**Steps To Reproduce**

**Tested on:**

- Android, API Level XX [e.g. 31], simulator or real device
- iOS, Version XX [e.g. 15], simulator or real device

**Other plugins:**

- List of others Flutter plugins that could interfere

**Additional logs**
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```shell
some logs
```

**Comment by mesiboku** [comment]
Any update on this one? @Lyokone 
Thank you!

**Comment by jithware** [comment]
@AbdrahmanKafo96 can you add your stack trace? Possible same issue in #804?

**Comment by AbdrahmanKafo96** [comment]
> @AbdrahmanKafo96 can you add your stack trace? Possible same issue in #804?

its the same bug that u mention it  https://github.com/Lyokone/flutterlocation/issues/804 is there any solution ?

**Comment by jithware** [comment]
I am seeing the same (see https://github.com/Lyokone/flutterlocation/issues/804#issuecomment-1409294203). Trying to group any issues together to help @Lyokone.
