### ISSUE TITLE
Getting Crash, with 3.7.0 flutter

### ISSUE THREAD

**Issue by vasuravada** [Lyokone/flutterlocation#802]
E/AndroidRuntime(19117): FATAL EXCEPTION: main
E/AndroidRuntime(19117): Process: com.wst.occser, PID: 19117
E/AndroidRuntime(19117): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~VhFUXXIUpfstjkqMFlJu1g==/com.wst.occser-3HLI65dMTJQS0CV814Hayg==/base.apk!classes3.dex)
E/AndroidRuntime(19117): 	at com.lyokone.location.FlutterLocation.startRequestingLocation(FlutterLocation.java:422)
E/AndroidRuntime(19117): 	at com.lyokone.location.FlutterLocation.onRequestPermissionsResultHandler(FlutterLocation.java:131)
E/AndroidRuntime(19117): 	at com.lyokone.location.FlutterLocation.onRequestPermissionsResult(FlutterLocation.java:122)
E/AndroidRuntime(19117): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:779)
E/AndroidRuntime(19117): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:411)
E/AndroidRuntime(19117): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:761)
E/AndroidRuntime(19117): 	at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:915)
E/AndroidRuntime(19117): 	at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:549)
E/AndroidRuntime(19117): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8619)
E/AndroidRuntime(19117): 	at android.app.Activity.dispatchActivityResult(Activity.java:8476)
E/AndroidRuntime(19117): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5560)
E/AndroidRuntime(19117): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5606)
E/AndroidRuntime(19117): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
E/AndroidRuntime(19117): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(19117): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(19117): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(19117): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
E/AndroidRuntime(19117): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19117): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(19117): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(19117): 	at android.app.ActivityThread.main(ActivityThread.java:8248)
E/AndroidRuntime(19117): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19117): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
E/AndroidRuntime(19117): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
I/Process (19117): Sending signal. PID: 19117 SIG: 9

**Comment by faisalansari0367** [comment]
<img width="1552" alt="Screenshot 2023-01-30 at 11 18 09 AM" src="https://user-images.githubusercontent.com/61263149/215397247-c5cb184f-2135-495a-83c7-afeb98c053b6.png">


Facing the same crash 


D/Location(10430): onPermissionGranted
E/AndroidRuntime(10430): FATAL EXCEPTION: main
E/AndroidRuntime(10430): Process: com.itrakassets.bioplus, PID: 10430
E/AndroidRuntime(10430): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~-iBHIbXOtsIp_N3wG9ANow==/com.itrakassets.bioplus-wMc7hm-t03P9fQZit0m9IA==/base.apk)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource.checkLocationSettings(GooglePlayServicesLocationSource.java:49)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.locationRequired(GooglePlayServicesLocationProvider.java:227)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.get(GooglePlayServicesLocationProvider.java:80)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.providers.locationprovider.DispatcherLocationProvider.getLocationFromGooglePlayServices(DispatcherLocationProvider.java:215)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.providers.locationprovider.DispatcherLocationProvider.checkGooglePlayServicesAvailability(DispatcherLocationProvider.java:130)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.providers.locationprovider.DispatcherLocationProvider.get(DispatcherLocationProvider.java:110)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.LocationManager.permissionGranted(LocationManager.java:255)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.LocationManager.askForPermission(LocationManager.java:233)
E/AndroidRuntime(10430): 	at com.lyokone.location.location.LocationManager.get(LocationManager.java:221)
E/AndroidRuntime(10430): 	at com.lyokone.location.LocationPlugin.onListen(LocationPlugin.kt:541)
E/AndroidRuntime(10430): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
E/AndroidRuntime(10430): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/AndroidRuntime(10430): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(10430): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(10430): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(10430): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10430): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10430): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(10430): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(10430): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(10430): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(10430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (10430): Sending signal. PID: 10430 SIG: 9
Lost connection to device.

**Comment by faisalansari0367** [comment]
What's the workaround for this to get this up and running?

**Comment by giorgio79** [comment]
Dupe of https://github.com/Lyokone/flutterlocation/issues/800

**Comment by Zasaz** [comment]
Facing same issue with location and app crashes as soon as it loads. I have a deployed app and we are migrating it to the latest flutter version and while creating apk it crashes. What's the workaround for this?

**Comment by faisalansari0367** [comment]
I tried going back to flutter 3.3.10 it was working on that version before but now i am getting the same error and it's not working on 3.3.10 too

**Comment by Zasaz** [comment]
Same not even working on previous versions!

**Comment by fayis672** [comment]
Going back doesn't fix the issue? Can anyone confirm

**Comment by LaxmikanthMadhyastha** [comment]
@fayis672 no, it will not fix the issue

**Comment by fayis672** [comment]
@LaxmikanthMadhyastha  Downgrading to 3.3.10 worked for me

**Comment by faisalansari0367** [comment]
How did you do it @fayis672 ? Can you please help me doing the same
Because for me it's not working. I have tried deleting the cache also but still issue persists

**Comment by LaxmikanthMadhyastha** [comment]
I don't think it is related to the flutter version, tried clearing the pub cache as well, did not help :(

**Comment by faisalansari0367** [comment]
Same here @LaxmikanthMadhyastha

**Comment by fayis672** [comment]
@faisalansari0367  `flutter clean` after downgrading, it worked for me.

**Comment by Zasaz** [comment]
Nope, it didn't worked for me. Even i truncated pub cache but same response.

**Comment by nazarrd** [comment]
downgrading flutter and repair cache didn't worked for me. any update on this? or maybe there is an alternative package?

**Comment by maulanauls** [comment]
This problem with   implementation "com.google.android.gms:play-services-location:19.0.1" -> in location_android please upgrade and fix the build gradle to be com.google.android.gms:play-services-location:21.0.1

**Comment by nazarrd** [comment]
@maulanauls in my case change `api 'com.google.android.gms:play-services-location:16.+'` to `api 'com.google.android.gms:play-services-location:21.0.1'` in packages build.gradle solve the issue. thanks!

**Comment by vasuravada** [comment]
> This problem with implementation "com.google.android.gms:play-services-location:19.0.1" -> in location_android please upgrade and fix the build gradle to be com.google.android.gms:play-services-location:21.0.1 --- https://github.com/Lyokone/flutterlocation/blob/master/packages/location_android/android/build.gradle `dependencies { implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" //implementation "com.google.android.gms:play-services-location:19.0.1" implementation "com.google.android.gms:play-services-location:21.0.1" implementation "androidx.appcompat:appcompat:1.4.1" }` have log from google play services https://developers.google.com/android/guides/releases#october_13_2022
> 
> So we hope @vasuravada the maintener repo fix it this case

Thanks @maulanauls , working, Cheers.

**Comment by husen313** [comment]
> @maulanauls in my case change `api 'com.google.android.gms:play-services-location:16.+'` to `api 'com.google.android.gms:play-services-location:21.0.1'` in packages build.gradle solve the issue. thanks!

working Fine thanks man

**Comment by hasnitha-zmakan** [comment]
api 'com.google.android.gms:play-services-location:16.+' to api 'com.google.android.gms:play-services-location:21.0.1'   this is not working for me

**Comment by hasnifasil** [comment]
implementation "com.google.android.gms:play-services-location:21.0.1" this one not working for me

**Comment by IrfanHangingPanda** [comment]
implementation "com.google.android.gms:play-services-location:21.0.1" this one not working for me

**Comment by kashiflab** [comment]
> @maulanauls in my case change `api 'com.google.android.gms:play-services-location:16.+'` to `api 'com.google.android.gms:play-services-location:21.0.1'` in packages build.gradle solve the issue. thanks!

not working for me

**Comment by maulanauls** [comment]
> implementation "com.google.android.gms:play-services-location:21.0.1" this one not working for me

/rootproject/android/build.gradle

Add this one maybe your problem not excatly on this plugin maybe other plugin have services-locations

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
        //** add this line
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-location:21.0.1"
            }
        }
    }
}

**Comment by kashiflab** [comment]
> > > This problem with implementation "com.google.android.gms:play-services-location:19.0.1" -> in location_android please upgrade and fix the build gradle to be com.google.android.gms:play-services-location:21.0.1 --- https://github.com/Lyokone/flutterlocation/blob/master/packages/location_android/android/build.gradle `dependencies { implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" //implementation "com.google.android.gms:play-services-location:19.0.1" implementation "com.google.android.gms:play-services-location:21.0.1" implementation "androidx.appcompat:appcompat:1.4.1" }` have log from google play services https://developers.google.com/android/guides/releases#october_13_2022
> > > So we hope @vasuravada the maintener repo fix it this case
> > 
> > 
> > @maulanauls not working for me
> 
> Some cases its different trouble try to get the logcat some case have error on plugin inside the kotlin language or java depends from your flutter use on it.
> 
> if you have error like this java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' the solution just upgrade the play services if different some kotlin inside the plugin should be change or maybe you can try
> 
> /rootproject/android/build.gradle
> 
> Add this one maybe your problem not excatly on this plugin maybe other plugin have services-locations
> 
> ```
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         maven {
>             url 'https://google.bintray.com/exoplayer/'
>         }
>         //** add this line
>         configurations.all {
>             resolutionStrategy {
>                 force "com.google.android.gms:play-services-location:21.0.1"
>             }
>         }
>     }
> }
> ```

Works like a charm... Thanks

**Comment by eyitayojason** [comment]
> @maulanauls in my case change `api 'com.google.android.gms:play-services-location:16.+'` to `api 'com.google.android.gms:play-services-location:21.0.1'` in packages build.gradle solve the issue. thanks!

Thank you

**Comment by LawrenceStent** [comment]
![giphy (4)](https://user-images.githubusercontent.com/3693512/217219529-1e705e68-8eb2-485e-b547-c63608a1c1d4.gif)

**Comment by tusharuit25** [comment]
> > implementation "com.google.android.gms:play-services-location:21.0.1" this one not working for me
> 
> /rootproject/android/build.gradle
> 
> Add this one maybe your problem not excatly on this plugin maybe other plugin have services-locations
> 
> ```
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         maven {
>             url 'https://google.bintray.com/exoplayer/'
>         }
>         //** add this line
>         configurations.all {
>             resolutionStrategy {
>                 force "com.google.android.gms:play-services-location:21.0.1"
>             }
>         }
>     }
> }
> ```

you saved my life

**Comment by elmar001** [comment]
> com.google.android.gms:play-services-location:21.0.1'

You need to manually edit Android/build.gradle file inside local copy of location package. Packages are hosted inside pub cache folder. For example full path to the folder: flutter/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/

Replace this line:

api 'com.google.android.gms:play-services-location:16.+'

With this:

api 'com.google.android.gms:play-services-location:21.0.1'

Note: You may have multiple versions of that package there. You need to find out which one your project is currently using and edit that one.

**Comment by hashnetic** [comment]
> configurations.all {
>             resolutionStrategy {
>                 force "com.google.android.gms:play-services-location:21.0.1"
>             }
>         }

This works for me!!

**Comment by bajajbros** [comment]
> 

thanks man it really works

**Comment by dhaq** [comment]
Not working

**Comment by jiteshdhamaniya** [comment]
> > implementation "com.google.android.gms:play-services-location:21.0.1" this one not working for me
> 
> /rootproject/android/build.gradle
> 
> Add this one maybe your problem not excatly on this plugin maybe other plugin have services-locations
> 
> ```
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         maven {
>             url 'https://google.bintray.com/exoplayer/'
>         }
>         //** add this line
>         configurations.all {
>             resolutionStrategy {
>                 force "com.google.android.gms:play-services-location:21.0.1"
>             }
>         }
>     }
> }
> ```

works for me. thanks @maulanauls
