### ISSUE TITLE
fix:   crash android app when calling requestService  Android 11 

### ISSUE THREAD

**Issue by abdalazeez1** [Lyokone/flutterlocation#804]
`Future<LocationData?> _getLocation() async {
         _serviceEnabled = await location.serviceEnabled();
        if (!_serviceEnabled!) {
        _serviceEnabled = await location.requestService();    ///  <--------  Crash here 
       if (!_serviceEnabled!) {
        return null;
        }
      }

    _permissionGranted = await location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {
        return null;
      }
       }

    return await location.getLocation();
  }`

E/AndroidRuntime(28634): FATAL EXCEPTION: main
E/AndroidRuntime(28634): Process: com.*******.******* , PID: ********
E/AndroidRuntime(28634): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~pZzYmvqLI-baoMZFne4zGQ==/com.*********r-BxvvzGYXN7MGuBkZ7OqVQg==/base.apk)
E/AndroidRuntime(28634): 	at com.lyokone.location.FlutterLocation.requestService(FlutterLocation.java:388)
E/AndroidRuntime(28634): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:55)
E/AndroidRuntime(28634): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(28634): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(28634): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(28634): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(28634): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(28634): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28634): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(28634): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/AndroidRuntime(28634): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28634): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(28634): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on Ubuntu 22.04.1 LTS 5.15.0-58-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by abdalazeez1** [comment]
maybe the error because i call  requestService  twice at the same time

**Comment by jithware** [comment]
Same with startRequestingLocation

```
E/AndroidRuntime(30946): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~ROzp0tcnN26s7dWxzcOYeQ==/com.jithware.mappoff-U-j-YudsXdFjGH4OjjsoOg==/base.apk)
E/AndroidRuntime(30946): 	at com.lyokone.location.FlutterLocation.startRequestingLocation(FlutterLocation.java:422)
E/AndroidRuntime(30946): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:121)
E/AndroidRuntime(30946): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
```

**Comment by adiiisanjayaa** [comment]
any update?

**Comment by AbdrahmanKafo96** [comment]
any update ?

**Comment by ilahi123** [comment]
any update?

**Comment by giorgio79** [comment]
https://github.com/Lyokone/flutterlocation/issues/802

**Comment by jithware** [comment]
Looks like https://github.com/Lyokone/flutterlocation/pull/803 solves issue originally reported in #802

Trying to test by adding to my projects pubspec.yaml

```
  location: 
    git:
      url: https://github.com/faisalansari0367/flutterlocation.git
      ref: master
      path: ./packages/location
```

However getting issue

```
Undefined class 'Location'.
Try changing the name to the name of an existing class, or creating a class with the name 'Location'.
```

Anyone else get git url working?

More duplicates in #806 and #807

**Comment by jithware** [comment]
Using #803 does not resolve issue for me:

```
E/AndroidRuntime(27886): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~OgeJMOgm3_4TYXUwiCNXCQ==/com.jithware.mappoff-KulSzR517kkqn8C_GCC99Q==/base.apk)
E/AndroidRuntime(27886): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource.removeLocationUpdates(GooglePlayServicesLocationSource.java:82)
E/AndroidRuntime(27886): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.removeLocationUpdates(GooglePlayServicesLocationProvider.java:284)
E/AndroidRuntime(27886): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.cancel(GooglePlayServicesLocationProvider.java:95)
E/AndroidRuntime(27886): 	at com.lyokone.location.location.providers.locationprovider.DispatcherLocationProvider.cancel(DispatcherLocationProvider.java:64)
E/AndroidRuntime(27886): 	at com.lyokone.location.location.providers.locationprovider.DispatcherLocationProvider.runScheduledTask(DispatcherLocationProvider.java:87)
```

@faisalansari0367 can you describe how you tested change in #803?

**Comment by LaxmikanthMadhyastha** [comment]
An easier way to test if this solution really works for you is to head to the Location plugin in your pub cache and directly update the build.gradle file use the latest location play services.

<img width="768" alt="Screenshot 2023-02-01 at 8 59 32 PM" src="https://user-images.githubusercontent.com/35574146/216086873-f772aeb0-611e-485a-ab59-eba014b72cec.png">

**Comment by faisalansari0367** [comment]
> An easier way to test if this solution really works for you is to head to the Location plugin in your pub cache and directly update the build.gradle file to use the latest location play services.
> 
> in my case I had to change `api 'com.google.android.gms:play-services-location:16.+'` to` api 'com.google.android.gms:play-services-location:21.0.1'`
> 
> <img alt="Screenshot 2023-02-01 at 8 59 32 PM" width="768" src="https://user-images.githubusercontent.com/35574146/216086873-f772aeb0-611e-485a-ab59-eba014b72cec.png">

I did the same i think we are not able to use this as a github repo in our pubspec open the build gradle file and change the location services version then it may be fixed

**Comment by jithware** [comment]
> > An easier way to test if this solution really works for you is to head to the Location plugin in your pub cache and directly update the build.gradle file to use the latest location play services.
> > in my case I had to change `api 'com.google.android.gms:play-services-location:16.+'` to` api 'com.google.android.gms:play-services-location:21.0.1'`
> > <img alt="Screenshot 2023-02-01 at 8 59 32 PM" width="768" src="https://user-images.githubusercontent.com/35574146/216086873-f772aeb0-611e-485a-ab59-eba014b72cec.png">
> 
> I did the same i think we are not able to use this as a github repo in our pubspec open the build gradle file and change the location services version then it may be fixed

I'm not sure this validates #803 because it is a push to [master](https://github.com/Lyokone/flutterlocation/tree/master) which is currently at [5.0.0](https://pub.dev/packages/location/versions#prerelease)

**Comment by abdalazeez1** [comment]
thanks it's work

**Comment by abdalazeez1** [comment]
> An easier way to test if [#802](https://github.com/Lyokone/flutterlocation/issues/802#issuecomment-1408420419) solution really works for you is to head to the Location plugin in your pub cache and directly update the build.gradle file to use the latest location play services.
> 
> in my case I had to change `api 'com.google.android.gms:play-services-location:16.+'` to` api 'com.google.android.gms:play-services-location:21.0.1'`
> 
> <img alt="Screenshot 2023-02-01 at 8 59 32 PM" width="768" src="https://user-images.githubusercontent.com/35574146/216086873-f772aeb0-611e-485a-ab59-eba014b72cec.png">

thanks it's work

**Comment by unshiny99** [comment]
A temporary solution that worked for me is to add the following code in android/build.gradle : 
```
configurations.all {
      resolutionStrategy {
          force "com.google.android.gms:play-services-location:21.0.1"
      }
}
```
This force the app to use a compatible version of services-location. Please note that we must remove this code when the bug will be fixed (i.e. this branhc merged)
