### ISSUE TITLE
Bug in version 4.4.0

### ISSUE THREAD

**Issue by TheLoveS** [Lyokone/flutterlocation#806]
When launching customer after the location permission, the application closes with an error:
`E/AndroidRuntime( 9545): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~uYsTH-L2soF9g1g5hdD0EA==/online.edentech.fuodz-taz4dVjFdz72QWHXo5aDzA==/base.apk!classes6.dex)
E/AndroidRuntime( 9545): 	at com.lyokone.location.FlutterLocation.createLocationCallback(FlutterLocation.java:219)
E/AndroidRuntime( 9545): 	at com.lyokone.location.FlutterLocation.changeSettings(FlutterLocation.java:197)
E/AndroidRuntime( 9545): 	at com.lyokone.location.MethodCallHandlerImpl.onChangeSettings(MethodCallHandlerImpl.java:106)
E/AndroidRuntime( 9545): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/AndroidRuntime( 9545): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 9545): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 9545): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 9545): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 9545): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 9545): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9545): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 9545): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 9545): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 9545): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9545): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 9545): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process ( 9545): Sending signal. PID: 9545 SIG: 9
Lost connection to device.`
And this is on all the phones of me and friends
Help solve the problem

**Comment by LaxmikanthMadhyastha** [comment]
Try [this](https://github.com/Lyokone/flutterlocation/issues/804#issuecomment-1412259071)temporary fix

**Comment by TheLoveS** [comment]
> Try [this](https://github.com/Lyokone/flutterlocation/issues/804#issuecomment-1412259071) temporary fix

Thank you very much, the problem has been solved thanks to you
