### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by hussenIbrahim** [Lyokone/flutterlocation#812]

**Comment by mikiyasET** [comment]
Maybe

**Comment by dsgriffin** [comment]
hopefully the author will give some willing participants repo access to continue fixing package issues, as it's the only one - afaik - that supports background location tracking (geolocator didn't last time i checked)

**Comment by mikiyasET** [comment]
> hopefully the author will give some willing participants repo access to continue fixing package issues, as it's the only one - afaik - that supports background location tracking (geolocator didn't last time i checked)

Yeah he should

**Comment by elninho22** [comment]
dead

**Comment by jithware** [comment]
Perhaps one of the [contributors](https://github.com/Lyokone/flutterlocation/graphs/contributors) would be willing to add their fork to pub.dev and rename it something like flutterlocation2, similar to what happened to [latlong2](https://pub.dev/packages/latlong2)?

**Comment by lecicdjuro** [comment]
![image](https://user-images.githubusercontent.com/19263556/222467638-1492b9e3-c566-406e-93ba-33e653739a40.png)
This resolved Android issue

**Comment by Lyokone** [comment]
Hey guys, sorry for not responding earlier. This package would probably need a bit more time than I can give it right now. 

I've pushed an update, `5.0.0-dev.8`, that contains fix so that the plugin can run on Flutter 3.7.

**Comment by IFLyer** [comment]
> Hey guys, sorry for not responding earlier. This package would probably need a bit more time than I can give it right now.
> 
> I've pushed an update, `5.0.0-dev.8`, that contains fix so that the plugin can run on Flutter 3.7.

hi Lyokone, thanks for updating the package.

it's look like you've release update 'location-v5.0.0-dev.9' but I can't find the update on pub.dev

**Comment by mikiyasET** [comment]
> hi Lyokone, thanks for updating the package.
> 
> it's look like you've release update 'location-v5.0.0-dev.9' but I can't find the update on pub.dev

https://pub.dev/packages/location/versions/5.0.0-dev.8

**Comment by 781flyingdutchman** [comment]
I had the same issue and believe the author is focused on V5 and not currently maintaining V4. I forked the V4 version and updated the gradle plugin version.  Until the author fixes this you can use my fork in the pubspec.yaml:
```
location:
    git:
      url: git@github.com:781flyingdutchman/flutterlocation.git
      ref: V4 
```

@Lyokone if you could create a branch at the point of your last V4 commit then I can offer you this as a *very* simple pull request!  I appreciate the work you're doing on V5 but it's not great to leave V4 unmaintained when many developers rely on it.

**Comment by bartekpacia** [comment]
Since this package is a "Flutter favorite", [I asked on the Flutter Discord server](https://discord.com/channels/608014603317936148/608020293944082452/1088189316871762112) whether it should still be marked as such given no maintenance. Just thought I'd share this with you.

**Comment by bartekpacia** [comment]
I talked with @Lyokone on fluttercon in Berlin a few days ago, and I asked him if I could help maintain this package, and he agreed :)

My plan for now is to release new v4 version asap to make the project build on latest Flutter & Gradle.

**Comment by 781flyingdutchman** [comment]
I've moved to the geolocation plugin, which does the same things for me and is properly maintained

**Comment by jithware** [comment]
> `geolocator` does not support location tracking when app is in the background, unlike this `location` package. so very glad to hear `location` will now continue to be maintained tada

Just and FYI, in the [geolocator_android/example](https://github.com/Baseflow/flutter-geolocator/blob/c212895ab376615bff6bde80559e70bae318f9b6/geolocator_android/example/lib/main.dart#L299C9-L299C37)  there is a way of using it in the background.
