### ISSUE TITLE
Unable to get location after disable then enable of gps!!

### ISSUE THREAD

**Issue by dadmad817** [Lyokone/flutterlocation#82]
first: the user allows permissions for the application and the gps is turned previosly
second:the user turns off the gps
third:the user tries to get his location but an error appears in the dubug console
fourth: the user enables the gps back
fifth: the user tries to get the location again but the error reappears even if everything is enabled
testing on samsung s7 verizon android 8.0
any help appreciated
code of error:

E/flutter (31861): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (31861): PlatformException(ERROR, Failed to get location., null)
E/flutter (31861): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551)
E/flutter (31861): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279)
E/flutter (31861): <asynchronous suspension>
E/flutter (31861): #2      Location.getLocation (package:location/location.dart:12)
E/flutter (31861): #3      SubmitState.build.<anonymous closure> (package:doctorradar/pages/doctorsarea.dart:1735)
E/flutter (31861): <asynchronous suspension>
E/flutter (31861): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503)
E/flutter (31861): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558)
E/flutter (31861): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102)
E/flutter (31861): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242)
E/flutter (31861): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204)
E/flutter (31861): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
E/flutter (31861): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147)
E/flutter (31861): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121)
E/flutter (31861): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101)
E/flutter (31861): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64)
E/flutter (31861): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48)
E/flutter (31861): #15     _invoke1 (dart:ui/hooks.dart:142)
E/flutter (31861): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:99)

**Comment by ian-workcircle** [comment]
Yes, I've been experiencing this. It feels like sometimes I have to open Google maps to get the gps going, then it will work fine. But not if no other app using gps is running.

**Comment by vortixhead** [comment]
Same here

**Comment by MustafaProgramer** [comment]
same here, any solution?

**Comment by josepalbert95** [comment]
Same here with latest version of flutter and latest version plugin

**Comment by thomas01155** [comment]
Same here. Is anyone still updating this plugin?

**Comment by Lyokone** [comment]
Hey ! it should be working with 2.1, I'll try to add a getter for the GPS status as well in next versions. Let me know if its fixed for you.

**Comment by tolotrasamuel** [comment]
@Lyokone  It does not work on 2.1 If the GPS is off: 


> I/flutter ( 2767): Permission: true
> I/flutter ( 2767): PlatformException(ERROR, Failed to get location., null)
