### ISSUE TITLE
fix: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method requestService on channel lyokone/location)

### ISSUE THREAD

**Issue by jitendraAn** [Lyokone/flutterlocation#821]
`
I want to turn on GPS from GPS dialog. When i upadate flutter version, now i am getting this error:  

      import 'package:location/location.dart'
       

  **Code is:**   
  ```
     Location location = Location();
        // openGPS(location);
        bool _serviceEnabled = await location.serviceEnabled();
        if (!_serviceEnabled) {
          _serviceEnabled = await location.requestService();
          if (!_serviceEnabled) {
            return;
          }
        }
```
      

     E/DartMessenger(29208): Uncaught exception in binary message listener
          E/DartMessenger(29208): java.lang.CloneNotSupportedException: Class com.google.android.gms.location.LocationSettingsRequest doesn't implement Cloneable
          E/DartMessenger(29208): 	at java.lang.Object.clone(Object.java:255)
          E/DartMessenger(29208): 	at com.lyokone.location.FlutterLocation.requestService(FlutterLocation.java:388)
          E/DartMessenger(29208): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:55)
          E/DartMessenger(29208): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
          E/DartMessenger(29208): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
          E/DartMessenger(29208): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
          E/DartMessenger(29208): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
          E/DartMessenger(29208): 	at android.os.Handler.handleCallback(Handler.java:938)
          E/DartMessenger(29208): 	at android.os.Handler.dispatchMessage(Handler.java:99)
          E/DartMessenger(29208): 	at android.os.Looper.loopOnce(Looper.java:226)
          E/DartMessenger(29208): 	at android.os.Looper.loop(Looper.java:313)
          E/DartMessenger(29208): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
          E/DartMessenger(29208): 	at java.lang.reflect.Method.invoke(Native Method)
          E/DartMessenger(29208): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
          E/DartMessenger(29208): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
          E/flutter (29208): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method requestService on channel lyokone/location)
          E/flutter (29208): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
          E/flutter (29208): <asynchronous suspension>
          E/flutter (29208): #1      MethodChannelLocation.requestService (package:location_platform_interface/src/method_channel_location.dart:137:25)
          E/flutter (29208): <asynchronous suspension>
          E/flutter (29208): #2      _PropertyPhotoCaptureState.getCurrentLocation (package:sampada/screens/services/property_photo_capture/PropertyPhotoCapture.dart:199:27)
          E/flutter (29208): <asynchronous suspension>
          E/flutter (29208): 

`

**Comment by bartekpacia** [comment]
Package version? Android version? Flutter version? Sorry, this issue is not reproducible, I have to close it.
