### ISSUE TITLE
FATAL ERROR: location: ^5.0.0-dev.8 on Android devices

### ISSUE THREAD

**Issue by amjadhck** [Lyokone/flutterlocation#822]
**Description**
.pub-cache/hosted/pub.dev/location_android-5.0.0-dev.3/android/src/main/kotlin/com/lyokone/location/LocationPlugin.kt: (153, 47): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?

**Tested on:**

- Android, API Level 29, simulator

Any Solution??

**Comment by Samuel-ML** [comment]
same...

**Comment by fairuzmn** [comment]
i have temporary solution, check out my comment at

https://github.com/Lyokone/flutterlocation/issues/829#issuecomment-1500944644

**Comment by IttaiBarkai** [comment]
similar issue on iOS Simulator

`
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(LOCATION_ERROR, The operation couldn’t be completed. (kCLErrorDomain error 0.), null, null)`

**Comment by bartekpacia** [comment]
The `v5.0.0-dev*` branch is abandoned for now. See also: #846.
