### ISSUE TITLE
 Could not find any matches for com.google.android.gms:play-services-location:16.+ as no versions of com.google.android.gms:play-services-location are available.

### ISSUE THREAD

**Issue by abbasihamed** [Lyokone/flutterlocation#828]
## When I run my project it gives me this error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.google.android.gms:play-services-location:16.+ as no versions of com.google.android.gms:play-services-location are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-location/maven-metadata.xml
     Required by:
         project :app > project :location
   > Could not find androidx.core:core-ktx:1.3.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/core/core-ktx/1.3.2/core-ktx-1.3.2.pom
       - https://repo.maven.apache.org/maven2/androidx/core/core-ktx/1.3.2/core-ktx-1.3.2.pom
       - https://storage.googleapis.com/download.flutter.io/androidx/core/core-ktx/1.3.2/core-ktx-1.3.2.pom
     Required by:
         project :app > project :location

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

How I can fix this?

**Comment by bartekpacia** [comment]
This is fixed in v5 versions.
