### ISSUE TITLE
fix: LocationData.time is null on android

### ISSUE THREAD

**Issue by ufoloko** [Lyokone/flutterlocation#835]
**Description**
Im trying to cast LocationData.time in app but is giving null value on android. for IOS is working perfectly.

**Expected behavior**
You should be able to cast time to date. This should have a valid epoch number

**Steps To Reproduce**

1. im using version 5.0.0-dev.8 for my app, because documentation and examples are using this version.
2. When you compile and call getLocation, you receive DataLocation object but time value is null in android

**Tested on:**

- Android, API Level 31 real device
- iOS, Version 16 real device

**Comment by bartekpacia** [comment]
Hi, please use the `5.0.*` version, not the `5.0.0-dev* ones.
