### ISSUE TITLE
fix: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by MartinCabrera137** [Lyokone/flutterlocation#844]
**Description**
The following dependencies do not satisfy the required version:
project ':location' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

**Comment by dbdean** [comment]
Duplicate of https://github.com/Lyokone/flutterlocation/issues/843 and https://github.com/Lyokone/flutterlocation/issues/838 I think

**Comment by bartekpacia** [comment]
Yup, that's a duplicate.
