### ISSUE TITLE
Execution failed for task ':app:preDebugBuild'.

### ISSUE THREAD

**Issue by sathishRA91** [Lyokone/flutterlocation#85]
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-v4' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

**Comment by gimox** [comment]
same here when used with other plugin like simple permission, please bump to sdk target 27
