### ISSUE TITLE
Connection closed while receiving data

### ISSUE THREAD

**Issue by Idikan** [Lyokone/flutterlocation#858]
**Describe the bug**
Upon adding Locaton 5.0.0, pubspec command "Pub get" failed with Error "Connection closed while receiving data
Process finished with exit code 69"

**Expected behavior**
Pubspec failed

**Tested on:**

**Additional logs**

``` shell
Connection closed while receiving data
Process finished with exit code 69
```

**Comment by bartekpacia** [comment]
this is a problem with your dev env, not with this plugin
