### ISSUE TITLE
Error on currentLocation.onLocationChanged.listen

### ISSUE THREAD

**Issue by jaimesalvador** [Lyokone/flutterlocation#863]
**Describe the bug**
The app can't listen for location events using the last version (5.0.1)

**Additional logs**

``` shell
E/flutter ( 8285): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter ( 8285): #0      MethodChannelLocation.onLocationChanged.<anonymous closure> (package:location_platform_interface/src/method_channel_location.dart:146:47)
E/flutter ( 8285): #1      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
E/flutter ( 8285): #2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 8285): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter ( 8285): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 8285): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter ( 8285): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter ( 8285): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter ( 8285): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 8285): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by hlhc** [comment]
Same problem with `5.0.1`

I fixed this issue by overriding the platform interfaces:
```yaml
dependency_overrides: 
  location_platform_interface: 3.0.0
```

**Comment by Kerbalximus** [comment]
Same problem

It helped me.

> ```yaml
> dependency_overrides: 
>   location_platform_interface: 3.0.0
> ```

**Comment by Milan-Verselix** [comment]
dfcd
3

**Comment by Milan-Verselix** [comment]
It's not working in my case..

> Same problem
> 
> It helped me.
> 
> > ```yaml
> > dependency_overrides: 
> >   location_platform_interface: 3.0.0
> > ```

**Comment by ninjagaru** [comment]
It's not working for me

dependency_overrides: 
  location_platform_interface: 3.0.0

**Comment by ninjagaru** [comment]
> It's not working in my case..
> 
> ```
>   geolocator: ^9.0.2
>   permission_handler: ^10.4.3
>   location: ^5.0.1
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
>   flutter_lints: ^2.0.0
>   location_platform_interface: ^3.1.0
> ```
> 
> > Same problem
> > It helped me.
> > > ```yaml
> > > dependency_overrides: 
> > >   location_platform_interface: 3.0.0
> > > ```

it's not working for me

**Comment by jaimesalvador** [comment]
I switch to Geolocator, it works fine!

**Comment by bardram** [comment]
Same problem here...

Could you release a fix, so that we don't need to either override dependencies (which does not work when using the `location` plugin in other `pub.dev` releases) or lock the dependency to version `5.0.0`? 

Anyway - thanks for a great plugin.

**Comment by tebalink** [comment]
Same problem 
e '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter ( 8285): #0      MethodChannelLocation.onLocationChanged.<anonymous closure> (package:location_platform_interface/src/method_channel_location.dart:146:47)

**Comment by burakglc** [comment]
Error 

#0      MethodChannelLocation.onLocationChanged.<anonymous closure> (package:location_platform_interface/src/method_channel_location.dart:146:47)
 #1      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
  #2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
 : #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
  #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
 #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
  #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
  #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
  #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
 #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by bartekpacia** [comment]
Hi, I'm so sorry for the problems.

I made a fix (see #871) and released it as [`v5.0.2`](https://pub.dev/packages/location/changelog#502). Let me know if it fixes it for you.

**Comment by komaxx** [comment]
Thank you for the fix, will test right away :)

**Comment by bartekpacia** [comment]
Thanks for confirmation, gonna close it.

**Comment by jaimesalvador** [comment]
Thanks for the fix.

**Comment by burakglc** [comment]
Thanks for the fix.
