### ISSUE TITLE
Android building error with app_settings:5.0.0

### ISSUE THREAD

**Issue by giovanni256** [Lyokone/flutterlocation#865]
Hi there.

I just upgraded to 5.0.0 app_settings and location too, and upgraded all firebase plugins to the latest versions.
I got this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
     Versions that do not match: 1.0.0
     Required by:
         project :app > project :firebase_crashlytics > com.google.firebase:firebase-crashlytics:18.4.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
```
I aldo tried to upgrade the kotlin version, the gradle version, remove OneSignal plugin, but I solved the issue by downgrading app_setting and location plugin.

Link to the issue reported in app_settings: https://github.com/spencerccf/app_settings/issues/187

**Comment by bartekpacia** [comment]
Please post a fully reproducible example, otherwise it's only guessing.

This looks like a problem with your app's native dependencies (i.e. Gradle), not with this plugin.
