### ISSUE TITLE
Not displaying the Map. only Start Location :{} and Continuous Location:{} .

### ISSUE THREAD

**Issue by crjgonato** [Lyokone/flutterlocation#87]

**Comment by ibrierley** [comment]
Possible to include some code and a bit more info etc.

**Comment by ElZombieIsra** [comment]
Have you added your Google Maps API Key, activated the API in Google CloudPlatform and added a payment method to the API?

**Comment by Lyokone** [comment]
Hey ! The maps is only a Static Map loaded over Image.network.
