### ISSUE TITLE
Specs satisfying the `location (from `.symlinks/plugins/location/ios`)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by bitsydarel** [Lyokone/flutterlocation#879]
**Describe the bug**
Specs satisfying the `location (from `.symlinks/plugins/location/ios`)` dependency were found, but they required a higher minimum deployment target.

**Expected behavior**
For project bellow platform ios version 13 should continue working.

[*There's no reason why the version should be bumped*](https://github.com/Lyokone/flutterlocation/blob/1f0a2d0217e75fb501ca9dde262438bee5a22865/packages/location/ios/location.podspec#L19C1-L19C1)

**Additional logs**

``` shell
[!] CocoaPods could not find compatible versions for pod "location":
  In Podfile:
    location (from `.symlinks/plugins/location/ios`)

Specs satisfying the `location (from `.symlinks/plugins/location/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by bartekpacia** [comment]
Feel free to submit a PR changing the minimum version to iOS 11 in `Podfile`. Also make sure it works on such an old system. I don't have a device or simulator to test it.

**Comment by bartekpacia** [comment]
FYI: https://telemetrydeck.com/blog/ios16-market-share-03-23
