### ISSUE TITLE
Add time to the location event object...

### ISSUE THREAD

**Issue by ibrierley** [Lyokone/flutterlocation#89]
If I add

               loc.put("time", (double) location.getTime());

to createLocationCallback

It returns the time as part of the object. It would seem sensible to include this, so that folk can store the exact time a gps event happened (i.e to record routes etc).

I note there are other things like 'heading', and 'bearing' but not sure if all of these work across ios as well, as I don't have a device to test this. But wondering why we don't include all of those as well ?

**Comment by Lyokone** [comment]
Will be added to next release.
