### ISSUE TITLE
Android phone，no response

### ISSUE THREAD

**Issue by Sindyue** [Lyokone/flutterlocation#895]
in android ，use the demo, location or listen location ，no response or err back，where is wrong？

**Comment by Sindyue** [comment]
W/FinalizerDaemon(29755): type=1400 audit(0.0:794): avc: denied { getopt } for path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c109,c256,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=com.lyokone.location.example

**Comment by bartekpacia** [comment]
not reproducible
