### ISSUE TITLE
io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()

### ISSUE THREAD

**Issue by anilkumar416** [Lyokone/flutterlocation#900]
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(14507): FATAL EXCEPTION: main
E/AndroidRuntime(14507): Process: in.ripplr.cdms_fulfillment, PID: 14507
E/AndroidRuntime(14507): java.lang.RuntimeException: Unable to destroy activity {in.ripplr.cdms_fulfillment/in.ripplr.cdms_fulfillment.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(14507): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5772)
E/AndroidRuntime(14507): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5805)
E/AndroidRuntime(14507): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6106)
E/AndroidRuntime(14507): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6021)
E/AndroidRuntime(14507): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:85)
E/AndroidRuntime(14507): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(14507): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14507): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14507): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2489)
E/AndroidRuntime(14507): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14507): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(14507): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(14507): 	at android.app.ActivityThread.main(ActivityThread.java:8427)
E/AndroidRuntime(14507): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14507): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/AndroidRuntime(14507): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
E/AndroidRuntime(14507): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(14507): 	at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:117)
E/AndroidRuntime(14507): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime(14507): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges(LocationPlugin.java:74)
E/AndroidRuntime(14507): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivityForConfigChanges(FlutterEngineConnectionRegistry.java:369)
E/AndroidRuntime(14507): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:743)
E/AndroidRuntime(14507): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:919)
E/AndroidRuntime(14507): 	at android.app.Activity.performDestroy(Activity.java:8695)
E/AndroidRuntime(14507): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1438)
E/AndroidRuntime(14507): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5759)
E/AndroidRuntime(14507): 	... 15 more

**Comment by sherzodkamoldinov** [comment]
Please answer! Is there a solution to this problem? I only need a window that automatically turns on the location.

**Comment by bartekpacia** [comment]
not reproducible
