### ISSUE TITLE
Apps opened too long because binding location service

### ISSUE THREAD

**Issue by AbdulDesu** [Lyokone/flutterlocation#905]
**Describe the bug**
After allow location persmission the apps is opened normally, but when app teminated and reopened the apps is take too much loading time at native splashscreen and when i check the logs it shows:

D/FlutterLocationService(15733): Creating service.
D/FlutterLocationService(15733): Binding to location service.

This problem solved temporary when i remove location permission and re allow it. but the bug still happen when i open the apps again with same solving solution by re allow the location permission.

**Expected behavior**
The apps opened normally when location permission already granted.

**Tested on:**
 - Android, API Level 33, emulator and real device
 - iOS, Version 11, simulator and real device

**Other plugins:**
 - Wakelock
 - Background_Fetch

**Comment by Flucadetena** [comment]
I have the same issue, been searching for the problem for several days and just located the same problem. It makes the app unusable. Please fix it.

If anyone finds a temporally fix please share. It would help a great deal.

**Comment by Flucadetena** [comment]
Ok I found the root problem. It is not this package but the "safe_device" package.

I migrated to this package: [Geolocator](https://pub.dev/packages/geolocator) that seems to be a brother of this. Don't know which one is the original. But it looks to be more maintained and have a bigger community. The migration was very ease, but didn't solve the problem. They had the same issue reported months ago: [This is the issue](https://github.com/Baseflow/flutter-geolocator/issues/1243) in case it helps someone.

A user found out that the real problem came from the "Safe_device" package and there is an issue opened for it: [Issue](https://github.com/ufukhawk/safe_device/issues/33)

I removed the package and everything was solved. The app opens as fast as it use to.

Hope it helps ;)

**Comment by AbdulDesu** [comment]
Thanks! The problem is solved after following your advice.
 Now the apps is opened normally without any problems ^^

**Comment by urbanjagodic** [comment]
@Flucadetena 

For me aswell was the `safe_device` package that was causing the startup app delay, and after removing the package, the app startup latency was back to normal, unfortunately the `safe_device` package is direly needed in my app.

But when i downgraded this location plugin to `4.4.0` version, it works fine without any timeout problems and delays.
It seems, there is a breaking change for android platform from `4.4.0` to `5.X.X` versions.

**Comment by urbanjagodic** [comment]
It looks like the change from 4.4.0 to 5.0.0 was the dependency upgrade 
![image](https://github.com/Baseflow/flutter-geolocator/assets/34213584/1f7b8a0e-d189-4fca-9fda-0a3d55a4ebbe)

of `google play services location` dependency to 21.+ version which according to this issue's comment is the source of slow app startup latency: https://github.com/Baseflow/flutter-geolocator/issues/1243#issuecomment-1772328273

The real fix for this package should be lowering this dependency and not removing other packagesas a workaround from user's codebase which are essential to app's core functionality.

**Comment by AmirKeshavarz** [comment]
> But when i downgraded this location plugin to 4.4.0 version, it works fine without any timeout problems and delays.

I decreased the version as u said but the problem continued. My Flutter version is 3.22.1 .

**Comment by osmancan23** [comment]
@Flucadetena thanks a lot

**Comment by Zataxo-BC** [comment]
> Ok I found the root problem. It is not this package but the "safe_device" package.
> 
> I migrated to this package: [Geolocator](https://pub.dev/packages/geolocator) that seems to be a brother of this. Don't know which one is the original. But it looks to be more maintained and have a bigger community. The migration was very ease, but didn't solve the problem. They had the same issue reported months ago: [This is the issue](https://github.com/Baseflow/flutter-geolocator/issues/1243) in case it helps someone.
> 
> A user found out that the real problem came from the "Safe_device" package and there is an issue opened for it: [Issue](https://github.com/ufukhawk/safe_device/issues/33)
> 
> I removed the package and everything was solved. The app opens as fast as it use to.
> 
> Hope it helps ;)

maaaaaan , been stuck for 2 days , although I'm using safe_device but configuring custom method channel is better than dealing with this
