### ISSUE TITLE
Prompt user to enable location service

### ISSUE THREAD

**Issue by naumanahmed19** [Lyokone/flutterlocation#91]
Anyway to prompt user to enable GPS like this screenshot.

<img src="https://i.stack.imgur.com/u9Q4D.png">

**Comment by tolotrasamuel** [comment]
@Lyokone It does not work on 2.1 If the GPS is off:

I/flutter ( 2767): Permission: true
I/flutter ( 2767): PlatformException(ERROR, Failed to get location., null)
