### ISSUE TITLE
Compatibility with Gradle 8

### ISSUE THREAD

**Issue by jakobleck** [Lyokone/flutterlocation#915]
Upgrade Gradle and AGP in an existing project using flutterlocation to use Gradle 8, then for Anrdroid build fails with:
```
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':location'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```

To make this go away, we need to add
```
android {
...
    if(project.android.hasProperty('namespace')) {
        namespace 'com.lyokone.location'
    }
}
```
in the android/build.gradle file of the package.

Tested with Flutter 3.16.0 on an API 33 Android simulator.

**Comment by bensonarafat** [comment]
Hi @jakobleck 
Thanks for opening the issue.. 
Pls, can you check if you are using the latest version?
[namespace](https://github.com/Lyokone/flutterlocation/blob/7cc54d74a5b53f8c6465ca0e4e5171b39fa49f8d/packages/location/android/build.gradle#L29C1-L29C1) has already been added

**Comment by jakobleck** [comment]
Ah, my bad. Thought I had upgraded all package versions, but the one for flutterlocation was fixed to a git ref. Sorry. And thanks for your reply.
