### ISSUE TITLE
How to check Location Service Status?

### ISSUE THREAD

**Issue by naumanahmed19** [Lyokone/flutterlocation#92]
hasPermission only checking if permission is guaranteed. Is there any way to check location service / GPS status if it activated/disabled?

**Comment by basestring2** [comment]
I would like to know as well, this is not stable my app don't know what to do and just keeps waiting for a location

**Comment by basestring2** [comment]
Got a work around, not sure if it the best way because I'm very new to flutter but not new to programming.
I changed the getLocation to this

```
Future<LocationData> getLocation() => _channel
      .invokeMethod('getLocation')
      .then((result) => LocationData.fromMap(result.cast<String, double>()))
      .timeout(Duration(seconds: 1));
```
now I can Catch a timeout error like this

```
try {
      currentLocation = await  location.getLocation();
    } on PlatformException {
      currentLocation = null;
    } catch (e) {
      currentLocation = null;
      print(e);
    } 
```

**Comment by Lyokone** [comment]
I'll look into adding this feature :)

**Comment by Lyokone** [comment]
Hey ! In 2.2 I've added `serviceEnabled()` and `requestService()` in order to check and request Location Service status. Let me know if it correspond to what you need :)

**Comment by vitaomds** [comment]
@Lyokone the method serviceEnabled() is not working on Android Pie.
Do you know why?

**Comment by Lyokone** [comment]
Hey ! It seems to be working fine on my end ( I'm using a Pie device to test the example app).
Let me check again today.

**Comment by mikeevstropov** [comment]
How to subscribe to serviceEnabled state changing?
