### ISSUE TITLE
Unable to Built Flutter App [ sdk: '>=3.2.3 <4.0.0' ]

### ISSUE THREAD

**Issue by Me-JJ** [Lyokone/flutterlocation#921]
**Describe the bug**
Execution failed for task ':location:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

**Expected behavior**
The app should start as usual .

**Tested on:**
 - Android, API Level 31, simulator

**Other plugins:**
No other plugins added.

**Additional logs**
┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                     │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then │
│ update /Users/jatin/Desktop/Mango_Oranges/location_test/android/build.gradle:              │
│ ext.kotlin_version = '<latest-version>'                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1

``` shell
some logs
```

**Comment by notcancername** [comment]
The fix is spelled out in the "flutter fix" box. Add `ext.kotlin_version = '1.8.0'` or some other version to your build.gradle.
