### ISSUE TITLE
Flutter Android Phone error 

### ISSUE THREAD

**Issue by LX19930301** [Lyokone/flutterlocation#922]
type=1400 audit(0.0:13741): avc: denied { getopt } for path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c209,c258,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=com.acupayth

**Comment by xunreal75** [comment]
When will it happen. 
Please use the issue template and provide additional data.
It's not possible to define an issue with your data.
