### ISSUE TITLE
Kotlin version 1.9.0 

### ISSUE THREAD

**Issue by MrAzimzadeh** [Lyokone/flutterlocation#923]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:/Users/azimz/AndroidStudioProjects/cafetti_user/build/location/.transforms/02be0e06ca0da88ea338d30247b858a1/transformed/out/jar
s/classes.jar!/META-INF/location_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/azimz/.gradle/caches/transforms-3/889ce5bd12f1117e5357d5fcdb5e1305/transformed/core-1.10.1/jars/classes.jar!/META-INF/co
re_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
he binary version of its metadata is 1.9.0, expected version is 1.6.0.
e: C:/Users/azimz/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.0/8ee15ef0c67dc83d874f412d84378d7f0eb50b63/kotlin-stdlib-1.9.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
e: C:/Users/azimz/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.9.0/cd65c21cfd1eec4d44ef09f9f52b6d9f8a720636/kotlin-stdlib-common-1.9.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
Running Gradle task 'assembleRelease'...                           76.3s
√  Built build\app\outputs\flutter-apk\app-release.apk (23.2MB).

**Comment by bartekpacia** [comment]
not reproducible
