### ISSUE TITLE
This Package not working why?

### ISSUE THREAD

**Issue by harshaIOT** [Lyokone/flutterlocation#93]
I have done the step by step process what the description said when I first run this code it throws error saying "permission_denied" which we mentioned in code catch PlatformException, and after u allow and re initiate your code you will get a new error saying "ERROR", that's because GPS location is off and gives a popup to on but it wont update after it is on and then re initiate then it works and listens to callbacks ..

I got stuck here for 3 days to figure out whats wrong, please let me know what mistake I have made. and why its throwing error and I need to re initiate my code all the time..

Flutter version : 0.5.1
Dart version : 2.0

**Comment by ibrierley** [comment]
Maybe put a basic test case of your code somewhere, as it's hard to see without it.

**Comment by harshaIOT** [comment]
I am using the example what the package provided,

`import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:location/location.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Map<String, double> _startLocation;
  Map<String, double> _currentLocation;

  StreamSubscription<Map<String, double>> _locationSubscription;

  Location _location = new Location();
  bool _permission = false;
  String error;

  bool currentWidget = true;

  Image image1;

  @override
  void initState() {
    super.initState();

    initPlatformState();

    _locationSubscription =
        _location.onLocationChanged().listen((Map<String,double> result) {
          setState(() {
            _currentLocation = result;
          });
        });
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  initPlatformState() async {
    Map<String, double> location;
    // Platform messages may fail, so we use a try/catch PlatformException.

    try {
      _permission = await _location.hasPermission();
      location = await _location.getLocation();


      error = null;
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
        error = 'Permission denied';
      } else if (e.code == 'PERMISSION_DENIED_NEVER_ASK') {
        error = 'Permission denied - please ask the user to enable it from the app settings';
      }

      location = null;
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    //if (!mounted) return;

    setState(() {
        _startLocation = location;
    });

  }

  @override
  Widget build(BuildContext context) {
    List<Widget> widgets;


    if (_currentLocation == null) {
      widgets = new List();
    } else {
      widgets = [
        new Image.network(
            "https://maps.googleapis.com/maps/api/staticmap?center=${_currentLocation["latitude"]},${_currentLocation["longitude"]}&zoom=18&size=640x400&key=YOUR_API_KEY")
      ];
    }

    widgets.add(new Center(
        child: new Text(_startLocation != null
            ? 'Start location: $_startLocation\n'
            : 'Error: $error\n')));

    widgets.add(new Center(
        child: new Text(_currentLocation != null
            ? 'Continuous location: $_currentLocation\n'
            : 'Error: $error\n')));

    widgets.add(new Center(
      child: new Text(_permission 
            ? 'Has permission : Yes' 
            : "Has permission : No")));

    return new MaterialApp(
        home: new Scaffold(
            appBar: new AppBar(
              title: new Text('Location plugin example app'),
            ),
            body: new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: widgets,
            )));
  }
}`

Added package` location: ^1.4.1`
Added ```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
``` in manifest file.

**Comment by harshaIOT** [comment]
I am just checking the sample example works or not so that I want to implement that in my application when I first run the code it displaying the below screenshot.

![screenshot 26](https://user-images.githubusercontent.com/42435996/48833466-6a13cc00-eda1-11e8-8f67-13f015222b2f.png)

**Comment by mulderpf** [comment]
Make sure the app has location permissions on the device?

**Comment by Lyokone** [comment]
Hey ! I'll close this, pls reopen another issue if it is still not working.
