### ISSUE TITLE
Platform Exception With Error code 'ERROR' in getLocation() method

### ISSUE THREAD

**Issue by somelikebit** [Lyokone/flutterlocation#97]
PlatformException(ERROR, Failed to get location., null)

hasPermission() returns true and device location is on but it still errors ..

**Comment by somelikebit** [comment]
the fun part is it solved after opening google maps once and closing it and trying to getLocation() again!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by magamigan** [comment]
Hi.

I have the same issue. I use this code, triggered by clicking on the floatingActionButton. I've tried to clean up the code, so maybe it does not really work as written here.

```dart
import 'dart:async';
import 'dart:core';
import 'package:location/location.dart';

class MyWidget extends StatefulWidget {
  MapWidget({
    Key key,
  }) : super(key: key);

  @override
  _MyWidgetState createState() => new _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  var _location;
  var _currentLocation;

  @override
  void initState() {
    super.initState();
  }

  Future _showMeAndCenter() async {
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {

      _currentLocation = <String, double>{};
      _location = new Location();

      _currentLocation = await _location.getLocation();
      print("current location: " + _currentLocation["latitude"]?.toString());

    } on Exception {
      _currentLocation = null;
    }
}

  Widget build(BuildContext context) {

var stack = new Stack();//it is actually more complete

    return new Scaffold(
      body: stack,
      floatingActionButton: new FloatingActionButton(
          onPressed: () {
            _showMeAndCenter();
          },
          child: new Icon(Icons.my_location)),
    );
  }
}
```

In debug mode, it goes into the `_showMeAndCenter` method, up to the `_currentLocation = await _location.getLocation();` line. It tries to evaluate `_location`, then `getLocation()`, then comes back to `await`, to finally jump to a file named `message_codes.dart`, line 551:
```dart
      throw PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
```
with the message:

> **Exception has occurred.**
> PlatformException (PlatformException(ERROR, Failed to get location., null))

If I can give anymore detail, feel free to ask.

**Comment by somelikebit** [comment]
hi..
i don't really know what was the problem but it solved after i opened googleMaps once working with it and closing!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
so strange!

**Comment by somelikebit** [comment]
hah!
fun
take a look here:
### https://stackoverflow.com/questions/29441384/fusedlocationapi-getlastlocation-always-null/29854418#29854418
exactly that! this plugin is using the fused location provider and that will work after some another client like google maps is trying to get the location from fused location provider api!!!
asking again
why so?
:/

**Comment by somelikebit** [comment]
this library is just using fusedLocationProvider.
you can use geolocator if you want to get location from android locationProvider instead of google fusedLocationProvider.

use it like this to force it to use android **LocationMenager** insead:

double lat;
double long;

> 
> Geolocator geolocator=new  Geolocator()..forceAndroidLocationManager=true;
> GeolocationStatus geolocationStatus  = await geolocator.checkGeolocationPermissionStatus();
> bool hasPermission=false;
> if(geolocationStatus==GeolocationStatus.granted)
> {
>     hasPermission=true;
> }
> if (hasPermission) {
>   try {
>       Position position = await geolocator.getLastKnownPosition(desiredAccuracy: LocationAccuracy.medium);
>       print(position);
>       if(position!=null){
>         lat=position.latitude;
>         long=position.longitude;
>    }
>    else
>         {
>           return null;
>         }
>   } on PlatformException catch (e) {
>       print("error");
>       print(e);
>       print('ERROR: ' +e.message.toString()+"\n"+e.details.toString()+"\n"+e.code.toString());
>       throw Exception("Fail!");
>     }
> } else {
>     print('location permission denied.');
>     throw Exception("failed to get Location (permission denied).");
> }
