### ISSUE TITLE
Support `web ^1.0.0`

### ISSUE THREAD

**Issue by RoarGronmo** [Lyokone/flutterlocation#982]
Many libraries are going for `web ^1.0.0` and we are now stuck because of this problem where we are trying to upgrade `web` dependency from `web ^0.5.1` to `web ^1.0.0`:

```
PS C:\FlutterProjects\mWork> flutter pub get
Resolving dependencies... (3.9s)
Because no versions of location match >7.0.0 <8.0.0 and location 7.0.0 depends on location_web ^5.0.3, location ^7.0.0 requires location_web ^5.0.3.
Because location_web 5.0.3 depends on web ^0.5.1 and no versions of location_web match >5.0.3 <6.0.0, location_web ^5.0.3 requires web ^0.5.1.
Thus, location ^7.0.0 requires web ^0.5.1.
So, because mwork depends on both location ^7.0.0 and web ^1.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on web: flutter pub add web:^0.5.1
PS C:\FlutterProjects\mWork> 
```

Could you please make an effort to make `location` and `location_web` compatible with `web ^1.0.0` ?

**Comment by mulderpf** [comment]
I second this request.  This is currently holding up some upgrades I need to do.

**Comment by RoarGronmo** [comment]
@Lyokone The fact that `location_web 5.0.3` is still dependent on `web 0.5.1` renders this PR not to sort out the problem that it isn't compatible with `web ^1.0.0`

...so I am sorry to say that problem still persists at the moment.

**Comment by sergiomeneses** [comment]
> @Lyokone The fact that `location_web 5.0.3` is still dependent on `web 0.5.1` renders this PR not to sort out the problem that it isn't compatible with `web ^1.0.0`
> 
> ...so I am sorry to say that problem still persists at the moment.

Confirm this, re open the issue please

**Comment by sergiomeneses** [comment]
Even the `fix` is wrong

**Comment by mulderpf** [comment]
The fix didn't resolve the issue and I am still getting the same error.

**Comment by hugofpaiva** [comment]
@Lyokone If possible, please check this!

**Comment by danielmessi13** [comment]
Any updates?
