### ISSUE TITLE
Bug on installing location package version 7.0.0

### ISSUE THREAD

**Issue by gopelkujo** [Lyokone/flutterlocation#988]
**Describe the bug**
I tried location package in a fresh flutter project. When i try install location by `flutter pub add location` and copy paste `location ^7.0.0` to pubspec.yaml, error happens.

Error for installing by `flutter pub add location` command:
```
The current Dart SDK version is 3.4.3.

Because location >=4.0.0-nullsafety.0 <4.0.0 depends on location_web ^2.0.0-nullsafety and
  location >=5.0.0-dev.0 <5.0.0-dev.2 depends on location_web ^5.0.0-dev.0, location
  >=4.0.0-nullsafety.0 <4.0.0 or >=5.0.0-dev.0 <5.0.0-dev.2 requires location_web
  ^2.0.0-nullsafety or ^5.0.0-dev.0.
And because location >=5.0.0-dev.2 <5.0.0-dev.3 depends on location_web ^5.0.0-dev.1, location
  >=4.0.0-nullsafety.0 <4.0.0 or >=5.0.0-dev.0 <5.0.0-dev.3 requires location_web
  ^2.0.0-nullsafety or >=5.0.0-dev.0 <6.0.0.
And because location >=5.0.0-dev.3 <5.0.0-dev.8 depends on location_web ^5.0.0-dev.2 and
  location >=5.0.0-dev.8 <5.0.0 depends on location_web ^5.0.0-dev.3, location
  >=4.0.0-nullsafety.0 <4.0.0 or >=5.0.0-dev.0 <5.0.0 requires location_web ^2.0.0-nullsafety or
  >=5.0.0-dev.0 <6.0.0.
And because location <4.0.0-nullsafety.0 doesn't support null safety and location >=4.0.0 <4.0.1
  depends on location_web ^2.0.0, location <4.0.1-∞ or >=5.0.0-dev.0 <5.0.0 requires location_web
  >=2.0.0-nullsafety <3.0.0 or >=5.0.0-dev.0 <6.0.0.
And because location >=4.0.1 <4.0.2 depends on location_web ^2.0.1 and location >=4.0.2 <4.1.0
  depends on location_web ^2.0.2, location <4.1.0-∞ or >=5.0.0-dev.0 <5.0.0 requires location_web
  >=2.0.0-nullsafety <3.0.0 or >=5.0.0-dev.0 <6.0.0.
And because location >=4.1.0 <4.2.0 depends on location_web ^3.0.0 and location >=4.2.0 <4.3.0
  depends on location_web ^3.1.0, location <4.3.0-∞ or >=5.0.0-dev.0 <5.0.0 requires location_web
  >=2.0.0-nullsafety <3.0.0 or >=3.0.0 <4.0.0 or >=5.0.0-dev.0 <6.0.0.
And because location >=4.3.0 <5.0.0-dev.0 depends on location_web ^3.1.1 and location >=5.0.0
  <5.0.1 depends on location_web ^4.0.0, location <5.0.1 requires location_web >=2.0.0-nullsafety
  <3.0.0 or >=3.0.0 <4.0.0 or ^4.0.0 or >=5.0.0-dev.0 <6.0.0.
And because location >=5.0.1 <5.0.2 depends on location_web ^4.1.0 and location ^5.0.2 depends
  on location_web ^4.1.1, location <6.0.0 requires location_web >=2.0.0-nullsafety <3.0.0 or
  >=3.0.0 <4.0.0 or >=4.0.0 <5.0.0 or >=5.0.0-dev.0 <6.0.0.
And because location ^6.0.0 depends on location_web ^5.0.0 and location >=7.0.0 depends on
  location_web ^5.0.3, every version of location requires location_web >=2.0.0-nullsafety <3.0.0
  or >=3.0.0 <4.0.0 or >=4.0.0 <5.0.0 or >=5.0.0-dev.0 <6.0.0.
So, because location_web depends on location any and location_web is 1.0.0+1, version solving
  failed.

The lower bound of "sdk: '<2.0.0 or >=2.0.0-dev.58.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
```

Error for installing by copy paste `location: ^7.0.0` to pubspec.yaml:
`Because location_web depends on location ^7.0.0 which depends on location_web ^5.0.3, location_web ^5.0.3 is required`

**Expected behavior**
Location package installed in my fresh project.

**Tested on:**
- Can't try on any device because, not installed yet.

**Flutter Doctor**

``` shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale
    en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for -. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

• No issues found!
```

**Comment by AumGupta** [comment]
## Solution
### Update your **pubspec.yaml** file as follows.
> pubspec.yaml
> ```
> environment:
> 	sdk: '>=2.12.0 <4.0.0'
> 
> dependencies:
> 	location: ^6.0.2
> ```

---

### **What are we doing above?**
> * Changing SDK version as the error says `The lower bound of "sdk: '<2.0.0 or >=2.0.0-dev.58.0 <3.0.0'" must be 2.12.0 or higher to enable null safety`
> * Downgrading the constraint on location to resolve pubspec, which can ***ALSO*** be done by running the following: `flutter pub add location:^6.0.2`

---
### **Optional**
> In-case of error, you can try the following suggestions to make the pubspec resolve:
> * Try using the Flutter SDK version: 3.24.1. 
---
If it helped, consider following @AumGupta

**Comment by gopelkujo** [comment]
And what i don't understand is, why the dependencies is depend to the lower version of it self. Is that normal?

**Comment by AumGupta** [comment]
Add `location_wev ^5.0.0` to pubspec.yaml.

> And yes dependence on an older version is normal when we access th older version of any package 

Let me know, if it helped.

**Comment by gopelkujo** [comment]
I did that too, and the error:
```
[location_web] flutter pub get --no-example
Resolving dependencies...
Error on line 39, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
39 │   location_web: ^5.0.0
   │   ^^^^^^^^^^^^
   ╵
exit code 65
```

**Comment by AumGupta** [comment]
If the name of your flutter project is also `location_web` then please change it.

You can check in your pubspec.yaml

```yaml
name: location_web

dependencies:
    location_web: ^5.0.0
```

Hope this answers your query.

**Comment by gopelkujo** [comment]
> If the name of your flutter project is also `location_web` then please change it.
> 
> You can check in your pubspec.yaml
> 
> ```yaml
> name: location_web
> 
> dependencies:
>     location_web: ^5.0.0
> ```
> 
> Hope this answers your query.

Hey that's the problem! my new project named location_web😅 I'm so delayed didn't realize that for long time, sorry my bad. Thanks for keep helping me! you gain new followers✌️

**Comment by AumGupta** [comment]
> > If the name of your flutter project is also `location_web` then please change it.
> > 
> > You can check in your pubspec.yaml
> > 
> > ```yaml
> > name: location_web
> > 
> > dependencies:
> >     location_web: ^5.0.0
> > ```
> > 
> > Hope this answers your query.
> 
> Hey that's the problem! my new project named location_web😅 I'm so delayed didn't realize that for long time, sorry my bad. Thanks for keep helping me! you gain new followers✌️

❤️ **Had a great time helping you out and thankyou for following.** You may mark the above as answered (accepted answer) so that others can also benefit from it. Happy Coding!

**Comment by gopelkujo** [comment]
I think the 'answered mark' feature is only available in discussion, but anyway i put the emoji to help other find the answer🚀
